BGC Tools: BGC.Utility.LogFilesTos3 Class Reference
BGC.Utility.LogFilesTos3 Class Reference
Static Public Member Functions
static void MigrateFiles (string bucketName, string serverPath)
Move all files to s3 and on success move them from the staging area to the permanent area of logs
Static Private Member Functions
static void migrateUser (string userName, string bucket, string serverPath)
Migrate user logs from staging to permanent on succesful upload to s3
Detailed Description
Definition at line 7 of file LogFilesToS3.cs.
Member Function Documentation
static void BGC.Utility.LogFilesTos3.MigrateFiles (string bucketName, string serverPath) inline static
Move all files to s3 and on success move them from the staging area to the permanent area of logs
Parameters
bucketName
serverPath
Definition at line 15 of file LogFilesToS3.cs.
References BGC.IO.LogDirectories.StagingDirectory.
         {
             string[] users = Directory.GetDirectories(LogDirectories.StagingDirectory);
             for (int i = 0; i < users.Length; ++i)
             {
                 migrateUser(Path.GetFileName(users[i]), bucketName, serverPath);
             }
         }
static void BGC.Utility.LogFilesTos3.migrateUser (string userName, string bucket, string serverPath) inline static private
Migrate user logs from staging to permanent on succesful upload to s3
Parameters
userName
bucket
serverPath
Definition at line 31 of file LogFilesToS3.cs.
References files(), BGC.Utility.ReservedFiles.IsFileReserved(), BGC.IO.LogDirectories.PermanentDirectory, BGC.Web.AWSServer.PostFileToAWS(), and BGC.IO.LogDirectories.StagingDirectory.
         {
             string stagingPath = Path.Combine(LogDirectories.StagingDirectory, userName);
             string permanentPath = Path.Combine(LogDirectories.PermanentDirectory, userName);
             string[] files = Directory.GetFiles(stagingPath);
             if(Directory.Exists(permanentPath) == false)
             {
                 Directory.CreateDirectory(permanentPath);
             }
             for (int i = 0; i < files.Length; ++i)
             {
                 string stagingFile = Path.Combine(stagingPath, files[i]);
                 string fileName = Path.GetFileName(stagingFile);
                 // skip files in use
                 if (ReservedFiles.IsFileReserved(stagingFile))
                 {
                     continue;
                 }
                 AWSServer.PostFileToAWS(
                     stagingFile,
                     bucket,
                     serverPath + "/" + fileName,
                     (bool error) => {
                         if (error == false)
{
                             string permanentFile = Path.Combine(permanentPath, fileName);
                             if (File.Exists(permanentFile))
{
                                 File.Delete(permanentFile);
                             }
                             File.Move(stagingFile, permanentFile);
                         }
                     });
             }
         }
The documentation for this class was generated from the following file:
Utility/LogFilesToS3.cs