BGC Tools: BGC.Utility.ReservedFiles Class Reference
BGC.Utility.ReservedFiles Class Reference
Static Public Member Functions
static bool ReserveFile (string path)
Reserve a file so other processes won't use them
static bool UnReserveFile (string path)
UnReserve a file if found
static bool UnReserveFile (string path, string userName, string bucket, string serverPath)
Unreserve a file and push it to the server
static bool IsFileReserved (string path)
Returns if the path is currently reserved
Static Private Attributes
static HashSet< string > files = new HashSet<string>()
Detailed Description
Definition at line 8 of file ReservedFiles.cs.
Member Function Documentation
static bool BGC.Utility.ReservedFiles.IsFileReserved (string path) inline static
Returns if the path is currently reserved
Parameters
path
Returns
True if the file is reserved, false if not
Definition at line 90 of file ReservedFiles.cs.
Referenced by BGC.Utility.LogFilesTos3.migrateUser().
         {
             return files.Contains(path);
         }
static bool BGC.Utility.ReservedFiles.ReserveFile (string path) inline static
Reserve a file so other processes won't use them
Parameters
path
Returns
True if the file was succesfully reserved
Definition at line 17 of file ReservedFiles.cs.
Referenced by BGC.IO.Logging.Logger.OpenFile().
         {
             if (files.Contains(path) == false)
             {
                 files.Add(path);
                 return true;
             }
             return false;
         }
static bool BGC.Utility.ReservedFiles.UnReserveFile (string path) inline static
UnReserve a file if found
Parameters
path
Returns
True if hte file was found and removed
Definition at line 33 of file ReservedFiles.cs.
Referenced by BGC.IO.Logging.Logger.CloseFile(), and BGC.IO.Logging.Logger.~Logger().
         {
             if(files.Contains(path))
             {
                 files.Remove(path);
                 return true;
             }
             return false;
         }
static bool BGC.Utility.ReservedFiles.UnReserveFile (string path, string userName, string bucket, string serverPath) inline static
Unreserve a file and push it to the server
Parameters
path
Returns
Definition at line 50 of file ReservedFiles.cs.
References BGC.IO.LogDirectories.PermanentDirectory, and BGC.Web.AWSServer.PostFileToAWS().
         {
             bool removed = UnReserveFile(path);
             #if !UNITY_EDITOR
                 AWSServer.PostFileToAWS(
                     path,
                     bucket,
                     serverPath + "/" + Path.GetFileName(path),
                     (bool error) => {
                         // move file from staging to permament on no error
                         if(error == false)
{
                             // @note: duplicate code from LogFilesToS3
                             string permanentPath = Path.Combine(LogDirectories.PermanentDirectory, userName);
                             if (Directory.Exists(permanentPath))
{
                                 Directory.CreateDirectory(permanentPath);
                             }
                             permanentPath = Path.Combine(permanentPath, Path.GetFileName(path));
                             if (File.Exists(permanentPath))
{
                                 File.Delete(permanentPath);
                             }
                             File.Move(path, permanentPath);
                         }
                     });
             #endif
             return removed;
         }
Field Documentation
HashSet<string> BGC.Utility.ReservedFiles.files = new HashSet<string>() static private
Definition at line 10 of file ReservedFiles.cs.
The documentation for this class was generated from the following file:
Utility/ReservedFiles.cs