BGC Tools: BGCTools.Bag< T > Class Template Reference
BGCTools.Bag< T > Class Template Reference
Bag implemnetation: https://algs4.cs.princeton.edu/13stacks/
Public Member Functions
Bag (List< T > startingCleanList)
Constructor method for bag with a list to build from
Bag (T[] startingCleanList)
Constructor method for a bag with an array to build from
void Add (T element)
Add element to the bag
void AddToBoth (T element)
add element to clean list and current bag
void Reset ()
Rese tbag to have entire clean list
T Pull (bool autoReset=false)
Pull from the bag and reset if autoreset is set to true else receive default value.
bool IsEmpty ()
Returns whether or not the bag is empty
Private Attributes
List< T > cleanList = new List<T>()
List< T > bag = new List<T>()
Detailed Description
Bag implemnetation: https://algs4.cs.princeton.edu/13stacks/
Note
: this class is okay but not perfect. My particular issue with it is
Template Parameters
T
Definition at line 17 of file Bag.cs.
Constructor & Destructor Documentation
BGCTools.Bag< T >.Bag (List< T > startingCleanList) inline
Constructor method for bag with a list to build from
Parameters
startingCleanList
Definition at line 26 of file Bag.cs.
References BGCTools.Bag< T >.Reset().
         {
             for (int i = 0; i < startingCleanList.Count; ++i)
             {
                 cleanList.Add(startingCleanList[i]);
             }
             Reset();
         }
BGCTools.Bag< T >.Bag (T[] startingCleanList) inline
Constructor method for a bag with an array to build from
Parameters
startingCleanList
Definition at line 40 of file Bag.cs.
References BGCTools.Bag< T >.Reset().
         {
             for (int i = 0; i < startingCleanList.Length; ++i)
             {
                 cleanList.Add(startingCleanList[i]);
             }
             Reset();
         }
Member Function Documentation
void BGCTools.Bag< T >.Add (T element) inline
Add element to the bag
Parameters
element
Definition at line 54 of file Bag.cs.
         {
             cleanList.Add(element);
         }
void BGCTools.Bag< T >.AddToBoth (T element) inline
add element to clean list and current bag
Parameters
element
Definition at line 63 of file Bag.cs.
         {
             cleanList.Add(element);
             bag.Add(element);
         }
bool BGCTools.Bag< T >.IsEmpty () inline
Returns whether or not the bag is empty
Returns
Definition at line 114 of file Bag.cs.
Referenced by BGCTools.Bag< T >.Pull().
         {
             return bag.Count <= 0;
         }
T BGCTools.Bag< T >.Pull (bool autoReset = false) inline
Pull from the bag and reset if autoreset is set to true else receive default value.
Parameters
autoReset
Returns
Definition at line 82 of file Bag.cs.
References BGCTools.Bag< T >.IsEmpty(), and BGCTools.Bag< T >.Reset().
         {
             T element;
             if (IsEmpty() == false)
             {
                 int index = bag.RandomIndex();
                 element = bag[index];
                 bag.RemoveAt(index);
                 if (autoReset == true && IsEmpty() == true)
                 {
                     Reset();
                 }
             }
             else
             {
                 // @note: the state where (autoReset == true && cleanList.Count > 0) == true
                 //        is impossible with the current implementation. If it is, then there
                 //        should be an extra if else here where that statement is evaluated and
                 //        if true then the Reset() functionchould be called and then element
                 //        should be set with a recursive Pull(autoReset) call.
                 element = default(T);
             }
             return element;
         }
void BGCTools.Bag< T >.Reset () inline
Rese tbag to have entire clean list
Definition at line 72 of file Bag.cs.
References BGCTools.Bag< T >.cleanList.
Referenced by BGCTools.Bag< T >.Bag(), and BGCTools.Bag< T >.Pull().
         {
             bag = new List<T>(cleanList);
         }
Field Documentation
List<T> BGCTools.Bag< T >.bag = new List<T>() private
Definition at line 20 of file Bag.cs.
List<T> BGCTools.Bag< T >.cleanList = new List<T>() private
Definition at line 19 of file Bag.cs.
Referenced by BGCTools.Bag< T >.Reset().
The documentation for this class was generated from the following file:
Bag.cs