BGC Tools: BGC.IO.DataManagement Class Reference
BGC.IO.DataManagement Class Reference
Static Public Member Functions
static IEnumerable< string > GetDataFiles (string dataDirectory)
Get a list of all data files in sub directory of os data directory
static string PathForDataFile (string dataDirectory, string fileName)
Returns the full path for specified datafile in a data directory
static string PathForDataDirectory (string dataDirectory)
Returns the full path to the dataDirectory directory.
static bool DataDirectoryExists (string dataDirectory)
static string PathForDataSubDirectory (params string[] dataDirectories)
Returns the full path to the dataDirectories directory.
static string NextAvailableFilePath (string filepath)
Returns an available filepath. Appends " (#)" to the filename, incrementing # until it is available, starting with any modifier present in the filepath.
Properties
static string RootDirectory [get]
Root directory for all users data
Static Private Member Functions
static string GetCleanFileName (string fileName, out int modifierValue)
Identifies any filename matching the pattern "NameStuffHere (3)" and strips off and spits out the modifier
Static Private Attributes
static string rootDirectory = null
Detailed Description
Definition at line 7 of file DataManagement.cs.
Member Function Documentation
DataDirectoryExists()
static bool BGC.IO.DataManagement.DataDirectoryExists (string dataDirectory) static
Referenced by BGC.Audio.Spatialization.ImpulseExtraction.PrepareRun().
GetCleanFileName()
static string BGC.IO.DataManagement.GetCleanFileName (string fileName, out int modifierValue) inline static private
Identifies any filename matching the pattern "NameStuffHere (3)" and strips off and spits out the modifier
Definition at line 82 of file DataManagement.cs.
         {
             //If FileName doesn't end with " (##)", it's not a modifier
             if (fileName.EndsWith(")") && fileName.Contains(" ("))
             {
                 //FileName ends with (##)
                 //It may have a modifier
                 int indexOfOpen = fileName.LastIndexOf(" (");
                 int indexOfClose = fileName.LastIndexOf(")");
                 int indexInside = indexOfOpen + 2;
                 int length = indexOfClose - indexInside;
                 //Make sure there are contents
                 //This would reject "TestFile ()"
                 if (length > 0)
                 {
                     string valueString = fileName.Substring(indexInside, length);
                     //Make sure value string can be parsed entirely, otherwise its not a modifier
                     //This would reject "TestFile (words)"
                     if (int.TryParse(valueString, out modifierValue))
                     {
                         //Reject negative numbers because that's now how we create modifiers
                         //This would reject "Test File (-1)"
                         if (modifierValue > 0)
{
                             modifierValue++;
                             return fileName.Substring(0, indexOfOpen);
                         }
                     }
                 }
             }
             modifierValue = 2;
             return fileName;
         }
GetDataFiles()
static IEnumerable<string> BGC.IO.DataManagement.GetDataFiles (string dataDirectory) static
Get a list of all data files in sub directory of os data directory
Referenced by BGC.Users.PlayerData.DeserializeUsers().
NextAvailableFilePath()
static string BGC.IO.DataManagement.NextAvailableFilePath (string filepath) inline static
Returns an available filepath. Appends " (#)" to the filename, incrementing # until it is available, starting with any modifier present in the filepath.
Returns
An available filepath
Definition at line 127 of file DataManagement.cs.
Referenced by BGC.Audio.Midi.MidiEncoding.SaveFile().
         {
             if (!File.Exists(filepath))
             {
                 return filepath;
             }
             string directory = Path.GetDirectoryName(filepath);
             string fileExtension = Path.GetExtension(filepath);
             string fileName = GetCleanFileName(
                 fileName: Path.GetFileNameWithoutExtension(filepath),
                 modifierValue: out int initialModifierValue);
             for (int i = initialModifierValue; ; i++)
             {
                 if (!File.Exists(filepath))
                 {
                     return filepath;
                 }
                 filepath = Path.Combine(directory, $"{fileName} ({i}){fileExtension}");
             }
         }
PathForDataDirectory()
static string BGC.IO.DataManagement.PathForDataDirectory (string dataDirectory) inline static
Returns the full path to the dataDirectory directory.
Definition at line 41 of file DataManagement.cs.
Referenced by BGC.Study.ProtocolManager.LoadProtocolSet(), BGC.Audio.Spatialization.ImpulseExtraction.PrepareRun(), BGC.Study.ProtocolManager.SerializeAll(), and BGC.Study.ProtocolManager.UpdateDefaults().
         {
             string path = Path.Combine(RootDirectory, dataDirectory);
             if (Directory.Exists(path) == false)
             {
                 Directory.CreateDirectory(path);
             }
             return path;
         }
PathForDataFile()
static string BGC.IO.DataManagement.PathForDataFile (string dataDirectory, string fileName) static
Returns the full path for specified datafile in a data directory
Referenced by BGC.Tests.SynthesisTests.FMTestBell(), BGC.Tests.SynthesisTests.FMTestBrass(), BGC.Tests.SynthesisTests.FMTestDrum(), BGC.Tests.SynthesisTests.FMTestOvertones(), BGC.Tests.SynthesisTests.FMTestPiano(), BGC.Tests.SynthesisTests.FMTestTrianglePiano(), BGC.Audio.Spatial.GetFilterFilename(), BGC.Audio.Calibration.Initialize(), BGC.Audio.Spatialization.ImpulseExtraction.PrepareRun(), BGC.Audio.Calibration.Serialize(), BGC.Tests.SynthesisTests.SmallAnalyticFMTest(), BGC.Tests.SynthesisTests.SmallSineFMTest(), BGC.Tests.SynthesisTests.SynthTestSnare(), BGC.Tests.SynthesisTests.TestAllPassFilterSpeech(), BGC.Tests.SynthesisTests.TestBiQuadFilters(), BGC.Tests.TestOverlapAdd.TestCarlileShuffler(), BGC.Tests.SynthesisTests.TestCarrierModifiedFakeVoices(), BGC.Tests.MidiEncodingTests.TestContinuousFilter(), BGC.Tests.WAVEncodingTests.TestDualChannelWave(), BGC.Tests.SynthesisTests.TestFakeVoice(), BGC.Tests.SynthesisTests.TestFDComposer(), BGC.Tests.SynthesisTests.TestFDComposerPure(), BGC.Tests.MidiEncodingTests.TestFlute(), BGC.Tests.SynthesisTests.TestFMFilterVoice(), BGC.Tests.SynthesisTests.TestFrequencyShifter(), BGC.Tests.SynthesisTests.TestFunFakeVoice(), BGC.Tests.MidiEncodingTests.TestGuitar(), BGC.Tests.MidiEncodingTests.TestHiHat(), BGC.Tests.MidiEncodingTests.TestLoadSaveMidiBare(), BGC.Tests.MidiEncodingTests.TestLoadSaveMidiFull(), BGC.Tests.TestOverlapAdd.TestNewConvolution(), BGC.Tests.TestOverlapAdd.TestNewSpatialization(), BGC.Tests.MidiEncodingTests.TestOrgan(), BGC.Tests.SynthesisTests.TestPhaseReEncoder(), BGC.Tests.TestOverlapAdd.TestPhaseVocoding(), BGC.Tests.MidiEncodingTests.TestPulses(), BGC.Tests.MidiEncodingTests.TestRenderMidi(), BGC.Tests.MidiEncodingTests.TestRenderToccataMidi(), BGC.Tests.SynthesisTests.TestSawtoothWave(), BGC.Tests.SynthesisTests.TestSineWave(), BGC.Tests.WAVEncodingTests.TestSingleChannelWave(), BGC.Tests.MidiEncodingTests.TestSnare(), BGC.Tests.SynthesisTests.TestSquareWave(), BGC.Tests.SynthesisTests.TestSTM(), BGC.Tests.SynthesisTests.TestTriangleWave(), BGC.Tests.ZipTests.TestZip(), BGC.Tests.SynthesisTests.TryAllPassFilter(), BGC.Tests.SynthesisTests.TryFMFilter(), and BGC.Tests.WAVEncodingTests.UpScalingTest().
PathForDataSubDirectory()
static string BGC.IO.DataManagement.PathForDataSubDirectory (params string [] dataDirectories) inline static
Returns the full path to the dataDirectories directory.
Definition at line 57 of file DataManagement.cs.
Referenced by BGC.Tests.ZipTests.TestZip().
         {
             string[] paths = new string[dataDirectories.Length + 1];
             paths[0] = RootDirectory;
             System.Array.Copy(
                 sourceArray: dataDirectories,
                 sourceIndex: 0,
                 destinationArray: paths,
                 destinationIndex: 1,
                 length: dataDirectories.Length);
             string path = Path.Combine(paths);
             if (Directory.Exists(path) == false)
             {
                 Directory.CreateDirectory(path);
             }
             return path;
         }
Field Documentation
rootDirectory
string BGC.IO.DataManagement.rootDirectory = null static private
Definition at line 9 of file DataManagement.cs.
Property Documentation
RootDirectory
string BGC.IO.DataManagement.RootDirectory static get
Root directory for all users data
Definition at line 13 of file DataManagement.cs.
The documentation for this class was generated from the following file:
IO/DataManagement.cs