BGC Tools: BGC.Audio.FrequencyDomain Class Reference
BGC.Audio.FrequencyDomain Class Reference
Collection of common mathematical processes used in the Frequency-Domain.
Static Public Member Functions
static void Populate (Complex64[] buffer, in ComplexCarrierTone carrierTone, double amplitudeFactor=1.0, int sideFreqCount=20)
static void Populate (Complex64[] buffer, double frequency, Complex64 amplitude, int sideFreqCount=20)
static double GetComplexSampleFrequency (int bufferSize, int sample)
static double GetComplexFrequencySample (int bufferSize, double frequency)
static int GetComplexFrequencyBin (int bufferSize, double frequency)
Properties
static double SamplingRate [get, set]
Static Private Member Functions
static double GetComplexNormalizedDeviation (int bufferSize, double frequency)
Get f_Delta * T
Detailed Description
Collection of common mathematical processes used in the Frequency-Domain.
Definition at line 9 of file FrequencyDomain.cs.
Member Function Documentation
static int BGC.Audio.FrequencyDomain.GetComplexFrequencyBin (int bufferSize, double frequency) static
Referenced by BGC.Audio.Filters.CarlileShuffler._Initialize(), and BGC.Audio.Visualization.SpectralDecomp.SpectralDecomp().
static double BGC.Audio.FrequencyDomain.GetComplexFrequencySample (int bufferSize, double frequency) static
static double BGC.Audio.FrequencyDomain.GetComplexNormalizedDeviation (int bufferSize, double frequency) static private
Get f_Delta * T
static double BGC.Audio.FrequencyDomain.GetComplexSampleFrequency (int bufferSize, int sample) static
Referenced by BGC.Audio.Visualization.Spectrogram.Decompose(), and BGC.Audio.Visualization.SpectralDecomp.SpectralDecomp().
static void BGC.Audio.FrequencyDomain.Populate (Complex64[] buffer, in ComplexCarrierTone carrierTone, double amplitudeFactor = 1.0, int sideFreqCount = 20) inline static
Definition at line 13 of file FrequencyDomain.cs.
Referenced by BGC.Audio.Synthesis.NoiseAudioClip._Initialize(), BGC.Audio.Synthesis.STMAudioClip._Initialize(), BGC.Audio.AnalyticStreams.AnalyticNoiseStream.Initialize(), and BGC.Audio.Synthesis.FrequencyDomainToneComposer.Read().
         {
             Populate(
                 buffer: buffer,
                 frequency: carrierTone.frequency,
                 amplitude: amplitudeFactor * carrierTone.amplitude,
                 sideFreqCount: sideFreqCount);
         }
static void BGC.Audio.FrequencyDomain.Populate (Complex64[] buffer, double frequency, Complex64 amplitude, int sideFreqCount = 20) inline static
Definition at line 26 of file FrequencyDomain.cs.
References BGC.Mathematics.Complex64.FromPolarCoordinates(), and BGC.Mathematics.Complex64.Sqrt().
         {
             int bin = GetComplexFrequencyBin(
                 bufferSize: buffer.Length,
                 frequency: frequency);
             if (bin < 1 || bin > buffer.Length / 2)
             {
                 //Skipping frequency as it's out of range
                 return;
             }
             double normalizedDeviation = GetComplexNormalizedDeviation(
                 bufferSize: buffer.Length,
                 frequency: frequency);
             amplitude *= Math.Sqrt(buffer.Length);
             if (normalizedDeviation == 0.0)
             {
                 //Perfect - No side terms
                 buffer[bin] += amplitude;
                 return;
             }
             amplitude *= (Math.Sin(Math.PI * normalizedDeviation) / Math.PI) *
                 Complex64.FromPolarCoordinates(1.0, Math.PI * normalizedDeviation);
             for (int N = -sideFreqCount; N <= sideFreqCount; N++)
             {
                 if (bin + N < 1 || bin + N > buffer.Length / 2)
                 {
                     //Skip frequencies out of range
                     continue;
                 }
                 buffer[bin + N] += amplitude / (N - normalizedDeviation);
             }
         }
Property Documentation
double BGC.Audio.FrequencyDomain.SamplingRate static get set
Definition at line 11 of file FrequencyDomain.cs.
The documentation for this class was generated from the following file:
Audio/FrequencyDomain.cs