BGC Tools: BGC.StateMachine.StateData Class Reference
BGC.StateMachine.StateData Class Reference
Public Member Functions
void AddBoolean (string key, bool value)
void SetBoolean (string key, bool value)
bool GetBoolean (string key)
void AddTrigger (string key)
void ActivateTrigger (string key)
void DeActivateTrigger (string key)
bool GetTrigger (string key)
Private Attributes
Dictionary< string, bool > booleans = new Dictionary<string, bool>()
Dictionary< string, bool > triggers = new Dictionary<string, bool>()
Detailed Description
Definition at line 5 of file StateData.cs.
Member Function Documentation
void BGC.StateMachine.StateData.ActivateTrigger (string key) inline
Definition at line 30 of file StateData.cs.
Referenced by BGC.StateMachine.StateMachine.ActivateTrigger().
         {
             triggers[key] = true;
         }
void BGC.StateMachine.StateData.AddBoolean (string key, bool value) inline
Definition at line 10 of file StateData.cs.
Referenced by BGC.StateMachine.StateMachine.AddAnyStateTransition().
         {
             booleans.Add(key, value);
         }
void BGC.StateMachine.StateData.AddTrigger (string key) inline
Definition at line 25 of file StateData.cs.
Referenced by BGC.StateMachine.StateMachine.AddTrigger().
         {
             triggers.Add(key, false);
         }
void BGC.StateMachine.StateData.DeActivateTrigger (string key) inline
Definition at line 35 of file StateData.cs.
Referenced by BGC.StateMachine.StateMachine.AddAnyStateTransition(), and BGC.StateMachine.StateMachine.AddTransition().
         {
             triggers[key] = false;
         }
bool BGC.StateMachine.StateData.GetBoolean (string key) inline
Definition at line 20 of file StateData.cs.
Referenced by BGC.StateMachine.StateMachine.GetBool().
         {
             return booleans[key];
         }
bool BGC.StateMachine.StateData.GetTrigger (string key) inline
Definition at line 40 of file StateData.cs.
Referenced by BGC.StateMachine.StateMachine.GetTrigger().
         {
             return triggers[key];
         }
void BGC.StateMachine.StateData.SetBoolean (string key, bool value) inline
Definition at line 15 of file StateData.cs.
Referenced by BGC.StateMachine.StateMachine.SetBool().
         {
             booleans[key] = value;
         }
Field Documentation
Dictionary<string, bool> BGC.StateMachine.StateData.booleans = new Dictionary<string, bool>() private
Definition at line 7 of file StateData.cs.
Dictionary<string, bool> BGC.StateMachine.StateData.triggers = new Dictionary<string, bool>() private
Definition at line 8 of file StateData.cs.
The documentation for this class was generated from the following file:
StateMachine/StateData.cs