BGC Tools: BGC.Audio.AnalyticStreams.AnalyticWave Class Reference
BGC.Audio.AnalyticStreams.AnalyticWave Class Reference
Public Member Functions
AnalyticWave (double amplitude, double frequency, double phase=0.0)
int Read (Complex64[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
void Reset ()
Sets this internal state of this stream to the initial state
void Seek (int position)
Seek to the indicated position in the stream
double GetRMS ()
The RMS amplitude of the stream (real component)
Data Fields
double SamplingRate => 44100.0
Private Member Functions
void IAnalyticStream. Initialize ()
Perform any calculations necessary to prepare the Stream
Private Attributes
int IAnalyticStream. Samples => int.MaxValue
readonly double frequency
readonly double amplitude
readonly double phase
Complex64 partial
readonly double cyclePartial
readonly Complex64[] samples
int position = 0
int cycles = 0
Additional Inherited Members
Properties inherited from BGC.Audio.AnalyticStreams.IAnalyticStream
int Samples [get]
The total number of Samples of this AnalyticStream
double SamplingRate [get]
The sampling rate of the Stream
Detailed Description
Definition at line 9 of file AnalyticWave.cs.
Constructor & Destructor Documentation
BGC.Audio.AnalyticStreams.AnalyticWave.AnalyticWave (double amplitude, double frequency, double phase = 0.0) inline
Definition at line 25 of file AnalyticWave.cs.
References BGC.Mathematics.Complex64.FromPolarCoordinates().
         {
             this.amplitude = amplitude;
             this.frequency = frequency;
             this.phase = phase;
             double sampleCount = SamplingRate / this.frequency;
             int intSampleCount = (int)Ceiling(sampleCount) - 1;
             cyclePartial = (2 * PI * this.frequency / SamplingRate ) * (intSampleCount - sampleCount);
             cycles = 0;
             partial = Complex64.FromPolarCoordinates(
                 magnitude: 1.0,
                 phase: cycles * cyclePartial);
             samples = new Complex64[intSampleCount];
             for (int i = 0; i < samples.Length; i++)
             {
                 samples[i] = Complex64.FromPolarCoordinates(
                     magnitude: this.amplitude,
                     phase: this.phase + 2 * PI * i / sampleCount);
             }
         }
Member Function Documentation
double BGC.Audio.AnalyticStreams.AnalyticWave.GetRMS ()
The RMS amplitude of the stream (real component)
Implements BGC.Audio.AnalyticStreams.IAnalyticStream.
void IAnalyticStream. BGC.Audio.AnalyticStreams.AnalyticWave.Initialize () inline private
Perform any calculations necessary to prepare the Stream
Implements BGC.Audio.AnalyticStreams.IAnalyticStream.
Definition at line 51 of file AnalyticWave.cs.
 { }
int BGC.Audio.AnalyticStreams.AnalyticWave.Read (Complex64[] data, int offset, int count) inline
Copy count samples into the Data buffer, starting at offset.
Returns
The number of samples copied
Implements BGC.Audio.AnalyticStreams.IAnalyticStream.
Definition at line 53 of file AnalyticWave.cs.
References BGC.Mathematics.Complex64.FromPolarCoordinates().
         {
             int samplesToRead = count;
             while (samplesToRead > 0)
             {
                 int readingSamples = Min(samplesToRead, samples.Length - position);
                 for (int i = 0; i < readingSamples; i++)
                 {
                     data[offset + i] = samples[position + i] * partial;
                 }
                 samplesToRead -= readingSamples;
                 offset += readingSamples;
                 position += readingSamples;
                 if (position == samples.Length)
                 {
                     position = 0;
                     cycles++;
                     partial = Complex64.FromPolarCoordinates(
                         magnitude: 1.0,
                         phase: cycles * cyclePartial);
                 }
             }
             return count;
         }
void BGC.Audio.AnalyticStreams.AnalyticWave.Reset () inline
Sets this internal state of this stream to the initial state
Implements BGC.Audio.AnalyticStreams.IAnalyticStream.
Definition at line 83 of file AnalyticWave.cs.
References BGC.Mathematics.Complex64.FromPolarCoordinates().
         {
             position = 0;
             cycles = 0;
             partial = Complex64.FromPolarCoordinates(
                 magnitude: 1.0,
                 phase: cycles * cyclePartial);
         }
void BGC.Audio.AnalyticStreams.AnalyticWave.Seek (int position) inline
Seek to the indicated position in the stream
Implements BGC.Audio.AnalyticStreams.IAnalyticStream.
Definition at line 92 of file AnalyticWave.cs.
References BGC.Mathematics.Complex64.FromPolarCoordinates().
         {
             if (position >= 0)
             {
                 cycles = position / samples.Length;
             }
             else
             {
                 cycles = (position - samples.Length + 1) / samples.Length;
             }
             this.position = position - cycles * samples.Length;
             partial = Complex64.FromPolarCoordinates(
                 magnitude: 1.0,
                 phase: cycles * cyclePartial);
         }
Field Documentation
readonly double BGC.Audio.AnalyticStreams.AnalyticWave.amplitude private
Definition at line 16 of file AnalyticWave.cs.
readonly double BGC.Audio.AnalyticStreams.AnalyticWave.cyclePartial private
Definition at line 20 of file AnalyticWave.cs.
int BGC.Audio.AnalyticStreams.AnalyticWave.cycles = 0 private
Definition at line 23 of file AnalyticWave.cs.
readonly double BGC.Audio.AnalyticStreams.AnalyticWave.frequency private
Definition at line 15 of file AnalyticWave.cs.
Complex64 BGC.Audio.AnalyticStreams.AnalyticWave.partial private
Definition at line 19 of file AnalyticWave.cs.
readonly double BGC.Audio.AnalyticStreams.AnalyticWave.phase private
Definition at line 17 of file AnalyticWave.cs.
int BGC.Audio.AnalyticStreams.AnalyticWave.position = 0 private
Definition at line 22 of file AnalyticWave.cs.
int IAnalyticStream. BGC.Audio.AnalyticStreams.AnalyticWave.Samples => int.MaxValue private
Definition at line 13 of file AnalyticWave.cs.
readonly Complex64 [] BGC.Audio.AnalyticStreams.AnalyticWave.samples private
Definition at line 21 of file AnalyticWave.cs.
double BGC.Audio.AnalyticStreams.AnalyticWave.SamplingRate => 44100.0
Definition at line 11 of file AnalyticWave.cs.
The documentation for this class was generated from the following file:
Audio/AnalyticStreams/AnalyticWave.cs