BGC Tools: BGC.Audio.Filters.StreamWindower Class Reference
BGC.Audio.Filters.StreamWindower Class Reference
Windows and truncates underlying stream
Public Member Functions
StreamWindower (IBGCStream stream, Windowing.Function function=Windowing.Function.Hamming, double totalDuration=double.NaN, int smoothingSamples=1000, int sampleShift=0, bool recalculateRMS=false)
StreamWindower (IBGCStream stream, Windowing.Function openingFunction, Windowing.Function closingFunction, int openingSmoothingSamples=1000, int closingSmoothingSamples=1000, int sampleShift=0, int totalChannelSamples=-1, bool recalculateRMS=false)
override void Reset ()
Sets this internal state of this stream to the initial state
override void Seek (int position)
Seek to the indicated position in the stream
override int Read (float[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
override IEnumerable< double > GetChannelRMS ()
The RMS amplitude of each channel
Public Member Functions inherited from BGC.Audio.Filters.SimpleBGCFilter
SimpleBGCFilter (IBGCStream stream)
override void Initialize ()
Perform any calculations necessary to prepare the Stream
Data Fields
override int Channels => stream.Channels
Data Fields inherited from BGC.Audio.Filters.SimpleBGCFilter
override float SamplingRate => stream.SamplingRate
Properties
override int TotalSamples [get]
override int ChannelSamples [get]
int Position [get, private set]
Properties inherited from BGC.Audio.Filters.SimpleBGCFilter
override IEnumerable< IBGCStream > InternalStreams [get]
Properties inherited from BGC.Audio.Filters.BGCFilter
abstract int Channels [get]
abstract int TotalSamples [get]
abstract int ChannelSamples [get]
abstract float SamplingRate [get]
abstract IEnumerable< IBGCStream > InternalStreams [get]
Properties inherited from BGC.Audio.IBGCStream
int Channels [get]
The number of underlying Channels of this BGCStream
int TotalSamples [get]
The total number of Samples of this BGCStream
int ChannelSamples [get]
The number of Samples of each channel for this BGCStream
float SamplingRate [get]
The sampling rate of the Stream
Private Attributes
readonly float [] openingWindow
readonly float [] closingWindow
readonly int sampleShift
readonly int endOpeningWindow
readonly int startClosingWindow
readonly bool recalculateRMS
IEnumerable< double > _channelRMS = null
Additional Inherited Members
Protected Member Functions inherited from BGC.Audio.Filters.BGCFilter
virtual void _Initialize ()
Protected Attributes inherited from BGC.Audio.Filters.SimpleBGCFilter
readonly IBGCStream stream
Protected Attributes inherited from BGC.Audio.Filters.BGCFilter
bool initialized = false
Detailed Description
Windows and truncates underlying stream
Definition at line 11 of file StreamWindower.cs.
Constructor & Destructor Documentation
StreamWindower() [1/2]
BGC.Audio.Filters.StreamWindower.StreamWindower (IBGCStream stream, Windowing.Function function = Windowing.Function.Hamming, double totalDuration = double.NaN, int smoothingSamples = 1000, int sampleShift = 0, bool recalculateRMS = false) inline
Definition at line 29 of file StreamWindower.cs.
References BGC.Audio.IBGCStream.ChannelSamples, and BGC.Audio.Windowing.GetHalfWindow().
             : base(stream)
         {
             if (sampleShift > stream.ChannelSamples)
             {
                 Debug.LogError("Requested a sampleOffset larger than clip length");
                 sampleShift = 0;
             }
             this.sampleShift = sampleShift;
             if (!double.IsNaN(totalDuration))
             {
                 ChannelSamples = Math.Min(
                     (int)Math.Round(totalDuration * SamplingRate),
                     stream.ChannelSamples - sampleShift);
                 TotalSamples = Channels * ChannelSamples;
             }
             else
             {
                 if (stream.ChannelSamples == int.MaxValue)
                 {
                     ChannelSamples = int.MaxValue;
                     TotalSamples = int.MaxValue;
                 }
                 else
                 {
                     ChannelSamples = stream.ChannelSamples - sampleShift;
                     TotalSamples = Channels * ChannelSamples;
                 }
             }
             this.recalculateRMS = recalculateRMS;
             smoothingSamples = Math.Min(smoothingSamples, ChannelSamples / 2);
             openingWindow = Windowing.GetHalfWindow(function, smoothingSamples);
             closingWindow = openingWindow;
             endOpeningWindow = smoothingSamples;
             startClosingWindow = ChannelSamples - smoothingSamples;
             Reset();
         }
StreamWindower() [2/2]
BGC.Audio.Filters.StreamWindower.StreamWindower (IBGCStream stream, Windowing.Function openingFunction, Windowing.Function closingFunction, int openingSmoothingSamples = 1000, int closingSmoothingSamples = 1000, int sampleShift = 0, int totalChannelSamples = -1, bool recalculateRMS = false) inline
Definition at line 80 of file StreamWindower.cs.
References BGC.Audio.IBGCStream.ChannelSamples, and BGC.Audio.Windowing.GetHalfWindow().
             : base(stream)
         {
             if (sampleShift > stream.ChannelSamples)
             {
                 Debug.LogError("Requested a sampleOffset larger than clip length");
                 sampleShift = 0;
             }
             this.sampleShift = sampleShift;
             this.recalculateRMS = recalculateRMS;
             if (totalChannelSamples != -1)
             {
                 ChannelSamples = Math.Min(
                     totalChannelSamples,
                     stream.ChannelSamples - sampleShift);
                 TotalSamples = Channels * ChannelSamples;
             }
             else
             {
                 if (stream.ChannelSamples == int.MaxValue)
                 {
                     ChannelSamples = int.MaxValue;
                     TotalSamples = int.MaxValue;
                 }
                 else
                 {
                     ChannelSamples = stream.ChannelSamples - sampleShift;
                     TotalSamples = Channels * ChannelSamples;
                 }
             }
             if (openingSmoothingSamples + closingSmoothingSamples > ChannelSamples)
             {
                 //Requested smoothing samples exceeded remaining stream length
                 int totalSmoothingSamples = openingSmoothingSamples + closingSmoothingSamples;
                 int excessSamples = ChannelSamples - totalSmoothingSamples;
                 //Allocate reduced smoothing samples based on requested percentage
                 openingSmoothingSamples -= (int)Math.Round(
                     excessSamples * (openingSmoothingSamples / (double)totalSmoothingSamples));
                 closingSmoothingSamples = ChannelSamples - openingSmoothingSamples;
             }
             openingWindow = Windowing.GetHalfWindow(openingFunction, openingSmoothingSamples);
             closingWindow = Windowing.GetHalfWindow(closingFunction, closingSmoothingSamples);
             endOpeningWindow = openingSmoothingSamples;
             startClosingWindow = ChannelSamples - closingSmoothingSamples;
             Reset();
         }
Member Function Documentation
GetChannelRMS()
override IEnumerable<double> BGC.Audio.Filters.StreamWindower.GetChannelRMS () inline virtual
The RMS amplitude of each channel
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 240 of file StreamWindower.cs.
         {
             if (_channelRMS == null)
             {
                 if (recalculateRMS)
                 {
                     _channelRMS = this.CalculateRMS();
                 }
                 else
                 {
                     _channelRMS = stream.GetChannelRMS();
                 }
             }
             return _channelRMS;
         }
Read()
override int BGC.Audio.Filters.StreamWindower.Read (float [] data, int offset, int count) inline virtual
Copy count samples into the Data buffer, starting at offset.
Returns
The number of samples copied
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 158 of file StreamWindower.cs.
         {
             int remainingSamples = count;
             while (remainingSamples > 0 && Position < ChannelSamples)
             {
                 if (Position < endOpeningWindow)
                 {
                     //Initial Window Period
                     int copyLength = Math.Min(
                         Channels * (endOpeningWindow - Position),
                         remainingSamples);
                     int readSamples = stream.Read(data, offset, copyLength);
                     if (readSamples == 0)
                     {
                         //No more samples
                         break;
                     }
                     for (int i = 0; i < readSamples; i++)
                     {
                         data[offset + i] *= openingWindow[Position + (i / Channels)];
                     }
                     remainingSamples -= readSamples;
                     offset += readSamples;
                     Position += readSamples / Channels;
                 }
                 else if (Position < startClosingWindow)
                 {
                     //Unwindowed Period
                     int copyLength = Math.Min(
                         Channels * (startClosingWindow - Position),
                         remainingSamples);
                     int readSamples = stream.Read(data, offset, copyLength);
                     if (readSamples == 0)
                     {
                         //No more samples
                         break;
                     }
                     remainingSamples -= readSamples;
                     offset += readSamples;
                     Position += readSamples / Channels;
                 }
                 else
                 {
                     //Ending Window Period
                     int copyLength = Math.Min(
                         Channels * (ChannelSamples - Position),
                         remainingSamples);
                     int readSamples = stream.Read(data, offset, copyLength);
                     if (readSamples == 0)
                     {
                         //No more samples
                         break;
                     }
                     for (int i = 0; i < readSamples; i++)
                     {
                         data[offset + i] *= closingWindow[closingWindow.Length + startClosingWindow - (Position + (i / Channels) + 1)];
                     }
                     remainingSamples -= readSamples;
                     offset += readSamples;
                     Position += readSamples / Channels;
                 }
             }
             return count - remainingSamples;
         }
Reset()
override void BGC.Audio.Filters.StreamWindower.Reset () inline virtual
Sets this internal state of this stream to the initial state
Reimplemented from BGC.Audio.Filters.SimpleBGCFilter.
Definition at line 142 of file StreamWindower.cs.
         {
             Position = 0;
             stream.Reset();
             if (sampleShift > 0)
             {
                 stream.Seek(sampleShift);
             }
         }
Seek()
override void BGC.Audio.Filters.StreamWindower.Seek (int position) inline virtual
Seek to the indicated position in the stream
Reimplemented from BGC.Audio.Filters.SimpleBGCFilter.
Definition at line 152 of file StreamWindower.cs.
References BGC.Mathematics.GeneralMath.Clamp().
         {
             Position = GeneralMath.Clamp(position, 0, ChannelSamples);
             stream.Seek(Position + sampleShift);
         }
Field Documentation
_channelRMS
IEnumerable<double> BGC.Audio.Filters.StreamWindower._channelRMS = null private
Definition at line 239 of file StreamWindower.cs.
Channels
override int BGC.Audio.Filters.StreamWindower.Channels => stream.Channels
Definition at line 13 of file StreamWindower.cs.
closingWindow
readonly float [] BGC.Audio.Filters.StreamWindower.closingWindow private
Definition at line 19 of file StreamWindower.cs.
endOpeningWindow
readonly int BGC.Audio.Filters.StreamWindower.endOpeningWindow private
Definition at line 22 of file StreamWindower.cs.
openingWindow
readonly float [] BGC.Audio.Filters.StreamWindower.openingWindow private
Definition at line 18 of file StreamWindower.cs.
recalculateRMS
readonly bool BGC.Audio.Filters.StreamWindower.recalculateRMS private
Definition at line 25 of file StreamWindower.cs.
sampleShift
readonly int BGC.Audio.Filters.StreamWindower.sampleShift private
Definition at line 20 of file StreamWindower.cs.
startClosingWindow
readonly int BGC.Audio.Filters.StreamWindower.startClosingWindow private
Definition at line 23 of file StreamWindower.cs.
Property Documentation
ChannelSamples
override int BGC.Audio.Filters.StreamWindower.ChannelSamples get
Definition at line 16 of file StreamWindower.cs.
Position
int BGC.Audio.Filters.StreamWindower.Position get private set
Definition at line 27 of file StreamWindower.cs.
TotalSamples
override int BGC.Audio.Filters.StreamWindower.TotalSamples get
Definition at line 15 of file StreamWindower.cs.
The documentation for this class was generated from the following file:
Audio/Filters/StreamWindower.cs