BGC Tools: BGC.IO.Logging.Logger Class Reference
BGC.IO.Logging.Logger Class Reference abstract
Public Member Functions
Logger (string applicationName, string applicationVersion, string userName, int sessionNumber, int[] fileIndices, bool pushToServer, string delimiter="|")
void CloseFile ()
void CloseFile (string userName, string organization, string study, string apiKey)
Protected Member Functions
virtual JsonObject ConstructAdditionalHeaders ()
abstract JsonObject ConstructColumnMapping ()
abstract JsonObject ConstructValueMapping ()
void PushLine (params IConvertible[] strings)
Push a line to the logger. Open the logger if it's null.
void PushString (string str)
Push a string to the logger. Open the logger if it's null.
Protected Attributes
string delimiter
Static Protected Attributes
static string TimeStamp => DateTime.Now.ToString("yy_MM_dd_HH_mm_ss")
Properties
abstract string Name [get]
Private Member Functions
~Logger ()
void ApplyHeaders ()
void OpenFile ()
string GetExceptionFileName ()
void ApplyRequiredFields (JsonObject jo)
string DelimiterLine (params IConvertible[] strings)
Static Private Member Functions
static string PathForLogFile (string userName, string filename, bool pushToServer)
Private Attributes
StreamWriter logger
string path
readonly string applicationName
readonly string applicationVersion
readonly string userName
readonly int sessionNumber
readonly int[] fileIndices
readonly bool pushToServer
Detailed Description
Definition at line 13 of file Logger.cs.
Constructor & Destructor Documentation
BGC.IO.Logging.Logger.Logger (string applicationName, string applicationVersion, string userName, int sessionNumber, int[] fileIndices, bool pushToServer, string delimiter = "|") inline
Definition at line 32 of file Logger.cs.
         {
             if (fileIndices == null)
             {
                 fileIndices = new int[] { };
             }
             this.applicationName = applicationName;
             this.applicationVersion = applicationVersion;
             this.userName = userName;
             this.sessionNumber = sessionNumber;
             this.fileIndices = fileIndices;
             this.pushToServer = pushToServer;
             this.delimiter = delimiter;
         }
BGC.IO.Logging.Logger.~Logger () inline private
Definition at line 55 of file Logger.cs.
         {
             CloseFile();
         }
Member Function Documentation
void BGC.IO.Logging.Logger.ApplyHeaders () inline private
Definition at line 64 of file Logger.cs.
References BGC.IO.Logging.LoggingKeys.AdditionalHeaders, BGC.IO.Logging.LoggingKeys.ColumnMapping, LightJson.JsonObject.ToString(), and BGC.IO.Logging.LoggingKeys.ValueMapping.
         {
             JsonObject header = new JsonObject
             {
                 { LoggingKeys.AdditionalHeaders, ConstructAdditionalHeaders() },
                 { LoggingKeys.ColumnMapping, ConstructColumnMapping() },
                 { LoggingKeys.ValueMapping, ConstructValueMapping() }
             };
             ApplyRequiredFields(header);
             PushLine(header.ToString());
         }
void BGC.IO.Logging.Logger.ApplyRequiredFields (JsonObject jo) inline private
Definition at line 207 of file Logger.cs.
References LightJson.JsonObject.Add(), BGC.IO.Logging.LoggingKeys.Delimiter, BGC.IO.Logging.LoggingKeys.DeviceID, BGC.IO.Logging.LoggingKeys.GameName, BGC.IO.Logging.LoggingKeys.Session, BGC.IO.Logging.LoggingKeys.UserName, and BGC.IO.Logging.LoggingKeys.Version.
         {
             jo.Add(LoggingKeys.GameName, applicationName);
             jo.Add(LoggingKeys.Version, applicationVersion);
             jo.Add(LoggingKeys.UserName, userName);
             jo.Add(LoggingKeys.DeviceID, SystemInfo.deviceUniqueIdentifier);
             jo.Add(LoggingKeys.Session, sessionNumber);
             jo.Add(LoggingKeys.Delimiter, delimiter);
         }
void BGC.IO.Logging.Logger.CloseFile () inline
Definition at line 130 of file Logger.cs.
References BGC.Utility.ReservedFiles.UnReserveFile().
         {
             if (logger != null)
             {
                 logger.Close();
                 ReservedFiles.UnReserveFile(path);
                 logger = null;
             }
         }
void BGC.IO.Logging.Logger.CloseFile (string userName, string organization, string study, string apiKey) inline
Definition at line 140 of file Logger.cs.
References BGC.Web.AWSServer.PostBGCToJSonToAWS(), BGC.IO.Utility.SafeMove(), BGC.Utility.ReservedFiles.UnReserveFile(), and BGC.IO.LogDirectories.UserErrorLogDirectory().
         {
             if (logger != null)
             {
                 logger.Close();
                 logger = null;
                 ReservedFiles.UnReserveFile(path);
                 if (pushToServer == true)
                 {
                     Assert.IsFalse(string.IsNullOrEmpty(userName));
                     Assert.IsFalse(string.IsNullOrEmpty(organization));
                     Assert.IsFalse(string.IsNullOrEmpty(study));
                     Assert.IsFalse(string.IsNullOrEmpty(apiKey));
 #if !UNITY_EDITOR
                     AWSServer.PostBGCToJSonToAWS(
                         path,
                         organization,
                         study,
                         applicationName,
                         apiKey,
                         (UnityWebRequest request, bool validJson) =>
{
                             if (validJson == true)
{
                                 if (request.isNetworkError == false)
{
                                     Utility.SafeMove(path, Path.Combine(
                                         LogDirectories.UserPermanentDirectory(userName),
                                         Path.GetFileName(path)));
                                 }
                                 else
{
                                     Debug.LogError(request.ToString());
                                 }
                             }
                             else
{
                                 Utility.SafeMove(path, Path.Combine(
                                     LogDirectories.UserErrorLogDirectory(userName),
                                     Path.GetFileName(path)));
                             }
                         });
 #endif
                 }
             }
         }
virtual JsonObject BGC.IO.Logging.Logger.ConstructAdditionalHeaders () inline protected virtual
Definition at line 60 of file Logger.cs.
 { return new JsonObject(); }
abstract JsonObject BGC.IO.Logging.Logger.ConstructColumnMapping () protected pure virtual
abstract JsonObject BGC.IO.Logging.Logger.ConstructValueMapping () protected pure virtual
string BGC.IO.Logging.Logger.DelimiterLine (params IConvertible[] strings) inline private
Definition at line 217 of file Logger.cs.
         {
             return string.Join(delimiter, strings.Select(x => x.ToString()).ToArray());
         }
string BGC.IO.Logging.Logger.GetExceptionFileName () inline private
Definition at line 189 of file Logger.cs.
References BGC.IO.LogDirectories.ExceptionDirectory.
         {
             return Path.Combine(
                 LogDirectories.ExceptionDirectory,
                 $"Exception_{TimeStamp}{FileExtensions.BGC}");
         }
void BGC.IO.Logging.Logger.OpenFile () inline private
Definition at line 105 of file Logger.cs.
References BGC.Utility.ReservedFiles.ReserveFile().
         {
             if (logger != null)
             {
                 throw new InvalidOperationException(
                     $"Must close the current file before opening a new one for \"{path}\"");
             }
             // if fileIndices is { }:           ""
             // if fileIndices is {5}:           "_005"
             // if fileIndices is {1, 2}:        "_001_002"
             // if fileIndices is {0, 1, 2}:     "_000_001_002"
             string indexString = string.Join("", fileIndices.Select(i => $"_{i.ToString("000")}"));
             string fileName = $"{userName}_{sessionNumber.ToString("000")}{indexString}_{Name}_{TimeStamp}{FileExtensions.BGC}";
             path = PathForLogFile(
                 userName: userName,
                 filename: fileName,
                 pushToServer: pushToServer);
             ReservedFiles.ReserveFile(path);
             logger = File.AppendText(path);
             ApplyHeaders();
         }
static string BGC.IO.Logging.Logger.PathForLogFile (string userName, string filename, bool pushToServer) inline static private
Definition at line 196 of file Logger.cs.
References BGC.IO.LogDirectories.UserPermanentDirectory(), and BGC.IO.LogDirectories.UserStagingDirectory().
         {
             if (pushToServer == false)
             {
                 //Files not being pushed to the server are written straight to the permanent dir
                 return Path.Combine(LogDirectories.UserPermanentDirectory(userName), filename);
             }
             return Path.Combine(LogDirectories.UserStagingDirectory(userName), filename);
         }
void BGC.IO.Logging.Logger.PushLine (params IConvertible[] strings) inline protected
Push a line to the logger. Open the logger if it's null.
Definition at line 80 of file Logger.cs.
         {
             if (logger == null)
             {
                 OpenFile();
             }
             logger.WriteLine(DelimiterLine(strings));
             logger.Flush();
         }
void BGC.IO.Logging.Logger.PushString (string str) inline protected
Push a string to the logger. Open the logger if it's null.
Definition at line 94 of file Logger.cs.
         {
             if (logger == null)
             {
                 OpenFile();
             }
             logger.Write(str);
             logger.Flush();
         }
Field Documentation
readonly string BGC.IO.Logging.Logger.applicationName private
Definition at line 21 of file Logger.cs.
readonly string BGC.IO.Logging.Logger.applicationVersion private
Definition at line 22 of file Logger.cs.
string BGC.IO.Logging.Logger.delimiter protected
Definition at line 17 of file Logger.cs.
readonly int [] BGC.IO.Logging.Logger.fileIndices private
Definition at line 26 of file Logger.cs.
StreamWriter BGC.IO.Logging.Logger.logger private
Definition at line 18 of file Logger.cs.
string BGC.IO.Logging.Logger.path private
Definition at line 19 of file Logger.cs.
readonly bool BGC.IO.Logging.Logger.pushToServer private
Definition at line 28 of file Logger.cs.
readonly int BGC.IO.Logging.Logger.sessionNumber private
Definition at line 24 of file Logger.cs.
string BGC.IO.Logging.Logger.TimeStamp => DateTime.Now.ToString("yy_MM_dd_HH_mm_ss") static protected
Definition at line 15 of file Logger.cs.
readonly string BGC.IO.Logging.Logger.userName private
Definition at line 23 of file Logger.cs.
Property Documentation
abstract string BGC.IO.Logging.Logger.Name get
Definition at line 30 of file Logger.cs.
The documentation for this class was generated from the following file:
IO/Logging/Logger.cs