BGC Tools: BGC.UI.Dialogs.ModalDialog Class Reference
BGC.UI.Dialogs.ModalDialog Class Reference
Public Types
enum Response {
Response.A = 0, Response.Confirm = A, Response.Yes = A, Response.B,
Response.Cancel = B, Response.No = B, Response.C, Response.Accept = C
}
enum Mode {
Mode.ConfirmCancel = 0, Mode.Accept, Mode.YesNo, Mode.InputConfirmCancel,
Mode.InputAccept, Mode.LockDown, Mode.ABC, Mode.InputInputConfirmCancel,
Mode.DropdownInput
}
Public Member Functions
delegate void ModalButtonCallback (Response response)
delegate void ModalInputCallback (Response response, string inputText)
delegate void ModalDoubleInputCallback (Response response, string primaryInput, string secondaryInput)
delegate void ModalDropdownInputCallback (Response response, int selectionIndex, string secondaryInput)
ModalDialog ()
void Initialize ()
Static Public Member Functions
static void ShowSimpleModal (Mode mode, string headerText, string bodyText, ModalButtonCallback callback=null)
Show the modal dialog in the indicated mode, and call the callback when it receives a response
static void ShowCustomSimpleModal (string headerText, string bodyText, string buttonALabel, string buttonBLabel, string buttonCLabel, ModalButtonCallback callback)
Show the modal dialog in the indicated mode, and call the callback when it receives a response
static void ShowInputModal (Mode mode, string headerText, string bodyText, ModalInputCallback inputCallback, ModalButtonCallback buttonCallback=null)
Show the modal dialog in the indicated mode, and call the callback when it receives a response
static void ShowInputModal (string headerText, string primaryBodyText, string secondaryBodyText, ModalDoubleInputCallback inputCallback, ModalButtonCallback buttonCallback=null)
Show the modal dialog in the indicated mode, and call the callback when it receives a response
static void ShowDropdownInputModal (string headerText, string primaryBodyText, string secondaryBodyText, IEnumerable< string > dropdownOptions, ModalDropdownInputCallback inputCallback, ModalButtonCallback buttonCallback=null)
Show the modal dialog in the indicated mode, and call the callback when it receives a response
Private Member Functions
void Awake ()
void SetHeaderText (string text)
void SetBodyText (string primaryText, string secondaryText="")
void SetMode (Mode mode)
void SetButtonText (string a="", string b="", string c="")
void HandleButtons (Response response)
Accept the button repsonse as input, invoke and clear the callbacks, and hide the dialog
Private Attributes
Button buttonA = null
Button buttonB = null
Button buttonC = null
Text headerText = null
Text primaryBodyText = null
InputField primaryInputField = null
Dropdown optionDropdown = null
Text secondaryBodyText = null
InputField secondaryInputField = null
ModalButtonCallback buttonCallback
ModalInputCallback inputCallback
ModalDoubleInputCallback doubleInputCallback
ModalDropdownInputCallback dropdownInputCallback
Static Private Attributes
static ModalDialog instance
Detailed Description
Definition at line 9 of file ModalDialog.cs.
Member Enumeration Documentation
Mode
enum BGC.UI.Dialogs.ModalDialog.Mode strong
Enumerator
ConfirmCancel
Accept
YesNo
InputConfirmCancel
InputAccept
LockDown
ABC
InputInputConfirmCancel
DropdownInput
Definition at line 49 of file ModalDialog.cs.
         {
             ConfirmCancel = 0,
             Accept,
             YesNo,
             InputConfirmCancel,
             InputAccept,
             LockDown,
             ABC,
             InputInputConfirmCancel,
             DropdownInput
         }
Response
enum BGC.UI.Dialogs.ModalDialog.Response strong
Enumerator
A
Confirm
Yes
B
Cancel
No
C
Accept
Definition at line 35 of file ModalDialog.cs.
         {
             A = 0,
             Confirm = A,
             Yes = A,
             B,
             Cancel = B,
             No = B,
             C,
             Accept = C
         }
Constructor & Destructor Documentation
ModalDialog()
BGC.UI.Dialogs.ModalDialog.ModalDialog () inline
Definition at line 74 of file ModalDialog.cs.
         {
             instance = this;
         }
Member Function Documentation
Awake()
void BGC.UI.Dialogs.ModalDialog.Awake () inline private
Definition at line 84 of file ModalDialog.cs.
         {
             buttonA.onClick.AddListener(() => HandleButtons(Response.A));
             buttonB.onClick.AddListener(() => HandleButtons(Response.B));
             buttonC.onClick.AddListener(() => HandleButtons(Response.C));
         }
HandleButtons()
void BGC.UI.Dialogs.ModalDialog.HandleButtons (Response response) inline private
Accept the button repsonse as input, invoke and clear the callbacks, and hide the dialog
Definition at line 288 of file ModalDialog.cs.
         {
             //Temporary copy to allow for the calling of the dialog within a callback
             ModalButtonCallback tmpCallback = buttonCallback;
             ModalInputCallback tmpInputCallback = inputCallback;
             ModalDoubleInputCallback tmpDoubleInputCallback = doubleInputCallback;
             ModalDropdownInputCallback tmpDropdownInputCallback = dropdownInputCallback;
             buttonCallback = null;
             inputCallback = null;
             doubleInputCallback = null;
             dropdownInputCallback = null;
             gameObject.SetActive(false);
             tmpCallback?.Invoke(response);
             tmpInputCallback?.Invoke(response, primaryInputField.text);
             tmpDoubleInputCallback?.Invoke(response, primaryInputField.text, secondaryInputField.text);
             tmpDropdownInputCallback?.Invoke(response, optionDropdown.value, secondaryInputField.text);
         }
Initialize()
void BGC.UI.Dialogs.ModalDialog.Initialize () inline
Definition at line 79 of file ModalDialog.cs.
         {
             instance = this;
         }
ModalButtonCallback()
delegate void BGC.UI.Dialogs.ModalDialog.ModalButtonCallback (Response response)
ModalDoubleInputCallback()
delegate void BGC.UI.Dialogs.ModalDialog.ModalDoubleInputCallback (Response response, string primaryInput, string secondaryInput)
ModalDropdownInputCallback()
delegate void BGC.UI.Dialogs.ModalDialog.ModalDropdownInputCallback (Response response, int selectionIndex, string secondaryInput)
ModalInputCallback()
delegate void BGC.UI.Dialogs.ModalDialog.ModalInputCallback (Response response, string inputText)
SetBodyText()
void BGC.UI.Dialogs.ModalDialog.SetBodyText (string primaryText, string secondaryText = "") inline private
Definition at line 96 of file ModalDialog.cs.
Referenced by BGC.UI.Dialogs.ModalDialog.ShowCustomSimpleModal(), BGC.UI.Dialogs.ModalDialog.ShowDropdownInputModal(), BGC.UI.Dialogs.ModalDialog.ShowInputModal(), and BGC.UI.Dialogs.ModalDialog.ShowSimpleModal().
         {
             primaryBodyText.text = primaryText;
             secondaryBodyText.text = secondaryText;
         }
SetButtonText()
void BGC.UI.Dialogs.ModalDialog.SetButtonText (string a = "", string b = "", string c = "") inline private
Definition at line 152 of file ModalDialog.cs.
Referenced by BGC.UI.Dialogs.ModalDialog.ShowCustomSimpleModal().
         {
             buttonA.gameObject.SetActive(string.IsNullOrEmpty(a) == false);
             buttonB.gameObject.SetActive(string.IsNullOrEmpty(b) == false);
             buttonC.gameObject.SetActive(string.IsNullOrEmpty(c) == false);
             buttonA.GetComponentInChildren<Text>().text = a;
             buttonB.GetComponentInChildren<Text>().text = b;
             buttonC.GetComponentInChildren<Text>().text = c;
         }
SetHeaderText()
void BGC.UI.Dialogs.ModalDialog.SetHeaderText (string text) inline private
Definition at line 91 of file ModalDialog.cs.
Referenced by BGC.UI.Dialogs.ModalDialog.ShowCustomSimpleModal(), BGC.UI.Dialogs.ModalDialog.ShowDropdownInputModal(), BGC.UI.Dialogs.ModalDialog.ShowInputModal(), and BGC.UI.Dialogs.ModalDialog.ShowSimpleModal().
         {
             headerText.text = text;
         }
SetMode()
void BGC.UI.Dialogs.ModalDialog.SetMode (Mode mode) inline private
Definition at line 102 of file ModalDialog.cs.
Referenced by BGC.UI.Dialogs.ModalDialog.ShowCustomSimpleModal(), BGC.UI.Dialogs.ModalDialog.ShowDropdownInputModal(), BGC.UI.Dialogs.ModalDialog.ShowInputModal(), and BGC.UI.Dialogs.ModalDialog.ShowSimpleModal().
         {
             primaryInputField.text = "";
             primaryInputField.gameObject.SetActive(
                 mode == Mode.InputAccept ||
                 mode == Mode.InputConfirmCancel ||
                 mode == Mode.InputInputConfirmCancel);
             secondaryBodyText.gameObject.SetActive(mode == Mode.InputInputConfirmCancel || mode == Mode.DropdownInput);
             secondaryInputField.text = "";
             secondaryInputField.gameObject.SetActive(mode == Mode.InputInputConfirmCancel || mode == Mode.DropdownInput);
             optionDropdown.gameObject.SetActive(mode == Mode.DropdownInput);
             //Set button text
             switch (mode)
             {
                 case Mode.ConfirmCancel:
                 case Mode.InputConfirmCancel:
                 case Mode.InputInputConfirmCancel:
                 case Mode.DropdownInput:
                     SetButtonText(a: "Confirm", b: "Cancel");
                     break;
                 case Mode.YesNo:
                     SetButtonText(a: "Yes", b: "No");
                     break;
                 case Mode.Accept:
                 case Mode.InputAccept:
                     SetButtonText(c: "Ok");
                     break;
                 case Mode.ABC:
                     //Do nothing - Text set separately
                     break;
                 case Mode.LockDown:
                     //Clear & Lock all buttons
                     SetButtonText(a: "", b: "", c: "");
                     break;
                 default:
                     Debug.LogError($"Unexpected DialogMode: {mode}");
                     break;
             }
         }
ShowCustomSimpleModal()
static void BGC.UI.Dialogs.ModalDialog.ShowCustomSimpleModal (string headerText, string bodyText, string buttonALabel, string buttonBLabel, string buttonCLabel, ModalButtonCallback callback) inline static
Show the modal dialog in the indicated mode, and call the callback when it receives a response
Definition at line 201 of file ModalDialog.cs.
References BGC.UI.Dialogs.ModalDialog.buttonCallback, BGC.UI.Dialogs.ModalDialog.doubleInputCallback, BGC.UI.Dialogs.ModalDialog.dropdownInputCallback, BGC.UI.Dialogs.ModalDialog.inputCallback, BGC.UI.Dialogs.ModalDialog.SetBodyText(), BGC.UI.Dialogs.ModalDialog.SetButtonText(), BGC.UI.Dialogs.ModalDialog.SetHeaderText(), and BGC.UI.Dialogs.ModalDialog.SetMode().
         {
             //Update Text
             instance.SetHeaderText(headerText);
             instance.SetBodyText(bodyText);
             //Update buttons
             instance.SetMode(Mode.ABC);
             instance.SetButtonText(buttonALabel, buttonBLabel, buttonCLabel);
             //Set dialog visible
             instance.gameObject.SetActive(true);
             //Update Callbacks
             instance.buttonCallback = callback;
             instance.inputCallback = null;
             instance.doubleInputCallback = null;
             instance.dropdownInputCallback = null;
         }
ShowDropdownInputModal()
static void BGC.UI.Dialogs.ModalDialog.ShowDropdownInputModal (string headerText, string primaryBodyText, string secondaryBodyText, IEnumerable< string > dropdownOptions, ModalDropdownInputCallback inputCallback, ModalButtonCallback buttonCallback = null) inline static
Show the modal dialog in the indicated mode, and call the callback when it receives a response
Definition at line 312 of file ModalDialog.cs.
References BGC.UI.Dialogs.ModalDialog.buttonCallback, BGC.UI.Dialogs.ModalDialog.doubleInputCallback, BGC.UI.Dialogs.ModalDialog.dropdownInputCallback, BGC.UI.Dialogs.ModalDialog.inputCallback, BGC.UI.Dialogs.ModalDialog.optionDropdown, BGC.UI.Dialogs.ModalDialog.SetBodyText(), BGC.UI.Dialogs.ModalDialog.SetHeaderText(), and BGC.UI.Dialogs.ModalDialog.SetMode().
         {
             //Update text
             instance.SetHeaderText(headerText);
             instance.SetBodyText(primaryBodyText, secondaryBodyText);
             //Update buttons
             instance.SetMode(Mode.DropdownInput);
             //Update dropdown
             instance.optionDropdown.ClearOptions();
             instance.optionDropdown.AddOptions(dropdownOptions.ToList());
             instance.optionDropdown.value = 0;
             instance.optionDropdown.RefreshShownValue();
             //Set dialog visible
             instance.gameObject.SetActive(true);
             //Update callbacks
             instance.buttonCallback = buttonCallback;
             instance.inputCallback = null;
             instance.doubleInputCallback = null;
             instance.dropdownInputCallback = inputCallback;
         }
ShowInputModal() [1/2]
static void BGC.UI.Dialogs.ModalDialog.ShowInputModal (Mode mode, string headerText, string bodyText, ModalInputCallback inputCallback, ModalButtonCallback buttonCallback = null) inline static
Show the modal dialog in the indicated mode, and call the callback when it receives a response
Definition at line 230 of file ModalDialog.cs.
References BGC.UI.Dialogs.ModalDialog.buttonCallback, BGC.UI.Dialogs.ModalDialog.doubleInputCallback, BGC.UI.Dialogs.ModalDialog.dropdownInputCallback, BGC.UI.Dialogs.ModalDialog.inputCallback, BGC.UI.Dialogs.ModalDialog.SetBodyText(), BGC.UI.Dialogs.ModalDialog.SetHeaderText(), and BGC.UI.Dialogs.ModalDialog.SetMode().
         {
             Debug.Assert(
                 condition: mode == Mode.InputAccept || mode == Mode.InputConfirmCancel,
                 message: "Incorrect method call.  Don't call ShowInputModal if not using input.");
             //Update text
             instance.SetHeaderText(headerText);
             instance.SetBodyText(bodyText);
             //Update buttons
             instance.SetMode(mode);
             //Set dialog visible
             instance.gameObject.SetActive(true);
             //Update callbacks
             instance.buttonCallback = buttonCallback;
             instance.inputCallback = inputCallback;
             instance.doubleInputCallback = null;
             instance.dropdownInputCallback = null;
         }
ShowInputModal() [2/2]
static void BGC.UI.Dialogs.ModalDialog.ShowInputModal (string headerText, string primaryBodyText, string secondaryBodyText, ModalDoubleInputCallback inputCallback, ModalButtonCallback buttonCallback = null) inline static
Show the modal dialog in the indicated mode, and call the callback when it receives a response
Definition at line 261 of file ModalDialog.cs.
References BGC.UI.Dialogs.ModalDialog.buttonCallback, BGC.UI.Dialogs.ModalDialog.doubleInputCallback, BGC.UI.Dialogs.ModalDialog.dropdownInputCallback, BGC.UI.Dialogs.ModalDialog.inputCallback, BGC.UI.Dialogs.ModalDialog.SetBodyText(), BGC.UI.Dialogs.ModalDialog.SetHeaderText(), and BGC.UI.Dialogs.ModalDialog.SetMode().
         {
             //Update text
             instance.SetHeaderText(headerText);
             instance.SetBodyText(primaryBodyText, secondaryBodyText);
             //Update buttons
             instance.SetMode(Mode.InputInputConfirmCancel);
             //Set dialog visible
             instance.gameObject.SetActive(true);
             //Update callbacks
             instance.buttonCallback = buttonCallback;
             instance.inputCallback = null;
             instance.doubleInputCallback = inputCallback;
             instance.dropdownInputCallback = null;
         }
ShowSimpleModal()
static void BGC.UI.Dialogs.ModalDialog.ShowSimpleModal (Mode mode, string headerText, string bodyText, ModalButtonCallback callback = null) inline static
Show the modal dialog in the indicated mode, and call the callback when it receives a response
Definition at line 166 of file ModalDialog.cs.
References BGC.UI.Dialogs.ModalDialog.buttonCallback, BGC.UI.Dialogs.ModalDialog.doubleInputCallback, BGC.UI.Dialogs.ModalDialog.dropdownInputCallback, BGC.UI.Dialogs.ModalDialog.inputCallback, BGC.UI.Dialogs.ModalDialog.SetBodyText(), BGC.UI.Dialogs.ModalDialog.SetHeaderText(), and BGC.UI.Dialogs.ModalDialog.SetMode().
         {
             Debug.Assert(
                 condition: mode != Mode.InputAccept && mode != Mode.InputConfirmCancel,
                 message: "Incorrect method call.  Call ShowInputModal instead.");
             Debug.Assert(
                 condition: mode != Mode.InputInputConfirmCancel,
                 message: "Incorrect method call.  Call ShowInputModal instead.");
             //Update text
             instance.SetHeaderText(headerText);
             instance.SetBodyText(bodyText);
             //Update buttons
             instance.SetMode(mode);
             //Set dialog visible
             instance.gameObject.SetActive(true);
             //Update Callbacks
             instance.buttonCallback = callback;
             instance.inputCallback = null;
             instance.doubleInputCallback = null;
             instance.dropdownInputCallback = null;
         }
Field Documentation
buttonA
Button BGC.UI.Dialogs.ModalDialog.buttonA = null private
Definition at line 13 of file ModalDialog.cs.
buttonB
Button BGC.UI.Dialogs.ModalDialog.buttonB = null private
Definition at line 15 of file ModalDialog.cs.
buttonC
Button BGC.UI.Dialogs.ModalDialog.buttonC = null private
Definition at line 17 of file ModalDialog.cs.
buttonCallback
ModalButtonCallback BGC.UI.Dialogs.ModalDialog.buttonCallback private
Definition at line 63 of file ModalDialog.cs.
Referenced by BGC.UI.Dialogs.ModalDialog.ShowCustomSimpleModal(), BGC.UI.Dialogs.ModalDialog.ShowDropdownInputModal(), BGC.UI.Dialogs.ModalDialog.ShowInputModal(), and BGC.UI.Dialogs.ModalDialog.ShowSimpleModal().
doubleInputCallback
ModalDoubleInputCallback BGC.UI.Dialogs.ModalDialog.doubleInputCallback private
Definition at line 69 of file ModalDialog.cs.
Referenced by BGC.UI.Dialogs.ModalDialog.ShowCustomSimpleModal(), BGC.UI.Dialogs.ModalDialog.ShowDropdownInputModal(), BGC.UI.Dialogs.ModalDialog.ShowInputModal(), and BGC.UI.Dialogs.ModalDialog.ShowSimpleModal().
dropdownInputCallback
ModalDropdownInputCallback BGC.UI.Dialogs.ModalDialog.dropdownInputCallback private
Definition at line 72 of file ModalDialog.cs.
Referenced by BGC.UI.Dialogs.ModalDialog.ShowCustomSimpleModal(), BGC.UI.Dialogs.ModalDialog.ShowDropdownInputModal(), BGC.UI.Dialogs.ModalDialog.ShowInputModal(), and BGC.UI.Dialogs.ModalDialog.ShowSimpleModal().
headerText
Text BGC.UI.Dialogs.ModalDialog.headerText = null private
Definition at line 21 of file ModalDialog.cs.
inputCallback
ModalInputCallback BGC.UI.Dialogs.ModalDialog.inputCallback private
Definition at line 66 of file ModalDialog.cs.
Referenced by BGC.UI.Dialogs.ModalDialog.ShowCustomSimpleModal(), BGC.UI.Dialogs.ModalDialog.ShowDropdownInputModal(), BGC.UI.Dialogs.ModalDialog.ShowInputModal(), and BGC.UI.Dialogs.ModalDialog.ShowSimpleModal().
instance
ModalDialog BGC.UI.Dialogs.ModalDialog.instance static private
Definition at line 33 of file ModalDialog.cs.
optionDropdown
Dropdown BGC.UI.Dialogs.ModalDialog.optionDropdown = null private
Definition at line 27 of file ModalDialog.cs.
Referenced by BGC.UI.Dialogs.ModalDialog.ShowDropdownInputModal().
primaryBodyText
Text BGC.UI.Dialogs.ModalDialog.primaryBodyText = null private
Definition at line 23 of file ModalDialog.cs.
primaryInputField
InputField BGC.UI.Dialogs.ModalDialog.primaryInputField = null private
Definition at line 25 of file ModalDialog.cs.
secondaryBodyText
Text BGC.UI.Dialogs.ModalDialog.secondaryBodyText = null private
Definition at line 29 of file ModalDialog.cs.
secondaryInputField
InputField BGC.UI.Dialogs.ModalDialog.secondaryInputField = null private
Definition at line 31 of file ModalDialog.cs.
The documentation for this class was generated from the following file:
UI/Dialogs/ModalDialog/ModalDialog.cs