BGC Tools: BGC.Audio.Filters.MultiConvolutionFilter Class Reference
BGC.Audio.Filters.MultiConvolutionFilter Class Reference
Performs a convolution on the underlying stream, generating one independent channel for each supplied filter.
Public Member Functions
MultiConvolutionFilter (IBGCStream stream, float[] filterL, float[] filterR, bool recalculateRMS=false)
MultiConvolutionFilter (IBGCStream stream, double[] filterL, double[] filterR, bool recalculateRMS=false)
MultiConvolutionFilter (IBGCStream stream, IBGCStream filter, bool recalculateRMS=false)
override int Read (float[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
override void Reset ()
Sets this internal state of this stream to the initial state
override void Seek (int position)
Seek to the indicated position in the stream
override IEnumerable< double > GetChannelRMS ()
The RMS amplitude of each channel
Public Member Functions inherited from BGC.Audio.Filters.SimpleBGCFilter
SimpleBGCFilter (IBGCStream stream)
override void Seek (int position)
Seek to the indicated position in the stream
override void Reset ()
Sets this internal state of this stream to the initial state
override void Initialize ()
Perform any calculations necessary to prepare the Stream
Protected Member Functions
override void _Initialize ()
Properties
override int Channels [get]
override int TotalSamples [get]
override int ChannelSamples [get]
Properties inherited from BGC.Audio.Filters.SimpleBGCFilter
override IEnumerable< IBGCStream > InternalStreams [get]
Properties inherited from BGC.Audio.Filters.BGCFilter
abstract int Channels [get]
abstract int TotalSamples [get]
abstract int ChannelSamples [get]
abstract float SamplingRate [get]
abstract IEnumerable< IBGCStream > InternalStreams [get]
Properties inherited from BGC.Audio.IBGCStream
int Channels [get]
The number of underlying Channels of this BGCStream
int TotalSamples [get]
The total number of Samples of this BGCStream
int ChannelSamples [get]
The number of Samples of each channel for this BGCStream
float SamplingRate [get]
The sampling rate of the Stream
Private Member Functions
int ReadBody (float[] buffer, int offset, int count)
void ClearBuffers ()
Private Attributes
const int FFT_EXP_MIN = 9
const int FFT_SIZE_BUMP = 1
readonly float [] inputBuffer
readonly Complex64 [][] filterFD
readonly Complex64 [] fftBuffer
readonly Complex64 [] ifftBuffer
readonly float [] outputAccumulation
readonly int fftLength
readonly int samplesPerOverlap
readonly int filterLength
int bufferIndex = 0
int bufferCount = 0
readonly bool recalculateRMS
IEnumerable< double > _channelRMS = null
Additional Inherited Members
Data Fields inherited from BGC.Audio.Filters.SimpleBGCFilter
override float SamplingRate => stream.SamplingRate
Protected Attributes inherited from BGC.Audio.Filters.SimpleBGCFilter
readonly IBGCStream stream
Protected Attributes inherited from BGC.Audio.Filters.BGCFilter
bool initialized = false
Detailed Description
Performs a convolution on the underlying stream, generating one independent channel for each supplied filter.
Definition at line 13 of file MultiConvolutionFilter.cs.
Constructor & Destructor Documentation
MultiConvolutionFilter() [1/3]
BGC.Audio.Filters.MultiConvolutionFilter.MultiConvolutionFilter (IBGCStream stream, float [] filterL, float [] filterR, bool recalculateRMS = false) inline
Definition at line 39 of file MultiConvolutionFilter.cs.
References BGC.Audio.IBGCStream.Channels, and BGC.Audio.IBGCStream.ChannelSamples.
             : base(stream)
         {
             Debug.Assert(stream.Channels == 1);
             Debug.Assert(filterL.Length == filterR.Length);
             filterLength = filterL.Length;
             Channels = 2;
             int fftSize = Math.Max(FFT_EXP_MIN, filterLength.ToNextExponentOf2() + FFT_SIZE_BUMP);
             fftLength = 1 << fftSize;
             samplesPerOverlap = fftLength - filterLength;
             //Protect against infinite streams
             if (stream.ChannelSamples == int.MaxValue)
             {
                 ChannelSamples = int.MaxValue;
                 TotalSamples = int.MaxValue;
             }
             else
             {
                 ChannelSamples = filterLength + stream.ChannelSamples - 1;
                 TotalSamples = Channels * ChannelSamples;
             }
             inputBuffer = new float[samplesPerOverlap];
             outputAccumulation = new float[Channels * fftLength];
             fftBuffer = new Complex64[fftLength];
             ifftBuffer = new Complex64[fftLength];
             filterFD = new Complex64[Channels][];
             filterFD[0] = new Complex64[fftLength];
             filterFD[1] = new Complex64[fftLength];
             for (int i = 0; i < filterLength; i++)
             {
                 filterFD[0][i] = filterL[i];
                 filterFD[1][i] = filterR[i];
             }
             initialized = false;
             this.recalculateRMS = recalculateRMS;
         }
MultiConvolutionFilter() [2/3]
BGC.Audio.Filters.MultiConvolutionFilter.MultiConvolutionFilter (IBGCStream stream, double [] filterL, double [] filterR, bool recalculateRMS = false) inline
Definition at line 88 of file MultiConvolutionFilter.cs.
References BGC.Audio.IBGCStream.Channels, and BGC.Audio.IBGCStream.ChannelSamples.
             : base(stream)
         {
             Debug.Assert(stream.Channels == 1);
             Debug.Assert(filterL.Length == filterR.Length);
             filterLength = filterL.Length;
             Channels = 2;
             int fftSize = Math.Max(FFT_EXP_MIN, filterLength.ToNextExponentOf2() + FFT_SIZE_BUMP);
             fftLength = 1 << fftSize;
             samplesPerOverlap = fftLength - filterLength;
             //Protect against infinite streams
             if (stream.ChannelSamples == int.MaxValue)
             {
                 ChannelSamples = int.MaxValue;
                 TotalSamples = int.MaxValue;
             }
             else
             {
                 ChannelSamples = filterLength + stream.ChannelSamples - 1;
                 TotalSamples = Channels * ChannelSamples;
             }
             inputBuffer = new float[samplesPerOverlap];
             outputAccumulation = new float[Channels * fftLength];
             fftBuffer = new Complex64[fftLength];
             ifftBuffer = new Complex64[fftLength];
             filterFD = new Complex64[Channels][];
             filterFD[0] = new Complex64[fftLength];
             filterFD[1] = new Complex64[fftLength];
             for (int i = 0; i < filterLength; i++)
             {
                 filterFD[0][i] = filterL[i];
                 filterFD[1][i] = filterR[i];
             }
             initialized = false;
             this.recalculateRMS = recalculateRMS;
         }
MultiConvolutionFilter() [3/3]
BGC.Audio.Filters.MultiConvolutionFilter.MultiConvolutionFilter (IBGCStream stream, IBGCStream filter, bool recalculateRMS = false) inline
Definition at line 137 of file MultiConvolutionFilter.cs.
References BGC.Audio.IBGCStream.Channels, and BGC.Audio.IBGCStream.ChannelSamples.
             : base(stream)
         {
             Debug.Assert(stream.Channels == 1);
             filterLength = filter.ChannelSamples;
             Channels = filter.Channels;
             int fftSize = Math.Max(FFT_EXP_MIN, filterLength.ToNextExponentOf2() + FFT_SIZE_BUMP);
             fftLength = 1 << fftSize;
             samplesPerOverlap = fftLength - filterLength;
             //Protect against infinite streams
             if (stream.ChannelSamples == int.MaxValue)
             {
                 ChannelSamples = int.MaxValue;
                 TotalSamples = int.MaxValue;
             }
             else
             {
                 ChannelSamples = filterLength + stream.ChannelSamples - 1;
                 TotalSamples = Channels * ChannelSamples;
             }
             inputBuffer = new float[samplesPerOverlap];
             outputAccumulation = new float[Channels * fftLength];
             fftBuffer = new Complex64[fftLength];
             ifftBuffer = new Complex64[fftLength];
             filterFD = new Complex64[Channels][];
             for (int i = 0; i < Channels; i++)
             {
                 filterFD[i] = filter.ComplexSamples(i, fftLength);
             }
             initialized = false;
             this.recalculateRMS = recalculateRMS;
         }
Member Function Documentation
_Initialize()
override void BGC.Audio.Filters.MultiConvolutionFilter._Initialize () inline protected virtual
Reimplemented from BGC.Audio.Filters.BGCFilter.
Definition at line 181 of file MultiConvolutionFilter.cs.
References BGC.Mathematics.Fourier.Forward().
         {
             double factor = fftLength;
             for (int i = 0; i < Channels; i++)
             {
                 Fourier.Forward(filterFD[i]);
                 for (int j = 0; j < fftLength; j++)
                 {
                     filterFD[i][j] *= factor;
                 }
             }
         }
ClearBuffers()
void BGC.Audio.Filters.MultiConvolutionFilter.ClearBuffers () inline private
Definition at line 291 of file MultiConvolutionFilter.cs.
         {
             bufferIndex = 0;
             bufferCount = 0;
             Array.Clear(outputAccumulation, 0, outputAccumulation.Length);
             Array.Clear(inputBuffer, 0, inputBuffer.Length);
         }
GetChannelRMS()
override IEnumerable<double> BGC.Audio.Filters.MultiConvolutionFilter.GetChannelRMS () inline virtual
The RMS amplitude of each channel
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 313 of file MultiConvolutionFilter.cs.
         {
             if (_channelRMS == null)
             {
                 if (recalculateRMS)
                 {
                     _channelRMS = this.CalculateRMS();
                 }
                 else
                 {
                     _channelRMS = Enumerable.Repeat(stream.GetChannelRMS().First(), Channels);
                 }
             }
             return _channelRMS;
         }
Read()
override int BGC.Audio.Filters.MultiConvolutionFilter.Read (float [] data, int offset, int count) inline virtual
Copy count samples into the Data buffer, starting at offset.
Returns
The number of samples copied
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 196 of file MultiConvolutionFilter.cs.
References BGC.Mathematics.Fourier.Forward(), and BGC.Mathematics.Fourier.Inverse().
         {
             if (!initialized)
             {
                 Initialize();
             }
             int samplesWritten = ReadBody(data, offset, count);
             while (samplesWritten < count)
             {
                 int read = stream.Read(inputBuffer, 0, inputBuffer.Length);
                 if (read <= 0)
                 {
                     //Done, No samples left to work with
                     break;
                 }
                 //Slide output samples over to accumulate on the remainder
                 Array.Copy(
                     sourceArray: outputAccumulation,
                     sourceIndex: bufferCount,
                     destinationArray: outputAccumulation,
                     destinationIndex: 0,
                     length: outputAccumulation.Length - bufferCount);
                 Array.Clear(
                     array: outputAccumulation,
                     index: outputAccumulation.Length - bufferCount,
                     length: bufferCount);
                 bufferIndex = 0;
                 bufferCount = Channels * samplesPerOverlap;
                 if (read < inputBuffer.Length)
                 {
                     //Copy all the remaining samples
                     //We are guaranteed to have enough room because the output buffer's
                     //length is Channels * (inputBuffer.Length + fftLength)
                     bufferCount = Channels * (read + filterLength - 1);
                     //Set rest of inputBuffer to zero
                     Array.Clear(inputBuffer, read, inputBuffer.Length - read);
                 }
                 for (int i = 0; i < samplesPerOverlap; i++)
                 {
                     fftBuffer[i] = inputBuffer[i];
                 }
                 Array.Clear(fftBuffer, samplesPerOverlap, fftLength - samplesPerOverlap);
                 //FFT
                 Fourier.Forward(fftBuffer);
                 for (int channel = 0; channel < Channels; channel++)
                 {
                     for (int i = 0; i < fftLength; i++)
                     {
                         ifftBuffer[i] = fftBuffer[i] * filterFD[channel][i];
                     }
                     //IFFT
                     Fourier.Inverse(ifftBuffer);
                     //Accumualte the window samples
                     for (int i = 0; i < fftLength; i++)
                     {
                         outputAccumulation[Channels * i + channel] += (float)ifftBuffer[i].Real;
                     }
                 }
                 samplesWritten += ReadBody(data, offset + samplesWritten, count - samplesWritten);
             }
             return samplesWritten;
         }
ReadBody()
int BGC.Audio.Filters.MultiConvolutionFilter.ReadBody (float [] buffer, int offset, int count) inline private
Definition at line 275 of file MultiConvolutionFilter.cs.
References BGC.Mathematics.GeneralMath.Clamp().
         {
             int samplesWritten = GeneralMath.Clamp(count, 0, bufferCount - bufferIndex);
             Array.Copy(
                 sourceArray: outputAccumulation,
                 sourceIndex: bufferIndex,
                 destinationArray: buffer,
                 destinationIndex: offset,
                 length: samplesWritten);
             bufferIndex += samplesWritten;
             return samplesWritten;
         }
Reset()
override void BGC.Audio.Filters.MultiConvolutionFilter.Reset () inline virtual
Sets this internal state of this stream to the initial state
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 300 of file MultiConvolutionFilter.cs.
         {
             ClearBuffers();
             stream.Reset();
         }
Seek()
override void BGC.Audio.Filters.MultiConvolutionFilter.Seek (int position) inline virtual
Seek to the indicated position in the stream
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 306 of file MultiConvolutionFilter.cs.
         {
             ClearBuffers();
             stream.Seek(position);
         }
Field Documentation
_channelRMS
IEnumerable<double> BGC.Audio.Filters.MultiConvolutionFilter._channelRMS = null private
Definition at line 312 of file MultiConvolutionFilter.cs.
bufferCount
int BGC.Audio.Filters.MultiConvolutionFilter.bufferCount = 0 private
Definition at line 30 of file MultiConvolutionFilter.cs.
bufferIndex
int BGC.Audio.Filters.MultiConvolutionFilter.bufferIndex = 0 private
Definition at line 29 of file MultiConvolutionFilter.cs.
FFT_EXP_MIN
const int BGC.Audio.Filters.MultiConvolutionFilter.FFT_EXP_MIN = 9 private
Definition at line 15 of file MultiConvolutionFilter.cs.
FFT_SIZE_BUMP
const int BGC.Audio.Filters.MultiConvolutionFilter.FFT_SIZE_BUMP = 1 private
Definition at line 16 of file MultiConvolutionFilter.cs.
fftBuffer
readonly Complex64 [] BGC.Audio.Filters.MultiConvolutionFilter.fftBuffer private
Definition at line 20 of file MultiConvolutionFilter.cs.
fftLength
readonly int BGC.Audio.Filters.MultiConvolutionFilter.fftLength private
Definition at line 24 of file MultiConvolutionFilter.cs.
filterFD
readonly Complex64 [][] BGC.Audio.Filters.MultiConvolutionFilter.filterFD private
Definition at line 19 of file MultiConvolutionFilter.cs.
filterLength
readonly int BGC.Audio.Filters.MultiConvolutionFilter.filterLength private
Definition at line 27 of file MultiConvolutionFilter.cs.
ifftBuffer
readonly Complex64 [] BGC.Audio.Filters.MultiConvolutionFilter.ifftBuffer private
Definition at line 21 of file MultiConvolutionFilter.cs.
inputBuffer
readonly float [] BGC.Audio.Filters.MultiConvolutionFilter.inputBuffer private
Definition at line 18 of file MultiConvolutionFilter.cs.
outputAccumulation
readonly float [] BGC.Audio.Filters.MultiConvolutionFilter.outputAccumulation private
Definition at line 22 of file MultiConvolutionFilter.cs.
recalculateRMS
readonly bool BGC.Audio.Filters.MultiConvolutionFilter.recalculateRMS private
Definition at line 31 of file MultiConvolutionFilter.cs.
samplesPerOverlap
readonly int BGC.Audio.Filters.MultiConvolutionFilter.samplesPerOverlap private
Definition at line 25 of file MultiConvolutionFilter.cs.
Property Documentation
Channels
override int BGC.Audio.Filters.MultiConvolutionFilter.Channels get
Definition at line 33 of file MultiConvolutionFilter.cs.
ChannelSamples
override int BGC.Audio.Filters.MultiConvolutionFilter.ChannelSamples get
Definition at line 37 of file MultiConvolutionFilter.cs.
TotalSamples
override int BGC.Audio.Filters.MultiConvolutionFilter.TotalSamples get
Definition at line 35 of file MultiConvolutionFilter.cs.
The documentation for this class was generated from the following file:
Audio/Filters/MultiConvolutionFilter.cs