BGC Tools: BGC.Audio.Synthesis.ActiveNoteStream Class Reference
BGC.Audio.Synthesis.ActiveNoteStream Class Reference
Stores and renders a set of active notes. Generally meant to interact with Active ADSR Envelopes.
Public Member Functions
ActiveNoteStream ()
void AddStream (int key, IBGCStream stream)
bool RemoveStream (IBGCStream stream)
bool RemoveStream (int key)
override void Reset ()
Sets this internal state of this stream to the initial state
void Clear ()
override int Read (float[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
bool Release (int key, bool immediate=false)
override void Seek (int position)
Seek to the indicated position in the stream
override IEnumerable< double > GetChannelRMS ()
The RMS amplitude of each channel
Public Member Functions inherited from BGC.Audio.Filters.BGCFilter
virtual void Initialize ()
Perform any calculations necessary to prepare the Stream
Data Fields
override IEnumerable< IBGCStream > InternalStreams => streams.Values
override int Channels => 1
override int TotalSamples => int.MaxValue
override int ChannelSamples => int.MaxValue
override float SamplingRate => 44100f
Private Attributes
List< IBGCStream > pendingDeletions = new List<IBGCStream>()
List< IBGCStream > collisionNotes = new List<IBGCStream>()
readonly Dictionary< int, IBGCStream > streams = new Dictionary<int, IBGCStream>()
const int BUFFER_SIZE = 512
readonly float [] buffer = new float[BUFFER_SIZE]
Additional Inherited Members
Protected Member Functions inherited from BGC.Audio.Filters.BGCFilter
virtual void _Initialize ()
Protected Attributes inherited from BGC.Audio.Filters.BGCFilter
bool initialized = false
Properties inherited from BGC.Audio.Filters.BGCFilter
abstract int Channels [get]
abstract int TotalSamples [get]
abstract int ChannelSamples [get]
abstract float SamplingRate [get]
abstract IEnumerable< IBGCStream > InternalStreams [get]
Properties inherited from BGC.Audio.IBGCStream
int Channels [get]
The number of underlying Channels of this BGCStream
int TotalSamples [get]
The total number of Samples of this BGCStream
int ChannelSamples [get]
The number of Samples of each channel for this BGCStream
float SamplingRate [get]
The sampling rate of the Stream
Detailed Description
Stores and renders a set of active notes. Generally meant to interact with Active ADSR Envelopes.
Definition at line 13 of file ActiveNoteStream.cs.
Constructor & Destructor Documentation
ActiveNoteStream()
BGC.Audio.Synthesis.ActiveNoteStream.ActiveNoteStream () inline
Definition at line 30 of file ActiveNoteStream.cs.
         {
         }
Member Function Documentation
AddStream()
void BGC.Audio.Synthesis.ActiveNoteStream.AddStream (int key, IBGCStream stream) inline
Definition at line 34 of file ActiveNoteStream.cs.
         {
             if (stream == null)
             {
                 Debug.Log("Added null stream");
                 return;
             }
             if (streams.ContainsKey(key))
             {
                 IBGCStream oldStream = streams[key];
                 collisionNotes.Add(oldStream);
                 if (oldStream is IADSR asdr)
                 {
                     asdr.TriggerRelease(true);
                 }
                 RemoveStream(key);
             }
             streams.Add(key, stream);
         }
Clear()
void BGC.Audio.Synthesis.ActiveNoteStream.Clear () inline
Definition at line 83 of file ActiveNoteStream.cs.
         {
             collisionNotes.Clear();
             pendingDeletions.Clear();
             streams.Clear();
         }
GetChannelRMS()
override IEnumerable<double> BGC.Audio.Synthesis.ActiveNoteStream.GetChannelRMS () inline virtual
The RMS amplitude of each channel
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 165 of file ActiveNoteStream.cs.
         {
             yield return Math.Sqrt(0.5);
         }
Read()
override int BGC.Audio.Synthesis.ActiveNoteStream.Read (float [] data, int offset, int count) inline virtual
Copy count samples into the Data buffer, starting at offset.
Returns
The number of samples copied
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 90 of file ActiveNoteStream.cs.
References BGC.Audio.IBGCStream.Read().
         {
             Array.Clear(data, offset, count);
             foreach (IBGCStream stream in pendingDeletions)
             {
                 RemoveStream(stream);
             }
             foreach (IBGCStream stream in streams.Values.Concat(collisionNotes))
             {
                 int streamRemainingSamples = count;
                 int streamOffset = offset;
                 while (streamRemainingSamples > 0)
                 {
                     int maxRead = Math.Min(BUFFER_SIZE, streamRemainingSamples);
                     int streamReadSamples = stream.Read(buffer, 0, maxRead);
                     if (streamReadSamples == 0)
                     {
                         pendingDeletions.Add(stream);
                         //Done with this stream
                         break;
                     }
                     for (int i = 0; i < streamReadSamples; i++)
                     {
                         data[streamOffset + i] += buffer[i];
                     }
                     streamOffset += streamReadSamples;
                     streamRemainingSamples -= streamReadSamples;
                 }
             }
             foreach (IBGCStream stream in pendingDeletions)
             {
                 RemoveStream(stream);
                 collisionNotes.Remove(stream);
             }
             pendingDeletions.Clear();
             return count;
         }
Release()
bool BGC.Audio.Synthesis.ActiveNoteStream.Release (int key, bool immediate = false) inline
Definition at line 137 of file ActiveNoteStream.cs.
         {
             if (streams.ContainsKey(key))
             {
                 if (streams[key] is ADSREnvelope activeEnvelope)
                 {
                     activeEnvelope.TriggerRelease(immediate);
                 }
                 else
                 {
                     RemoveStream(key);
                 }
                 return true;
             }
             return false;
         }
RemoveStream() [1/2]
bool BGC.Audio.Synthesis.ActiveNoteStream.RemoveStream (IBGCStream stream) inline
Definition at line 58 of file ActiveNoteStream.cs.
         {
             if (streams.ContainsValue(stream))
             {
                 int key = streams.FirstOrDefault(x => x.Value == stream).Key;
                 streams.Remove(key);
                 return true;
             }
             return false;
         }
RemoveStream() [2/2]
bool BGC.Audio.Synthesis.ActiveNoteStream.RemoveStream (int key) inline
Definition at line 70 of file ActiveNoteStream.cs.
         {
             return streams.Remove(key);
         }
Reset()
override void BGC.Audio.Synthesis.ActiveNoteStream.Reset () inline virtual
Sets this internal state of this stream to the initial state
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 75 of file ActiveNoteStream.cs.
References BGC.Audio.IBGCStream.Reset().
         {
             foreach (IBGCStream stream in streams.Values)
             {
                 stream.Reset();
             }
         }
Seek()
override void BGC.Audio.Synthesis.ActiveNoteStream.Seek (int position) inline virtual
Seek to the indicated position in the stream
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 156 of file ActiveNoteStream.cs.
References BGC.Audio.IBGCStream.Seek().
         {
             foreach (IBGCStream stream in streams.Values)
             {
                 stream.Seek(position);
             }
         }
Field Documentation
buffer
readonly float [] BGC.Audio.Synthesis.ActiveNoteStream.buffer = new float[BUFFER_SIZE] private
Definition at line 28 of file ActiveNoteStream.cs.
BUFFER_SIZE
const int BGC.Audio.Synthesis.ActiveNoteStream.BUFFER_SIZE = 512 private
Definition at line 27 of file ActiveNoteStream.cs.
Channels
override int BGC.Audio.Synthesis.ActiveNoteStream.Channels => 1
Definition at line 20 of file ActiveNoteStream.cs.
ChannelSamples
override int BGC.Audio.Synthesis.ActiveNoteStream.ChannelSamples => int.MaxValue
Definition at line 23 of file ActiveNoteStream.cs.
collisionNotes
List<IBGCStream> BGC.Audio.Synthesis.ActiveNoteStream.collisionNotes = new List<IBGCStream>() private
Definition at line 16 of file ActiveNoteStream.cs.
InternalStreams
override IEnumerable<IBGCStream> BGC.Audio.Synthesis.ActiveNoteStream.InternalStreams => streams.Values
Definition at line 18 of file ActiveNoteStream.cs.
pendingDeletions
List<IBGCStream> BGC.Audio.Synthesis.ActiveNoteStream.pendingDeletions = new List<IBGCStream>() private
Definition at line 15 of file ActiveNoteStream.cs.
SamplingRate
override float BGC.Audio.Synthesis.ActiveNoteStream.SamplingRate => 44100f
Definition at line 25 of file ActiveNoteStream.cs.
streams
readonly Dictionary<int, IBGCStream> BGC.Audio.Synthesis.ActiveNoteStream.streams = new Dictionary<int, IBGCStream>() private
Definition at line 17 of file ActiveNoteStream.cs.
TotalSamples
override int BGC.Audio.Synthesis.ActiveNoteStream.TotalSamples => int.MaxValue
Definition at line 22 of file ActiveNoteStream.cs.
The documentation for this class was generated from the following file:
Audio/Synthesis/ActiveNoteStream.cs