BGC Tools: BGC.Audio.AnalyticStreams.AnalyticStreamExtensions Class Reference
BGC.Audio.AnalyticStreams.AnalyticStreamExtensions Class Reference
Static Public Member Functions
static IBGCStream ToBGCStream (this IAnalyticStream stream)
Returns the AnalyticStream augmented with an BGCStreamConverter
static IAnalyticStream ToAnalyticStream (this IBGCStream stream)
Returns the BGCStream augmented with an AnalyticStreamConverter
static IBGCStream ToEnvelopeStream (this IAnalyticStream stream)
Returns the BGCStream equivalent of the AnalyticStream's Envelope
static IAnalyticStream FrequencyModulation (this IAnalyticStream stream, double modulationRate, double modulationDepth)
Returns the AnalyticStream augmented with a FrequencyModulationFilter
static IAnalyticStream FrequencyShift (this IAnalyticStream stream, double frequencyShift)
static IAnalyticStream Window (this IAnalyticStream stream, double totalDuration, Windowing.Function function=Windowing.Function.Hamming, int smoothingSamples=1000)
static IAnalyticStream Window (this IAnalyticStream stream, Windowing.Function function=Windowing.Function.Hamming, int smoothingSamples=1000)
static IAnalyticStream Add (this IAnalyticStream stream, IAnalyticStream other)
static IAnalyticStream Add (this IAnalyticStream stream, params IAnalyticStream[] others)
static IAnalyticStream Fork (this IAnalyticStream stream, out IAnalyticStream forkedStream)
static IAnalyticStream Center (this IAnalyticStream stream, double minimumDuration=0.0)
Returns an AnalyticStream at least minimumDuration in duration, with the clip centered in it
static IAnalyticStream Center (this IAnalyticStream stream, int preDelaySamples, int postDelaySamples)
static IAnalyticStream ADSR (this IAnalyticStream stream, double timeToPeak, double timeToSustain, double sustainAmplitude, double sustainDecayTime)
static IAnalyticStream ADSR (this IAnalyticStream stream, double timeToPeak, double timeToSustain, double sustainAmplitude, double sustainDecayTime, double releaseDecayTime)
static IAnalyticStream ADSR (this IAnalyticStream stream, double timeToPeak, double timeToSustain, double timeToRelease, double sustainAmplitude, double sustainDecayTime, double releaseDecayTime)
static double Duration (this IAnalyticStream stream)
Calculates the effective Duration of the AnalyticStream
static double CalculateRMS (this IAnalyticStream stream)
Slowest Backup Alternative for calculating RMS
Detailed Description
Definition at line 6 of file AnalyticStreamExtensions.cs.
Member Function Documentation
Add() [1/2]
static IAnalyticStream BGC.Audio.AnalyticStreams.AnalyticStreamExtensions.Add (this IAnalyticStream stream, IAnalyticStream other) inline static
Definition at line 56 of file AnalyticStreamExtensions.cs.
         {
             return new AnalyticStreamAdder(stream, other);
         }
Add() [2/2]
static IAnalyticStream BGC.Audio.AnalyticStreams.AnalyticStreamExtensions.Add (this IAnalyticStream stream, params IAnalyticStream [] others) inline static
Definition at line 63 of file AnalyticStreamExtensions.cs.
References BGC.Audio.AnalyticStreams.AnalyticStreamAdder.AddStreams().
         {
             AnalyticStreamAdder adder = new AnalyticStreamAdder(stream);
             adder.AddStreams(others);
             return adder;
         }
ADSR() [1/3]
static IAnalyticStream BGC.Audio.AnalyticStreams.AnalyticStreamExtensions.ADSR (this IAnalyticStream stream, double timeToPeak, double timeToSustain, double sustainAmplitude, double sustainDecayTime) inline static
Definition at line 98 of file AnalyticStreamExtensions.cs.
         {
             return new AnalyticADSREnvelope(
                 stream: stream,
                 timeToPeak: timeToPeak,
                 timeToSustain: timeToSustain,
                 sustainAmplitude: sustainAmplitude,
                 sustainDecayTime: sustainDecayTime,
                 releaseDecayTime: sustainDecayTime);
         }
ADSR() [2/3]
static IAnalyticStream BGC.Audio.AnalyticStreams.AnalyticStreamExtensions.ADSR (this IAnalyticStream stream, double timeToPeak, double timeToSustain, double sustainAmplitude, double sustainDecayTime, double releaseDecayTime) inline static
Definition at line 114 of file AnalyticStreamExtensions.cs.
         {
             return new AnalyticADSREnvelope(
                 stream: stream,
                 timeToPeak: timeToPeak,
                 timeToSustain: timeToSustain,
                 sustainAmplitude: sustainAmplitude,
                 sustainDecayTime: sustainDecayTime,
                 releaseDecayTime: releaseDecayTime);
         }
ADSR() [3/3]
static IAnalyticStream BGC.Audio.AnalyticStreams.AnalyticStreamExtensions.ADSR (this IAnalyticStream stream, double timeToPeak, double timeToSustain, double timeToRelease, double sustainAmplitude, double sustainDecayTime, double releaseDecayTime) inline static
Definition at line 131 of file AnalyticStreamExtensions.cs.
References BGC.Audio.AnalyticStreams.IAnalyticStream.Samples, and BGC.Audio.AnalyticStreams.IAnalyticStream.SamplingRate.
         {
             return new AnalyticADSREnvelope(
                 stream: stream,
                 timeToPeak: timeToPeak,
                 timeToSustain: timeToSustain,
                 timeToRelease: timeToRelease,
                 sustainAmplitude: sustainAmplitude,
                 sustainDecayTime: sustainDecayTime,
                 releaseDecayTime: releaseDecayTime);
         }
CalculateRMS()
static double BGC.Audio.AnalyticStreams.AnalyticStreamExtensions.CalculateRMS (this IAnalyticStream stream) inline static
Slowest Backup Alternative for calculating RMS
Definition at line 156 of file AnalyticStreamExtensions.cs.
References BGC.Audio.AnalyticStreams.IAnalyticStream.Read(), BGC.Mathematics.Complex64.Real, BGC.Audio.AnalyticStreams.IAnalyticStream.Reset(), and BGC.Audio.AnalyticStreams.IAnalyticStream.Samples.
         {
             double rms = 0.0;
             int readSamples;
             const int BUFFER_SIZE = 512;
             Complex64[] buffer = new Complex64[BUFFER_SIZE];
             stream.Reset();
             do
             {
                 readSamples = stream.Read(buffer, 0, BUFFER_SIZE);
                 for (int i = 0; i < readSamples; i++)
                 {
                     rms += buffer[i].Real * buffer[i].Real;
                 }
             }
             while (readSamples > 0);
             stream.Reset();
             return Math.Sqrt(rms / stream.Samples);
         }
Center() [1/2]
static IAnalyticStream BGC.Audio.AnalyticStreams.AnalyticStreamExtensions.Center (this IAnalyticStream stream, double minimumDuration = 0.0) inline static
Returns an AnalyticStream at least minimumDuration in duration, with the clip centered in it
Definition at line 83 of file AnalyticStreamExtensions.cs.
         {
             return new AnalyticStreamCenterer(stream, Math.Max(stream.Duration(), minimumDuration));
         }
Center() [2/2]
static IAnalyticStream BGC.Audio.AnalyticStreams.AnalyticStreamExtensions.Center (this IAnalyticStream stream, int preDelaySamples, int postDelaySamples) inline static
Definition at line 90 of file AnalyticStreamExtensions.cs.
         {
             return new AnalyticStreamCenterer(stream, preDelaySamples, postDelaySamples);
         }
Duration()
static double BGC.Audio.AnalyticStreams.AnalyticStreamExtensions.Duration (this IAnalyticStream stream) static
Calculates the effective Duration of the AnalyticStream
Fork()
static IAnalyticStream BGC.Audio.AnalyticStreams.AnalyticStreamExtensions.Fork (this IAnalyticStream stream, out IAnalyticStream forkedStream) inline static
Definition at line 72 of file AnalyticStreamExtensions.cs.
         {
             return new AnalyticStreamFork(stream, out forkedStream);
         }
FrequencyModulation()
static IAnalyticStream BGC.Audio.AnalyticStreams.AnalyticStreamExtensions.FrequencyModulation (this IAnalyticStream stream, double modulationRate, double modulationDepth) inline static
Returns the AnalyticStream augmented with a FrequencyModulationFilter
Definition at line 21 of file AnalyticStreamExtensions.cs.
         {
             return new AnalyticFrequencyModulationFilter(stream, modulationRate, modulationDepth);
         }
FrequencyShift()
static IAnalyticStream BGC.Audio.AnalyticStreams.AnalyticStreamExtensions.FrequencyShift (this IAnalyticStream stream, double frequencyShift) inline static
Definition at line 29 of file AnalyticStreamExtensions.cs.
         {
             return new AnalyticStreamFrequencyShifter(stream, frequencyShift);
         }
ToAnalyticStream()
static IAnalyticStream BGC.Audio.AnalyticStreams.AnalyticStreamExtensions.ToAnalyticStream (this IBGCStream stream) static
Returns the BGCStream augmented with an AnalyticStreamConverter
ToBGCStream()
static IBGCStream BGC.Audio.AnalyticStreams.AnalyticStreamExtensions.ToBGCStream (this IAnalyticStream stream) static
Returns the AnalyticStream augmented with an BGCStreamConverter
ToEnvelopeStream()
static IBGCStream BGC.Audio.AnalyticStreams.AnalyticStreamExtensions.ToEnvelopeStream (this IAnalyticStream stream) static
Returns the BGCStream equivalent of the AnalyticStream's Envelope
Window() [1/2]
static IAnalyticStream BGC.Audio.AnalyticStreams.AnalyticStreamExtensions.Window (this IAnalyticStream stream, double totalDuration, Windowing.Function function = Windowing.Function.Hamming, int smoothingSamples = 1000) inline static
Definition at line 36 of file AnalyticStreamExtensions.cs.
         {
             return new AnalyticStreamWindower(stream, function,
                 totalDuration: totalDuration,
                 smoothingSamples: smoothingSamples);
         }
Window() [2/2]
static IAnalyticStream BGC.Audio.AnalyticStreams.AnalyticStreamExtensions.Window (this IAnalyticStream stream, Windowing.Function function = Windowing.Function.Hamming, int smoothingSamples = 1000) inline static
Definition at line 47 of file AnalyticStreamExtensions.cs.
         {
             return new AnalyticStreamWindower(stream, function,
                 smoothingSamples: smoothingSamples);
         }
The documentation for this class was generated from the following file:
Audio/AnalyticStreams/AnalyticStreamExtensions.cs