BGC Tools: BGC.Users.PlayerData Class Reference
BGC.Users.PlayerData Class Reference
Static Public Member Functions
static void Save ()
Serialize the current user's data
static bool HasKey (string key)
static void RemoveKey (string key)
static void SetInt (string key, int value)
static void SetBool (string key, bool value)
static void SetString (string key, string value)
static void SetFloat (string key, float value)
static void SetDouble (string key, double value)
static void SetJsonValue (string key, JsonValue value)
static void SetJsonArray (string key, JsonArray value)
static int GetInt (string key, int defaultReturn=0)
static bool GetBool (string key, bool defaultReturn=false)
static string GetString (string key, string defaultReturn="")
static float GetFloat (string key, float defaultReturn=0f)
static double GetDouble (string key, double defaultReturn=0.0)
static JsonValue GetJsonValue (string key, JsonValue defaultReturn=default(JsonValue))
static JsonArray GetJsonArray (string key, JsonArray defaultReturn=default(JsonArray))
static void DeserializeUsers ()
Load all usernames
static IEnumerable< string > GetUserNames ()
Returns an enumeration of all loaded usernames
static bool UserExists (string userName)
Does the requested user already exist?
static bool LogIn (string userName, Action userChangingCallback=null)
Attempts to log in with userName
static void LogOut ()
Save and clear the current user
static bool AddUser (string userName)
Add a new user.
static void DeleteUserData (string userName)
Deserialize, delete, and remove a user
static IEnumerable< MigrationData > GetMigrationData (string pushLogsKey, string organizationKey, string studyKey)
Get the migration preferences of all profiles.
Data Fields
const string UserDataDir = "SaveData"
Static Public Attributes
static DefaultData DefaultData => _defaultData ?? (_defaultData = new DefaultData())
The default profile data.
static ProfileData ProfileData => _currentUserData as ProfileData ?? DefaultData
Profile Data of the current user. Or default if none are logged in.
static string UserName => ProfileData.UserName
The Current Profile UserName
static bool IsDefault => ProfileData.IsDefault
The Current Profile IsDefault Status
Properties
static bool IsLocked [get, set]
Is the device currently in a Locked mode?
static bool EverUnlocked [get, set]
Has the device ever been unlocked?
Private Attributes
const string LockStateKey = "LockState"
const string EverUnlockedKey = "EverUnlocked"
Static Private Attributes
static DefaultData _defaultData = null
static UserData _currentUserData = null
static bool initialized = false
static string previousUser = ""
static readonly List< string > users = new List<string>()
Detailed Description
Definition at line 11 of file PlayerData.cs.
Member Function Documentation
static bool BGC.Users.PlayerData.AddUser (string userName) inline static
Add a new user.
Returns
Returns if the operation was successful
Definition at line 167 of file PlayerData.cs.
References BGC.Users.ProfileData.Serialize().
         {
             if (!initialized)
             {
                 //If deleteUser is attempted without first loading data
                 Debug.LogError($"Tried to AddUser before initializing PlayerData.  userName: {userName}");
                 return false;
             }
             if (users.Contains(userName))
             {
                 return false;
             }
             UserData newUser = new UserData(userName);
             users.Add(userName);
             newUser.Serialize();
             return true;
         }
static void BGC.Users.PlayerData.DeleteUserData (string userName) inline static
Deserialize, delete, and remove a user
Definition at line 189 of file PlayerData.cs.
References BGC.Users.ProfileData.DeletePlayerData(), and BGC.Users.ProfileData.Deserialize().
         {
             UserData tempUserData = new UserData(userName);
             if (tempUserData.Deserialize())
             {
                 tempUserData.DeletePlayerData();
             }
             users.Remove(userName);
         }
static void BGC.Users.PlayerData.DeserializeUsers () inline static
Load all usernames
Definition at line 98 of file PlayerData.cs.
References BGC.IO.DataManagement.GetDataFiles(), and BGC.IO.FileExtensions.JSON.
         {
             //Load up saved information
             users.Clear();
             foreach (string fileName in DataManagement.GetDataFiles(UserDataDir))
             {
                 if (Path.GetExtension(fileName) == FileExtensions.JSON)
                 {
                     string newUserName = Path.GetFileNameWithoutExtension(fileName);
                     if (newUserName != "Default")
                     {
                         users.Add(newUserName);
                     }
                 }
             }
             initialized = true;
         }
static bool BGC.Users.PlayerData.GetBool (string key, bool defaultReturn = false) static
static double BGC.Users.PlayerData.GetDouble (string key, double defaultReturn = 0.0) static
static float BGC.Users.PlayerData.GetFloat (string key, float defaultReturn = 0f) static
static int BGC.Users.PlayerData.GetInt (string key, int defaultReturn = 0) static
static JsonArray BGC.Users.PlayerData.GetJsonArray (string key, JsonArray defaultReturn = default(JsonArray)) static
static JsonValue BGC.Users.PlayerData.GetJsonValue (string key, JsonValue defaultReturn = default(JsonValue)) static
static IEnumerable<MigrationData> BGC.Users.PlayerData.GetMigrationData (string pushLogsKey, string organizationKey, string studyKey) inline static
Get the migration preferences of all profiles.
Definition at line 201 of file PlayerData.cs.
References BGC.Users.ProfileData.Deserialize(), BGC.Users.ProfileData.GetBool(), BGC.Users.ProfileData.GetString(), and BGC.Users.ProfileData.UserName.
         {
             List<MigrationData> migrationData = new List<MigrationData>();
             if (initialized == false)
             {
                 DeserializeUsers();
             }
             foreach (string userName in users)
             {
                 UserData data = new UserData(userName);
                 //Load in the data first
                 if (data.Deserialize() && data.GetBool(pushLogsKey, false))
                 {
                     migrationData.Add(new MigrationData
                     {
                         userName = data.UserName,
                         organization = data.GetString(organizationKey, "braingamecenter"),
                         study = data.GetString(studyKey, "default")
                     });
                 }
             }
             return migrationData;
         }
static string BGC.Users.PlayerData.GetString (string key, string defaultReturn = "") static
static IEnumerable<string> BGC.Users.PlayerData.GetUserNames () static
Returns an enumeration of all loaded usernames
static bool BGC.Users.PlayerData.HasKey (string key) static
static bool BGC.Users.PlayerData.LogIn (string userName, Action userChangingCallback = null) inline static
Attempts to log in with userName
Parameters
userName Name of user to log into
userChangingCallback Optional callback invoked when the user will change. Typically clearing logs, for example.
Returns
Whether the user was successfully logged in
Definition at line 132 of file PlayerData.cs.
References BGC.Users.ProfileData.Deserialize().
         {
             //If we're logging into a new user...
             if (previousUser != userName)
             {
                 userChangingCallback?.Invoke();
                 previousUser = userName;
             }
             _currentUserData = new UserData(userName);
             if (_currentUserData.Deserialize() == false)
             {
                 //Failed to load user
                 _currentUserData = null;
                 previousUser = "";
                 Debug.LogError($"Failed to load selected user data: {userName}");
                 return false;
             }
             return true;
         }
static void BGC.Users.PlayerData.LogOut () inline static
Save and clear the current user
Definition at line 159 of file PlayerData.cs.
         {
             Save();
             _currentUserData = null;
         }
static void BGC.Users.PlayerData.RemoveKey (string key) static
static void BGC.Users.PlayerData.Save () static
Serialize the current user's data
Referenced by BGC.Study.ProtocolManager.ExecuteNextElement().
static void BGC.Users.PlayerData.SetBool (string key, bool value) static
static void BGC.Users.PlayerData.SetDouble (string key, double value) static
static void BGC.Users.PlayerData.SetFloat (string key, float value) static
static void BGC.Users.PlayerData.SetInt (string key, int value) static
static void BGC.Users.PlayerData.SetJsonArray (string key, JsonArray value) static
static void BGC.Users.PlayerData.SetJsonValue (string key, JsonValue value) static
static void BGC.Users.PlayerData.SetString (string key, string value) static
static bool BGC.Users.PlayerData.UserExists (string userName) static
Does the requested user already exist?
Field Documentation
UserData BGC.Users.PlayerData._currentUserData = null static private
Definition at line 19 of file PlayerData.cs.
DefaultData BGC.Users.PlayerData._defaultData = null static private
Definition at line 15 of file PlayerData.cs.
DefaultData BGC.Users.PlayerData.DefaultData => _defaultData ?? (_defaultData = new DefaultData()) static
The default profile data.
Definition at line 17 of file PlayerData.cs.
const string BGC.Users.PlayerData.EverUnlockedKey = "EverUnlocked" private
Definition at line 32 of file PlayerData.cs.
bool BGC.Users.PlayerData.initialized = false static private
Definition at line 24 of file PlayerData.cs.
bool BGC.Users.PlayerData.IsDefault => ProfileData.IsDefault static
The Current Profile IsDefault Status
Definition at line 71 of file PlayerData.cs.
const string BGC.Users.PlayerData.LockStateKey = "LockState" private
Definition at line 31 of file PlayerData.cs.
string BGC.Users.PlayerData.previousUser = "" static private
Definition at line 26 of file PlayerData.cs.
ProfileData BGC.Users.PlayerData.ProfileData => _currentUserData as ProfileData ?? DefaultData static
Profile Data of the current user. Or default if none are logged in.
Definition at line 21 of file PlayerData.cs.
const string BGC.Users.PlayerData.UserDataDir = "SaveData"
Definition at line 13 of file PlayerData.cs.
string BGC.Users.PlayerData.UserName => ProfileData.UserName static
The Current Profile UserName
Definition at line 69 of file PlayerData.cs.
readonly List<string> BGC.Users.PlayerData.users = new List<string>() static private
Definition at line 28 of file PlayerData.cs.
Property Documentation
bool BGC.Users.PlayerData.EverUnlocked static get set
Has the device ever been unlocked?
Definition at line 54 of file PlayerData.cs.
bool BGC.Users.PlayerData.IsLocked static get set
Is the device currently in a Locked mode?
Definition at line 36 of file PlayerData.cs.
The documentation for this class was generated from the following file:
Users/PlayerData.cs