BGC Tools: BGC.Study.ProtocolManager Class Reference
BGC.Study.ProtocolManager Class Reference
Data Structures
class DataKeys
Public Member Functions
delegate void MigrateProtocols (ref JsonObject protocols)
delegate void SessionElementOverrun ()
delegate void PrepareNextElement (bool resuming)
delegate SessionElement ParseSessionElement (JsonObject sessionElement)
Static Public Member Functions
static void PrepareProtocol (string protocolName, int protocolID)
static ProtocolStatus TryUpdateProtocol (string protocolName, int protocolID, int sessionIndex, int sessionElementIndex=0)
static ProtocolStatus SetSession (int session, int element=0)
static JsonValue GetEnvValue (string key, JsonValue defaultReturn=default(JsonValue))
static bool GetEnvBool (string key, bool defaultValue=false)
static int GetEnvInt (string key, int defaultValue=0)
static string GetEnvStr (string key, string defaultValue="")
static float GetEnvFloat (string key, float defaultValue=0f)
static void RegisterSpecializers (SessionElementOverrun sessionElementOverrun, PrepareNextElement prepareNextElement, ParseSessionElement parseSessionElement, MigrateProtocols migrateProtocols)
static ProtocolStatus ExecuteNextElement (bool resuming=false)
static void SaveAs (string protocolName)
static void SerializeAll ()
static bool LoadProtocolSet (string protocolName)
static JsonArray SerializeProtocols ()
static void DeserializeProtocols (JsonArray protocols)
static JsonArray SerializeSessions ()
static void DeserializeSessions (JsonArray sessions)
static JsonArray SerializeSessionElements ()
static void DeserializeSessionElements (JsonArray elements)
static void UpdateDefaults ()
static string GetProtocolName (int protocolID)
static void HardClearAll ()
Data Fields
const int protocolDataVersion = 2
Static Public Attributes
static Dictionary< int, Protocol > protocolDictionary = new Dictionary<int, Protocol>()
static Dictionary< int, Session > sessionDictionary = new Dictionary<int, Session>()
static Dictionary< int, SessionElement > sessionElementDictionary
static Protocol currentProtocol = null
static Session currentSession = null
static SessionElement currentSessionElement = null
static int nextSessionElementIndex = -1
Properties
static int ElementNumber [get, set]
static int SessionNumber [get, set]
static bool SessionInProgress [get, set]
Static Private Member Functions
static void RemoveRedundancies ()
Private Attributes
const string protocolDataDir = "Protocols"
Static Private Attributes
static string loadedProtocol = ""
static SessionElementOverrun sessionElementOverrun = null
static PrepareNextElement prepareNextElement = null
static MigrateProtocols migrateProtocols = null
static ParseSessionElement parseSessionElement = null
Detailed Description
Definition at line 21 of file ProtocolManager.cs.
Member Function Documentation
DeserializeProtocols()
static void BGC.Study.ProtocolManager.DeserializeProtocols (JsonArray protocols) inline static
Definition at line 471 of file ProtocolManager.cs.
References BGC.Study.ProtocolKeys.Protocol.EnvironmentValues, BGC.Study.ProtocolKeys.Protocol.Id, and BGC.Study.ProtocolKeys.Protocol.SessionIDs.
         {
             protocolDictionary.Clear();
             foreach (JsonObject protocol in protocols)
             {
                 List<SessionID> sessions = new List<SessionID>();
                 foreach (int sessionID in protocol[ProtocolKeys.Protocol.SessionIDs].AsJsonArray)
                 {
                     sessions.Add(sessionID);
                 }
                 JsonObject envVals;
                 if (protocol.ContainsKey(ProtocolKeys.Protocol.EnvironmentValues))
                 {
                     envVals = protocol[ProtocolKeys.Protocol.EnvironmentValues].AsJsonObject;
                 }
                 else
                 {
                     envVals = new JsonObject();
                 }
                 protocolDictionary.Add(
                     protocol[ProtocolKeys.Protocol.Id],
                     new Protocol(protocol[ProtocolKeys.Protocol.Id].AsInteger)
                     {
                         name = protocol[ProtocolKeys.Protocol.Name],
                         sessions = sessions,
                         envVals = envVals
                     });
             }
         }
DeserializeSessionElements()
static void BGC.Study.ProtocolManager.DeserializeSessionElements (JsonArray elements) inline static
Definition at line 540 of file ProtocolManager.cs.
References BGC.Study.SessionElement.id.
         {
             sessionElementDictionary.Clear();
             foreach (JsonObject element in elements)
             {
                 SessionElement parsedElement = parseSessionElement?.Invoke(element);
                 if (parsedElement == null)
                 {
                     Debug.LogError($"Failed to parse SessionElement: {element.ToString()}");
                     continue;
                 }
                 sessionElementDictionary.Add(parsedElement.id, parsedElement);
             }
         }
DeserializeSessions()
static void BGC.Study.ProtocolManager.DeserializeSessions (JsonArray sessions) inline static
Definition at line 516 of file ProtocolManager.cs.
References BGC.Study.Session.id.
         {
             sessionDictionary.Clear();
             foreach (JsonObject sessionData in sessions)
             {
                 Session session = new Session(sessionData);
                 sessionDictionary.Add(session.id, session);
             }
         }
ExecuteNextElement()
static ProtocolStatus BGC.Study.ProtocolManager.ExecuteNextElement (bool resuming = false) inline static
Definition at line 251 of file ProtocolManager.cs.
References BGC.Study.SessionElement.CleanupElement(), BGC.Study.Session.Count, BGC.Study.SessionElement.ExecuteElement(), and BGC.Users.PlayerData.Save().
         {
             if (nextSessionElementIndex == -1)
             {
                 return ProtocolStatus.Uninitialized;
             }
             if (nextSessionElementIndex == currentSession.Count)
             {
                 //In principle, this should only happen if an EndSessionElement was forgotten
                 ElementNumber = 0;
                 SessionInProgress = false;
                 ++SessionNumber;
                 sessionElementOverrun?.Invoke();
                 PlayerData.Save();
                 return ProtocolStatus.SessionFinished;
             }
             //This only happens when the last element was running
             currentSessionElement?.CleanupElement();
             currentSessionElement = currentSession[nextSessionElementIndex];
             ElementNumber = nextSessionElementIndex;
             SessionInProgress = true;
             prepareNextElement?.Invoke(resuming);
             currentSessionElement.ExecuteElement(resuming);
             PlayerData.Save();
             ++nextSessionElementIndex;
             return ProtocolStatus.SessionReady;
         }
GetEnvBool()
static bool BGC.Study.ProtocolManager.GetEnvBool (string key, bool defaultValue = false) inline static
Definition at line 181 of file ProtocolManager.cs.
References LightJson.JsonValue.AsBoolean, LightJson.JsonValue.AsInteger, LightJson.JsonValue.IsBoolean, and LightJson.JsonValue.IsInteger.
         {
             JsonValue val = GetEnvValue(key, defaultValue);
             if (val.IsBoolean)
             {
                 return val.AsBoolean;
             }
             if (val.IsInteger)
             {
                 Debug.LogWarning($"EnvVal type mismatch: Found {val.Type}, Expected: {defaultValue.GetType().Name}.  Converting.");
                 return val.AsInteger != 0;
             }
             Debug.LogError($"EnvVal type mismatch: Found {val.Type}, Expected: {defaultValue.GetType().Name}");
             return defaultValue;
         }
GetEnvFloat()
static float BGC.Study.ProtocolManager.GetEnvFloat (string key, float defaultValue = 0f) inline static
Definition at line 226 of file ProtocolManager.cs.
References LightJson.JsonValue.AsNumber, and LightJson.JsonValue.IsNumber.
         {
             JsonValue val = GetEnvValue(key, defaultValue);
             if (val.IsNumber)
             {
                 return (float)val.AsNumber;
             }
             Debug.LogError($"EnvVal type mismatch: Found {val.Type}, Expected: {defaultValue.GetType().Name}");
             return defaultValue;
         }
GetEnvInt()
static int BGC.Study.ProtocolManager.GetEnvInt (string key, int defaultValue = 0) inline static
Definition at line 200 of file ProtocolManager.cs.
References LightJson.JsonValue.AsInteger, and LightJson.JsonValue.IsInteger.
         {
             JsonValue val = GetEnvValue(key, defaultValue);
             if (val.IsInteger)
             {
                 return val.AsInteger;
             }
             Debug.LogError($"EnvVal type mismatch: Found {val.Type}, Expected: {defaultValue.GetType().Name}");
             return defaultValue;
         }
GetEnvStr()
static string BGC.Study.ProtocolManager.GetEnvStr (string key, string defaultValue = "") inline static
Definition at line 213 of file ProtocolManager.cs.
References LightJson.JsonValue.AsString, and LightJson.JsonValue.IsString.
         {
             JsonValue val = GetEnvValue(key, defaultValue);
             if (val.IsString)
             {
                 return val.AsString;
             }
             Debug.LogError($"EnvVal type mismatch: Found {val.Type}, Expected: {defaultValue.GetType().Name}");
             return defaultValue;
         }
GetEnvValue()
static JsonValue BGC.Study.ProtocolManager.GetEnvValue (string key, JsonValue defaultReturn = default(JsonValue)) inline static
Definition at line 153 of file ProtocolManager.cs.
References LightJson.JsonObject.ContainsKey(), BGC.Study.SessionElement.envVals, BGC.Study.Protocol.envVals, and BGC.Study.Session.envVals.
         {
             if (loadedProtocol == "" ||
                 currentProtocol == null || currentSession == null || currentSessionElement == null)
             {
                 Debug.Log($"EnvVal not ready for query: {key}");
                 return defaultReturn;
             }
             if (currentSessionElement.envVals.ContainsKey(key))
             {
                 return currentSessionElement.envVals[key];
             }
             if (currentSession.envVals.ContainsKey(key))
             {
                 return currentSession.envVals[key];
             }
             if (currentProtocol.envVals.ContainsKey(key))
             {
                 return currentProtocol.envVals[key];
             }
             Debug.Log($"EnvVal not found: {key}");
             return defaultReturn;
         }
GetProtocolName()
static string BGC.Study.ProtocolManager.GetProtocolName (int protocolID) inline static
Definition at line 570 of file ProtocolManager.cs.
         {
             if (protocolDictionary.ContainsKey(protocolID))
             {
                 return protocolDictionary[protocolID].name;
             }
             return "Invalid";
         }
HardClearAll()
static void BGC.Study.ProtocolManager.HardClearAll () inline static
Definition at line 580 of file ProtocolManager.cs.
References BGC.Study.Protocol.HardClear(), BGC.Study.SessionElement.HardClear(), and BGC.Study.Session.HardClear().
         {
             loadedProtocol = "";
             protocolDictionary.Clear();
             sessionDictionary.Clear();
             sessionElementDictionary.Clear();
             Protocol.HardClear();
             Session.HardClear();
             SessionElement.HardClear();
         }
LoadProtocolSet()
static bool BGC.Study.ProtocolManager.LoadProtocolSet (string protocolName) inline static
Definition at line 402 of file ProtocolManager.cs.
References BGC.IO.DataManagement.PathForDataDirectory(), BGC.Study.ProtocolKeys.Protocols, BGC.IO.FileReader.ReadJsonFile(), BGC.Study.ProtocolKeys.SessionElements, and BGC.Study.ProtocolKeys.Sessions.
         {
             if (protocolName == "")
             {
                 protocolName = "DefaultSet";
             }
             if (loadedProtocol == protocolName)
             {
                 return true;
             }
             string previousLoadedProtocol = loadedProtocol;
             loadedProtocol = protocolName;
             foreach (char c in Path.GetInvalidFileNameChars())
             {
                 loadedProtocol = loadedProtocol.Replace(c.ToString(), "");
             }
             return FileReader.ReadJsonFile(
                 path: Path.Combine(DataManagement.PathForDataDirectory(protocolDataDir), $"{loadedProtocol}.json"),
                 successCallback: (JsonObject jsonProtocols) =>
                 {
                     migrateProtocols?.Invoke(ref jsonProtocols);
                     DeserializeProtocols(jsonProtocols[ProtocolKeys.Protocols]);
                     DeserializeSessions(jsonProtocols[ProtocolKeys.Sessions]);
                     DeserializeSessionElements(jsonProtocols[ProtocolKeys.SessionElements]);
                 },
                 failCallback: () =>
                 {
                     loadedProtocol = "";
                     protocolDictionary.Clear();
                     sessionDictionary.Clear();
                     sessionElementDictionary.Clear();
                 },
                 fileNotFoundCallback: () => loadedProtocol = previousLoadedProtocol);
         }
MigrateProtocols()
delegate void BGC.Study.ProtocolManager.MigrateProtocols (ref JsonObject protocols)
ParseSessionElement()
delegate SessionElement BGC.Study.ProtocolManager.ParseSessionElement (JsonObject sessionElement)
PrepareNextElement()
delegate void BGC.Study.ProtocolManager.PrepareNextElement (bool resuming)
PrepareProtocol()
static void BGC.Study.ProtocolManager.PrepareProtocol (string protocolName, int protocolID) inline static
Definition at line 74 of file ProtocolManager.cs.
         {
             currentProtocol = null;
             currentSession = null;
             currentSessionElement = null;
             nextSessionElementIndex = -1;
             loadedProtocol = "";
             LoadProtocolSet(protocolName);
             if (protocolDictionary.ContainsKey(protocolID))
             {
                 currentProtocol = protocolDictionary[protocolID];
             }
             else
             {
                 Debug.LogError($"Loaded Protocol \"{loadedProtocol}\" does not contain requested protocolID {protocolID}.");
                 return;
             }
         }
RegisterSpecializers()
static void BGC.Study.ProtocolManager.RegisterSpecializers (SessionElementOverrun sessionElementOverrun, PrepareNextElement prepareNextElement, ParseSessionElement parseSessionElement, MigrateProtocols migrateProtocols) inline static
Definition at line 239 of file ProtocolManager.cs.
References BGC.Study.ProtocolManager.migrateProtocols, BGC.Study.ProtocolManager.parseSessionElement, BGC.Study.ProtocolManager.prepareNextElement, and BGC.Study.ProtocolManager.sessionElementOverrun.
         {
             ProtocolManager.sessionElementOverrun = sessionElementOverrun;
             ProtocolManager.prepareNextElement = prepareNextElement;
             ProtocolManager.parseSessionElement = parseSessionElement;
             ProtocolManager.migrateProtocols = migrateProtocols;
         }
RemoveRedundancies()
static void BGC.Study.ProtocolManager.RemoveRedundancies () inline static private
Definition at line 298 of file ProtocolManager.cs.
References BGC.Study.ProtocolKeys.Session.Id, BGC.Study.ProtocolKeys.SessionElement.Id, LightJson.JsonObject.Remove(), and LightJson.JsonObject.ToString().
         {
             Dictionary<int, int> sessionElementRemapping = new Dictionary<int, int>();
             Dictionary<string, int> sessionElements = new Dictionary<string, int>();
             foreach (KeyValuePair<int, SessionElement> sessionElement in sessionElementDictionary)
             {
                 JsonObject serializedElement = sessionElement.Value.SerializeElement();
                 serializedElement.Remove(ProtocolKeys.SessionElement.Id);
                 string serialization = serializedElement.ToString();
                 if (sessionElements.ContainsKey(serialization))
                 {
                     //Collision - Add it to be remapped
                     int newID = sessionElements[serialization];
                     sessionElementRemapping.Add(sessionElement.Key, newID);
                 }
                 else
                 {
                     //It's a different sessionElement - Add it to the dictionary
                     sessionElements.Add(serialization, sessionElement.Key);
                 }
             }
             Dictionary<int, int> sessionRemapping = new Dictionary<int, int>();
             Dictionary<string, int> sessions = new Dictionary<string, int>();
             foreach (KeyValuePair<int, Session> session in sessionDictionary)
             {
                 //Apply Remapping To Sessions
                 List<SessionElementID> elementIDs = session.Value.sessionElements;
                 for (int i = 0; i < elementIDs.Count; i++)
                 {
                     if (sessionElementRemapping.ContainsKey(elementIDs[i].id))
                     {
                         elementIDs[i] = new SessionElementID(sessionElementRemapping[elementIDs[i].id]);
                     }
                 }
                 JsonObject serializedSession = session.Value.SerializeSession();
                 serializedSession.Remove(ProtocolKeys.Session.Id);
                 string serialization = serializedSession.ToString();
                 if (sessions.ContainsKey(serialization))
                 {
                     //Collision - Add it to be remapped
                     int newID = sessions[serialization];
                     sessionRemapping.Add(session.Key, newID);
                 }
                 else
                 {
                     //It's a different session - Add it to the dictionary
                     sessions.Add(serialization, session.Key);
                 }
             }
             foreach (KeyValuePair<int, Protocol> protocol in protocolDictionary)
             {
                 //Apply Remapping To Protocols
                 List<SessionID> sessionIDs = protocol.Value.sessions;
                 for (int i = 0; i < sessionIDs.Count; i++)
                 {
                     if (sessionRemapping.ContainsKey(sessionIDs[i].id))
                     {
                         sessionIDs[i] = new SessionID(sessionRemapping[sessionIDs[i].id]);
                     }
                 }
             }
             //Remove eliminated SessionElements
             foreach (int sessionElementID in sessionElementRemapping.Keys)
             {
                 sessionElementDictionary.Remove(sessionElementID);
             }
             //Remove eliminated Sessions
             foreach (int sessionID in sessionRemapping.Keys)
             {
                 sessionDictionary.Remove(sessionID);
             }
         }
SaveAs()
static void BGC.Study.ProtocolManager.SaveAs (string protocolName) inline static
Definition at line 291 of file ProtocolManager.cs.
         {
             loadedProtocol = protocolName;
             RemoveRedundancies();
             SerializeAll();
         }
SerializeAll()
static void BGC.Study.ProtocolManager.SerializeAll () inline static
Definition at line 382 of file ProtocolManager.cs.
References BGC.IO.DataManagement.PathForDataDirectory(), BGC.Study.ProtocolKeys.Protocols, BGC.Study.ProtocolKeys.SessionElements, BGC.Study.ProtocolKeys.Sessions, BGC.Study.ProtocolKeys.Version, and BGC.IO.FileWriter.WriteJson().
         {
             if (loadedProtocol == "")
             {
                 Debug.LogError("Can't serialize protocol - none loaded");
                 return;
             }
             FileWriter.WriteJson(
                 path: Path.Combine(DataManagement.PathForDataDirectory(protocolDataDir), $"{loadedProtocol}.json"),
                 createJson: () => new JsonObject()
                 {
                     { ProtocolKeys.Version, protocolDataVersion },
                     { ProtocolKeys.Protocols, SerializeProtocols() },
                     { ProtocolKeys.Sessions, SerializeSessions() },
                     { ProtocolKeys.SessionElements, SerializeSessionElements() }
                 },
                 pretty: true);
         }
SerializeProtocols()
static JsonArray BGC.Study.ProtocolManager.SerializeProtocols () inline static
Definition at line 441 of file ProtocolManager.cs.
References LightJson.JsonObject.Add(), LightJson.JsonObject.Count, BGC.Study.ProtocolKeys.Protocol.EnvironmentValues, BGC.Study.Protocol.envVals, BGC.Study.Protocol.id, BGC.Study.ProtocolKeys.Protocol.Id, BGC.Study.SessionID.id, BGC.Study.Protocol.name, BGC.Study.ProtocolKeys.Protocol.Name, BGC.Study.ProtocolKeys.Protocol.SessionIDs, and BGC.Study.Protocol.sessions.
         {
             JsonArray protocols = new JsonArray();
             foreach (Protocol protocol in protocolDictionary.Values)
             {
                 JsonArray jsonSessionIDs = new JsonArray();
                 foreach (SessionID sessionID in protocol.sessions)
                 {
                     jsonSessionIDs.Add(sessionID.id);
                 }
                 JsonObject newProtocol = new JsonObject()
                 {
                     { ProtocolKeys.Protocol.Id, protocol.id },
                     { ProtocolKeys.Protocol.Name, protocol.name },
                     { ProtocolKeys.Protocol.SessionIDs, jsonSessionIDs }
                 };
                 if (protocol.envVals.Count > 0)
                 {
                     newProtocol.Add(ProtocolKeys.Protocol.EnvironmentValues, protocol.envVals);
                 }
                 protocols.Add(newProtocol);
             }
             return protocols;
         }
SerializeSessionElements()
static JsonArray BGC.Study.ProtocolManager.SerializeSessionElements () inline static
Definition at line 528 of file ProtocolManager.cs.
References BGC.Study.SessionElement.SerializeElement().
         {
             JsonArray sessions = new JsonArray();
             foreach (SessionElement element in sessionElementDictionary.Values)
             {
                 sessions.Add(element.SerializeElement());
             }
             return sessions;
         }
SerializeSessions()
static JsonArray BGC.Study.ProtocolManager.SerializeSessions () inline static
Definition at line 504 of file ProtocolManager.cs.
References BGC.Study.Session.SerializeSession().
         {
             JsonArray sessions = new JsonArray();
             foreach (Session session in sessionDictionary.Values)
             {
                 sessions.Add(session.SerializeSession());
             }
             return sessions;
         }
SessionElementOverrun()
delegate void BGC.Study.ProtocolManager.SessionElementOverrun ()
SetSession()
static ProtocolStatus BGC.Study.ProtocolManager.SetSession (int session, int element = 0) inline static
Definition at line 118 of file ProtocolManager.cs.
References BGC.Study.Protocol.Count, BGC.Study.Session.Count, and BGC.Study.Protocol.id.
         {
             currentSession = null;
             currentSessionElement = null;
             nextSessionElementIndex = -1;
             if (loadedProtocol == "")
             {
                 return ProtocolStatus.Uninitialized;
             }
             if (!protocolDictionary.ContainsKey(currentProtocol.id))
             {
                 return ProtocolStatus.InvalidProtocol;
             }
             if (session >= currentProtocol.Count)
             {
                 return ProtocolStatus.SessionLimitExceeded;
             }
             SessionNumber = session;
             currentSession = currentProtocol[session];
             if (element >= currentSession.Count)
             {
                 return ProtocolStatus.SessionElementLimitExceeded;
             }
             //The next session element to run will be the current one
             nextSessionElementIndex = element;
             return ProtocolStatus.SessionReady;
         }
TryUpdateProtocol()
static ProtocolStatus BGC.Study.ProtocolManager.TryUpdateProtocol (string protocolName, int protocolID, int sessionIndex, int sessionElementIndex = 0) inline static
Definition at line 94 of file ProtocolManager.cs.
         {
             if (LoadProtocolSet(protocolName))
             {
                 if (protocolDictionary.ContainsKey(protocolID))
                 {
                     currentProtocol = protocolDictionary[protocolID];
                     return SetSession(sessionIndex, sessionElementIndex);
                 }
                 else
                 {
                     Debug.LogError($"Loaded Protocol \"{loadedProtocol}\" does not contain requested protocolID {protocolID}.");
                     return ProtocolStatus.InvalidProtocol;
                 }
             }
             return ProtocolStatus.Uninitialized;
         }
UpdateDefaults()
static void BGC.Study.ProtocolManager.UpdateDefaults () inline static
Definition at line 558 of file ProtocolManager.cs.
References BGC.IO.FileExtensions.AddJsonExtension(), and BGC.IO.DataManagement.PathForDataDirectory().
         {
             string path = DataManagement.PathForDataDirectory(protocolDataDir);
             TextAsset[] assets = Resources.LoadAll<TextAsset>(protocolDataDir);
             foreach (TextAsset asset in assets)
             {
                 string currentFile = Path.Combine(path, FileExtensions.AddJsonExtension(asset.name));
                 File.WriteAllText(currentFile, asset.text);
             }
         }
Field Documentation
currentProtocol
Protocol BGC.Study.ProtocolManager.currentProtocol = null static
Definition at line 40 of file ProtocolManager.cs.
currentSession
Session BGC.Study.ProtocolManager.currentSession = null static
Definition at line 41 of file ProtocolManager.cs.
currentSessionElement
SessionElement BGC.Study.ProtocolManager.currentSessionElement = null static
Definition at line 42 of file ProtocolManager.cs.
loadedProtocol
string BGC.Study.ProtocolManager.loadedProtocol = "" static private
Definition at line 26 of file ProtocolManager.cs.
migrateProtocols
MigrateProtocols BGC.Study.ProtocolManager.migrateProtocols = null static private
Definition at line 71 of file ProtocolManager.cs.
Referenced by BGC.Study.ProtocolManager.RegisterSpecializers().
nextSessionElementIndex
int BGC.Study.ProtocolManager.nextSessionElementIndex = -1 static
Definition at line 44 of file ProtocolManager.cs.
parseSessionElement
ParseSessionElement BGC.Study.ProtocolManager.parseSessionElement = null static private
Definition at line 72 of file ProtocolManager.cs.
Referenced by BGC.Study.ProtocolManager.RegisterSpecializers().
prepareNextElement
PrepareNextElement BGC.Study.ProtocolManager.prepareNextElement = null static private
Definition at line 70 of file ProtocolManager.cs.
Referenced by BGC.Study.ProtocolManager.RegisterSpecializers().
protocolDataDir
const string BGC.Study.ProtocolManager.protocolDataDir = "Protocols" private
Definition at line 23 of file ProtocolManager.cs.
protocolDataVersion
const int BGC.Study.ProtocolManager.protocolDataVersion = 2
Definition at line 24 of file ProtocolManager.cs.
protocolDictionary
Dictionary<int, Protocol> BGC.Study.ProtocolManager.protocolDictionary = new Dictionary<int, Protocol>() static
Definition at line 35 of file ProtocolManager.cs.
Referenced by BGC.Study.Protocol.Protocol().
sessionDictionary
Dictionary<int, Session> BGC.Study.ProtocolManager.sessionDictionary = new Dictionary<int, Session>() static
Definition at line 36 of file ProtocolManager.cs.
Referenced by BGC.Study.Session.Session().
sessionElementDictionary
Dictionary<int, SessionElement> BGC.Study.ProtocolManager.sessionElementDictionary static
Initial value:
=
            new Dictionary<int, SessionElement>()
Definition at line 37 of file ProtocolManager.cs.
Referenced by BGC.Study.SessionElement.SessionElement().
sessionElementOverrun
SessionElementOverrun BGC.Study.ProtocolManager.sessionElementOverrun = null static private
Definition at line 69 of file ProtocolManager.cs.
Referenced by BGC.Study.ProtocolManager.RegisterSpecializers().
Property Documentation
ElementNumber
int BGC.Study.ProtocolManager.ElementNumber static get set
Definition at line 47 of file ProtocolManager.cs.
SessionInProgress
bool BGC.Study.ProtocolManager.SessionInProgress static get set
Definition at line 59 of file ProtocolManager.cs.
SessionNumber
int BGC.Study.ProtocolManager.SessionNumber static get set
Definition at line 53 of file ProtocolManager.cs.
The documentation for this class was generated from the following file:
Study/ProtocolManager.cs