BGC Tools: LightJson.JsonObject Class Reference
LightJson.JsonObject Class Reference
Represents a key-value pair collection of JsonValue objects.
Data Structures
class JsonObjectDebugView
Public Member Functions
JsonObject ()
Initializes a new instance of JsonObject.
JsonObject Add (string key)
Adds a key with a null value to this collection.
JsonObject Add (string key, JsonValue value)
Adds a value associated with a key to this collection.
JsonObject AddIfNotNull (string key, JsonValue value)
Adds a value associated with a key to this collection only if the value is not null.
bool Remove (string key)
Removes a property with the given key.
JsonObject Clear ()
Clears the contents of this collection.
JsonObject Rename (string oldKey, string newKey)
Changes the key of one of the items in the collection.
bool ContainsKey (string key)
Determines whether this collection contains an item assosiated with the given key.
bool ContainsKey (string key, out JsonValue value)
Determines whether this collection contains an item assosiated with the given key.
bool Contains (JsonValue value)
Determines whether this collection contains the given JsonValue.
IEnumerator< KeyValuePair< string, JsonValue > > GetEnumerator ()
Returns an enumerator that iterates through this collection.
override string ToString ()
Returns a JSON string representing the state of the object.
string ToString (bool pretty)
Returns a JSON string representing the state of the object.
Data Fields
int Count => properties.Count
The number of properties in this JsonObject.
Properties
JsonValue this[string key] [get, set]
The property with the given key.
Private Member Functions
IEnumerator< JsonValue > IEnumerable< JsonValue >. GetEnumerator ()
Returns an enumerator that iterates through this collection.
System.Collections.IEnumerator System.Collections.IEnumerable. GetEnumerator ()
Returns an enumerator that iterates through this collection.
Private Attributes
Dictionary< string, JsonValue > properties = new Dictionary<string, JsonValue>()
Detailed Description
Represents a key-value pair collection of JsonValue objects.
Definition at line 13 of file JsonObject.cs.
Constructor & Destructor Documentation
JsonObject()
LightJson.JsonObject.JsonObject () inline
Initializes a new instance of JsonObject.
Definition at line 45 of file JsonObject.cs.
References LightJson.JsonObject.Add(), and LightJson.JsonValue.Null.
 { }
Member Function Documentation
Add() [1/2]
JsonObject LightJson.JsonObject.Add (string key)
Adds a key with a null value to this collection.
Parameters
key The key of the property to be added.
Returns this JsonObject.
Referenced by LightJson.JsonObject.Add(), LightJson.JsonObject.AddIfNotNull(), BGC.Audio.Calibration.DeserializeCalibration(), LightJson.JsonObject.JsonObject(), LightJson.Serialization.JsonReader.ReadObject(), BGC.Study.SessionElement.SerializeElement(), BGC.Study.ProtocolManager.SerializeProtocols(), BGC.Study.Session.SerializeSession(), BGC.Study.Session.Session(), BGC.Users.ProfileData.SetBool(), BGC.Users.ProfileData.SetDouble(), BGC.Users.ProfileData.SetFloat(), BGC.Users.ProfileData.SetInt(), BGC.Users.ProfileData.SetJsonArray(), BGC.Users.ProfileData.SetJsonValue(), BGC.Users.ProfileData.SetString(), BGC.Utility.EnumUtility.ToJsonObject< T >(), and BGC.Extensions.JsonExtensions.TryGetValue().
Add() [2/2]
JsonObject LightJson.JsonObject.Add (string key, JsonValue value) inline
Adds a value associated with a key to this collection.
Parameters
key The key of the property to be added.
value The value of the property to be added.
Returns
Returns this JsonObject.
Definition at line 60 of file JsonObject.cs.
References LightJson.JsonObject.Add().
         {
             properties.Add(key, value);
             return this;
         }
AddIfNotNull()
JsonObject LightJson.JsonObject.AddIfNotNull (string key, JsonValue value) inline
Adds a value associated with a key to this collection only if the value is not null.
Parameters
key The key of the property to be added.
value The value of the property to be added.
Returns
Returns this JsonObject.
Definition at line 72 of file JsonObject.cs.
References LightJson.JsonObject.Add(), LightJson.JsonValue.IsNull, and LightJson.JsonObject.Remove().
         {
             if (value.IsNull == false)
             {
                 Add(key, value);
             }
             return this;
         }
Clear()
JsonObject LightJson.JsonObject.Clear () inline
Clears the contents of this collection.
Returns
Returns this JsonObject.
Definition at line 95 of file JsonObject.cs.
References LightJson.JsonObject.Clear().
Referenced by BGC.Users.ProfileData.Clear(), and LightJson.JsonObject.Clear().
         {
             properties.Clear();
             return this;
         }
Contains()
bool LightJson.JsonObject.Contains (JsonValue value)
Determines whether this collection contains the given JsonValue.
Parameters
value The value to locate in this collection.
Returns
Returns true if the value is found; otherwise, false.
Referenced by LightJson.JsonObject.Rename().
ContainsKey() [1/2]
bool LightJson.JsonObject.ContainsKey (string key)
Determines whether this collection contains an item assosiated with the given key.
Parameters
key The key to locate in this collection.
Returns
Returns true if the key is found; otherwise, false.
Referenced by BGC.Users.ProfileData.Deserialize(), BGC.Users.ProfileData.GetBool(), BGC.Users.ProfileData.GetDouble(), BGC.Study.ProtocolManager.GetEnvValue(), BGC.Users.ProfileData.GetFloat(), BGC.Users.ProfileData.GetInt(), BGC.Users.ProfileData.GetJsonArray(), BGC.Users.ProfileData.GetJsonValue(), BGC.Users.ProfileData.GetString(), LightJson.Serialization.JsonReader.ReadObject(), LightJson.JsonObject.Rename(), BGC.Study.SessionElement.SessionElement(), BGC.Users.ProfileData.SetBool(), BGC.Users.ProfileData.SetDouble(), BGC.Users.ProfileData.SetFloat(), BGC.Users.ProfileData.SetInt(), BGC.Users.ProfileData.SetJsonArray(), BGC.Users.ProfileData.SetJsonValue(), BGC.Users.ProfileData.SetString(), and BGC.Extensions.JsonExtensions.TryGetValue().
ContainsKey() [2/2]
bool LightJson.JsonObject.ContainsKey (string key, out JsonValue value)
Determines whether this collection contains an item assosiated with the given key.
Parameters
key The key to locate in this collection.
value When this method returns, this value gets assigned the JsonValue assosiated with the key, if the key is found; otherwise, JsonValue.Null is assigned.
Returns
Returns true if the key is found; otherwise, false.
GetEnumerator() [1/3]
IEnumerator<KeyValuePair<string, JsonValue> > LightJson.JsonObject.GetEnumerator ()
Returns an enumerator that iterates through this collection.
Referenced by LightJson.Serialization.JsonWriter.GetJsonObjectEnumerator(), and LightJson.JsonObject.Rename().
GetEnumerator() [2/3]
IEnumerator<JsonValue> IEnumerable<JsonValue>. LightJson.JsonObject.GetEnumerator () private
Returns an enumerator that iterates through this collection.
GetEnumerator() [3/3]
System.Collections.IEnumerator System.Collections.IEnumerable. LightJson.JsonObject.GetEnumerator () private
Returns an enumerator that iterates through this collection.
Remove()
bool LightJson.JsonObject.Remove (string key)
Removes a property with the given key.
Parameters
key The key of the property to be removed.
Returns
Returns true if the given key is found and removed; otherwise, false.
Referenced by LightJson.JsonObject.AddIfNotNull(), BGC.Users.ProfileData.GetJsonArray(), BGC.Study.ProtocolManager.RemoveRedundancies(), and LightJson.JsonObject.Rename().
Rename()
JsonObject LightJson.JsonObject.Rename (string oldKey, string newKey) inline
Changes the key of one of the items in the collection.
This method has no effects if the oldKey does not exists. If the newKey already exists, the value will be overwritten.
Parameters
oldKey The name of the key to be changed.
newKey The new name of the key.
Returns
Returns this JsonObject.
Definition at line 111 of file JsonObject.cs.
References LightJson.JsonObject.Contains(), LightJson.JsonObject.ContainsKey(), LightJson.JsonObject.GetEnumerator(), LightJson.JsonObject.Remove(), LightJson.Serialization.JsonWriter.Serialize(), and LightJson.JsonObject.ToString().
         {
             JsonValue value;
             if (properties.TryGetValue(oldKey, out value))
             {
                 Remove(oldKey);
                 this[newKey] = value;
             }
             return this;
         }
ToString() [1/2]
override string LightJson.JsonObject.ToString ()
Returns a JSON string representing the state of the object.
The resulting string is safe to be inserted as is into dynamically generated JavaScript or JSON code.
Referenced by BGC.Study.ProtocolManager.RemoveRedundancies(), and LightJson.JsonObject.Rename().
ToString() [2/2]
string LightJson.JsonObject.ToString (bool pretty)
Returns a JSON string representing the state of the object.
The resulting string is safe to be inserted as is into dynamically generated JavaScript or JSON code.
Parameters
pretty Indicates whether the resulting string should be formatted for human-readability.
Field Documentation
Count
int LightJson.JsonObject.Count => properties.Count
The number of properties in this JsonObject.
Definition at line 18 of file JsonObject.cs.
Referenced by BGC.Study.SessionElement.SerializeElement(), BGC.Study.ProtocolManager.SerializeProtocols(), and BGC.Study.Session.SerializeSession().
properties
Dictionary<string, JsonValue> LightJson.JsonObject.properties = new Dictionary<string, JsonValue>() private
Definition at line 15 of file JsonObject.cs.
Property Documentation
this[string key]
JsonValue LightJson.JsonObject.this[string key] get set
The property with the given key.
Parameters
key The key of the property to get or set.
Returns JsonValue.Null if the given key is not assosiated with any value.
Definition at line 24 of file JsonObject.cs.
The documentation for this class was generated from the following file:
LightJSON/JsonObject.cs