BGC Tools: BGC.Audio.Midi.MidiFile Class Reference
BGC.Audio.Midi.MidiFile Class Reference
Public Member Functions
MidiFile (in HeaderInfo headerInfo, bool retainAll=false)
MidiFile (Stream headerStream, bool retainAll=false)
Deserialization Constructor
void Add (MidiTrack track)
void AddRange (IEnumerable< MidiTrack > tracks)
void ReadTrack (Stream trackStream)
void Serialize (Stream outputStream)
Data Fields
const string HEADER_CHUNK_NAME = "MThd"
readonly List< MidiTrack > tracks = new List<MidiTrack>()
readonly HeaderInfo headerInfo
Private Attributes
readonly bool retainAll
Detailed Description
Definition at line 13 of file MidiFile.cs.
Constructor & Destructor Documentation
MidiFile() [1/2]
BGC.Audio.Midi.MidiFile.MidiFile (in HeaderInfo headerInfo, bool retainAll = false) inline
Definition at line 21 of file MidiFile.cs.
         {
             this.headerInfo = headerInfo;
             this.retainAll = retainAll;
         }
MidiFile() [2/2]
BGC.Audio.Midi.MidiFile.MidiFile (Stream headerStream, bool retainAll = false) inline
Deserialization Constructor
Definition at line 30 of file MidiFile.cs.
         {
             headerInfo = new HeaderInfo(headerStream.ReadRemainder());
             this.retainAll = retainAll;
             switch (headerInfo.format)
             {
                 case Format.SingleTrack:
                 case Format.TempoMapped:
                 case Format.SequenceContainer:
                     //Do nothing - this is fine
                     break;
                 case Format.UNDEFINED:
                 default:
                     throw new MidiParsingException($"Unexpected Format: {headerInfo.format}");
             }
         }
Member Function Documentation
Add()
void BGC.Audio.Midi.MidiFile.Add (MidiTrack track) inline
Definition at line 51 of file MidiFile.cs.
         {
             tracks.Add(track);
         }
AddRange()
void BGC.Audio.Midi.MidiFile.AddRange (IEnumerable< MidiTrack > tracks) inline
Definition at line 56 of file MidiFile.cs.
         {
             foreach (MidiTrack track in tracks)
             {
                 Add(track);
             }
         }
ReadTrack()
void BGC.Audio.Midi.MidiFile.ReadTrack (Stream trackStream)
Serialize()
void BGC.Audio.Midi.MidiFile.Serialize (Stream outputStream) inline
Definition at line 71 of file MidiFile.cs.
References BGC.Audio.Midi.MidiTrack.Serialize().
Referenced by BGC.Audio.Midi.MidiEncoding.SaveFile().
         {
             byte[] header = headerInfo.Serialize();
             outputStream.Write(Encoding.UTF8.GetBytes(HEADER_CHUNK_NAME), 0, 4);
             outputStream.WriteByte((byte)(header.Length >> 24));
             outputStream.WriteByte((byte)((header.Length >> 16) & 0b1111_1111));
             outputStream.WriteByte((byte)((header.Length >> 8) & 0b1111_1111));
             outputStream.WriteByte((byte)(header.Length & 0b1111_1111));
             outputStream.Write(header, 0, header.Length);
             tracks.ForEach(track => track.Serialize(outputStream));
         }
Field Documentation
HEADER_CHUNK_NAME
const string BGC.Audio.Midi.MidiFile.HEADER_CHUNK_NAME = "MThd"
Definition at line 15 of file MidiFile.cs.
Referenced by BGC.Audio.Midi.MidiEncoding.LoadFile().
headerInfo
readonly HeaderInfo BGC.Audio.Midi.MidiFile.headerInfo
Definition at line 19 of file MidiFile.cs.
retainAll
readonly bool BGC.Audio.Midi.MidiFile.retainAll private
Definition at line 18 of file MidiFile.cs.
tracks
readonly List<MidiTrack> BGC.Audio.Midi.MidiFile.tracks = new List<MidiTrack>()
Definition at line 16 of file MidiFile.cs.
Referenced by BGC.Audio.Midi.MidiFileStream.MidiFileStream().
The documentation for this class was generated from the following file:
Audio/Midi/MidiFile.cs