BGC Tools: BGC.Audio.CrossFadingRefClip Class Reference
BGC.Audio.CrossFadingRefClip Class Reference
Holds a reference to a large underlying sample buffer. Loops and crossfades with itself. Used for managing extra-large TENoise sample.
Public Member Functions
CrossFadingRefClip (float[] samples, double leftFactor, double rightFactor, int initialPosition=-1)
override void Reset ()
Sets this internal state of this stream to the initial state
override int Read (float[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
override void Seek (int position)
Seek to the indicated position in the stream
override IEnumerable< double > GetChannelRMS ()
The RMS amplitude of each channel
Public Member Functions inherited from BGC.Audio.BGCStream
void Initialize ()
Perform any calculations necessary to prepare the Stream
Data Fields
override int Channels => 2
override int TotalSamples => Channels * Samples.Length
override int ChannelSamples => Samples.Length
Data Fields inherited from BGC.Audio.BGCAudioClip
float Duration => ChannelSamples / SamplingRate
override float SamplingRate => 44100f
Properties
float[] Samples [get]
int Position [get, private set]
Properties inherited from BGC.Audio.BGCStream
abstract int Channels [get]
abstract int TotalSamples [get]
abstract int ChannelSamples [get]
abstract float SamplingRate [get]
Properties inherited from BGC.Audio.IBGCStream
int Channels [get]
The number of underlying Channels of this BGCStream
int TotalSamples [get]
The total number of Samples of this BGCStream
int ChannelSamples [get]
The number of Samples of each channel for this BGCStream
float SamplingRate [get]
The sampling rate of the Stream
Private Attributes
readonly float leftFactor = 0f
readonly float rightFactor = 0f
const float FADE_DURATION = 1.0f
readonly float[] window = null
int initialWindowStart = -1
readonly int startCrossFade
Additional Inherited Members
Protected Member Functions inherited from BGC.Audio.BGCStream
virtual void _Initialize ()
Protected Attributes inherited from BGC.Audio.BGCStream
bool initialized = false
Detailed Description
Holds a reference to a large underlying sample buffer. Loops and crossfades with itself. Used for managing extra-large TENoise sample.
Definition at line 12 of file CrossFadingRefClip.cs.
Constructor & Destructor Documentation
BGC.Audio.CrossFadingRefClip.CrossFadingRefClip (float[] samples, double leftFactor, double rightFactor, int initialPosition = -1) inline
Definition at line 33 of file CrossFadingRefClip.cs.
References BGC.Mathematics.CustomRandom.Next().
         {
             Samples = samples;
             this.leftFactor = (float)leftFactor;
             this.rightFactor = (float)rightFactor;
             window = new float[(int)(SamplingRate * FADE_DURATION)];
             double sineArgument = Math.PI / (2 * window.Length - 1);
             for (int i = 0; i < window.Length; i++)
             {
                 window[i] = (float)Math.Sin(i * sineArgument);
             }
             startCrossFade = Samples.Length - window.Length;
             if (initialPosition == -1)
             {
                 //Start at least 2 window lengths before end
                 initialPosition = CustomRandom.Next(0, Samples.Length - (2 * window.Length + 2));
             }
             Position = initialPosition;
             initialWindowStart = Position;
         }
Member Function Documentation
override IEnumerable<double> BGC.Audio.CrossFadingRefClip.GetChannelRMS () virtual
The RMS amplitude of each channel
Implements BGC.Audio.BGCStream.
override int BGC.Audio.CrossFadingRefClip.Read (float[] data, int offset, int count) inline virtual
Copy count samples into the Data buffer, starting at offset.
Returns
The number of samples copied
Implements BGC.Audio.BGCStream.
Definition at line 72 of file CrossFadingRefClip.cs.
References BGC.Mathematics.GeneralMath.Clamp().
         {
             //Split into regions
             int remainingCount = count;
             while (remainingCount > 0)
             {
                 if (initialWindowStart != -1)
                 {
                     //Initial window period
                     //Windowing region
                     int initialWindowingEndSample = initialWindowStart + window.Length;
                     int copyLength = Math.Min(initialWindowingEndSample - Position, remainingCount / 2);
                     for (int i = 0; i < copyLength; i++)
                     {
                         float sample = window[Position - initialWindowStart + i] * Samples[Position + i];
                         data[offset + 2 * i] = leftFactor * sample;
                         data[offset + 2 * i + 1] = rightFactor * sample;
                     }
                     //Advance Indices
                     Position += copyLength;
                     offset += 2 * copyLength;
                     remainingCount -= 2 * copyLength;
                     if (Position == initialWindowingEndSample)
                     {
                         //Done with initial window
                         initialWindowStart = -1;
                     }
                 }
                 else if (Position < startCrossFade)
                 {
                     //Region 1 - No windowing Needed
                     int copyLength = Math.Min(startCrossFade - Position, remainingCount / 2);
                     for (int i = 0; i < copyLength; i++)
                     {
                         data[offset + 2 * i] = leftFactor * Samples[Position + i];
                         data[offset + 2 * i + 1] = rightFactor * Samples[Position + i];
                     }
                     //Advance Indices
                     Position += copyLength;
                     offset += 2 * copyLength;
                     remainingCount -= 2 * copyLength;
                 }
                 else
                 {
                     //Region 2 - Cross-windowing
                     int copyLength = Math.Min(Samples.Length - Position, remainingCount / 2);
                     for (int i = 0; i < copyLength; i++)
                     {
                         float outSample = window[Samples.Length - Position - i - 1] * Samples[Position + i];
                         float inSample = window[Position + i - startCrossFade] * Samples[Position + i - startCrossFade];
                         data[offset + 2 * i] = leftFactor * (outSample + inSample);
                         data[offset + 2 * i + 1] = rightFactor * (outSample + inSample);
                     }
                     //Advance Indices
                     Position += copyLength;
                     offset += 2 * copyLength;
                     remainingCount -= 2 * copyLength;
                     if (Position >= Samples.Length)
                     {
                         Position = window.Length;
                     }
                 }
             }
             return count;
         }
override void BGC.Audio.CrossFadingRefClip.Reset () inline virtual
Sets this internal state of this stream to the initial state
Implements BGC.Audio.BGCStream.
Definition at line 65 of file CrossFadingRefClip.cs.
References BGC.Mathematics.CustomRandom.Next().
         {
             //Start at least 2 window lengths before end
             Position = CustomRandom.Next(0, Samples.Length - (2 * window.Length + 2));
             initialWindowStart = Position;
         }
override void BGC.Audio.CrossFadingRefClip.Seek (int position) virtual
Seek to the indicated position in the stream
Implements BGC.Audio.BGCStream.
Field Documentation
override int BGC.Audio.CrossFadingRefClip.Channels => 2
Definition at line 15 of file CrossFadingRefClip.cs.
override int BGC.Audio.CrossFadingRefClip.ChannelSamples => Samples.Length
Definition at line 18 of file CrossFadingRefClip.cs.
const float BGC.Audio.CrossFadingRefClip.FADE_DURATION = 1.0f private
Definition at line 27 of file CrossFadingRefClip.cs.
int BGC.Audio.CrossFadingRefClip.initialWindowStart = -1 private
Definition at line 30 of file CrossFadingRefClip.cs.
readonly float BGC.Audio.CrossFadingRefClip.leftFactor = 0f private
Definition at line 24 of file CrossFadingRefClip.cs.
readonly float BGC.Audio.CrossFadingRefClip.rightFactor = 0f private
Definition at line 25 of file CrossFadingRefClip.cs.
readonly int BGC.Audio.CrossFadingRefClip.startCrossFade private
Definition at line 31 of file CrossFadingRefClip.cs.
override int BGC.Audio.CrossFadingRefClip.TotalSamples => Channels * Samples.Length
Definition at line 17 of file CrossFadingRefClip.cs.
readonly float [] BGC.Audio.CrossFadingRefClip.window = null private
Definition at line 29 of file CrossFadingRefClip.cs.
Property Documentation
int BGC.Audio.CrossFadingRefClip.Position get private set
Definition at line 22 of file CrossFadingRefClip.cs.
float [] BGC.Audio.CrossFadingRefClip.Samples get
Definition at line 20 of file CrossFadingRefClip.cs.
The documentation for this class was generated from the following file:
Audio/Streams/CrossFadingRefClip.cs