BGC Tools: BGC.Audio.Filters.SinglePassPhaseReencoder Class Reference
BGC.Audio.Filters.SinglePassPhaseReencoder Class Reference
A Decorator class for BGCAudioClips that applies the a SinglePass Phase reencoding for introducing an effective ITD
Public Member Functions
SinglePassPhaseReencoder (IBGCStream stream, double timeShift)
SinglePassPhaseReencoder (IBGCStream stream, double leftTimeShift, double rightTimeShift)
override int Read (float[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
override void Reset ()
Sets this internal state of this stream to the initial state
override void Seek (int position)
Seek to the indicated position in the stream
override IEnumerable< double > GetChannelRMS ()
The RMS amplitude of each channel
Public Member Functions inherited from BGC.Audio.Filters.SimpleBGCFilter
SimpleBGCFilter (IBGCStream stream)
override void Initialize ()
Perform any calculations necessary to prepare the Stream
Data Fields
override int TotalSamples => Channels * ChannelSamples
override int ChannelSamples => stream.ChannelSamples
override float SamplingRate => stream.SamplingRate
Data Fields inherited from BGC.Audio.Filters.SimpleBGCFilter
override float SamplingRate => stream.SamplingRate
Protected Member Functions
override void _Initialize ()
Properties
override int Channels [get]
int Position [get, private set]
float [] Samples = 0 [get, private set]
Properties inherited from BGC.Audio.Filters.SimpleBGCFilter
override IEnumerable< IBGCStream > InternalStreams [get]
Properties inherited from BGC.Audio.Filters.BGCFilter
abstract int Channels [get]
abstract int TotalSamples [get]
abstract int ChannelSamples [get]
abstract float SamplingRate [get]
abstract IEnumerable< IBGCStream > InternalStreams [get]
Properties inherited from BGC.Audio.IBGCStream
int Channels [get]
The number of underlying Channels of this BGCStream
int TotalSamples [get]
The total number of Samples of this BGCStream
int ChannelSamples [get]
The number of Samples of each channel for this BGCStream
float SamplingRate [get]
The sampling rate of the Stream
Private Member Functions
void TimeShift (Complex64[] samples, double timeShift)
Private Attributes
int RemainingSamples => ChannelSamples - Position
readonly double leftTimeShift = null
readonly double rightTimeShift
IEnumerable< double > _channelRMS = null
Additional Inherited Members
Protected Attributes inherited from BGC.Audio.Filters.SimpleBGCFilter
readonly IBGCStream stream
Protected Attributes inherited from BGC.Audio.Filters.BGCFilter
bool initialized = false
Detailed Description
A Decorator class for BGCAudioClips that applies the a SinglePass Phase reencoding for introducing an effective ITD
This class is a bit wordy in its implementation, but I really wanted to make the Initialize method have certain work-skipping optimizations
Definition at line 15 of file SinglePassPhaseReencoder.cs.
Constructor & Destructor Documentation
SinglePassPhaseReencoder() [1/2]
BGC.Audio.Filters.SinglePassPhaseReencoder.SinglePassPhaseReencoder (IBGCStream stream, double timeShift) inline
Definition at line 32 of file SinglePassPhaseReencoder.cs.
References BGC.Audio.IBGCStream.Channels, and BGC.Audio.IBGCStream.ChannelSamples.
             : base(stream)
         {
             if (stream.ChannelSamples == int.MaxValue)
             {
                 throw new ArgumentException("Cannot Single-Pass Phase Rencode an infinite stream.  " +
                     "Truncate first or use a Frame-based Reencoder.");
             }
             if (stream.Channels != 1)
             {
                 throw new ArgumentException("Cannot Single-Pass Phase Rencode a stereo stream with " +
                     "only one argument.   Use two arguments or Split first.");
             }
             Channels = 1;
             leftTimeShift = timeShift;
             rightTimeShift = 0.0;
             Samples = new float[TotalSamples];
         }
SinglePassPhaseReencoder() [2/2]
BGC.Audio.Filters.SinglePassPhaseReencoder.SinglePassPhaseReencoder (IBGCStream stream, double leftTimeShift, double rightTimeShift) inline
Definition at line 57 of file SinglePassPhaseReencoder.cs.
References BGC.Audio.IBGCStream.Channels, and BGC.Audio.IBGCStream.ChannelSamples.
             : base(stream)
         {
             if (stream.ChannelSamples == int.MaxValue)
             {
                 throw new ArgumentException("Cannot Single-Pass Phase Rencode an infinite stream.  " +
                     "Truncate first or use a Frame-based Reencoder.");
             }
             if (stream.Channels > 2)
             {
                 throw new ArgumentException("Cannot Single-Pass Phase Rencode a stream with more than " +
                     "2 channels.");
             }
             Channels = 2;
             this.leftTimeShift = leftTimeShift;
             this.rightTimeShift = rightTimeShift;
             Samples = new float[TotalSamples];
         }
Member Function Documentation
_Initialize()
override void BGC.Audio.Filters.SinglePassPhaseReencoder._Initialize () inline protected virtual
Reimplemented from BGC.Audio.Filters.BGCFilter.
Definition at line 83 of file SinglePassPhaseReencoder.cs.
         {
             if (Channels == 1)
             {
                 Complex64[] samples = stream.ComplexSamples();
                 int length = samples.Length;
                 TimeShift(samples, leftTimeShift);
                 for (int i = 0; i < length; i++)
                 {
                     Samples[i] = (float)samples[i].Real;
                 }
             }
             else if (stream.Channels == 2)
             {
                 //Two Channels to Two Channels
                 //Left Channel
                 Complex64[] samples = stream.ComplexSamples(channelIndex: 0);
                 int length = samples.Length;
                 if (leftTimeShift != 0.0)
                 {
                     //Skip this step if we're not timeshifting the left channel
                     TimeShift(samples, leftTimeShift);
                 }
                 for (int i = 0; i < length; i++)
                 {
                     Samples[2 * i] = (float)samples[i].Real;
                 }
                 //Right Channel
                 samples = stream.ComplexSamples(channelIndex: 1);
                 if (rightTimeShift != 0.0)
                 {
                     //Skip this step if we're not timeshifting the right channel
                     TimeShift(samples, rightTimeShift);
                 }
                 for (int i = 0; i < length; i++)
                 {
                     Samples[2 * i + 1] = (float)samples[i].Real;
                 }
             }
             else
             {
                 //One Channel to Two Channels
                 Complex64[] samples = stream.ComplexSamples();
                 int length = samples.Length;
                 //Copy samples before we destroy them
                 //Left shiftless
                 if (leftTimeShift == 0.0)
                 {
                     for (int i = 0; i < length; i++)
                     {
                         Samples[2 * i] = (float)samples[i].Real;
                     }
                 }
                 //Right shiftless
                 if (rightTimeShift == 0.0)
                 {
                     for (int i = 0; i < length; i++)
                     {
                         Samples[2 * i + 1] = (float)samples[i].Real;
                     }
                 }
                 //Destructive actions start here
                 //Left shifting
                 if (leftTimeShift != 0.0)
                 {
                     TimeShift(samples, leftTimeShift);
                     for (int i = 0; i < length; i++)
                     {
                         Samples[2 * i] = (float)samples[i].Real;
                     }
                 }
                 //Right shifting
                 if (rightTimeShift != 0.0)
                 {
                     if (leftTimeShift != 0.0)
                     {
                         //Reacquire samples that were destroyed
                         samples = stream.ComplexSamples();
                     }
                     TimeShift(samples, rightTimeShift);
                     for (int i = 0; i < length; i++)
                     {
                         Samples[2 * i + 1] = (float)samples[i].Real;
                     }
                 }
             }
         }
GetChannelRMS()
override IEnumerable<double> BGC.Audio.Filters.SinglePassPhaseReencoder.GetChannelRMS () inline virtual
The RMS amplitude of each channel
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 235 of file SinglePassPhaseReencoder.cs.
         {
             if (_channelRMS == null)
             {
                 if (Channels == stream.Channels)
                 {
                     //1->1 or 2->2
                     _channelRMS = stream.GetChannelRMS();
                 }
                 else
                 {
                     //Only 1->2
                     double rms = stream.GetChannelRMS().First();
                     _channelRMS = new double[] { rms, rms };
                 }
             }
             return _channelRMS;
         }
Read()
override int BGC.Audio.Filters.SinglePassPhaseReencoder.Read (float [] data, int offset, int count) inline virtual
Copy count samples into the Data buffer, starting at offset.
Returns
The number of samples copied
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 208 of file SinglePassPhaseReencoder.cs.
References BGC.Mathematics.GeneralMath.Clamp().
         {
             if (!initialized)
             {
                 Initialize();
             }
             int samplesToCopy = Math.Min(count, Channels * RemainingSamples);
             Array.Copy(
                 sourceArray: Samples,
                 sourceIndex: Channels * Position,
                 destinationArray: data,
                 destinationIndex: offset,
                 length: samplesToCopy);
             Position += samplesToCopy / Channels;
             return samplesToCopy;
         }
Reset()
override void BGC.Audio.Filters.SinglePassPhaseReencoder.Reset () virtual
Sets this internal state of this stream to the initial state
Reimplemented from BGC.Audio.Filters.SimpleBGCFilter.
Seek()
override void BGC.Audio.Filters.SinglePassPhaseReencoder.Seek (int position) virtual
Seek to the indicated position in the stream
Reimplemented from BGC.Audio.Filters.SimpleBGCFilter.
TimeShift()
void BGC.Audio.Filters.SinglePassPhaseReencoder.TimeShift (Complex64 [] samples, double timeShift) inline private
Definition at line 186 of file SinglePassPhaseReencoder.cs.
References BGC.Mathematics.Fourier.Forward(), BGC.Mathematics.Complex64.FromPolarCoordinates(), and BGC.Mathematics.Fourier.Inverse().
         {
             int length = samples.Length;
             Fourier.Forward(samples);
             double offset = 2 * Math.PI * stream.SamplingRate * timeShift / length;
             for (int i = 1; i < (length / 2) - 1; i++)
             {
                 //Double and rotate
                 samples[i] *= Complex64.FromPolarCoordinates(2.0, -i * offset);
             }
             //Clear negative frequencies
             Array.Clear(
                 array: samples,
                 index: length / 2 + 1,
                 length: length / 2 - 1);
             Fourier.Inverse(samples);
         }
Field Documentation
_channelRMS
IEnumerable<double> BGC.Audio.Filters.SinglePassPhaseReencoder._channelRMS = null private
Definition at line 234 of file SinglePassPhaseReencoder.cs.
ChannelSamples
override int BGC.Audio.Filters.SinglePassPhaseReencoder.ChannelSamples => stream.ChannelSamples
Definition at line 20 of file SinglePassPhaseReencoder.cs.
leftTimeShift
readonly double BGC.Audio.Filters.SinglePassPhaseReencoder.leftTimeShift = null private
Definition at line 27 of file SinglePassPhaseReencoder.cs.
RemainingSamples
int BGC.Audio.Filters.SinglePassPhaseReencoder.RemainingSamples => ChannelSamples - Position private
Definition at line 24 of file SinglePassPhaseReencoder.cs.
rightTimeShift
readonly double BGC.Audio.Filters.SinglePassPhaseReencoder.rightTimeShift private
Definition at line 30 of file SinglePassPhaseReencoder.cs.
SamplingRate
override float BGC.Audio.Filters.SinglePassPhaseReencoder.SamplingRate => stream.SamplingRate
Definition at line 22 of file SinglePassPhaseReencoder.cs.
TotalSamples
override int BGC.Audio.Filters.SinglePassPhaseReencoder.TotalSamples => Channels * ChannelSamples
Definition at line 19 of file SinglePassPhaseReencoder.cs.
Property Documentation
Channels
override int BGC.Audio.Filters.SinglePassPhaseReencoder.Channels get
Definition at line 17 of file SinglePassPhaseReencoder.cs.
Position
int BGC.Audio.Filters.SinglePassPhaseReencoder.Position get private set
Definition at line 26 of file SinglePassPhaseReencoder.cs.
Samples
float [] BGC.Audio.Filters.SinglePassPhaseReencoder.Samples = 0 get private set
Definition at line 27 of file SinglePassPhaseReencoder.cs.
The documentation for this class was generated from the following file:
Audio/Filters/SinglePassPhaseReencoder.cs