BGC Tools: BGC.Utility.JsonUtility Class Reference
BGC.Utility.JsonUtility Class Reference
Static Public Member Functions
static JsonArray ToJsonArray< T > (this IList< T > list, Func< T, JsonValue > lambda)
Convert list to json array with lambda that turns elements into json values
static JsonArray ToJsonArray (this IList< int > list)
Convert list of ints to json array
static JsonArray ToJsonArray (this IList< string > list)
Convert list of strings to json array
static T[] ToArray< T > (this JsonArray jsonArray, Func< JsonValue, T > lambda)
Convert json array to array with lambda to convert elements to defined type
static int[] ToIntArray (this JsonArray jsonArray)
Conver json array to array of integers
static JsonObject CombineJsonObjects (JsonObject a, JsonObject b)
Detailed Description
Definition at line 8 of file JsonUtility.cs.
Member Function Documentation
static JsonObject BGC.Utility.JsonUtility.CombineJsonObjects (JsonObject a, JsonObject b) inline static
Definition at line 100 of file JsonUtility.cs.
         {
             JsonObject combined = new JsonObject();
             foreach (KeyValuePair<string, JsonValue> json in a)
             {
                 combined.Add(json.Key, json.Value);
             }
             foreach (KeyValuePair<string, JsonValue> json in b)
             {
                 Assert.IsFalse(combined.ContainsKey(json.Key));
                 combined.Add(json.Key, json.Value);
             }
             return combined;
         }
static T [] BGC.Utility.JsonUtility.ToArray< T > (this JsonArray jsonArray, Func< JsonValue, T > lambda) inline static
Convert json array to array with lambda to convert elements to defined type
Template Parameters
T
Parameters
jsonArray
lambda
Returns
Definition at line 71 of file JsonUtility.cs.
         {
             Assert.IsNotNull(lambda);
             T[] array = new T[jsonArray.Count];
             for (int i = 0; i < array.Length; ++i)
             {
                 array[i] = lambda(jsonArray[i]);
             }
             return array;
         }
static int [] BGC.Utility.JsonUtility.ToIntArray (this JsonArray jsonArray) inline static
Conver json array to array of integers
Parameters
jsonArray
Returns
Definition at line 89 of file JsonUtility.cs.
References LightJson.JsonArray.Count.
         {
             int[] array = new int[jsonArray.Count];
             for (int i = 0; i < array.Length; ++i)
             {
                 array[i] = jsonArray[i];
             }
             return array;
         }
static JsonArray BGC.Utility.JsonUtility.ToJsonArray (this IList< int > list) inline static
Convert list of ints to json array
Parameters
list
Returns
Definition at line 35 of file JsonUtility.cs.
References LightJson.JsonArray.Add().
         {
             JsonArray jsonArray = new JsonArray();
             for (int i = 0; i < list.Count; ++i)
             {
                 jsonArray.Add(list[i]);
             }
             return jsonArray;
         }
static JsonArray BGC.Utility.JsonUtility.ToJsonArray (this IList< string > list) inline static
Convert list of strings to json array
Parameters
list
Returns
Definition at line 51 of file JsonUtility.cs.
References LightJson.JsonArray.Add().
         {
             JsonArray jsonArray = new JsonArray();
             int length = list.Count;
             for (int i = 0; i < length; ++i)
             {
                 jsonArray.Add(list[i]);
             }
             return jsonArray;
         }
static JsonArray BGC.Utility.JsonUtility.ToJsonArray< T > (this IList< T > list, Func< T, JsonValue > lambda) inline static
Convert list to json array with lambda that turns elements into json values
Template Parameters
T
Parameters
list
lambda
Returns
Definition at line 17 of file JsonUtility.cs.
References LightJson.JsonArray.Add().
         {
             Assert.IsNotNull(lambda);
             JsonArray jsonArray = new JsonArray();
             for (int i = 0; i < list.Count; ++i)
             {
                 jsonArray.Add(lambda(list[i]));
             }
             return jsonArray;
         }
The documentation for this class was generated from the following file:
Utility/JsonUtility.cs