BGC Tools: BGC.IO.LogDirectories Class Reference
BGC.IO.LogDirectories Class Reference
Static Public Member Functions
static string UserStagingDirectory (string user)
Get the path to the user in the stagin directory. This automatically creates a directory if it does not exist
static string UserPermanentDirectory (string user)
Get the path to the user in the permanent directory. This automatically creates a directory if it does not exists
static string UserErrorLogDirectory (string user)
Data Fields
const string LogsDirectory = "Logs"
const string S3StagingDirectory = "Staging"
const string ExceptionsDirectory = "Exceptions"
const string S3PermanentDirectory = "Permanent"
const string ErrorLogsDirectory = "ErrorLogs"
Properties
static string LogDirectory [get]
Logs directory for all users
static string StagingDirectory [get]
Directory for all staged files that are to be moved to s3 and then put into the PermanentDirectory
static string PermanentDirectory [get]
Directory for all logs that have been merged into s3
static string ErrorLogDirectory [get]
Directory for all logs that have errors and can't be merged into s3
static string ExceptionDirectory [get]
Get path for exceptions directory. Creates directory if it does not exist
Static Private Attributes
static string logDirectory = null
static string stagingDirectory = null
static string permanentDirectory = null
static string exceptionDirectory = null
static string errorLogDirectory = null
Detailed Description
Definition at line 5 of file LogDirectories.cs.
Member Function Documentation
static string BGC.IO.LogDirectories.UserErrorLogDirectory (string user) inline static
Definition at line 155 of file LogDirectories.cs.
Referenced by BGC.IO.Logging.Logger.CloseFile(), and BGC.Utility.LogFilesTos3.MigrateUser().
         {
             string dir = Path.Combine(ErrorLogDirectory, user);
             if (Directory.Exists(dir) == false)
             {
                 Directory.CreateDirectory(dir);
             }
             return dir;
         }
static string BGC.IO.LogDirectories.UserPermanentDirectory (string user) inline static
Get the path to the user in the permanent directory. This automatically creates a directory if it does not exists
Parameters
user
Returns
Definition at line 144 of file LogDirectories.cs.
Referenced by BGC.Utility.LogFilesTos3.MigrateUser(), and BGC.IO.Logging.Logger.PathForLogFile().
         {
             string dir = Path.Combine(PermanentDirectory, user);
             if (Directory.Exists(dir) == false)
             {
                 Directory.CreateDirectory(dir);
             }
             return dir;
         }
static string BGC.IO.LogDirectories.UserStagingDirectory (string user) inline static
Get the path to the user in the stagin directory. This automatically creates a directory if it does not exist
Parameters
user
Returns
Definition at line 127 of file LogDirectories.cs.
Referenced by BGC.Utility.LogFilesTos3.MigrateUser(), and BGC.IO.Logging.Logger.PathForLogFile().
         {
             string dir = Path.Combine(StagingDirectory, user);
             if (Directory.Exists(dir) == false)
             {
                 Directory.CreateDirectory(dir);
             }
             return dir;
         }
Field Documentation
string BGC.IO.LogDirectories.errorLogDirectory = null static private
Definition at line 17 of file LogDirectories.cs.
const string BGC.IO.LogDirectories.ErrorLogsDirectory = "ErrorLogs"
Definition at line 11 of file LogDirectories.cs.
string BGC.IO.LogDirectories.exceptionDirectory = null static private
Definition at line 16 of file LogDirectories.cs.
const string BGC.IO.LogDirectories.ExceptionsDirectory = "Exceptions"
Definition at line 9 of file LogDirectories.cs.
string BGC.IO.LogDirectories.logDirectory = null static private
Definition at line 13 of file LogDirectories.cs.
const string BGC.IO.LogDirectories.LogsDirectory = "Logs"
Definition at line 7 of file LogDirectories.cs.
string BGC.IO.LogDirectories.permanentDirectory = null static private
Definition at line 15 of file LogDirectories.cs.
const string BGC.IO.LogDirectories.S3PermanentDirectory = "Permanent"
Definition at line 10 of file LogDirectories.cs.
const string BGC.IO.LogDirectories.S3StagingDirectory = "Staging"
Definition at line 8 of file LogDirectories.cs.
string BGC.IO.LogDirectories.stagingDirectory = null static private
Definition at line 14 of file LogDirectories.cs.
Property Documentation
string BGC.IO.LogDirectories.ErrorLogDirectory static get
Directory for all logs that have errors and can't be merged into s3
Definition at line 84 of file LogDirectories.cs.
string BGC.IO.LogDirectories.ExceptionDirectory static get
Get path for exceptions directory. Creates directory if it does not exist
Definition at line 105 of file LogDirectories.cs.
Referenced by BGC.IO.Logging.Logger.GetExceptionFileName().
string BGC.IO.LogDirectories.LogDirectory static get
Logs directory for all users
Definition at line 23 of file LogDirectories.cs.
string BGC.IO.LogDirectories.PermanentDirectory static get
Directory for all logs that have been merged into s3
Definition at line 64 of file LogDirectories.cs.
string BGC.IO.LogDirectories.StagingDirectory static get
Directory for all staged files that are to be moved to s3 and then put into the PermanentDirectory
Definition at line 44 of file LogDirectories.cs.
Referenced by BGC.Utility.LogFilesTos3.MigrateFiles().
The documentation for this class was generated from the following file:
IO/Logging/LogDirectories.cs