BGC Tools: BGC.UI.Panels.ModePanelManager Class Reference
BGC.UI.Panels.ModePanelManager Class Reference
Public Member Functions
void ImmediatePanelSet (ModePanel newPanel)
void SetPanelActive (ModePanel newPanel, ShowPanelMode mode=ShowPanelMode.Hierarchy)
Protected Member Functions
void SetPanelActive (ModePanel newPanel, bool newPanelInferior)
void SpecialSetPanelActive (ModePanel newPanel, bool newPanelInferior)
Private Member Functions
void Awake ()
void Start ()
void DisableModePanel (ModePanel panel)
Private Attributes
ModePanel initialPanel = null
ModePanel [] orderedListOfPanels = null
Axis panelAxis = Axis.XAxis
float flipTime = 0.3f
CopyPanel copyPanel = null
Dictionary< ModePanel, int > animationControlOrderMap
ModePanel lastActivePanel = null
Detailed Description
Definition at line 17 of file ModePanelManager.cs.
Member Function Documentation
Awake()
void BGC.UI.Panels.ModePanelManager.Awake () inline private
Definition at line 35 of file ModePanelManager.cs.
         {
             lastActivePanel = initialPanel;
         }
DisableModePanel()
void BGC.UI.Panels.ModePanelManager.DisableModePanel (ModePanel panel) private
ImmediatePanelSet()
void BGC.UI.Panels.ModePanelManager.ImmediatePanelSet (ModePanel newPanel) inline
Definition at line 60 of file ModePanelManager.cs.
References BGC.UI.Panels.ModePanel.FocusAcquired(), BGC.UI.Panels.ModePanel.FocusLost(), and BGC.UI.Panels.ModePanel.ImmediateStateSet().
         {
             if (lastActivePanel == newPanel)
             {
                 //Cleanup panel
                 newPanel.FocusLost();
                 //Reprepare panel
                 newPanel.FocusAcquired();
                 return;
             }
             else if (!animationControlOrderMap.ContainsKey(newPanel))
             {
                 Debug.LogError("Error: Panel Not included in initialization array.");
                 return;
             }
             newPanel.gameObject.SetActive(true);
             lastActivePanel.FocusLost();
             lastActivePanel.ImmediateStateSet(false);
             newPanel.FocusAcquired();
             newPanel.ImmediateStateSet(true);
             lastActivePanel.gameObject.SetActive(false);
             lastActivePanel = newPanel;
         }
SetPanelActive() [1/2]
void BGC.UI.Panels.ModePanelManager.SetPanelActive (ModePanel newPanel, ShowPanelMode mode = ShowPanelMode.Hierarchy) inline
Definition at line 89 of file ModePanelManager.cs.
         {
             bool newPanelInferior;
             switch (mode)
             {
                 case ShowPanelMode.Hierarchy:
                     newPanelInferior = animationControlOrderMap[lastActivePanel] < animationControlOrderMap[newPanel];
                     break;
                 case ShowPanelMode.Push:
                 case ShowPanelMode.PushClone:
                     newPanelInferior = true;
                     break;
                 case ShowPanelMode.Pop:
                 case ShowPanelMode.PopClone:
                     newPanelInferior = false;
                     break;
                 case ShowPanelMode.MAX:
                 default:
                     newPanelInferior = true;
                     Debug.LogError($"Unrecognized ShowPanelMode: {mode}");
                     break;
             }
             switch (mode)
             {
                 case ShowPanelMode.Hierarchy:
                 case ShowPanelMode.Push:
                 case ShowPanelMode.Pop:
                     SetPanelActive(newPanel, newPanelInferior);
                     break;
                 case ShowPanelMode.PushClone:
                 case ShowPanelMode.PopClone:
                     SpecialSetPanelActive(newPanel, newPanelInferior);
                     break;
                 case ShowPanelMode.MAX:
                 default:
                     Debug.LogError($"Unrecognized ShowPanelMode: {mode}");
                     break;
             }
         }
SetPanelActive() [2/2]
void BGC.UI.Panels.ModePanelManager.SetPanelActive (ModePanel newPanel, bool newPanelInferior) inline protected
Definition at line 131 of file ModePanelManager.cs.
References BGC.UI.Panels.ModePanel.FocusAcquired(), BGC.UI.Panels.ModePanel.FocusLost(), and BGC.UI.Panels.ModePanel.LerpHandler.
         {
             if (lastActivePanel == newPanel)
             {
                 //Cleanup panel
                 newPanel.FocusLost();
                 //Reprepare panel
                 newPanel.FocusAcquired();
                 return;
             }
             else if (!animationControlOrderMap.ContainsKey(newPanel))
             {
                 Debug.LogError("Error: Panel Not included in initialization array.");
                 return;
             }
             newPanel.gameObject.SetActive(true);
             lastActivePanel.FocusLost();
             newPanel.LerpHandler.Activate(
                 duration: flipTime,
                 lerpAction: new ModePanelTranslator(
                     direction: Direction.Show,
                     axis: panelAxis,
                     orientation: newPanelInferior ? Orientation.Inferior : Orientation.Superior));
             lastActivePanel.LerpHandler.Activate(
                 duration: 0.8f * flipTime,
                 lerpAction: new ModePanelTranslator(
                     direction: Direction.Hide,
                     axis: panelAxis,
                     orientation: newPanelInferior ? Orientation.Superior : Orientation.Inferior),
                 finishedCallback: DisableModePanel);
             newPanel.FocusAcquired();
             lastActivePanel = newPanel;
         }
SpecialSetPanelActive()
void BGC.UI.Panels.ModePanelManager.SpecialSetPanelActive (ModePanel newPanel, bool newPanelInferior) inline protected
Definition at line 170 of file ModePanelManager.cs.
References BGC.UI.Panels.ModePanel.FocusAcquired(), BGC.UI.Panels.ModePanel.FocusLost(), BGC.UI.Panels.ModePanel.ImmediateStateSet(), BGC.UI.Panels.ModePanel.LerpHandler, BGC.UI.Panels.ModePanel.RectTransform, and BGC.UI.Panels.CopyPanel.TakeSnapshot().
         {
             copyPanel.gameObject.SetActive(true);
             copyPanel.TakeSnapshot(lastActivePanel.RectTransform);
             lastActivePanel.FocusLost();
             lastActivePanel.ImmediateStateSet(false);
             if (lastActivePanel != newPanel)
             {
                 lastActivePanel.gameObject.SetActive(false);
                 newPanel.gameObject.SetActive(true);
             }
             newPanel.LerpHandler.Activate(
                 duration: flipTime,
                 lerpAction: new ModePanelTranslator(
                     direction: Direction.Show,
                     axis: panelAxis,
                     orientation: newPanelInferior ? Orientation.Inferior : Orientation.Superior));
             copyPanel.LerpHandler.Activate(
                 duration: 0.8f * flipTime,
                 lerpAction: new ModePanelTranslator(
                     direction: Direction.Hide,
                     axis: panelAxis,
                     orientation: newPanelInferior ? Orientation.Superior : Orientation.Inferior),
                 finishedCallback: DisableModePanel);
             newPanel.FocusAcquired();
             lastActivePanel = newPanel;
         }
Start()
void BGC.UI.Panels.ModePanelManager.Start () inline private
Definition at line 40 of file ModePanelManager.cs.
References BGC.UI.Panels.ModePanel.FocusAcquired(), and BGC.UI.Panels.ModePanel.ImmediateStateSet().
         {
             Debug.Assert(initialPanel != null, "InitialPanel must be set");
             animationControlOrderMap = new Dictionary<ModePanel, int>(orderedListOfPanels.Length);
             int i = 0;
             foreach (ModePanel modePanel in orderedListOfPanels)
             {
                 animationControlOrderMap.Add(modePanel, i++);
                 bool visible = modePanel == initialPanel;
                 modePanel.ImmediateStateSet(visible);
                 modePanel.gameObject.SetActive(visible);
             }
             initialPanel.FocusAcquired();
         }
Field Documentation
animationControlOrderMap
Dictionary<ModePanel, int> BGC.UI.Panels.ModePanelManager.animationControlOrderMap private
Definition at line 31 of file ModePanelManager.cs.
copyPanel
CopyPanel BGC.UI.Panels.ModePanelManager.copyPanel = null private
Definition at line 29 of file ModePanelManager.cs.
flipTime
float BGC.UI.Panels.ModePanelManager.flipTime = 0.3f private
Definition at line 27 of file ModePanelManager.cs.
initialPanel
ModePanel BGC.UI.Panels.ModePanelManager.initialPanel = null private
Definition at line 20 of file ModePanelManager.cs.
lastActivePanel
ModePanel BGC.UI.Panels.ModePanelManager.lastActivePanel = null private
Definition at line 33 of file ModePanelManager.cs.
orderedListOfPanels
ModePanel [] BGC.UI.Panels.ModePanelManager.orderedListOfPanels = null private
Definition at line 23 of file ModePanelManager.cs.
panelAxis
Axis BGC.UI.Panels.ModePanelManager.panelAxis = Axis.XAxis private
Definition at line 25 of file ModePanelManager.cs.
The documentation for this class was generated from the following file:
UI/Panels/ModePanelManager.cs