BGC Tools: BGC.Mathematics.GeneralMath Class Reference
BGC.Mathematics.GeneralMath Class Reference
Static Public Member Functions
static int Mod (int x, int m)
x mod m
static float Mod (float x, float m)
x mod m
static double Tanh (double angle)
Hyperbolic Tangent in radian
static double Sinh (double angle)
Hyperbolic Sine
static double Cosh (double angle)
Hyperbolic Cosine
static float Tanh (float angle)
Hyperbolic Tangent in radian
static float Sinh (float angle)
Hyperbolic Sine
static float Cosh (float angle)
Hyperbolic Cosine
static bool IsPowerOfTwo (this int number)
Find out whether the provided 32 bit integer is a perfect power of two.
static int ToNextExponentOf2 (this int x)
static int CeilingToPowerOfTwo (this int v)
static decimal Clamp (decimal value, decimal min, decimal max)
static double Clamp (double value, double min, double max)
static float Clamp (float value, float min, float max)
static long Clamp (long value, long min, long max)
static ulong Clamp (ulong value, ulong min, ulong max)
static int Clamp (int value, int min, int max)
static uint Clamp (uint value, uint min, uint max)
static short Clamp (short value, short min, short max)
static ushort Clamp (ushort value, ushort min, ushort max)
static byte Clamp (byte value, byte min, byte max)
static sbyte Clamp (sbyte value, sbyte min, sbyte max)
static decimal Clamp01 (decimal value)
Clamps value to range [0, 1]
static double Clamp01 (double value)
Clamps value to range [0, 1]
static float Clamp01 (float value)
Clamps value to range [0, 1]
static decimal Lerp (decimal initial, decimal final, decimal t)
Linearly interpolates between initial and final by t , clamps t to range [0,1]
static decimal LerpUnclamped (decimal initial, decimal final, decimal t)
Linearly interpolates between initial and final by t without clamping t between 0 and 1
static double Lerp (double initial, double final, double t)
Linearly interpolates between initial and final by t , clamps t to range [0,1]
static double LerpUnclamped (double initial, double final, double t)
Linearly interpolates between initial and final by t without clamping t between 0 and 1
static float Lerp (float initial, float final, float t)
Linearly interpolates between initial and final by t , clamps t to range [0,1]
static float LerpUnclamped (float initial, float final, float t)
Linearly interpolates between initial and final by t without clamping t between 0 and 1
static decimal Repeat (decimal value, decimal min, decimal max)
static double Repeat (double value, double min, double max)
static float Repeat (float value, float min, float max)
static long Repeat (long value, long min, long max)
static int Repeat (int value, int min, int max)
static bool Approximately (float a, float b)
static bool Approximately (double a, double b)
Private Attributes
const float FLOAT_MANTISSA_LOWER_BOUND = 1.1920929E-7f
const float FLOAT_SMALLEST_NORMAL = 1.1754943508E-38f
const float FLOAT_COMPARISON_MAX_FACTOR = 8 * FLOAT_MANTISSA_LOWER_BOUND
const float FLOAT_COMPARISON_LOWER_BOUND = 8 * FLOAT_SMALLEST_NORMAL
const double DOUBLE_MANTISSA_LOWER_BOUND = 2.220446E-16
const double DOUBLE_SMALLEST_NORMAL = 2.2250738585072014E10-308
const double DOUBLE_COMPARISON_MAX_FACTOR = 8 * DOUBLE_MANTISSA_LOWER_BOUND
const double DOUBLE_COMPARISON_LOWER_BOUND = 8 * DOUBLE_SMALLEST_NORMAL
Detailed Description
Definition at line 6 of file GeneralMath.cs.
Member Function Documentation
Approximately() [1/2]
static bool BGC.Mathematics.GeneralMath.Approximately (float a, float b) inline static
Definition at line 326 of file GeneralMath.cs.
Referenced by BGC.Mathematics.Complex64.Equals(), and BGC.Mathematics.Complex32.Equals().
         {
             return Math.Abs(b - a) <= Math.Max(
                 FLOAT_COMPARISON_MAX_FACTOR * Math.Max(Math.Abs(a), Math.Abs(b)),
                 FLOAT_COMPARISON_LOWER_BOUND);
         }
Approximately() [2/2]
static bool BGC.Mathematics.GeneralMath.Approximately (double a, double b) inline static
Definition at line 338 of file GeneralMath.cs.
         {
             return Math.Abs(b - a) <= Math.Max(
                 DOUBLE_COMPARISON_MAX_FACTOR * Math.Max(Math.Abs(a), Math.Abs(b)),
                 DOUBLE_COMPARISON_LOWER_BOUND);
         }
CeilingToPowerOfTwo()
static int BGC.Mathematics.GeneralMath.CeilingToPowerOfTwo (this int v) inline static
Definition at line 124 of file GeneralMath.cs.
         {
             v--;
             v |= v >> 1;
             v |= v >> 2;
             v |= v >> 4;
             v |= v >> 8;
             v |= v >> 16;
             v++;
             return v;
         }
Clamp() [1/11]
static decimal BGC.Mathematics.GeneralMath.Clamp (decimal value, decimal min, decimal max) static
Referenced by BGC.Audio.Spatial.NearestValidOffset(), BGC.Audio.Synthesis.SilenceStream.Read(), BGC.Audio.SimpleAudioClip.Read(), BGC.Audio.InterlacingAudioClip.Read(), BGC.Audio.NormalizedMonoClip.Read(), BGC.Audio.Synthesis.WhiteNoiseStream.Read(), BGC.Audio.CrossFadingRefClip.Read(), BGC.Audio.Synthesis.NoiseAudioClip.Read(), BGC.Audio.Synthesis.SweepAudioClip.Read(), BGC.Audio.Synthesis.STMAudioClip.Read(), BGC.Audio.Filters.SinglePassPhaseReencoder.Read(), BGC.Audio.Filters.MultiConvolutionFilter.ReadBody(), BGC.Audio.Filters.StreamEnveloper.Seek(), BGC.Audio.Filters.StreamTimeShiftFilter.Seek(), BGC.Audio.AnalyticStreams.AnalyticFrequencyModulationFilter.Seek(), BGC.Audio.AnalyticStreams.AnalyticStreamWindower.Seek(), BGC.Audio.AnalyticStreams.AnalyticStreamFrequencyShifter.Seek(), BGC.Audio.AnalyticStreams.AnalyticStreamCenterer.Seek(), BGC.Audio.Filters.AllPassFilter.Seek(), BGC.Audio.Filters.StreamCenterer.Seek(), BGC.Audio.AnalyticStreams.AnalyticStreamConverter.Seek(), BGC.Audio.Filters.StreamTruncator.Seek(), BGC.Audio.Filters.FrequencyModulationFilter.Seek(), BGC.Audio.Filters.StreamWindower.Seek(), BGC.Audio.AnalyticStreams.AnalyticADSREnvelope.Seek(), BGC.IO.SubStream.Seek(), BGC.Audio.Synthesis.ADSREnvelope.Seek(), BGC.Audio.Normalization.SPLToAdjustmentDB(), BGC.Audio.Filters.ContinuousFilter.UpdateCoefficients(), and BGC.UI.ColorUIExtensions.updateColorValue().
Clamp() [2/11]
static double BGC.Mathematics.GeneralMath.Clamp (double value, double min, double max) static
Clamp() [3/11]
static float BGC.Mathematics.GeneralMath.Clamp (float value, float min, float max) static
Clamp() [4/11]
static long BGC.Mathematics.GeneralMath.Clamp (long value, long min, long max) static
Clamp() [5/11]
static ulong BGC.Mathematics.GeneralMath.Clamp (ulong value, ulong min, ulong max) static
Clamp() [6/11]
static int BGC.Mathematics.GeneralMath.Clamp (int value, int min, int max) static
Clamp() [7/11]
static uint BGC.Mathematics.GeneralMath.Clamp (uint value, uint min, uint max) static
Clamp() [8/11]
static short BGC.Mathematics.GeneralMath.Clamp (short value, short min, short max) static
Clamp() [9/11]
static ushort BGC.Mathematics.GeneralMath.Clamp (ushort value, ushort min, ushort max) static
Clamp() [10/11]
static byte BGC.Mathematics.GeneralMath.Clamp (byte value, byte min, byte max) static
Clamp() [11/11]
static sbyte BGC.Mathematics.GeneralMath.Clamp (sbyte value, sbyte min, sbyte max) static
Clamp01() [1/3]
static decimal BGC.Mathematics.GeneralMath.Clamp01 (decimal value) inline static
Clamps value to range [0, 1]
Definition at line 177 of file GeneralMath.cs.
         {
             if (value < 0)
             {
                 return 0;
             }
             else if (value > 1)
             {
                 return 1;
             }
             return value;
         }
Clamp01() [2/3]
static double BGC.Mathematics.GeneralMath.Clamp01 (double value) inline static
Clamps value to range [0, 1]
Definition at line 194 of file GeneralMath.cs.
         {
             if (value < 0)
             {
                 return 0;
             }
             else if (value > 1)
             {
                 return 1;
             }
             return value;
         }
Clamp01() [3/3]
static float BGC.Mathematics.GeneralMath.Clamp01 (float value) inline static
Clamps value to range [0, 1]
Definition at line 211 of file GeneralMath.cs.
         {
             if (value < 0)
             {
                 return 0;
             }
             else if (value > 1)
             {
                 return 1;
             }
             return value;
         }
Cosh() [1/2]
static double BGC.Mathematics.GeneralMath.Cosh (double angle) static
Hyperbolic Cosine
Parameters
angle The hyperbolic angle, i.e. the area of the hyperbolic sector.
Returns
The hyperbolic Cosine of the angle.
Referenced by BGC.Mathematics.Complex64.Cos(), BGC.Mathematics.Complex32.Cos(), BGC.Mathematics.Complex64.Cosh(), BGC.Mathematics.Complex32.Cosh(), BGC.Mathematics.Complex64.Sin(), BGC.Mathematics.Complex32.Sin(), BGC.Mathematics.Complex64.Sinh(), BGC.Mathematics.Complex32.Sinh(), BGC.Mathematics.Complex64.Tanh(), and BGC.Mathematics.Complex32.Tanh().
Cosh() [2/2]
static float BGC.Mathematics.GeneralMath.Cosh (float angle) static
Hyperbolic Cosine
Parameters
angle The hyperbolic angle, i.e. the area of the hyperbolic sector.
Returns
The hyperbolic Cosine of the angle.
IsPowerOfTwo()
static bool BGC.Mathematics.GeneralMath.IsPowerOfTwo (this int number) static
Find out whether the provided 32 bit integer is a perfect power of two.
Parameters
number The number to very whether it's a power of two.
Returns
True if and only if it is a power of two.
Lerp() [1/3]
static decimal BGC.Mathematics.GeneralMath.Lerp (decimal initial, decimal final, decimal t) inline static
Linearly interpolates between initial and final by t , clamps t to range [0,1]
Definition at line 232 of file GeneralMath.cs.
Referenced by BGC.MonoUtility.Interpolation.FadeImageAlpha.CallAction(), BGC.Audio.Calibration.GetLevelOffset(), and BGC.Audio.Visualization.SpectralDecomp.Linterp().
         {
             t = Clamp01(t);
             return initial * (1 - t) + final * t;
         }
Lerp() [2/3]
static double BGC.Mathematics.GeneralMath.Lerp (double initial, double final, double t) inline static
Linearly interpolates between initial and final by t , clamps t to range [0,1]
Definition at line 251 of file GeneralMath.cs.
         {
             t = Clamp01(t);
             return initial * (1 - t) + final * t;
         }
Lerp() [3/3]
static float BGC.Mathematics.GeneralMath.Lerp (float initial, float final, float t) inline static
Linearly interpolates between initial and final by t , clamps t to range [0,1]
Definition at line 270 of file GeneralMath.cs.
         {
             t = Clamp01(t);
             return initial * (1 - t) + final * t;
         }
LerpUnclamped() [1/3]
static decimal BGC.Mathematics.GeneralMath.LerpUnclamped (decimal initial, decimal final, decimal t) inline static
Linearly interpolates between initial and final by t without clamping t between 0 and 1
Definition at line 242 of file GeneralMath.cs.
         {
             return initial * (1 - t) + final * t;
         }
LerpUnclamped() [2/3]
static double BGC.Mathematics.GeneralMath.LerpUnclamped (double initial, double final, double t) inline static
Linearly interpolates between initial and final by t without clamping t between 0 and 1
Definition at line 261 of file GeneralMath.cs.
         {
             return initial * (1 - t) + final * t;
         }
LerpUnclamped() [3/3]
static float BGC.Mathematics.GeneralMath.LerpUnclamped (float initial, float final, float t) inline static
Linearly interpolates between initial and final by t without clamping t between 0 and 1
Definition at line 280 of file GeneralMath.cs.
         {
             return initial * (1 - t) + final * t;
         }
Mod() [1/2]
static int BGC.Mathematics.GeneralMath.Mod (int x, int m) inline static
x mod m
Parameters
x
m
Returns
Definition at line 14 of file GeneralMath.cs.
         {
             // https://stackoverflow.com/questions/1082917/mod-of-negative-number-is-melting-my-brain
             return ((x % m) + m) % m;
         }
Mod() [2/2]
static float BGC.Mathematics.GeneralMath.Mod (float x, float m) inline static
x mod m
Parameters
x
m
Returns
Definition at line 26 of file GeneralMath.cs.
         {
             return ((x % m) + m) % m;
         }
Repeat() [1/5]
static decimal BGC.Mathematics.GeneralMath.Repeat (decimal value, decimal min, decimal max) inline static
Definition at line 288 of file GeneralMath.cs.
Referenced by BGC.Audio.CarrierTone.CarrierTone().
         {
             decimal scanningValue = (value - min) % (max - min);
             return scanningValue >= 0 ? scanningValue + min : scanningValue + max;
         }
Repeat() [2/5]
static double BGC.Mathematics.GeneralMath.Repeat (double value, double min, double max) inline static
Definition at line 294 of file GeneralMath.cs.
         {
             double scanningValue = (value - min) % (max - min);
             return scanningValue >= 0 ? scanningValue + min : scanningValue + max;
         }
Repeat() [3/5]
static float BGC.Mathematics.GeneralMath.Repeat (float value, float min, float max) inline static
Definition at line 300 of file GeneralMath.cs.
         {
             float scanningValue = (value - min) % (max - min);
             return scanningValue >= 0 ? scanningValue + min : scanningValue + max;
         }
Repeat() [4/5]
static long BGC.Mathematics.GeneralMath.Repeat (long value, long min, long max) inline static
Definition at line 306 of file GeneralMath.cs.
         {
             long scanningValue = (value - min) % (max - min);
             return scanningValue >= 0 ? scanningValue + min : scanningValue + max;
         }
Repeat() [5/5]
static int BGC.Mathematics.GeneralMath.Repeat (int value, int min, int max) inline static
Definition at line 312 of file GeneralMath.cs.
         {
             int scanningValue = (value - min) % (max - min);
             return scanningValue >= 0 ? scanningValue + min : scanningValue + max;
         }
Sinh() [1/2]
static double BGC.Mathematics.GeneralMath.Sinh (double angle) static
Hyperbolic Sine
Parameters
angle The hyperbolic angle, i.e. the area of the hyperbolic sector.
Returns
The hyperbolic sine of the angle.
Referenced by BGC.Mathematics.Complex64.Cos(), BGC.Mathematics.Complex32.Cos(), BGC.Mathematics.Complex64.Cosh(), BGC.Mathematics.Complex32.Cosh(), BGC.Mathematics.Complex64.Sin(), BGC.Mathematics.Complex32.Sin(), BGC.Mathematics.Complex64.Sinh(), BGC.Mathematics.Complex32.Sinh(), BGC.Mathematics.Complex64.Tanh(), and BGC.Mathematics.Complex32.Tanh().
Sinh() [2/2]
static float BGC.Mathematics.GeneralMath.Sinh (float angle) static
Hyperbolic Sine
Parameters
angle The hyperbolic angle, i.e. the area of the hyperbolic sector.
Returns
The hyperbolic sine of the angle.
Tanh() [1/2]
static double BGC.Mathematics.GeneralMath.Tanh (double angle) inline static
Hyperbolic Tangent in radian
Parameters
angle The hyperbolic angle, i.e. the area of the hyperbolic sector.
Returns
The hyperbolic tangent of the angle.
Definition at line 38 of file GeneralMath.cs.
Referenced by BGC.Audio.Envelopes.SigmoidEnvelope.Read(), BGC.Audio.Envelopes.SigmoidEnvelope.ReadNextSample(), BGC.Mathematics.Complex64.Tanh(), and BGC.Mathematics.Complex32.Tanh().
         {
             if (angle > 19.1)
             {
                 return 1.0;
             }
             if (angle < -19.1)
             {
                 return -1.0;
             }
             double e1 = Math.Exp(angle);
             double e2 = Math.Exp(-angle);
             return (e1 - e2) / (e1 + e2);
         }
Tanh() [2/2]
static float BGC.Mathematics.GeneralMath.Tanh (float angle) inline static
Hyperbolic Tangent in radian
Parameters
angle The hyperbolic angle, i.e. the area of the hyperbolic sector.
Returns
The hyperbolic tangent of the angle.
Definition at line 79 of file GeneralMath.cs.
         {
             if (angle > 19.1f)
             {
                 return 1.0f;
             }
             if (angle < -19.1f)
             {
                 return -1f;
             }
             float e1 = Mathf.Exp(angle);
             float e2 = Mathf.Exp(-angle);
             return (e1 - e2) / (e1 + e2);
         }
ToNextExponentOf2()
static int BGC.Mathematics.GeneralMath.ToNextExponentOf2 (this int x) static
Field Documentation
DOUBLE_COMPARISON_LOWER_BOUND
const double BGC.Mathematics.GeneralMath.DOUBLE_COMPARISON_LOWER_BOUND = 8 * DOUBLE_SMALLEST_NORMAL private
Definition at line 336 of file GeneralMath.cs.
DOUBLE_COMPARISON_MAX_FACTOR
const double BGC.Mathematics.GeneralMath.DOUBLE_COMPARISON_MAX_FACTOR = 8 * DOUBLE_MANTISSA_LOWER_BOUND private
Definition at line 335 of file GeneralMath.cs.
DOUBLE_MANTISSA_LOWER_BOUND
const double BGC.Mathematics.GeneralMath.DOUBLE_MANTISSA_LOWER_BOUND = 2.220446E-16 private
Definition at line 333 of file GeneralMath.cs.
DOUBLE_SMALLEST_NORMAL
const double BGC.Mathematics.GeneralMath.DOUBLE_SMALLEST_NORMAL = 2.2250738585072014E10-308 private
Definition at line 334 of file GeneralMath.cs.
FLOAT_COMPARISON_LOWER_BOUND
const float BGC.Mathematics.GeneralMath.FLOAT_COMPARISON_LOWER_BOUND = 8 * FLOAT_SMALLEST_NORMAL private
Definition at line 324 of file GeneralMath.cs.
FLOAT_COMPARISON_MAX_FACTOR
const float BGC.Mathematics.GeneralMath.FLOAT_COMPARISON_MAX_FACTOR = 8 * FLOAT_MANTISSA_LOWER_BOUND private
Definition at line 323 of file GeneralMath.cs.
FLOAT_MANTISSA_LOWER_BOUND
const float BGC.Mathematics.GeneralMath.FLOAT_MANTISSA_LOWER_BOUND = 1.1920929E-7f private
Definition at line 321 of file GeneralMath.cs.
FLOAT_SMALLEST_NORMAL
const float BGC.Mathematics.GeneralMath.FLOAT_SMALLEST_NORMAL = 1.1754943508E-38f private
Definition at line 322 of file GeneralMath.cs.
The documentation for this class was generated from the following file:
Mathematics/GeneralMath.cs