BGC Tools: BGC.Audio.Midi.Events.MidiEvent Class Reference
BGC.Audio.Midi.Events.MidiEvent Class Reference abstract
Public Types
enum MidiMessageClass {
MidiMessageClass.ChannelEvent = 0, MidiMessageClass.SysexEvent, MidiMessageClass.SysCommEvent, MidiMessageClass.SysRTEvent,
MidiMessageClass.MetaEvent, MidiMessageClass.MAX
}
Public Member Functions
MidiEvent (int deltaTime, byte eventCode)
void Serialize (Stream outputStream, bool running)
abstract void ExecuteEvent (MidiTrack track)
override string ToString ()
Static Public Member Functions
static MidiEvent ParseEvent (Stream inputStream, int deltaTime, byte eventCode, byte nextByte)
Data Fields
int time
int deltaTime
readonly byte eventCode
virtual bool Essential => true
virtual int Length => deltaTime.GetVarQuantitySize()
Protected Member Functions
abstract void Serialize (Stream outputStream)
Properties
abstract string EventName [get]
abstract MidiMessageClass MessageClass [get]
Private Attributes
const int VAR_1BYTE_MAX = 0b0111_1111
const int VAR_2BYTE_MAX = (VAR_1BYTE_MAX << 7) | VAR_1BYTE_MAX
const int VAR_3BYTE_MAX = (VAR_2BYTE_MAX << 7) | VAR_1BYTE_MAX
const int VAR_4BYTE_MAX = (VAR_3BYTE_MAX << 7) | VAR_1BYTE_MAX
Detailed Description
Definition at line 6 of file MidiEvent.cs.
Member Enumeration Documentation
MidiMessageClass
enum BGC.Audio.Midi.Events.MidiEvent.MidiMessageClass strong
Enumerator
ChannelEvent
SysexEvent
SysCommEvent
SysRTEvent
MetaEvent
MAX
Definition at line 8 of file MidiEvent.cs.
         {
             ChannelEvent = 0,
             SysexEvent,
             SysCommEvent,
             SysRTEvent,
             MetaEvent,
             MAX
         }
Constructor & Destructor Documentation
MidiEvent()
BGC.Audio.Midi.Events.MidiEvent.MidiEvent (int deltaTime, byte eventCode) inline
Definition at line 28 of file MidiEvent.cs.
         {
             this.deltaTime = deltaTime;
             this.eventCode = eventCode;
         }
Member Function Documentation
ExecuteEvent()
abstract void BGC.Audio.Midi.Events.MidiEvent.ExecuteEvent (MidiTrack track) pure virtual
Implemented in BGC.Audio.Midi.Events.ControllerMidiEvent, BGC.Audio.Midi.Events.SystemCommonMidiEvent, BGC.Audio.Midi.Events.MetaMidiEvent, BGC.Audio.Midi.Events.NoteMidiEvent, BGC.Audio.Midi.Events.SysexMidiEvent, BGC.Audio.Midi.Events.PitchBendMidiEvent, BGC.Audio.Midi.Events.ProgramMidiEvent, BGC.Audio.Midi.Events.SystemRealTimeMidiEvent, BGC.Audio.Midi.Events.SetTempoMetaMidiEvent, BGC.Audio.Midi.Events.ChannelPressureMidiEvent, and BGC.Audio.Midi.Events.UnknownMidiEvent.
Referenced by BGC.Audio.Midi.MidiTrack.Read().
ParseEvent()
static MidiEvent BGC.Audio.Midi.Events.MidiEvent.ParseEvent (Stream inputStream, int deltaTime, byte eventCode, byte nextByte) inline static
Definition at line 34 of file MidiEvent.cs.
References BGC.Audio.Midi.Events.ChannelMidiEvent.ParseChannelEvent(), BGC.Audio.Midi.Events.MetaMidiEvent.ParseMetaEvent(), BGC.Audio.Midi.Events.SysexMidiEvent.ParseSysexEvent(), and BGC.Audio.Midi.Events.UnknownMidiEvent.ParseUnknownMidiEvent().
Referenced by BGC.Audio.Midi.MidiTrack.ParseEvent().
         {
             switch (eventCode)
             {
                 case 0xF0:
                 case 0xF7:
                     return SysexMidiEvent.ParseSysexEvent(
                         inputStream: inputStream,
                         deltaTime: deltaTime,
                         eventCode: eventCode,
                         nextByte: nextByte);
                 case 0xFF:
                     return MetaMidiEvent.ParseMetaEvent(
                         inputStream: inputStream,
                         deltaTime: deltaTime,
                         metaTypeCode: nextByte);
             }
             //Check Channel Banks
             //Upper Nibble anywhere between 0x80 and 0xEF
             if (eventCode >= 0x80 && eventCode < 0xF0)
             {
                 return ChannelMidiEvent.ParseChannelEvent(
                     inputStream: inputStream,
                     deltaTime: deltaTime,
                     eventCode: eventCode,
                     nextByte: nextByte);
             }
             return UnknownMidiEvent.ParseUnknownMidiEvent(
                 deltaTime: deltaTime,
                 eventCode: eventCode,
                 nextByte: nextByte);
         }
Serialize() [1/2]
void BGC.Audio.Midi.Events.MidiEvent.Serialize (Stream outputStream, bool running) inline
Definition at line 75 of file MidiEvent.cs.
Referenced by BGC.Audio.Midi.MidiTrack.Serialize().
         {
             outputStream.WriteVarQuantity(deltaTime);
             if (!running)
             {
                 outputStream.WriteByte(eventCode);
             }
             Serialize(outputStream);
         }
Serialize() [2/2]
abstract void BGC.Audio.Midi.Events.MidiEvent.Serialize (Stream outputStream) protected pure virtual
Implemented in BGC.Audio.Midi.Events.ControllerMidiEvent, BGC.Audio.Midi.Events.MetaMidiEvent, BGC.Audio.Midi.Events.SystemCommonMidiEvent, BGC.Audio.Midi.Events.NoteMidiEvent, BGC.Audio.Midi.Events.ChannelMidiEvent, BGC.Audio.Midi.Events.SysexMidiEvent, BGC.Audio.Midi.Events.SMTPEOffsetMetaMidiEvent, BGC.Audio.Midi.Events.TimeSignatureMetaMidiEvent, BGC.Audio.Midi.Events.SystemRealTimeMidiEvent, BGC.Audio.Midi.Events.KeySignatureMetaMidiEvent, BGC.Audio.Midi.Events.TextMetaMidiEvent, BGC.Audio.Midi.Events.ProgramMidiEvent, BGC.Audio.Midi.Events.PitchBendMidiEvent, BGC.Audio.Midi.Events.ChannelPressureMidiEvent, BGC.Audio.Midi.Events.UnknownMidiEvent, BGC.Audio.Midi.Events.ChannelPrefixMetaMidiEvent, BGC.Audio.Midi.Events.SequencerSpecificMetaMidiEvent, BGC.Audio.Midi.Events.UnknownMetaMidiEvent, BGC.Audio.Midi.Events.SequenceNumberMetaMidiEvent, BGC.Audio.Midi.Events.SetTempoMetaMidiEvent, and BGC.Audio.Midi.Events.EndOfTrackMetaMidiEvent.
ToString()
override string BGC.Audio.Midi.Events.MidiEvent.ToString ()
Field Documentation
deltaTime
int BGC.Audio.Midi.Events.MidiEvent.deltaTime
Definition at line 19 of file MidiEvent.cs.
Referenced by BGC.Audio.Midi.MidiTrack.HandleIntegration(), and BGC.Audio.Midi.MidiTrack.Insert().
Essential
virtual bool BGC.Audio.Midi.Events.MidiEvent.Essential => true
Definition at line 23 of file MidiEvent.cs.
Referenced by BGC.Audio.Midi.MidiTrack.Add(), and BGC.Audio.Midi.MidiTrack.Insert().
eventCode
readonly byte BGC.Audio.Midi.Events.MidiEvent.eventCode
Definition at line 20 of file MidiEvent.cs.
Referenced by BGC.Audio.Midi.MidiTrack.Serialize().
Length
virtual int BGC.Audio.Midi.Events.MidiEvent.Length => deltaTime.GetVarQuantitySize()
Definition at line 26 of file MidiEvent.cs.
Referenced by BGC.Audio.Midi.MidiTrack.Serialize().
time
int BGC.Audio.Midi.Events.MidiEvent.time
Definition at line 18 of file MidiEvent.cs.
Referenced by BGC.Audio.Midi.MidiTrack.HandleIntegration(), BGC.Audio.Midi.MidiFileStream.InsertTempoEvent(), and BGC.Audio.Midi.MidiTrack.Read().
VAR_1BYTE_MAX
const int BGC.Audio.Midi.Events.MidiEvent.VAR_1BYTE_MAX = 0b0111_1111 private
Definition at line 90 of file MidiEvent.cs.
VAR_2BYTE_MAX
const int BGC.Audio.Midi.Events.MidiEvent.VAR_2BYTE_MAX = (VAR_1BYTE_MAX << 7) | VAR_1BYTE_MAX private
Definition at line 91 of file MidiEvent.cs.
VAR_3BYTE_MAX
const int BGC.Audio.Midi.Events.MidiEvent.VAR_3BYTE_MAX = (VAR_2BYTE_MAX << 7) | VAR_1BYTE_MAX private
Definition at line 92 of file MidiEvent.cs.
VAR_4BYTE_MAX
const int BGC.Audio.Midi.Events.MidiEvent.VAR_4BYTE_MAX = (VAR_3BYTE_MAX << 7) | VAR_1BYTE_MAX private
Definition at line 93 of file MidiEvent.cs.
Property Documentation
EventName
abstract string BGC.Audio.Midi.Events.MidiEvent.EventName get
Definition at line 22 of file MidiEvent.cs.
MessageClass
abstract MidiMessageClass BGC.Audio.Midi.Events.MidiEvent.MessageClass get
Definition at line 25 of file MidiEvent.cs.
Referenced by BGC.Audio.Midi.MidiTrack.Add(), BGC.Audio.Midi.MidiTrack.HandleIntegration(), BGC.Audio.Midi.MidiTrack.ParseEvent(), and BGC.Audio.Midi.MidiTrack.Serialize().
The documentation for this class was generated from the following file:
Audio/Midi/Events/MidiEvent.cs