BGC Tools: BGC.Audio.Spatialization.ImpulseExtraction Class Reference
BGC.Audio.Spatialization.ImpulseExtraction Class Reference
Extracts the packaged HRTF files, generously provided by Nirmal Srinivasan, Asst Professor of the Deptartment of Speech-Language Pathology & Audiology at Towson University
Protected Member Functions
override bool PrepareRun ()
override void FinishedRunning (bool runSuccessful)
override Task< bool > ExecuteTask ()
Private Attributes
TextAsset impulseZip = null
const string HRTFDirectory = "HRTF"
const string ImpulseVersionKey = "ImpulseVersion"
const int ImpulseVersion = 3
byte[] rawData
string outputPath
Detailed Description
Extracts the packaged HRTF files, generously provided by Nirmal Srinivasan, Asst Professor of the Deptartment of Speech-Language Pathology & Audiology at Towson University
Definition at line 15 of file ImpulseExtraction.cs.
Member Function Documentation
override Task<bool> BGC.Audio.Spatialization.ImpulseExtraction.ExecuteTask () protected virtual
Implements BGC.MonoUtility.AsyncInitTask.
override void BGC.Audio.Spatialization.ImpulseExtraction.FinishedRunning (bool runSuccessful) inline protected virtual
Implements BGC.MonoUtility.AsyncInitTask.
Definition at line 40 of file ImpulseExtraction.cs.
References BGC.IO.Compression.Zip.DecompressMemory().
         {
             if (runSuccessful)
             {
                 PlayerPrefs.SetInt(ImpulseVersionKey, ImpulseVersion);
             }
         }
override bool BGC.Audio.Spatialization.ImpulseExtraction.PrepareRun () inline protected virtual
Implements BGC.MonoUtility.AsyncInitTask.
Definition at line 27 of file ImpulseExtraction.cs.
References BGC.IO.DataManagement.DataDirectoryExists(), and BGC.IO.DataManagement.PathForDataDirectory().
         {
             if (PlayerPrefs.GetInt(ImpulseVersionKey, 0) < ImpulseVersion ||
                 !DataManagement.DataDirectoryExists(HRTFDirectory))
             {
                 rawData = (byte[])impulseZip.bytes.Clone();
                 outputPath = DataManagement.PathForDataDirectory(HRTFDirectory);
                 return true;
             }
             return false;
         }
Field Documentation
const string BGC.Audio.Spatialization.ImpulseExtraction.HRTFDirectory = "HRTF" private
Definition at line 20 of file ImpulseExtraction.cs.
const int BGC.Audio.Spatialization.ImpulseExtraction.ImpulseVersion = 3 private
Definition at line 22 of file ImpulseExtraction.cs.
const string BGC.Audio.Spatialization.ImpulseExtraction.ImpulseVersionKey = "ImpulseVersion" private
Definition at line 21 of file ImpulseExtraction.cs.
TextAsset BGC.Audio.Spatialization.ImpulseExtraction.impulseZip = null private
Definition at line 18 of file ImpulseExtraction.cs.
string BGC.Audio.Spatialization.ImpulseExtraction.outputPath private
Definition at line 25 of file ImpulseExtraction.cs.
byte [] BGC.Audio.Spatialization.ImpulseExtraction.rawData private
Definition at line 24 of file ImpulseExtraction.cs.
The documentation for this class was generated from the following file:
Audio/Spatialization/ImpulseExtraction.cs