BGC Tools: BGC.Tests.WAVEncodingTests Class Reference
BGC.Tests.WAVEncodingTests Class Reference
Public Member Functions
void TestSingleChannelWave ()
void TestDualChannelWave ()
void UpScalingTest ()
Private Member Functions
float [] CreateSineWave (int channels, float samplingRate=44100f)
Detailed Description
Definition at line 13 of file WaveEncodingTests.cs.
Member Function Documentation
CreateSineWave()
float [] BGC.Tests.WAVEncodingTests.CreateSineWave (int channels, float samplingRate = 44100f) inline private
Definition at line 79 of file WaveEncodingTests.cs.
         {
             const float duration = 1f;
             const float freq = 440f;
             int samplesPerChannel = (int)(samplingRate * duration);
             int sampleCount = samplesPerChannel * channels;
             float[] samples = new float[sampleCount];
             float arg = 2 * Mathf.PI * freq;
             for (int i = 0; i < samplesPerChannel; i++)
             {
                 float time = i / samplingRate;
                 for (int j = 0; j < channels; j++)
                 {
                     samples[channels * i + j] = 0.25f * Mathf.Sin(arg * time);
                 }
             }
             return samples;
         }
TestDualChannelWave()
void BGC.Tests.WAVEncodingTests.TestDualChannelWave () inline
Definition at line 48 of file WaveEncodingTests.cs.
References BGC.Audio.WaveEncoding.LoadFile(), BGC.IO.DataManagement.PathForDataFile(), and BGC.Audio.WaveEncoding.SaveFile().
         {
             float[] dualChannelSamples = CreateSineWave(2);
             string dualChannelFile = DataManagement.PathForDataFile("Test", "dualChannel.wav");
             string secondDualChannel = DataManagement.PathForDataFile("Test", "dualChannel2.wav");
             Assert.IsTrue(WaveEncoding.SaveFile(
                 filepath: dualChannelFile,
                 channels: 2,
                 samples: dualChannelSamples,
                 overwrite: true));
             dualChannelSamples = null;
             Assert.IsTrue(File.Exists(dualChannelFile));
             Assert.IsTrue(WaveEncoding.LoadFile(
                 filepath: dualChannelFile,
                 channels: out int channels,
                 samples: out dualChannelSamples));
             Assert.IsTrue(channels == 2);
             Assert.IsTrue(dualChannelSamples != null);
             Assert.IsTrue(WaveEncoding.SaveFile(
                 filepath: secondDualChannel,
                 channels: 2,
                 samples: dualChannelSamples,
                 overwrite: true));
         }
TestSingleChannelWave()
void BGC.Tests.WAVEncodingTests.TestSingleChannelWave () inline
Definition at line 16 of file WaveEncodingTests.cs.
References BGC.Audio.WaveEncoding.LoadFile(), BGC.IO.DataManagement.PathForDataFile(), and BGC.Audio.WaveEncoding.SaveFile().
         {
             float[] singleChannelSamples = CreateSineWave(1);
             string singleChannelFile = DataManagement.PathForDataFile("Test", "singleChannel.wav");
             string secondSingleChannel = DataManagement.PathForDataFile("Test", "singleChannel2.wav");
             Assert.IsTrue(WaveEncoding.SaveFile(
                 filepath: singleChannelFile,
                 channels: 1,
                 samples: singleChannelSamples,
                 overwrite: true));
             singleChannelSamples = null;
             Assert.IsTrue(File.Exists(singleChannelFile));
             Assert.IsTrue(WaveEncoding.LoadFile(
                 filepath: singleChannelFile,
                 channels: out int channels,
                 samples: out singleChannelSamples));
             Assert.IsTrue(channels == 1);
             Assert.IsTrue(singleChannelSamples != null);
             Assert.IsTrue(WaveEncoding.SaveFile(
                 filepath: secondSingleChannel,
                 channels: 1,
                 samples: singleChannelSamples,
                 overwrite: true));
         }
UpScalingTest()
void BGC.Tests.WAVEncodingTests.UpScalingTest () inline
Definition at line 105 of file WaveEncodingTests.cs.
References BGC.Audio.LinearInterpolation.FactorUpscaler(), BGC.IO.DataManagement.PathForDataFile(), and BGC.Audio.WaveEncoding.SaveStream().
         {
             float[] singleChannelSamples = CreateSineWave(1, 22050f);
             string upscaledFile = DataManagement.PathForDataFile("Test", "upscaled.wav");
             IBGCStream stream = new SimpleAudioClip(
                 samples: LinearInterpolation.FactorUpscaler(
                     samples: singleChannelSamples,
                     factor: 2,
                     channels: 1),
                 channels: 1);
             Assert.IsTrue(WaveEncoding.SaveStream(
                 filepath: upscaledFile,
                 stream: stream,
                 overwrite: true));
         }
The documentation for this class was generated from the following file:
Editor/Tests/Audio/WaveEncodingTests.cs