BGC Tools: BGC.Audio.Midi.Events.MetaMidiEvent Class Reference
BGC.Audio.Midi.Events.MetaMidiEvent Class Reference abstract
Public Types
enum MidiMetaType : byte {
MidiMetaType.SequenceNumber = 0x00, MidiMetaType.Text = 0x01, MidiMetaType.CopyrightNotice = 0x02, MidiMetaType.SeqTrackName = 0x03,
MidiMetaType.InstrumentName = 0x04, MidiMetaType.Lyric = 0x05, MidiMetaType.Marker = 0x06, MidiMetaType.CuePoint = 0x07,
MidiMetaType.ChannelPrefix = 0x20, MidiMetaType.EndOfTrack = 0x2F, MidiMetaType.SetTempo = 0x51, MidiMetaType.SMTPEOffset = 0x54,
MidiMetaType.TimeSignature = 0x58, MidiMetaType.KeySignature = 0x59, MidiMetaType.SequencerSpecific = 0x7F
}
Public Types inherited from BGC.Audio.Midi.Events.MidiEvent
enum MidiMessageClass {
MidiMessageClass.ChannelEvent = 0, MidiMessageClass.SysexEvent, MidiMessageClass.SysCommEvent, MidiMessageClass.SysRTEvent,
MidiMessageClass.MetaEvent, MidiMessageClass.MAX
}
Public Member Functions
MetaMidiEvent (int deltaTime, byte metaTypeCode)
override string ToString ()
abstract void Integrate (MidiTrack track)
override void ExecuteEvent (MidiTrack track)
Public Member Functions inherited from BGC.Audio.Midi.Events.MidiEvent
MidiEvent (int deltaTime, byte eventCode)
void Serialize (Stream outputStream, bool running)
override string ToString ()
Static Public Member Functions
static MetaMidiEvent ParseMetaEvent (Stream inputStream, int deltaTime, byte metaTypeCode)
Static Public Member Functions inherited from BGC.Audio.Midi.Events.MidiEvent
static MidiEvent ParseEvent (Stream inputStream, int deltaTime, byte eventCode, byte nextByte)
Data Fields
override MidiMessageClass MessageClass => MidiMessageClass.MetaEvent
readonly byte metaTypeCode
MidiMetaType MetaType => (MidiMetaType)metaTypeCode
override int Length => base.Length + 1
Data Fields inherited from BGC.Audio.Midi.Events.MidiEvent
int time
int deltaTime
readonly byte eventCode
virtual bool Essential => true
virtual int Length => deltaTime.GetVarQuantitySize()
Protected Member Functions
override void Serialize (Stream outputStream)
Additional Inherited Members
Properties inherited from BGC.Audio.Midi.Events.MidiEvent
abstract string EventName [get]
abstract MidiMessageClass MessageClass [get]
Detailed Description
Definition at line 7 of file MetaMidiEvent.cs.
Member Enumeration Documentation
MidiMetaType
enum BGC.Audio.Midi.Events.MetaMidiEvent.MidiMetaType : byte strong
Enumerator
SequenceNumber
Text
CopyrightNotice
SeqTrackName
InstrumentName
Lyric
Marker
CuePoint
ChannelPrefix
EndOfTrack
SetTempo
SMTPEOffset
TimeSignature
KeySignature
SequencerSpecific
Definition at line 9 of file MetaMidiEvent.cs.
                                  : byte
         {
             SequenceNumber = 0x00,
             Text = 0x01,
             CopyrightNotice = 0x02,
             SeqTrackName = 0x03,
             InstrumentName = 0x04,
             Lyric = 0x05,
             Marker = 0x06,
             CuePoint = 0x07,
             ChannelPrefix = 0x20,
             EndOfTrack = 0x2F,
             SetTempo = 0x51,
             SMTPEOffset = 0x54,
             TimeSignature = 0x58,
             KeySignature = 0x59,
             SequencerSpecific = 0x7F
         }
Constructor & Destructor Documentation
MetaMidiEvent()
BGC.Audio.Midi.Events.MetaMidiEvent.MetaMidiEvent (int deltaTime, byte metaTypeCode) inline
Definition at line 35 of file MetaMidiEvent.cs.
             : base(deltaTime, 0xFF)
         {
             this.metaTypeCode = metaTypeCode;
         }
Member Function Documentation
ExecuteEvent()
override void BGC.Audio.Midi.Events.MetaMidiEvent.ExecuteEvent (MidiTrack track) inline virtual
Implements BGC.Audio.Midi.Events.MidiEvent.
Reimplemented in BGC.Audio.Midi.Events.SetTempoMetaMidiEvent.
Definition at line 95 of file MetaMidiEvent.cs.
 { }
Integrate()
abstract void BGC.Audio.Midi.Events.MetaMidiEvent.Integrate (MidiTrack track) pure virtual
Implemented in BGC.Audio.Midi.Events.SMTPEOffsetMetaMidiEvent, BGC.Audio.Midi.Events.TimeSignatureMetaMidiEvent, BGC.Audio.Midi.Events.KeySignatureMetaMidiEvent, BGC.Audio.Midi.Events.TextMetaMidiEvent, BGC.Audio.Midi.Events.ChannelPrefixMetaMidiEvent, BGC.Audio.Midi.Events.UnknownMetaMidiEvent, BGC.Audio.Midi.Events.SequencerSpecificMetaMidiEvent, BGC.Audio.Midi.Events.EndOfTrackMetaMidiEvent, BGC.Audio.Midi.Events.SequenceNumberMetaMidiEvent, and BGC.Audio.Midi.Events.SetTempoMetaMidiEvent.
Referenced by BGC.Audio.Midi.MidiTrack.HandleIntegration().
ParseMetaEvent()
static MetaMidiEvent BGC.Audio.Midi.Events.MetaMidiEvent.ParseMetaEvent (Stream inputStream, int deltaTime, byte metaTypeCode) inline static
Definition at line 41 of file MetaMidiEvent.cs.
References BGC.Audio.Midi.Events.ChannelPrefixMetaMidiEvent.ParseChannelPrefixMetaMidiEvent(), BGC.Audio.Midi.Events.EndOfTrackMetaMidiEvent.ParseEndOfTrackMetaMidiEvent(), BGC.Audio.Midi.Events.KeySignatureMetaMidiEvent.ParseKeySignatureMetaMidiEvent(), BGC.Audio.Midi.Events.SequenceNumberMetaMidiEvent.ParseSequenceNumberMetaMidiEvent(), BGC.Audio.Midi.Events.SequencerSpecificMetaMidiEvent.ParseSequencerSpecificMetaMidiEvent(), BGC.Audio.Midi.Events.SetTempoMetaMidiEvent.ParseSetTempoMetaMidiEvent(), BGC.Audio.Midi.Events.SMTPEOffsetMetaMidiEvent.ParseSMTPEOffsetMetaMidiEvent(), BGC.Audio.Midi.Events.TextMetaMidiEvent.ParseTextMetaMidiEvent(), BGC.Audio.Midi.Events.TimeSignatureMetaMidiEvent.ParseTimeSignatureMetaMidiEvent(), and BGC.Audio.Midi.Events.UnknownMetaMidiEvent.ParseUnknownMetaMidiEvent().
Referenced by BGC.Audio.Midi.Events.MidiEvent.ParseEvent().
         {
             MidiMetaType metaType = (MidiMetaType)metaTypeCode;
             switch (metaType)
             {
                 case MidiMetaType.SequenceNumber:
                     return SequenceNumberMetaMidiEvent.ParseSequenceNumberMetaMidiEvent(inputStream, deltaTime);
                 case MidiMetaType.Text:
                 case MidiMetaType.CopyrightNotice:
                 case MidiMetaType.SeqTrackName:
                 case MidiMetaType.InstrumentName:
                 case MidiMetaType.Lyric:
                 case MidiMetaType.Marker:
                 case MidiMetaType.CuePoint:
                     return TextMetaMidiEvent.ParseTextMetaMidiEvent(inputStream, deltaTime, metaTypeCode);
                 case MidiMetaType.ChannelPrefix:
                     return ChannelPrefixMetaMidiEvent.ParseChannelPrefixMetaMidiEvent(inputStream, deltaTime);
                 case MidiMetaType.EndOfTrack:
                     return EndOfTrackMetaMidiEvent.ParseEndOfTrackMetaMidiEvent(inputStream, deltaTime);
                 case MidiMetaType.SetTempo:
                     return SetTempoMetaMidiEvent.ParseSetTempoMetaMidiEvent(inputStream, deltaTime);
                 case MidiMetaType.SMTPEOffset:
                     return SMTPEOffsetMetaMidiEvent.ParseSMTPEOffsetMetaMidiEvent(inputStream, deltaTime);
                 case MidiMetaType.TimeSignature:
                     return TimeSignatureMetaMidiEvent.ParseTimeSignatureMetaMidiEvent(inputStream, deltaTime);
                 case MidiMetaType.KeySignature:
                     return KeySignatureMetaMidiEvent.ParseKeySignatureMetaMidiEvent(inputStream, deltaTime);
                 case MidiMetaType.SequencerSpecific:
                     return SequencerSpecificMetaMidiEvent.ParseSequencerSpecificMetaMidiEvent(inputStream, deltaTime);
                 default:
                     Debug.Log($"Encountered Unknown Meta Midi Event: {metaTypeCode:X2}");
                     return UnknownMetaMidiEvent.ParseUnknownMetaMidiEvent(inputStream, deltaTime, metaTypeCode);
             }
         }
Serialize()
override void BGC.Audio.Midi.Events.MetaMidiEvent.Serialize (Stream outputStream) inline protected virtual
Implements BGC.Audio.Midi.Events.MidiEvent.
Reimplemented in BGC.Audio.Midi.Events.SMTPEOffsetMetaMidiEvent, BGC.Audio.Midi.Events.TimeSignatureMetaMidiEvent, BGC.Audio.Midi.Events.TextMetaMidiEvent, BGC.Audio.Midi.Events.SequencerSpecificMetaMidiEvent, BGC.Audio.Midi.Events.UnknownMetaMidiEvent, BGC.Audio.Midi.Events.SequenceNumberMetaMidiEvent, and BGC.Audio.Midi.Events.SetTempoMetaMidiEvent.
Definition at line 86 of file MetaMidiEvent.cs.
         {
             outputStream.WriteByte(metaTypeCode);
         }
ToString()
override string BGC.Audio.Midi.Events.MetaMidiEvent.ToString ()
Field Documentation
Length
override int BGC.Audio.Midi.Events.MetaMidiEvent.Length => base.Length + 1
Definition at line 33 of file MetaMidiEvent.cs.
MessageClass
override MidiMessageClass BGC.Audio.Midi.Events.MetaMidiEvent.MessageClass => MidiMessageClass.MetaEvent
Definition at line 28 of file MetaMidiEvent.cs.
MetaType
MidiMetaType BGC.Audio.Midi.Events.MetaMidiEvent.MetaType => (MidiMetaType)metaTypeCode
Definition at line 31 of file MetaMidiEvent.cs.
metaTypeCode
readonly byte BGC.Audio.Midi.Events.MetaMidiEvent.metaTypeCode
Definition at line 29 of file MetaMidiEvent.cs.
The documentation for this class was generated from the following file:
Audio/Midi/Events/MetaMidiEvent.cs