BGC Tools: BGC.Audio.Envelopes.EnvelopeConcatenator Class Reference
BGC.Audio.Envelopes.EnvelopeConcatenator Class Reference
Public Member Functions
EnvelopeConcatenator ()
EnvelopeConcatenator (params IBGCEnvelopeStream[] streams)
EnvelopeConcatenator (IEnumerable< IBGCEnvelopeStream > streams)
void AddStream (IBGCEnvelopeStream stream)
void AddStreams (IEnumerable< IBGCEnvelopeStream > streams)
override void Reset ()
Sets this internal state of this stream to the initial state
override bool HasMoreSamples ()
Returns if the BGCEnvelopeStream has more samples
override float ReadNextSample ()
Returns the next sample in the BGCEnvelopeStream
override int Read (float[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
override void Seek (int position)
Seek to the indicated position in the stream
Public Member Functions inherited from BGC.Audio.Envelopes.BGCEnvelopeFilter
virtual void Initialize ()
Perform any calculations necessary to prepare the Stream
Data Fields
override IEnumerable< IBGCEnvelopeStream > InternalStreams => streams
override int Samples => _sampleCount
override float SamplingRate => _samplingRate
Properties
int CurrentClipIndex [get, private set]
int Position [get, private set]
Properties inherited from BGC.Audio.Envelopes.BGCEnvelopeFilter
abstract int Samples [get]
abstract float SamplingRate [get]
abstract IEnumerable< IBGCEnvelopeStream > InternalStreams [get]
Properties inherited from BGC.Audio.Envelopes.IBGCEnvelopeStream
int Samples [get]
The total number of Samples of this BGCEnvelopeStream
float SamplingRate [get]
The sampling rate of the BGCEnvelopeStream
Private Member Functions
void UpdateStats ()
Private Attributes
readonly List< IBGCEnvelopeStream > streams = new List<IBGCEnvelopeStream>()
int _sampleCount = 0
float _samplingRate
Additional Inherited Members
Protected Member Functions inherited from BGC.Audio.Envelopes.BGCEnvelopeFilter
virtual void _Initialize ()
Protected Attributes inherited from BGC.Audio.Envelopes.BGCEnvelopeFilter
bool initialized = false
Detailed Description
Definition at line 7 of file EnvelopeConcatenator.cs.
Constructor & Destructor Documentation
EnvelopeConcatenator() [1/3]
BGC.Audio.Envelopes.EnvelopeConcatenator.EnvelopeConcatenator () inline
Definition at line 21 of file EnvelopeConcatenator.cs.
         {
             UpdateStats();
         }
EnvelopeConcatenator() [2/3]
BGC.Audio.Envelopes.EnvelopeConcatenator.EnvelopeConcatenator (params IBGCEnvelopeStream [] streams) inline
Definition at line 26 of file EnvelopeConcatenator.cs.
         {
             AddStreams(streams);
         }
EnvelopeConcatenator() [3/3]
BGC.Audio.Envelopes.EnvelopeConcatenator.EnvelopeConcatenator (IEnumerable< IBGCEnvelopeStream > streams) inline
Definition at line 31 of file EnvelopeConcatenator.cs.
         {
             AddStreams(streams);
         }
Member Function Documentation
AddStream()
void BGC.Audio.Envelopes.EnvelopeConcatenator.AddStream (IBGCEnvelopeStream stream) inline
Definition at line 36 of file EnvelopeConcatenator.cs.
         {
             streams.Add(stream);
             UpdateStats();
         }
AddStreams()
void BGC.Audio.Envelopes.EnvelopeConcatenator.AddStreams (IEnumerable< IBGCEnvelopeStream > streams) inline
Definition at line 42 of file EnvelopeConcatenator.cs.
         {
             this.streams.AddRange(streams);
             UpdateStats();
         }
HasMoreSamples()
override bool BGC.Audio.Envelopes.EnvelopeConcatenator.HasMoreSamples () virtual
Returns if the BGCEnvelopeStream has more samples
Implements BGC.Audio.Envelopes.BGCEnvelopeFilter.
Read()
override int BGC.Audio.Envelopes.EnvelopeConcatenator.Read (float [] data, int offset, int count) inline virtual
Copy count samples into the Data buffer, starting at offset.
Returns
The number of samples copied
Implements BGC.Audio.Envelopes.BGCEnvelopeFilter.
Definition at line 86 of file EnvelopeConcatenator.cs.
References BGC.Audio.Envelopes.IBGCEnvelopeStream.Read().
         {
             int remainingSamples = count;
             while (remainingSamples > 0)
             {
                 if (CurrentClipIndex >= streams.Count)
                 {
                     //Hit the end
                     break;
                 }
                 IBGCEnvelopeStream stream = streams[CurrentClipIndex];
                 int readSamples = stream.Read(data, offset, remainingSamples);
                 remainingSamples -= readSamples;
                 offset += readSamples;
                 Position += readSamples;
                 if (readSamples <= 0)
                 {
                     CurrentClipIndex++;
                     if (CurrentClipIndex < streams.Count)
                     {
                         //Reset on advancing allows a concatenator to hold multiple
                         //copies of the same clip
                         streams[CurrentClipIndex].Reset();
                     }
                 }
             }
             return count - remainingSamples;
         }
ReadNextSample()
override float BGC.Audio.Envelopes.EnvelopeConcatenator.ReadNextSample () inline virtual
Returns the next sample in the BGCEnvelopeStream
Returns
The next sample
Implements BGC.Audio.Envelopes.BGCEnvelopeFilter.
Definition at line 57 of file EnvelopeConcatenator.cs.
References BGC.Audio.Envelopes.IBGCEnvelopeStream.HasMoreSamples(), BGC.Audio.Envelopes.IBGCEnvelopeStream.ReadNextSample(), and BGC.Audio.Envelopes.IBGCEnvelopeStream.Reset().
         {
             float value = 0f;
             while (CurrentClipIndex < streams.Count)
             {
                 IBGCEnvelopeStream stream = streams[CurrentClipIndex];
                 if (!stream.HasMoreSamples())
                 {
                     CurrentClipIndex++;
                     if (CurrentClipIndex < streams.Count)
                     {
                         //Reset on advancing allows a concatenator to hold multiple
                         //copies of the same clip
                         streams[CurrentClipIndex].Reset();
                     }
                     continue;
                 }
                 value = stream.ReadNextSample();
                 Position++;
                 break;
             }
             //Hit the end
             return value;
         }
Reset()
override void BGC.Audio.Envelopes.EnvelopeConcatenator.Reset () inline virtual
Sets this internal state of this stream to the initial state
Implements BGC.Audio.Envelopes.BGCEnvelopeFilter.
Definition at line 48 of file EnvelopeConcatenator.cs.
         {
             CurrentClipIndex = 0;
             Position = 0;
             streams.ForEach(x => x.Reset());
         }
Seek()
override void BGC.Audio.Envelopes.EnvelopeConcatenator.Seek (int position) inline virtual
Seek to the indicated position in the stream
Implements BGC.Audio.Envelopes.BGCEnvelopeFilter.
Definition at line 122 of file EnvelopeConcatenator.cs.
References BGC.Audio.Envelopes.IBGCEnvelopeStream.Reset(), BGC.Audio.Envelopes.IBGCEnvelopeStream.Samples, and BGC.Audio.Envelopes.IBGCEnvelopeStream.Seek().
         {
             Position = position;
             CurrentClipIndex = streams.Count;
             for (int i = 0; i < streams.Count; i++)
             {
                 IBGCEnvelopeStream clip = streams[i];
                 if (position > 0)
                 {
                     //Seek
                     if (position > clip.Samples)
                     {
                         clip.Seek(clip.Samples);
                         position -= clip.Samples;
                     }
                     else
                     {
                         clip.Seek(position);
                         position = 0;
                         CurrentClipIndex = i;
                     }
                 }
                 else
                 {
                     clip.Reset();
                 }
             }
         }
UpdateStats()
void BGC.Audio.Envelopes.EnvelopeConcatenator.UpdateStats () inline private
Definition at line 152 of file EnvelopeConcatenator.cs.
         {
             if (streams.Count > 0)
             {
                 IEnumerable<float> samplingRates = streams.Select(x => x.SamplingRate);
                 _samplingRate = samplingRates.Max();
                 if (_samplingRate != samplingRates.Min())
                 {
                     throw new Exception("AudioClipConcatenator requires all streams have the same samplingRate.");
                 }
                 if (streams.Any(x=>x.Samples == int.MaxValue))
                 {
                     _sampleCount = int.MaxValue;
                 }
                 else
                 {
                     _sampleCount = streams.Select(x => x.Samples).Sum();
                 }
             }
             else
             {
                 _sampleCount = 0;
                 _samplingRate = 44100f;
             }
         }
Field Documentation
_sampleCount
int BGC.Audio.Envelopes.EnvelopeConcatenator._sampleCount = 0 private
Definition at line 12 of file EnvelopeConcatenator.cs.
_samplingRate
float BGC.Audio.Envelopes.EnvelopeConcatenator._samplingRate private
Definition at line 15 of file EnvelopeConcatenator.cs.
InternalStreams
override IEnumerable<IBGCEnvelopeStream> BGC.Audio.Envelopes.EnvelopeConcatenator.InternalStreams => streams
Definition at line 10 of file EnvelopeConcatenator.cs.
Samples
override int BGC.Audio.Envelopes.EnvelopeConcatenator.Samples => _sampleCount
Definition at line 13 of file EnvelopeConcatenator.cs.
SamplingRate
override float BGC.Audio.Envelopes.EnvelopeConcatenator.SamplingRate => _samplingRate
Definition at line 16 of file EnvelopeConcatenator.cs.
streams
readonly List<IBGCEnvelopeStream> BGC.Audio.Envelopes.EnvelopeConcatenator.streams = new List<IBGCEnvelopeStream>() private
Definition at line 9 of file EnvelopeConcatenator.cs.
Property Documentation
CurrentClipIndex
int BGC.Audio.Envelopes.EnvelopeConcatenator.CurrentClipIndex get private set
Definition at line 18 of file EnvelopeConcatenator.cs.
Position
int BGC.Audio.Envelopes.EnvelopeConcatenator.Position get private set
Definition at line 19 of file EnvelopeConcatenator.cs.
The documentation for this class was generated from the following file:
Audio/Envelopes/EnvelopeConcatenator.cs