BGC Tools: BGC.Web.AWSServer Class Reference
BGC.Web.AWSServer Class Reference
Data Structures
class BodyKeys
class HeaderKeys
Static Public Member Functions
static Dictionary< string, string > Header (string apiKey)
static void PostBGCToJSonToAWS (string filePath, string organization, string study, string game, string apiKey, Action< UnityWebRequest, bool > callBack=null)
static void PostToAWS (string fileName, string organization, string study, string game, JsonObject content, string apiKey, Action< UnityWebRequest, bool > callBack=null)
Post to aws
static void GetCodeConfig (string code, string game, string apiKey, StatusPanel statusPanel, Action< string, int > callback=null)
static void GetCondition (string path, string apiKey, StatusPanel statusPanel, Action< string, int > callback=null)
static string Combine (string a, string b)
Combine two strings to form a path in AWS
Data Fields
const string ConditionURL = "https://84cje3rj4j.execute-api.us-east-1.amazonaws.com/Production/condition-retriever"
const string CodeURL = "https://84cje3rj4j.execute-api.us-east-1.amazonaws.com/Production/code-retriever"
const string ToS3URL = "https://84cje3rj4j.execute-api.us-east-1.amazonaws.com/Production/to-s3"
const string PathSeparator = "/"
const string CacheControl = "no-cache"
const string BGCExtension = ".bgc"
const string JSONExtension = ".json"
Static Private Member Functions
static bool ContainsBGCExtension (string path)
static bool ContainsJSONExtension (string fileName)
Private Attributes
const char extensionSplitter = '.'
Detailed Description
Definition at line 12 of file AWSServer.cs.
Member Function Documentation
static string BGC.Web.AWSServer.Combine (string a, string b) inline static
Combine two strings to form a path in AWS
Parameters
str
Returns
a + "/" + b
Definition at line 214 of file AWSServer.cs.
         {
             return $"{a}{PathSeparator}{b}";
         }
static bool BGC.Web.AWSServer.ContainsBGCExtension (string path) inline static private
Definition at line 219 of file AWSServer.cs.
         {
             return Path.HasExtension(BGCExtension);
         }
static bool BGC.Web.AWSServer.ContainsJSONExtension (string fileName) inline static private
Definition at line 224 of file AWSServer.cs.
         {
             return Path.HasExtension(JSONExtension);
         }
static void BGC.Web.AWSServer.GetCodeConfig (string code, string game, string apiKey, StatusPanel statusPanel, Action< string, int > callback = null) inline static
Definition at line 135 of file AWSServer.cs.
References BGC.Web.AWSServer.BodyKeys.Code, BGC.Web.AWSServer.BodyKeys.Game, BGC.Web.Utility.Rest.PostRequest(), BGC.MonoUtility.StatusPanel.Status, LightJson.String, and LightJson.JsonObject.ToString().
         {
             Assert.IsNotNull(statusPanel);
             Assert.IsFalse(String.IsNullOrEmpty(code));
             Assert.IsFalse(String.IsNullOrEmpty(game));
             Assert.IsFalse(String.IsNullOrEmpty(apiKey));
             statusPanel.Status = "Requesting code configuration...";
             JsonObject body = new JsonObject
             {
                 {
                     "body",
                     new JsonObject
                     {
                         { BodyKeys.Game, game },
                         { BodyKeys.Code, code }
                     }
                 }
             };
             Rest.PostRequest(
                 CodeURL,
                 Header(apiKey),
                 body.ToString(),
                 (UnityWebRequest uwr, bool valid) => {
                     if (callback != null)
                     {
                         statusPanel.Status = "Downloading server response...";
                         DownloadHandler downloader = uwr.downloadHandler;
                         callback(downloader.text, (int) uwr.responseCode);
                     }
                 });
         }
static void BGC.Web.AWSServer.GetCondition (string path, string apiKey, StatusPanel statusPanel, Action< string, int > callback = null) inline static
Definition at line 175 of file AWSServer.cs.
References BGC.Web.AWSServer.BodyKeys.Condition, BGC.Web.Utility.Rest.PostRequest(), BGC.MonoUtility.StatusPanel.Status, LightJson.String, and LightJson.JsonObject.ToString().
         {
             Assert.IsFalse(String.IsNullOrEmpty(apiKey));
             Assert.IsFalse(String.IsNullOrEmpty(path));
             Assert.IsNotNull(statusPanel);
             statusPanel.Status = "Requesting condition...";
             JsonObject body = new JsonObject
             {
                 {
                     "body",
                     new JsonObject
                     {
                         { BodyKeys.Condition, path }
                     }
                }
             };
             Rest.PostRequest(
                 ConditionURL,
                 Header(apiKey),
                 body.ToString(),
                 (uwr, validJson) =>
                 {
                     if (callback != null)
                     {
                         statusPanel.Status = "Downloading server response...";
                         DownloadHandler downloader = uwr.downloadHandler;
                         callback(downloader.text, (int)uwr.responseCode);
                     }
                 });
         }
static Dictionary<string, string> BGC.Web.AWSServer.Header (string apiKey) inline static
Definition at line 42 of file AWSServer.cs.
References BGC.Web.AWSServer.HeaderKeys.ApiKey.
         {
             return new Dictionary<string, string>
             {
                 { HeaderKeys.ApiKey, apiKey},
                 { "Content-Type", "application/x-www-form-urlencoded" }
             };
         }
static void BGC.Web.AWSServer.PostBGCToJSonToAWS (string filePath, string organization, string study, string game, string apiKey, Action< UnityWebRequest, bool > callBack = null) inline static
Definition at line 51 of file AWSServer.cs.
References BGC.Utility.BgcToJson.ConvertBgcToJson(), and LightJson.String.
Referenced by BGC.IO.Logging.Logger.CloseFile(), and BGC.Utility.LogFilesTos3.MigrateUser().
         {
             Assert.IsFalse(String.IsNullOrEmpty(filePath));
             Assert.IsFalse(String.IsNullOrEmpty(organization));
             Assert.IsFalse(String.IsNullOrEmpty(study));
             Assert.IsFalse(String.IsNullOrEmpty(game));
             Assert.IsTrue(ContainsBGCExtension(filePath));
             Assert.IsTrue(File.Exists(filePath));
             StreamReader reader = new StreamReader(filePath);
             string content = reader.ReadToEnd();
             reader.Close();
             try
             {
                 JsonObject jsonContent = BGC.Utility.BgcToJson.ConvertBgcToJson(content);
                 PostToAWS(
                     Path.GetFileName(filePath).Replace(BGCExtension, JSONExtension),
                     organization,
                     study,
                     game,
                     jsonContent,
                     apiKey,
                     callBack);
             }
             catch (Exception e)
             {
                 UnityEngine.Debug.LogError($"Error sending file {filePath} with exception {e.Message}.");
                 callBack(null, false);
             }
         }
static void BGC.Web.AWSServer.PostToAWS (string fileName, string organization, string study, string game, JsonObject content, string apiKey, Action< UnityWebRequest, bool > callBack = null) inline static
Post to aws
Parameters
filePath
organization
study
game
callBack
Definition at line 98 of file AWSServer.cs.
References BGC.Web.AWSServer.BodyKeys.Content, BGC.Web.AWSServer.BodyKeys.FileName, BGC.Web.AWSServer.BodyKeys.Game, BGC.Web.AWSServer.BodyKeys.Oganization, BGC.Web.Utility.Rest.PostRequest(), LightJson.String, BGC.Web.AWSServer.BodyKeys.Study, and LightJson.JsonObject.ToString().
         {
             Assert.IsFalse(String.IsNullOrEmpty(fileName));
             Assert.IsFalse(String.IsNullOrEmpty(organization));
             Assert.IsFalse(String.IsNullOrEmpty(study));
             Assert.IsFalse(String.IsNullOrEmpty(game));
             Assert.IsTrue(ContainsJSONExtension(fileName));
             JsonObject body = new JsonObject
             {
                 {
                     "body",
                     new JsonObject
                     {
                         { BodyKeys.Oganization, organization },
                         { BodyKeys.Study, study },
                         { BodyKeys.Game, game },
                         { BodyKeys.FileName, fileName },
                         { BodyKeys.Content, content.ToString() }
                     }
                 }
             };
             Rest.PostRequest(
                 ToS3URL,
                 Header(apiKey),
                 body.ToString(),
                 callBack);
         }
Field Documentation
const string BGC.Web.AWSServer.BGCExtension = ".bgc"
Definition at line 37 of file AWSServer.cs.
const string BGC.Web.AWSServer.CacheControl = "no-cache"
Definition at line 36 of file AWSServer.cs.
const string BGC.Web.AWSServer.CodeURL = "https://84cje3rj4j.execute-api.us-east-1.amazonaws.com/Production/code-retriever"
Definition at line 32 of file AWSServer.cs.
const string BGC.Web.AWSServer.ConditionURL = "https://84cje3rj4j.execute-api.us-east-1.amazonaws.com/Production/condition-retriever"
Definition at line 31 of file AWSServer.cs.
const char BGC.Web.AWSServer.extensionSplitter = '.' private
Definition at line 40 of file AWSServer.cs.
const string BGC.Web.AWSServer.JSONExtension = ".json"
Definition at line 38 of file AWSServer.cs.
const string BGC.Web.AWSServer.PathSeparator = "/"
Definition at line 35 of file AWSServer.cs.
const string BGC.Web.AWSServer.ToS3URL = "https://84cje3rj4j.execute-api.us-east-1.amazonaws.com/Production/to-s3"
Definition at line 33 of file AWSServer.cs.
The documentation for this class was generated from the following file:
Web/AWSServer.cs