BGC Tools: BGC.Audio.Filters.FramedPhaseReencoder Class Reference
BGC.Audio.Filters.FramedPhaseReencoder Class Reference
Applies an ITD by adjusting the phase in the frequency domain, frame-based
Public Member Functions
FramedPhaseReencoder (IBGCStream stream, double timeShift, int frameSize=(1<< 11), int overlapFactor=8)
FramedPhaseReencoder (IBGCStream stream, double leftTimeShift, double rightTimeShift, int frameSize=(1<< 11), int overlapFactor=8)
override int Read (float[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
override void Reset ()
Sets this internal state of this stream to the initial state
override void Seek (int position)
Seek to the indicated position in the stream
override IEnumerable< double > GetChannelRMS ()
The RMS amplitude of each channel
Public Member Functions inherited from BGC.Audio.Filters.SimpleBGCFilter
SimpleBGCFilter (IBGCStream stream)
override void Seek (int position)
Seek to the indicated position in the stream
override void Reset ()
Sets this internal state of this stream to the initial state
override void Initialize ()
Perform any calculations necessary to prepare the Stream
Static Public Member Functions
static IBGCStream StereoifyStream (IBGCStream stream)
Data Fields
override int ChannelSamples => stream.ChannelSamples
Data Fields inherited from BGC.Audio.Filters.SimpleBGCFilter
override float SamplingRate => stream.SamplingRate
Properties
override int Channels [get]
override int TotalSamples [get]
Properties inherited from BGC.Audio.Filters.SimpleBGCFilter
override IEnumerable< IBGCStream > InternalStreams [get]
Properties inherited from BGC.Audio.Filters.BGCFilter
abstract int Channels [get]
abstract int TotalSamples [get]
abstract int ChannelSamples [get]
abstract float SamplingRate [get]
abstract IEnumerable< IBGCStream > InternalStreams [get]
Properties inherited from BGC.Audio.IBGCStream
int Channels [get]
The number of underlying Channels of this BGCStream
int TotalSamples [get]
The total number of Samples of this BGCStream
int ChannelSamples [get]
The number of Samples of each channel for this BGCStream
float SamplingRate [get]
The sampling rate of the Stream
Private Member Functions
int ReadBody (float[] buffer, int offset, int count)
void ClearBuffers ()
Private Attributes
readonly int frameSize
readonly int overlapFactor
readonly int halfFrameSize
readonly int stepSize
readonly int overlap
readonly double outputScalar
readonly float [] localSampleBuffer
Holds samples from underlying stream
readonly float [] cachedSampleBuffer
Store computed samples ready to deliver
readonly Complex64 [][] phasors
readonly float [][] inputBuffers
readonly Complex64 [] fftBuffer
readonly float [] outputAccumulation
readonly double [] windowInput
readonly double [] timeShifts
int bufferIndex = 0
int bufferCount = 0
Additional Inherited Members
Protected Member Functions inherited from BGC.Audio.Filters.BGCFilter
virtual void _Initialize ()
Protected Attributes inherited from BGC.Audio.Filters.SimpleBGCFilter
readonly IBGCStream stream
Protected Attributes inherited from BGC.Audio.Filters.BGCFilter
bool initialized = false
Detailed Description
Applies an ITD by adjusting the phase in the frequency domain, frame-based
Definition at line 13 of file FramedPhaseReencoder.cs.
Constructor & Destructor Documentation
FramedPhaseReencoder() [1/2]
BGC.Audio.Filters.FramedPhaseReencoder.FramedPhaseReencoder (IBGCStream stream, double timeShift, int frameSize = (1 << 11), int overlapFactor = 8) inline
Definition at line 53 of file FramedPhaseReencoder.cs.
References BGC.Audio.IBGCStream.Channels, BGC.Audio.IBGCStream.ChannelSamples, and BGC.Mathematics.Complex64.FromPolarCoordinates().
             : base(stream)
         {
             UnityEngine.Debug.LogWarning("FramedPhaseReencoder isn't really ready... use at your own risk.");
             this.frameSize = frameSize;
             this.overlapFactor = overlapFactor;
             halfFrameSize = frameSize / 2;
             stepSize = frameSize / this.overlapFactor;
             overlap = frameSize - stepSize;
             Channels = stream.Channels;
             if (stream.ChannelSamples == int.MaxValue)
             {
                 TotalSamples = int.MaxValue;
             }
             else
             {
                 TotalSamples = Channels * stream.ChannelSamples;
             }
             localSampleBuffer = new float[Channels * stepSize];
             cachedSampleBuffer = new float[Channels * stepSize];
             phasors = new Complex64[Channels][];
             inputBuffers = new float[Channels][];
             outputAccumulation = new float[Channels * frameSize];
             fftBuffer = new Complex64[frameSize];
             timeShifts = Enumerable.Repeat(timeShift, Channels).ToArray();
             for (int i = 0; i < Channels; i++)
             {
                 inputBuffers[i] = new float[frameSize];
                 double rotationFactor = -2.0 * PI * SamplingRate * timeShifts[i] / frameSize;
                 for (int j = 1; j < halfFrameSize; j++)
                 {
                     //Initialize phasors to 2 so that it doubles the amplitudes on copy and rotation
                     phasors[i][j] = Complex64.FromPolarCoordinates(2.0, j * rotationFactor);
                 }
                 phasors[i][0] = 1.0;
             }
             outputScalar = 1.0 / (this.overlapFactor);
             windowInput = new double[frameSize];
             for (int i = 0; i < frameSize; i++)
             {
                 //Hamming
                 windowInput[i] = 0.54 - 0.46 * Cos(2.0 * PI * i / (frameSize - 1));
             }
         }
FramedPhaseReencoder() [2/2]
BGC.Audio.Filters.FramedPhaseReencoder.FramedPhaseReencoder (IBGCStream stream, double leftTimeShift, double rightTimeShift, int frameSize = (1 << 11), int overlapFactor = 8) inline
Definition at line 116 of file FramedPhaseReencoder.cs.
References BGC.Audio.IBGCStream.Channels, BGC.Audio.IBGCStream.ChannelSamples, and BGC.Mathematics.Complex64.FromPolarCoordinates().
             : base(StereoifyStream(stream))
         {
             UnityEngine.Debug.LogWarning("FramedPhaseReencoder isn't really ready... use at your own risk.");
             this.frameSize = frameSize;
             this.overlapFactor = overlapFactor;
             halfFrameSize = frameSize / 2;
             stepSize = frameSize / this.overlapFactor;
             overlap = frameSize - stepSize;
             Channels = this.stream.Channels;
             if (this.stream.ChannelSamples == int.MaxValue)
             {
                 TotalSamples = int.MaxValue;
             }
             else
             {
                 TotalSamples = Channels * this.stream.ChannelSamples;
             }
             localSampleBuffer = new float[Channels * stepSize];
             cachedSampleBuffer = new float[Channels * stepSize];
             phasors = new Complex64[Channels][];
             inputBuffers = new float[Channels][];
             outputAccumulation = new float[Channels * frameSize];
             fftBuffer = new Complex64[frameSize];
             timeShifts = new double[] { leftTimeShift, rightTimeShift };
             for (int i = 0; i < Channels; i++)
             {
                 inputBuffers[i] = new float[frameSize];
                 phasors[i] = new Complex64[halfFrameSize];
                 double rotationFactor = -2.0 * PI * SamplingRate * timeShifts[i] / frameSize;
                 for (int j = 1; j < halfFrameSize; j++)
                 {
                     //Initialize phasors to 2 so that it doubles the amplitudes on copy and rotation
                     phasors[i][j] = Complex64.FromPolarCoordinates(2.0, j * rotationFactor);
                 }
                 phasors[i][0] = 1.0;
             }
             outputScalar = 2.0 / this.overlapFactor;
             windowInput = new double[frameSize];
             for (int i = 0; i < frameSize; i++)
             {
                 //Hamming
                 windowInput[i] = 0.54 - 0.46 * Cos(2.0 * PI * i / (frameSize - 1));
             }
         }
Member Function Documentation
ClearBuffers()
void BGC.Audio.Filters.FramedPhaseReencoder.ClearBuffers () inline private
Definition at line 288 of file FramedPhaseReencoder.cs.
         {
             bufferIndex = 0;
             bufferCount = 0;
             Array.Clear(outputAccumulation, 0, outputAccumulation.Length);
             for (int i = 0; i < Channels; i++)
             {
                 Array.Clear(inputBuffers[i], 0, inputBuffers[i].Length);
             }
         }
GetChannelRMS()
override IEnumerable<double> BGC.Audio.Filters.FramedPhaseReencoder.GetChannelRMS () virtual
The RMS amplitude of each channel
Implements BGC.Audio.Filters.BGCFilter.
Read()
override int BGC.Audio.Filters.FramedPhaseReencoder.Read (float [] data, int offset, int count) inline virtual
Copy count samples into the Data buffer, starting at offset.
Returns
The number of samples copied
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 181 of file FramedPhaseReencoder.cs.
References BGC.Mathematics.Fourier.Forward(), BGC.Mathematics.Fourier.Inverse(), and BGC.Audio.IBGCStream.Read().
         {
             int samplesWritten = ReadBody(data, offset, count);
             while (samplesWritten < count)
             {
                 int read = stream.Read(localSampleBuffer, 0, localSampleBuffer.Length);
                 if (read <= 0)
                 {
                     //Done
                     break;
                 }
                 else if (read < localSampleBuffer.Length)
                 {
                     //Set rest to zero
                     Array.Clear(localSampleBuffer, read, localSampleBuffer.Length - read);
                 }
                 bufferIndex = 0;
                 bufferCount = Channels * stepSize;
                 for (int channel = 0; channel < Channels; channel++)
                 {
                     //Slide input samples over
                     Array.Copy(
                         sourceArray: inputBuffers[channel],
                         sourceIndex: stepSize,
                         destinationArray: inputBuffers[channel],
                         destinationIndex: 0,
                         length: overlap);
                     //Copy new samples into buffer
                     for (int i = 0; i < stepSize; i++)
                     {
                         inputBuffers[channel][overlap + i] = localSampleBuffer[Channels * i + channel];
                     }
                     //Copy and Window into fftbuffer
                     for (int i = 0; i < frameSize; i++)
                     {
                         fftBuffer[i] = inputBuffers[channel][i] * windowInput[i];
                     }
                     //FFT
                     Fourier.Forward(fftBuffer);
                     //Copy values into IFFT Buffer
                     for (int i = 0; i < halfFrameSize; i++)
                     {
                         fftBuffer[i] *= phasors[channel][i];
                     }
                     Array.Clear(
                         array: fftBuffer,
                         index: halfFrameSize + 1,
                         length: halfFrameSize - 1);
                     //IFFT
                     Fourier.Inverse(fftBuffer);
                     //Accumualte the window samples
                     for (int i = 0; i < frameSize; i++)
                     {
                         outputAccumulation[Channels * i + channel] += (float)(outputScalar * fftBuffer[i].Real);
                     }
                 }
                 //Copy output samples to output buffer
                 Array.Copy(
                     sourceArray: outputAccumulation,
                     destinationArray: cachedSampleBuffer,
                     length: bufferCount);
                 //Slide down output accumulation
                 Array.Copy(
                     sourceArray: outputAccumulation,
                     sourceIndex: bufferCount,
                     destinationArray: outputAccumulation,
                     destinationIndex: 0,
                     length: outputAccumulation.Length - bufferCount);
                 //Clear empty output accumulation region
                 Array.Clear(outputAccumulation, outputAccumulation.Length - bufferCount, bufferCount);
                 samplesWritten += ReadBody(data, offset + samplesWritten, count - samplesWritten);
             }
             return samplesWritten;
         }
ReadBody()
int BGC.Audio.Filters.FramedPhaseReencoder.ReadBody (float [] buffer, int offset, int count) inline private
Definition at line 272 of file FramedPhaseReencoder.cs.
         {
             int samplesWritten = Math.Min(count, bufferCount - bufferIndex);
             Array.Copy(
                 sourceArray: cachedSampleBuffer,
                 sourceIndex: bufferIndex,
                 destinationArray: buffer,
                 destinationIndex: offset,
                 length: samplesWritten);
             bufferIndex += samplesWritten;
             return samplesWritten;
         }
Reset()
override void BGC.Audio.Filters.FramedPhaseReencoder.Reset () inline virtual
Sets this internal state of this stream to the initial state
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 301 of file FramedPhaseReencoder.cs.
References BGC.Audio.IBGCStream.Reset().
         {
             ClearBuffers();
             stream.Reset();
         }
Seek()
override void BGC.Audio.Filters.FramedPhaseReencoder.Seek (int position) inline virtual
Seek to the indicated position in the stream
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 307 of file FramedPhaseReencoder.cs.
References BGC.Audio.IBGCStream.GetChannelRMS(), and BGC.Audio.IBGCStream.Seek().
         {
             ClearBuffers();
             stream.Seek(position);
         }
StereoifyStream()
static IBGCStream BGC.Audio.Filters.FramedPhaseReencoder.StereoifyStream (IBGCStream stream) inline static
Definition at line 316 of file FramedPhaseReencoder.cs.
References BGC.Audio.IBGCStream.Channels.
         {
             if (stream.Channels == 1)
             {
                 return stream.UpChannel();
             }
             return stream;
         }
Field Documentation
bufferCount
int BGC.Audio.Filters.FramedPhaseReencoder.bufferCount = 0 private
Definition at line 45 of file FramedPhaseReencoder.cs.
bufferIndex
int BGC.Audio.Filters.FramedPhaseReencoder.bufferIndex = 0 private
Definition at line 44 of file FramedPhaseReencoder.cs.
cachedSampleBuffer
readonly float [] BGC.Audio.Filters.FramedPhaseReencoder.cachedSampleBuffer private
Store computed samples ready to deliver
Definition at line 33 of file FramedPhaseReencoder.cs.
ChannelSamples
override int BGC.Audio.Filters.FramedPhaseReencoder.ChannelSamples => stream.ChannelSamples
Definition at line 51 of file FramedPhaseReencoder.cs.
fftBuffer
readonly Complex64 [] BGC.Audio.Filters.FramedPhaseReencoder.fftBuffer private
Definition at line 37 of file FramedPhaseReencoder.cs.
frameSize
readonly int BGC.Audio.Filters.FramedPhaseReencoder.frameSize private
Definition at line 15 of file FramedPhaseReencoder.cs.
halfFrameSize
readonly int BGC.Audio.Filters.FramedPhaseReencoder.halfFrameSize private
Definition at line 18 of file FramedPhaseReencoder.cs.
inputBuffers
readonly float [][] BGC.Audio.Filters.FramedPhaseReencoder.inputBuffers private
Definition at line 36 of file FramedPhaseReencoder.cs.
localSampleBuffer
readonly float [] BGC.Audio.Filters.FramedPhaseReencoder.localSampleBuffer private
Holds samples from underlying stream
Definition at line 28 of file FramedPhaseReencoder.cs.
outputAccumulation
readonly float [] BGC.Audio.Filters.FramedPhaseReencoder.outputAccumulation private
Definition at line 38 of file FramedPhaseReencoder.cs.
outputScalar
readonly double BGC.Audio.Filters.FramedPhaseReencoder.outputScalar private
Definition at line 23 of file FramedPhaseReencoder.cs.
overlap
readonly int BGC.Audio.Filters.FramedPhaseReencoder.overlap private
Definition at line 21 of file FramedPhaseReencoder.cs.
overlapFactor
readonly int BGC.Audio.Filters.FramedPhaseReencoder.overlapFactor private
Definition at line 16 of file FramedPhaseReencoder.cs.
phasors
readonly Complex64 [][] BGC.Audio.Filters.FramedPhaseReencoder.phasors private
Definition at line 35 of file FramedPhaseReencoder.cs.
stepSize
readonly int BGC.Audio.Filters.FramedPhaseReencoder.stepSize private
Definition at line 20 of file FramedPhaseReencoder.cs.
timeShifts
readonly double [] BGC.Audio.Filters.FramedPhaseReencoder.timeShifts private
Definition at line 42 of file FramedPhaseReencoder.cs.
windowInput
readonly double [] BGC.Audio.Filters.FramedPhaseReencoder.windowInput private
Definition at line 40 of file FramedPhaseReencoder.cs.
Property Documentation
Channels
override int BGC.Audio.Filters.FramedPhaseReencoder.Channels get
Definition at line 47 of file FramedPhaseReencoder.cs.
TotalSamples
override int BGC.Audio.Filters.FramedPhaseReencoder.TotalSamples get
Definition at line 49 of file FramedPhaseReencoder.cs.
The documentation for this class was generated from the following file:
Audio/Filters/FramedPhaseReencoder.cs