BGC Tools: BGC.Audio.LinearInterpolation Class Reference
BGC.Audio.LinearInterpolation Class Reference
Resampling methods
Static Public Member Functions
static float [] FactorUpscaler (float[] samples, int factor, int channels)
static float [] Resample (float[] samples, double oldSamplingRate, double newSamplingRate, int channels)
static short [] Resample (short[] samples, double oldSamplingRate, double newSamplingRate, int channels)
Static Public Attributes
static float [] leftSamples
Static Private Member Functions
static float [] float [] rightSamples Resample ((float[] leftSamples, float[] rightSamples) samples, double oldSamplingRate, double newSamplingRate, int channels)
Detailed Description
Resampling methods
Definition at line 8 of file LinearInterpolation.cs.
Member Function Documentation
FactorUpscaler()
static float [] BGC.Audio.LinearInterpolation.FactorUpscaler (float [] samples, int factor, int channels) inline static
Definition at line 23 of file LinearInterpolation.cs.
Referenced by BGC.Tests.WAVEncodingTests.UpScalingTest().
         {
             int inputSampleCount = samples.Length / channels;
             int outputSampleCount = factor * inputSampleCount;
             float[] outputSamples = new float[outputSampleCount * channels];
             for (int chan = 0; chan < channels; chan++)
             {
                 for (int j = 0; j < inputSampleCount; j++)
                 {
                     outputSamples[factor * j * channels + chan] = samples[j * channels + chan];
                 }
             }
             return outputSamples;
         }
Resample() [1/3]
static float [] float [] rightSamples BGC.Audio.LinearInterpolation.Resample ((float[] leftSamples, float[] rightSamples) samples, double oldSamplingRate, double newSamplingRate, int channels) inline static private
Definition at line 10 of file LinearInterpolation.cs.
Referenced by BGC.Audio.WaveEncoding.LoadBGCSimple(), BGC.Audio.WaveEncoding.LoadBGCStream(), BGC.Audio.WaveEncoding.LoadFile(), BGC.Audio.WaveEncoding.LoadPCMFile(), and BGC.Audio.WaveEncoding.LoadStereoFile().
         {
             float[] newLeftSamples = Resample(samples.leftSamples, oldSamplingRate, newSamplingRate, 1);
             float[] newRightSamples = Resample(samples.rightSamples, oldSamplingRate, newSamplingRate, 1);
             return (newLeftSamples, newRightSamples);
         }
Resample() [2/3]
static float [] BGC.Audio.LinearInterpolation.Resample (float [] samples, double oldSamplingRate, double newSamplingRate, int channels) inline static
Definition at line 44 of file LinearInterpolation.cs.
         {
             //Smaller than 1 when downsampling
             double rateRatio = newSamplingRate / oldSamplingRate;
             //Larger than 1 when downsampling
             double invRateRatio = oldSamplingRate / newSamplingRate;
             int inputSampleCount = samples.Length / channels;
             int outputSampleCount = (int)Math.Floor(inputSampleCount * rateRatio);
             float[] outputSamples = new float[outputSampleCount * channels];
             double i;
             int i0;
             int i1;
             for (int chan = 0; chan < channels; chan++)
             {
                 for (int j = 0; j < outputSampleCount; j++)
                 {
                     i = j * invRateRatio;
                     i0 = (int)i;
                     i1 = i0 + 1;
                     outputSamples[j * channels + chan] = (float)((i1 - i) * samples[i0 * channels + chan] + (i - i0) * samples[i1 * channels + chan]);
                 }
             }
             return outputSamples;
         }
Resample() [3/3]
static short [] BGC.Audio.LinearInterpolation.Resample (short [] samples, double oldSamplingRate, double newSamplingRate, int channels) inline static
Definition at line 78 of file LinearInterpolation.cs.
         {
             //Smaller than 1 when downsampling
             double rateRatio = newSamplingRate / oldSamplingRate;
             //Larger than 1 when downsampling
             double invRateRatio = oldSamplingRate / newSamplingRate;
             int inputSampleCount = samples.Length / channels;
             int outputSampleCount = (int)Math.Ceiling(inputSampleCount * rateRatio);
             short[] outputSamples = new short[outputSampleCount * channels];
             double i;
             int i0;
             int i1;
             for (int chan = 0; chan < channels; chan++)
             {
                 for (int j = 0; j < outputSampleCount; j++)
                 {
                     i = j * invRateRatio;
                     i0 = (int)i;
                     i1 = i0 + 1;
                     outputSamples[j * channels + chan] = (short)Math.Round((i1 - i) * samples[i0 * channels + chan] + (i - i0) * samples[i1 * channels + chan]);
                 }
             }
             return outputSamples;
         }
Field Documentation
leftSamples
float [] BGC.Audio.LinearInterpolation.leftSamples static
Definition at line 10 of file LinearInterpolation.cs.
The documentation for this class was generated from the following file:
Audio/LinearInterpolation.cs