BGC Tools: BGC.Audio.AnalyticStreams.AnalyticStreamFrequencyShifter Class Reference
BGC.Audio.AnalyticStreams.AnalyticStreamFrequencyShifter Class Reference
Applies FrequencyShift to the underlying stream. Utilizes the FFT Shift Theorem
Public Member Functions
AnalyticStreamFrequencyShifter (IAnalyticStream stream, double frequencyShift)
override int Read (Complex64[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
override void Reset ()
Sets this internal state of this stream to the initial state
override void Seek (int position)
Seek to the indicated position in the stream
override double GetRMS ()
The RMS amplitude of the stream (real component)
Public Member Functions inherited from BGC.Audio.AnalyticStreams.SimpleAnalyticFilter
SimpleAnalyticFilter (IAnalyticStream stream)
override void Seek (int position)
Seek to the indicated position in the stream
override void Reset ()
Sets this internal state of this stream to the initial state
Public Member Functions inherited from BGC.Audio.AnalyticStreams.AnalyticFilter
void Initialize ()
Perform any calculations necessary to prepare the Stream
Data Fields
override int Samples => stream.Samples
Data Fields inherited from BGC.Audio.AnalyticStreams.SimpleAnalyticFilter
override IEnumerable< IAnalyticStream > InternalStreams => new IAnalyticStream[] { stream }
override double SamplingRate => stream.SamplingRate
Private Attributes
readonly double frequencyShift
Complex64 partial
readonly double cyclePartial
readonly Complex64[] shifterSamples
int position = 0
int cycles = 0
Additional Inherited Members
Protected Member Functions inherited from BGC.Audio.AnalyticStreams.AnalyticFilter
virtual void _Initialize ()
Protected Attributes inherited from BGC.Audio.AnalyticStreams.SimpleAnalyticFilter
readonly IAnalyticStream stream
Protected Attributes inherited from BGC.Audio.AnalyticStreams.AnalyticFilter
bool initialized = false
Properties inherited from BGC.Audio.AnalyticStreams.AnalyticFilter
abstract int Samples [get]
abstract double SamplingRate [get]
abstract IEnumerable< IAnalyticStream > InternalStreams [get]
Properties inherited from BGC.Audio.AnalyticStreams.IAnalyticStream
int Samples [get]
The total number of Samples of this AnalyticStream
double SamplingRate [get]
The sampling rate of the Stream
Detailed Description
Applies FrequencyShift to the underlying stream. Utilizes the FFT Shift Theorem
Definition at line 13 of file AnalyticStreamFrequencyShifter.cs.
Constructor & Destructor Documentation
BGC.Audio.AnalyticStreams.AnalyticStreamFrequencyShifter.AnalyticStreamFrequencyShifter (IAnalyticStream stream, double frequencyShift) inline
Definition at line 25 of file AnalyticStreamFrequencyShifter.cs.
References BGC.Mathematics.Complex64.FromPolarCoordinates().
             : base(stream)
         {
             this.frequencyShift = frequencyShift;
             double sampleCount = SamplingRate / this.frequencyShift;
             int intSampleCount = (int)Ceiling(sampleCount) - 1;
             cyclePartial = (2 * PI * this.frequencyShift / SamplingRate) * (intSampleCount - sampleCount);
             cycles = 0;
             partial = Complex64.FromPolarCoordinates(
                 magnitude: 1.0,
                 phase: cycles * cyclePartial);
             shifterSamples = new Complex64[intSampleCount];
             for (int i = 0; i < shifterSamples.Length; i++)
             {
                 shifterSamples[i] = Complex64.FromPolarCoordinates(
                     magnitude: 1.0,
                     phase: 2 * PI * i / sampleCount);
             }
         }
Member Function Documentation
override double BGC.Audio.AnalyticStreams.AnalyticStreamFrequencyShifter.GetRMS () virtual
The RMS amplitude of the stream (real component)
Implements BGC.Audio.AnalyticStreams.AnalyticFilter.
override int BGC.Audio.AnalyticStreams.AnalyticStreamFrequencyShifter.Read (Complex64[] data, int offset, int count) inline virtual
Copy count samples into the Data buffer, starting at offset.
Returns
The number of samples copied
Implements BGC.Audio.AnalyticStreams.AnalyticFilter.
Definition at line 52 of file AnalyticStreamFrequencyShifter.cs.
References BGC.Mathematics.Complex64.FromPolarCoordinates().
         {
             int samplesRead = stream.Read(data, offset, count);
             for (int i = 0; i < samplesRead; i++)
             {
                 data[offset + i] *= shifterSamples[position++] * partial;
                 if (position == shifterSamples.Length)
                 {
                     position = 0;
                     cycles++;
                     partial = Complex64.FromPolarCoordinates(
                         magnitude: 1.0,
                         phase: cycles * cyclePartial);
                 }
             }
             return samplesRead;
         }
override void BGC.Audio.AnalyticStreams.AnalyticStreamFrequencyShifter.Reset () inline virtual
Sets this internal state of this stream to the initial state
Implements BGC.Audio.AnalyticStreams.AnalyticFilter.
Definition at line 72 of file AnalyticStreamFrequencyShifter.cs.
References BGC.Mathematics.Complex64.FromPolarCoordinates().
         {
             stream.Reset();
             position = 0;
             cycles = 0;
             partial = Complex64.FromPolarCoordinates(
                 magnitude: 1.0,
                 phase: cycles * cyclePartial);
         }
override void BGC.Audio.AnalyticStreams.AnalyticStreamFrequencyShifter.Seek (int position) inline virtual
Seek to the indicated position in the stream
Implements BGC.Audio.AnalyticStreams.AnalyticFilter.
Definition at line 82 of file AnalyticStreamFrequencyShifter.cs.
References BGC.Mathematics.GeneralMath.Clamp(), and BGC.Mathematics.Complex64.FromPolarCoordinates().
         {
             position = GeneralMath.Clamp(position, 0, Samples);
             stream.Seek(position);
             cycles = position / shifterSamples.Length;
             partial = Complex64.FromPolarCoordinates(
                 magnitude: 1.0,
                 phase: cycles * cyclePartial);
             this.position = position % shifterSamples.Length;
         }
Field Documentation
readonly double BGC.Audio.AnalyticStreams.AnalyticStreamFrequencyShifter.cyclePartial private
Definition at line 20 of file AnalyticStreamFrequencyShifter.cs.
int BGC.Audio.AnalyticStreams.AnalyticStreamFrequencyShifter.cycles = 0 private
Definition at line 23 of file AnalyticStreamFrequencyShifter.cs.
readonly double BGC.Audio.AnalyticStreams.AnalyticStreamFrequencyShifter.frequencyShift private
Definition at line 17 of file AnalyticStreamFrequencyShifter.cs.
Complex64 BGC.Audio.AnalyticStreams.AnalyticStreamFrequencyShifter.partial private
Definition at line 19 of file AnalyticStreamFrequencyShifter.cs.
int BGC.Audio.AnalyticStreams.AnalyticStreamFrequencyShifter.position = 0 private
Definition at line 22 of file AnalyticStreamFrequencyShifter.cs.
override int BGC.Audio.AnalyticStreams.AnalyticStreamFrequencyShifter.Samples => stream.Samples
Definition at line 15 of file AnalyticStreamFrequencyShifter.cs.
readonly Complex64 [] BGC.Audio.AnalyticStreams.AnalyticStreamFrequencyShifter.shifterSamples private
Definition at line 21 of file AnalyticStreamFrequencyShifter.cs.
The documentation for this class was generated from the following file:
Audio/AnalyticStreams/AnalyticStreamFrequencyShifter.cs