BGC Tools: LightJson.Serialization.JsonWriter Class Reference
LightJson.Serialization.JsonWriter Class Reference
Represents a writer that can write string representations of JsonValues.
Public Member Functions
JsonWriter (TextWriter innerWriter)
Initializes a new instance of JsonWriter.
JsonWriter (TextWriter innerWriter, bool pretty)
Initializes a new instance of JsonWriter.
void Write (JsonValue jsonValue)
Writes the given value to the InnerWriter.
Static Public Member Functions
static string Serialize (JsonValue value)
Returns a string representation of the given JsonValue.
static string Serialize (JsonValue value, bool pretty)
Generates a string representation of the given value.
Properties
string IndentString [get, set]
The string representing indentation in the output.
string SpacingString [get, set]
The string representing spacing in the output.
string NewLineString [get, set]
The string representing a new line on the output.
bool SortObjects [get, set]
Whether JsonObject properties should be written in a deterministic order.
TextWriter InnerWriter [get, set]
The TextWriter to which this JsonWriter writes.
Private Member Functions
void Write (string text)
void WriteEncodedJsonValue (JsonValue value)
void WriteEncodedString (string text)
void WriteIndentation ()
void WriteSpacing ()
void WriteLine ()
void WriteLine (string line)
void AddRenderingCollection (IEnumerable< JsonValue > value)
void RemoveRenderingCollection (IEnumerable< JsonValue > value)
void Render (JsonValue value)
void Render (JsonArray value)
void Render (JsonObject value)
IEnumerator< KeyValuePair< string, JsonValue > > GetJsonObjectEnumerator (JsonObject jsonObject)
Gets a JsonObject enumarator based on the configuration of this JsonWriter. If JsonWriter.SortObjects is set to true, then a ordered enumerator is returned. Otherwise, a faster non-deterministic enumerator is returned.
Static Private Member Functions
static bool IsValidNumber (double number)
Private Attributes
int indent
bool isNewLine
HashSet< IEnumerable< JsonValue > > renderingCollections = new HashSet<IEnumerable<JsonValue>>()
A set of containing all the collection objects (JsonObject/JsonArray) being rendered. It is used to prevent circular references; since collections that contain themselves will never finish rendering.
Detailed Description
Represents a writer that can write string representations of JsonValues.
Definition at line 14 of file JsonWriter.cs.
Constructor & Destructor Documentation
LightJson.Serialization.JsonWriter.JsonWriter (TextWriter innerWriter) inline
Initializes a new instance of JsonWriter.
Parameters
innerWriter The TextWriter used to write JsonValues.
Definition at line 45 of file JsonWriter.cs.
 : this(innerWriter, false) { }
LightJson.Serialization.JsonWriter.JsonWriter (TextWriter innerWriter, bool pretty) inline
Initializes a new instance of JsonWriter.
Parameters
innerWriter The TextWriter used to write JsonValues.
pretty Whether the output of the writer should be human-readable.
Definition at line 52 of file JsonWriter.cs.
         {
             if (pretty)
             {
                 IndentString = "\t";
                 SpacingString = " ";
                 NewLineString = "\n";
             }
             InnerWriter = innerWriter;
         }
Member Function Documentation
void LightJson.Serialization.JsonWriter.AddRenderingCollection (IEnumerable< JsonValue > value) inline private
Definition at line 190 of file JsonWriter.cs.
         {
             if (!renderingCollections.Add(value))
             {
                 throw new JsonSerializationException(ErrorType.CircularReference);
             }
         }
IEnumerator<KeyValuePair<string, JsonValue> > LightJson.Serialization.JsonWriter.GetJsonObjectEnumerator (JsonObject jsonObject) inline private
Gets a JsonObject enumarator based on the configuration of this JsonWriter. If JsonWriter.SortObjects is set to true, then a ordered enumerator is returned. Otherwise, a faster non-deterministic enumerator is returned.
Parameters
jsonObject The JsonObject for which to get an enumerator.
Definition at line 308 of file JsonWriter.cs.
References LightJson.JsonObject.GetEnumerator().
         {
             if (SortObjects)
             {
                 SortedDictionary<string, JsonValue> sortedDictionary = new SortedDictionary<string, JsonValue>(StringComparer.Ordinal);
                 foreach (KeyValuePair<string, JsonValue> item in jsonObject)
                 {
                     sortedDictionary.Add(item.Key, item.Value);
                 }
                 return sortedDictionary.GetEnumerator();
             }
             else
             {
                 return jsonObject.GetEnumerator();
             }
         }
static bool LightJson.Serialization.JsonWriter.IsValidNumber (double number) static private
void LightJson.Serialization.JsonWriter.RemoveRenderingCollection (IEnumerable< JsonValue > value) inline private
Definition at line 198 of file JsonWriter.cs.
         {
             renderingCollections.Remove(value);
         }
void LightJson.Serialization.JsonWriter.Render (JsonValue value) inline private
Definition at line 203 of file JsonWriter.cs.
References LightJson.JsonValue.Type.
         {
             switch (value.Type)
             {
                 case JsonValueType.Null:
                 case JsonValueType.Boolean:
                 case JsonValueType.Number:
                 case JsonValueType.String:
                     WriteEncodedJsonValue(value);
                     break;
                 case JsonValueType.Object:
                     Render((JsonObject)value);
                     break;
                 case JsonValueType.Array:
                     Render((JsonArray)value);
                     break;
                 default:
                     throw new JsonSerializationException(ErrorType.InvalidValueType);
             }
         }
void LightJson.Serialization.JsonWriter.Render (JsonArray value) inline private
Definition at line 227 of file JsonWriter.cs.
References LightJson.JsonArray.GetEnumerator().
         {
             AddRenderingCollection(value);
             WriteLine("[");
             indent += 1;
             using (IEnumerator<JsonValue> enumerator = value.GetEnumerator())
             {
                 bool hasNext = enumerator.MoveNext();
                 while (hasNext)
                 {
                     Render(enumerator.Current);
                     hasNext = enumerator.MoveNext();
                     if (hasNext)
                     {
                         WriteLine(",");
                     }
                     else
                     {
                         WriteLine();
                     }
                 }
             }
             indent -= 1;
             Write("]");
             RemoveRenderingCollection(value);
         }
void LightJson.Serialization.JsonWriter.Render (JsonObject value) inline private
Definition at line 263 of file JsonWriter.cs.
         {
             AddRenderingCollection(value);
             WriteLine("{");
             indent += 1;
             using (IEnumerator<KeyValuePair<string, JsonValue>> enumerator = GetJsonObjectEnumerator(value))
             {
                 bool hasNext = enumerator.MoveNext();
                 while (hasNext)
                 {
                     WriteEncodedString(enumerator.Current.Key);
                     Write(":");
                     WriteSpacing();
                     Render(enumerator.Current.Value);
                     hasNext = enumerator.MoveNext();
                     if (hasNext)
                     {
                         WriteLine(",");
                     }
                     else
                     {
                         WriteLine();
                     }
                 }
             }
             indent -= 1;
             Write("}");
             RemoveRenderingCollection(value);
         }
static string LightJson.Serialization.JsonWriter.Serialize (JsonValue value) static
Returns a string representation of the given JsonValue.
Parameters
value The JsonValue to serialize.
Referenced by LightJson.JsonArray.Clear(), LightJson.JsonValue.GetHashCode(), and LightJson.JsonObject.Rename().
static string LightJson.Serialization.JsonWriter.Serialize (JsonValue value, bool pretty) inline static
Generates a string representation of the given value.
Parameters
value The value to serialize.
pretty Indicates whether the resulting string should be formatted for human-readability.
Definition at line 357 of file JsonWriter.cs.
References LightJson.Serialization.JsonWriter.Write().
         {
             using (StringWriter stringWriter = new StringWriter())
             {
                 JsonWriter jsonWriter = new JsonWriter(stringWriter, pretty);
                 jsonWriter.Write(value);
                 return stringWriter.ToString();
             }
         }
void LightJson.Serialization.JsonWriter.Write (string text) inline private
Definition at line 64 of file JsonWriter.cs.
Referenced by LightJson.Serialization.JsonWriter.Serialize().
         {
             if (isNewLine)
             {
                 isNewLine = false;
                 WriteIndentation();
             }
             InnerWriter.Write(text);
         }
void LightJson.Serialization.JsonWriter.Write (JsonValue jsonValue) inline
Writes the given value to the InnerWriter.
Parameters
jsonValue The JsonValue to write.
Definition at line 333 of file JsonWriter.cs.
         {
             indent = 0;
             isNewLine = true;
             Render(jsonValue);
             renderingCollections.Clear();
         }
void LightJson.Serialization.JsonWriter.WriteEncodedJsonValue (JsonValue value) inline private
Definition at line 75 of file JsonWriter.cs.
References LightJson.JsonValue.AsString, and LightJson.JsonValue.Type.
         {
             switch (value.Type)
             {
                 case JsonValueType.Null:
                     Write("null");
                     break;
                 case JsonValueType.Boolean:
                     Write(value.AsString);
                     break;
                 case JsonValueType.Number:
                     if (!IsValidNumber(value))
                     {
                         throw new JsonSerializationException(ErrorType.InvalidNumber);
                     }
                     Write(((double)value).ToString(CultureInfo.InvariantCulture));
                     break;
                 case JsonValueType.String:
                     WriteEncodedString((string)value);
                     break;
                 case JsonValueType.Object:
                     Write($"JsonObject[{value.AsJsonObject.Count}]");
                     break;
                 case JsonValueType.Array:
                     Write($"JsonArray[{value.AsJsonArray.Count}]");
                     break;
                 default:
                     throw new InvalidOperationException("Invalid value type.");
             }
         }
void LightJson.Serialization.JsonWriter.WriteEncodedString (string text) inline private
Definition at line 113 of file JsonWriter.cs.
         {
             Write("\"");
             for (int i = 0; i < text.Length; i += 1)
             {
                 char currentChar = text[i];
                 // Encoding special characters.
                 switch (currentChar)
                 {
                     case '\\':
                         InnerWriter.Write("\\\\");
                         break;
                     case '\"':
                         InnerWriter.Write("\\\"");
                         break;
                     case '/':
                         InnerWriter.Write("\\/");
                         break;
                     case '\b':
                         InnerWriter.Write("\\b");
                         break;
                     case '\f':
                         InnerWriter.Write("\\f");
                         break;
                     case '\n':
                         InnerWriter.Write("\\n");
                         break;
                     case '\r':
                         InnerWriter.Write("\\r");
                         break;
                     case '\t':
                         InnerWriter.Write("\\t");
                         break;
                     default:
                         InnerWriter.Write(currentChar);
                         break;
                 }
             }
             InnerWriter.Write("\"");
         }
void LightJson.Serialization.JsonWriter.WriteIndentation () inline private
Definition at line 165 of file JsonWriter.cs.
         {
             for (int i = 0; i < indent; i += 1)
             {
                 Write(IndentString);
             }
         }
void LightJson.Serialization.JsonWriter.WriteLine () inline private
Definition at line 178 of file JsonWriter.cs.
         {
             Write(NewLineString);
             isNewLine = true;
         }
void LightJson.Serialization.JsonWriter.WriteLine (string line) inline private
Definition at line 184 of file JsonWriter.cs.
         {
             Write(line);
             WriteLine();
         }
void LightJson.Serialization.JsonWriter.WriteSpacing () inline private
Definition at line 173 of file JsonWriter.cs.
         {
             Write(SpacingString);
         }
Field Documentation
int LightJson.Serialization.JsonWriter.indent private
Definition at line 16 of file JsonWriter.cs.
bool LightJson.Serialization.JsonWriter.isNewLine private
Definition at line 17 of file JsonWriter.cs.
HashSet<IEnumerable<JsonValue> > LightJson.Serialization.JsonWriter.renderingCollections = new HashSet<IEnumerable<JsonValue>>() private
A set of containing all the collection objects (JsonObject/JsonArray) being rendered. It is used to prevent circular references; since collections that contain themselves will never finish rendering.
Definition at line 24 of file JsonWriter.cs.
Property Documentation
string LightJson.Serialization.JsonWriter.IndentString get set
The string representing indentation in the output.
Definition at line 27 of file JsonWriter.cs.
TextWriter LightJson.Serialization.JsonWriter.InnerWriter get set
The TextWriter to which this JsonWriter writes.
Definition at line 39 of file JsonWriter.cs.
string LightJson.Serialization.JsonWriter.NewLineString get set
The string representing a new line on the output.
Definition at line 33 of file JsonWriter.cs.
bool LightJson.Serialization.JsonWriter.SortObjects get set
Whether JsonObject properties should be written in a deterministic order.
Definition at line 36 of file JsonWriter.cs.
string LightJson.Serialization.JsonWriter.SpacingString get set
The string representing spacing in the output.
Definition at line 30 of file JsonWriter.cs.
The documentation for this class was generated from the following file:
LightJSON/Serialization/JsonWriter.cs