BGC Tools: BGC.Audio.Visualization.Spectrogram Class Reference
BGC.Audio.Visualization.Spectrogram Class Reference
Static Public Member Functions
static SpectralDecomp Decompose (IBGCStream stream, int windowCount=400, int windowOrder=12, int targetChannel=0, double minFreq=0.0, double maxFreq=double.PositiveInfinity)
Detailed Description
Definition at line 8 of file Spectrogram.cs.
Member Function Documentation
static SpectralDecomp BGC.Audio.Visualization.Spectrogram.Decompose (IBGCStream stream, int windowCount = 400, int windowOrder = 12, int targetChannel = 0, double minFreq = 0.0, double maxFreq = double.PositiveInfinity) inline static
Definition at line 10 of file Spectrogram.cs.
References BGC.Audio.Visualization.SpectralDecomp.Add(), BGC.Audio.IBGCStream.Channels, BGC.Mathematics.Fourier.Forward(), BGC.Audio.FrequencyDomain.GetComplexSampleFrequency(), BGC.Audio.Envelopes.CosineEnvelope.HammingWindow(), BGC.Audio.Envelopes.IBGCEnvelopeStream.ReadNextSample(), and BGC.Audio.Envelopes.IBGCEnvelopeStream.Reset().
         {
             //WindowSize is 2 ^ windowOrder
             int windowSize = 1 << windowOrder;
             if (stream.Channels <= targetChannel)
             {
                 throw new ArgumentException(
                     $"TargetChannel ({targetChannel}) exceeded stream channels ({stream.Channels})",
                     nameof(targetChannel));
             }
             float[] samples = stream.IsolateChannel(targetChannel).Cache().Samples;
             int sampleOffset = (int)((samples.Length - windowSize) / (double)(windowCount - 1));
             //Adjust windowSize to conform to sample size and requirements
             while (sampleOffset <= 0 && windowOrder > 4)
             {
                 --windowOrder;
                 windowSize = 1 << windowOrder;
                 windowCount /= 2;
                 sampleOffset = (int)((samples.Length - windowSize) / (double)(windowCount - 1));
             }
             if (windowOrder == 4)
             {
                 throw new ArgumentException("Clip too short to evaluate");
             }
             if (maxFreq == double.PositiveInfinity)
             {
                 //Default MaxFrequency to be determined by the size of the window
                 maxFreq = FrequencyDomain.GetComplexSampleFrequency(windowSize, windowSize / 2);
             }
             //Limit Max Frquency by the size of the window
             maxFreq = Math.Min(maxFreq, FrequencyDomain.GetComplexSampleFrequency(windowSize, windowSize / 2));
             //Limit Min Frequency by the
             minFreq = Math.Max(minFreq, FrequencyDomain.GetComplexSampleFrequency(windowSize, 1));
             //Our output will be just the real-valued amplitudes
             SpectralDecomp decomp = new SpectralDecomp(minFreq, maxFreq, windowSize, windowCount);
             Complex64[] fftBuffer = new Complex64[windowSize];
             IBGCEnvelopeStream hammingWindow = new EnvelopeConcatenator(
                 CosineEnvelope.HammingWindow(windowSize / 2, true),
                 CosineEnvelope.HammingWindow(windowSize / 2, false));
             for (int window = 0; window < windowCount; window++)
             {
                 int specificOffset = sampleOffset * window;
                 hammingWindow.Reset();
                 //Copy samples into buffer
                 for (int i = 0; i < windowSize; i++)
                 {
                     //Set real value
                     fftBuffer[i] = samples[specificOffset + i] * hammingWindow.ReadNextSample();
                 }
                 Fourier.Forward(fftBuffer);
                 decomp.Add(window, fftBuffer);
             }
             return decomp;
         }
The documentation for this class was generated from the following file:
Audio/Spectrogram/Spectrogram.cs