BGC Tools: BGC.StateMachine.State Class Reference
BGC.StateMachine.State Class Reference abstract
This class is implemented by states that are use din game. It comes with access to state machine related functions once it has been added to the machine. Users must implement OnEnter and OnExit. Users can override Update if they have a function they want to call on a frame by frame basis.
Public Member Functions
State ()
Create a state with the default name
State (string name)
Create a state with a custom name rather than the default
void OnEnter ()
Called when the state is entered
void OnExit ()
Called when the state is exited, before the next state is entered
virtual void Update ()
This can be called every frame or whenever for complex states that have behavior on a frame by X basis.
void SetVerbose (bool isVerbose)
Set whether the state machine is verbose or not
Protected Member Functions
abstract void OnStateEnter ()
Called when the state is entered
virtual void OnStateExit ()
Called when the state is exited before the next state is entered
Protected Attributes
virtual string DefaultName => "State"
Properties
string Name [get, private set]
Name of the state. This will either be user defined or the default state name depending on the constructor used
Private Attributes
bool verbose = false
Detailed Description
This class is implemented by states that are use din game. It comes with access to state machine related functions once it has been added to the machine. Users must implement OnEnter and OnExit. Users can override Update if they have a function they want to call on a frame by frame basis.
Definition at line 13 of file State.cs.
Constructor & Destructor Documentation
State() [1/2]
BGC.StateMachine.State.State () inline
Create a state with the default name
Definition at line 28 of file State.cs.
         {
             Debug.Assert(!string.IsNullOrEmpty(DefaultName));
             Name = DefaultName;
         }
State() [2/2]
BGC.StateMachine.State.State (string name) inline
Create a state with a custom name rather than the default
Definition at line 37 of file State.cs.
         {
             Debug.Assert(!string.IsNullOrEmpty(name));
             Name = name;
         }
Member Function Documentation
OnEnter()
void BGC.StateMachine.State.OnEnter () inline
Called when the state is entered
Definition at line 46 of file State.cs.
Referenced by BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >.ExecuteTransitions(), and BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >.Update().
         {
             if (verbose)
             {
                 Debug.Log($"{Name} entered.");
             }
             OnStateEnter();
         }
OnExit()
void BGC.StateMachine.State.OnExit () inline
Called when the state is exited, before the next state is entered
Definition at line 59 of file State.cs.
         {
             if (verbose)
             {
                 Debug.Log($"{Name} left.");
             }
             OnStateExit();
         }
OnStateEnter()
abstract void BGC.StateMachine.State.OnStateEnter () protected pure virtual
Called when the state is entered
Implemented in BGC.StateMachine.TriggeringUpdatingLambdaState< TTriggerEnum >, BGC.StateMachine.UpdatingLambdaState< TBoolEnum, TTriggerEnum >, BGC.StateMachine.TriggeringLambdaState< TTriggerEnum >, BGC.StateMachine.LambdaState, and BGC.StateMachine.EmptyState.
OnStateExit()
virtual void BGC.StateMachine.State.OnStateExit () inline protected virtual
Called when the state is exited before the next state is entered
Reimplemented in BGC.StateMachine.TriggeringUpdatingLambdaState< TTriggerEnum >, BGC.StateMachine.TriggeringLambdaState< TTriggerEnum >, BGC.StateMachine.UpdatingLambdaState< TBoolEnum, TTriggerEnum >, and BGC.StateMachine.LambdaState.
Definition at line 77 of file State.cs.
 { }
SetVerbose()
void BGC.StateMachine.State.SetVerbose (bool isVerbose) inline
Set whether the state machine is verbose or not
Parameters
isVerbose
Definition at line 90 of file State.cs.
Referenced by BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >.AddState().
         {
             verbose = isVerbose;
         }
Update()
virtual void BGC.StateMachine.State.Update () inline virtual
This can be called every frame or whenever for complex states that have behavior on a frame by X basis.
Reimplemented in BGC.StateMachine.TriggeringUpdatingLambdaState< TTriggerEnum >, and BGC.StateMachine.UpdatingLambdaState< TBoolEnum, TTriggerEnum >.
Definition at line 83 of file State.cs.
 { }
Field Documentation
DefaultName
virtual string BGC.StateMachine.State.DefaultName => "State" protected
Definition at line 15 of file State.cs.
verbose
bool BGC.StateMachine.State.verbose = false private
Definition at line 16 of file State.cs.
Property Documentation
Name
string BGC.StateMachine.State.Name get private set
Name of the state. This will either be user defined or the default state name depending on the constructor used
Definition at line 23 of file State.cs.
The documentation for this class was generated from the following file:
StateMachine/State.cs