BGC Tools: BGC.Audio.Midi.Events.ControllerMidiEvent Class Reference
BGC.Audio.Midi.Events.ControllerMidiEvent Class Reference
A Midi event that is sent when a controller other than a key (e.g. a pedal, wheel, etc) is moved in order to modify the sound of a note (e.g. modulation, sustain, etc) Midi 1.0 Detailed Specification 4.2 - p.11
Public Types
enum ChannelModeMessageTypes {
ChannelModeMessageTypes.BankSelect_MSB = 0x00, ChannelModeMessageTypes.Modulation_MSB = 0x01, ChannelModeMessageTypes.BreathController_MSB = 0x02, ChannelModeMessageTypes.Undefined_01_MSB = 0x03,
ChannelModeMessageTypes.FootController_MSB = 0x04, ChannelModeMessageTypes.PortamentoTime_MSB = 0x05, ChannelModeMessageTypes.DataEntry_MSB = 0x06, ChannelModeMessageTypes.ChannelVolume_MSB = 0x07,
ChannelModeMessageTypes.Balance_MSB = 0x08, ChannelModeMessageTypes.Undefined_02_MSB = 0x09, ChannelModeMessageTypes.Pan_MSB = 0x0A, ChannelModeMessageTypes.ExpressionController_MSB = 0x0B,
ChannelModeMessageTypes.EffectControl_01_MSB = 0x0C, ChannelModeMessageTypes.EffectControl_02_MSB = 0x0D, ChannelModeMessageTypes.Undefined_03_MSB = 0x0E, ChannelModeMessageTypes.Undefined_04_MSB = 0x0F,
ChannelModeMessageTypes.GeneralPurposeController_01_MSB = 0x10, ChannelModeMessageTypes.GeneralPurposeController_02_MSB = 0x11, ChannelModeMessageTypes.GeneralPurposeController_03_MSB = 0x12, ChannelModeMessageTypes.GeneralPurposeController_04_MSB = 0x13,
ChannelModeMessageTypes.Undefined_05_MSB = 0x14, ChannelModeMessageTypes.Undefined_06_MSB = 0x15, ChannelModeMessageTypes.Undefined_07_MSB = 0x16, ChannelModeMessageTypes.Undefined_08_MSB = 0x17,
ChannelModeMessageTypes.Undefined_09_MSB = 0x18, ChannelModeMessageTypes.Undefined_0A_MSB = 0x19, ChannelModeMessageTypes.Undefined_0B_MSB = 0x1A, ChannelModeMessageTypes.Undefined_0C_MSB = 0x1B,
ChannelModeMessageTypes.Undefined_0D_MSB = 0x1C, ChannelModeMessageTypes.Undefined_0E_MSB = 0x1D, ChannelModeMessageTypes.Undefined_0F_MSB = 0x1E, ChannelModeMessageTypes.Undefined_10_MSB = 0x1F,
ChannelModeMessageTypes.BankSelect_LSB = 0x20, ChannelModeMessageTypes.Modulation_LSB = 0x21, ChannelModeMessageTypes.BreathController_LSB = 0x22, ChannelModeMessageTypes.Undefined_01_LSB = 0x23,
ChannelModeMessageTypes.FootController_LSB = 0x24, ChannelModeMessageTypes.PortamentoTime_LSB = 0x25, ChannelModeMessageTypes.DataEntry_LSB = 0x26, ChannelModeMessageTypes.ChannelVolume_LSB = 0x27,
ChannelModeMessageTypes.Balance_LSB = 0x28, ChannelModeMessageTypes.Undefined_02_LSB = 0x29, ChannelModeMessageTypes.Pan_LSB = 0x2A, ChannelModeMessageTypes.ExpressionController_LSB = 0x2B,
ChannelModeMessageTypes.EffectControl_01_LSB = 0x2C, ChannelModeMessageTypes.EffectControl_02_LSB = 0x2D, ChannelModeMessageTypes.Undefined_03_LSB = 0x2E, ChannelModeMessageTypes.Undefined_04_LSB = 0x2F,
ChannelModeMessageTypes.GeneralPurposeController_01_LSB = 0x30, ChannelModeMessageTypes.GeneralPurposeController_02_LSB = 0x31, ChannelModeMessageTypes.GeneralPurposeController_03_LSB = 0x32, ChannelModeMessageTypes.GeneralPurposeController_04_LSB = 0x33,
ChannelModeMessageTypes.Undefined_05_LSB = 0x34, ChannelModeMessageTypes.Undefined_06_LSB = 0x35, ChannelModeMessageTypes.Undefined_07_LSB = 0x36, ChannelModeMessageTypes.Undefined_08_LSB = 0x37,
ChannelModeMessageTypes.Undefined_09_LSB = 0x38, ChannelModeMessageTypes.Undefined_0A_LSB = 0x39, ChannelModeMessageTypes.Undefined_0B_LSB = 0x3A, ChannelModeMessageTypes.Undefined_0C_LSB = 0x3B,
ChannelModeMessageTypes.Undefined_0D_LSB = 0x3C, ChannelModeMessageTypes.Undefined_0E_LSB = 0x3D, ChannelModeMessageTypes.Undefined_0F_LSB = 0x3E, ChannelModeMessageTypes.Undefined_10_LSB = 0x3F,
ChannelModeMessageTypes.SustainPedal = 0x40, ChannelModeMessageTypes.PortamentoToggle = 0x41, ChannelModeMessageTypes.Sostenuto = 0x42, ChannelModeMessageTypes.SoftPedal = 0x43,
ChannelModeMessageTypes.LegatoFootswitch = 0x44, ChannelModeMessageTypes.Hold_02 = 0x45, ChannelModeMessageTypes.SoundController_01 = 0x46, ChannelModeMessageTypes.SoundController_02 = 0x47,
ChannelModeMessageTypes.SoundController_03 = 0x48, ChannelModeMessageTypes.SoundController_04 = 0x49, ChannelModeMessageTypes.SoundController_05 = 0x4A, ChannelModeMessageTypes.SoundController_06 = 0x4B,
ChannelModeMessageTypes.SoundController_07 = 0x4C, ChannelModeMessageTypes.SoundController_08 = 0x4D, ChannelModeMessageTypes.SoundController_09 = 0x4E, ChannelModeMessageTypes.SoundController_0A = 0x4F,
ChannelModeMessageTypes.GeneralPurposeController_05 = 0x50, ChannelModeMessageTypes.GeneralPurposeController_06 = 0x51, ChannelModeMessageTypes.GeneralPurposeController_07 = 0x52, ChannelModeMessageTypes.GeneralPurposeController_08 = 0x53,
ChannelModeMessageTypes.PortamentoControl = 0x54, ChannelModeMessageTypes.Undefined_1A = 0x55, ChannelModeMessageTypes.Undefined_1B = 0x56, ChannelModeMessageTypes.Undefined_1C = 0x57,
ChannelModeMessageTypes.Undefined_1D = 0x58, ChannelModeMessageTypes.Undefined_1E = 0x59, ChannelModeMessageTypes.Undefined_1F = 0x5A, ChannelModeMessageTypes.Effects_01_Depth = 0x5B,
ChannelModeMessageTypes.Effects_02_Depth = 0x5C, ChannelModeMessageTypes.Effects_03_Depth = 0x5D, ChannelModeMessageTypes.Effects_04_Depth = 0x5E, ChannelModeMessageTypes.Effects_05_Depth = 0x5F,
ChannelModeMessageTypes.DataIncrement = 0x60, ChannelModeMessageTypes.DataDecrement = 0x61, ChannelModeMessageTypes.NonRegisteredParameterNumber_LSB = 0x62, ChannelModeMessageTypes.NonRegisteredParameterNumber_MSB = 0x63,
ChannelModeMessageTypes.RegisteredParameterNumber_LSB = 0x64, ChannelModeMessageTypes.RegisteredParameterNumber_MSB = 0x65, ChannelModeMessageTypes.Undefined_20 = 0x66, ChannelModeMessageTypes.Undefined_21 = 0x67,
ChannelModeMessageTypes.Undefined_22 = 0x68, ChannelModeMessageTypes.Undefined_23 = 0x69, ChannelModeMessageTypes.Undefined_24 = 0x6A, ChannelModeMessageTypes.Undefined_25 = 0x6B,
ChannelModeMessageTypes.Undefined_26 = 0x6C, ChannelModeMessageTypes.Undefined_27 = 0x6D, ChannelModeMessageTypes.Undefined_28 = 0x6E, ChannelModeMessageTypes.Undefined_29 = 0x6F,
ChannelModeMessageTypes.Undefined_2A = 0x70, ChannelModeMessageTypes.Undefined_2B = 0x71, ChannelModeMessageTypes.Undefined_2C = 0x72, ChannelModeMessageTypes.Undefined_2D = 0x73,
ChannelModeMessageTypes.Undefined_2E = 0x74, ChannelModeMessageTypes.Undefined_2F = 0x75, ChannelModeMessageTypes.Undefined_30 = 0x76, ChannelModeMessageTypes.Undefined_31 = 0x77,
ChannelModeMessageTypes.AllSoundOff = 0x78, ChannelModeMessageTypes.ResetAll = 0x79, ChannelModeMessageTypes.LocalControl = 0x7A, ChannelModeMessageTypes.AllNotesOff = 0x7B,
ChannelModeMessageTypes.OmniModeOff = 0x7C, ChannelModeMessageTypes.OmniModeOn = 0x7D, ChannelModeMessageTypes.MonoModeOn = 0x7E, ChannelModeMessageTypes.PolyModeOn = 0x7F
}
Documented in Midi 1.0 Detailed Specification 4.2, Table III
enum RegisteredParameters {
RegisteredParameters.PitchBendSensitivity = 0x0000, RegisteredParameters.FineTuning = 0x0001, RegisteredParameters.CoarseTuning = 0x0002, RegisteredParameters.TuningProgramSelect = 0x0003,
RegisteredParameters.TuningBankSelect = 0x0004
}
Combination of MSB and LSB from RegisteredParameterNumber message Documented in Midi 1.0 Detailed Specification 4.2, Table IIIa
Public Types inherited from BGC.Audio.Midi.Events.ChannelMidiEvent
enum ChannelEventType {
ChannelEventType.Note = 0, ChannelEventType.Controller, ChannelEventType.Program, ChannelEventType.ChannelPressure,
ChannelEventType.PitchBend, ChannelEventType.Mode
}
Public Types inherited from BGC.Audio.Midi.Events.MidiEvent
enum MidiMessageClass {
MidiMessageClass.ChannelEvent = 0, MidiMessageClass.SysexEvent, MidiMessageClass.SysCommEvent, MidiMessageClass.SysRTEvent,
MidiMessageClass.MetaEvent, MidiMessageClass.MAX
}
Public Member Functions
ControllerMidiEvent (int deltaTime, byte channel, byte controllerNumber, byte controllerValue)
ControllerMidiEvent (int deltaTime, ChannelModeMessageTypes channelModeMessageType, byte channel, byte value=0x00)
override string ToString ()
override void ExecuteEvent (MidiTrack track)
Public Member Functions inherited from BGC.Audio.Midi.Events.ChannelMidiEvent
ChannelMidiEvent (int deltaTime, byte eventCode)
Public Member Functions inherited from BGC.Audio.Midi.Events.MidiEvent
MidiEvent (int deltaTime, byte eventCode)
void Serialize (Stream outputStream, bool running)
override string ToString ()
Static Public Member Functions
static ControllerMidiEvent ParseControllerMidiEvent (int deltaTime, byte typeCode, byte dataA, byte dataB)
Static Public Member Functions inherited from BGC.Audio.Midi.Events.ChannelMidiEvent
static ChannelMidiEvent ParseChannelEvent (Stream inputStream, int deltaTime, byte eventCode, byte nextByte)
Static Public Member Functions inherited from BGC.Audio.Midi.Events.MidiEvent
static MidiEvent ParseEvent (Stream inputStream, int deltaTime, byte eventCode, byte nextByte)
Data Fields
override string EventName => $"Control({ModeMessageType})"
override ChannelEventType EventType => ChannelEventType.Controller
override int Length => base.Length + 2
readonly byte channel
readonly byte dataA
readonly byte dataB
ChannelModeMessageTypes ModeMessageType => (ChannelModeMessageTypes)dataA
Data Fields inherited from BGC.Audio.Midi.Events.ChannelMidiEvent
override MidiMessageClass MessageClass => MidiMessageClass.ChannelEvent
Data Fields inherited from BGC.Audio.Midi.Events.MidiEvent
int time
int deltaTime
readonly byte eventCode
virtual bool Essential => true
virtual int Length => deltaTime.GetVarQuantitySize()
Protected Member Functions
override void Serialize (Stream outputStream)
Additional Inherited Members
Properties inherited from BGC.Audio.Midi.Events.ChannelMidiEvent
abstract ChannelEventType EventType [get]
Properties inherited from BGC.Audio.Midi.Events.MidiEvent
abstract string EventName [get]
abstract MidiMessageClass MessageClass [get]
Detailed Description
A Midi event that is sent when a controller other than a key (e.g. a pedal, wheel, etc) is moved in order to modify the sound of a note (e.g. modulation, sustain, etc) Midi 1.0 Detailed Specification 4.2 - p.11
Definition at line 11 of file ControllerMidiEvent.cs.
Member Enumeration Documentation
ChannelModeMessageTypes
enum BGC.Audio.Midi.Events.ControllerMidiEvent.ChannelModeMessageTypes strong
Documented in Midi 1.0 Detailed Specification 4.2, Table III
Enumerator
BankSelect_MSB
Modulation_MSB
BreathController_MSB
Undefined_01_MSB
FootController_MSB
PortamentoTime_MSB
DataEntry_MSB
ChannelVolume_MSB
Balance_MSB
Undefined_02_MSB
Pan_MSB
ExpressionController_MSB
EffectControl_01_MSB
EffectControl_02_MSB
Undefined_03_MSB
Undefined_04_MSB
GeneralPurposeController_01_MSB
GeneralPurposeController_02_MSB
GeneralPurposeController_03_MSB
GeneralPurposeController_04_MSB
Undefined_05_MSB
Undefined_06_MSB
Undefined_07_MSB
Undefined_08_MSB
Undefined_09_MSB
Undefined_0A_MSB
Undefined_0B_MSB
Undefined_0C_MSB
Undefined_0D_MSB
Undefined_0E_MSB
Undefined_0F_MSB
Undefined_10_MSB
BankSelect_LSB
Modulation_LSB
BreathController_LSB
Undefined_01_LSB
FootController_LSB
PortamentoTime_LSB
DataEntry_LSB
ChannelVolume_LSB
Balance_LSB
Undefined_02_LSB
Pan_LSB
ExpressionController_LSB
EffectControl_01_LSB
EffectControl_02_LSB
Undefined_03_LSB
Undefined_04_LSB
GeneralPurposeController_01_LSB
GeneralPurposeController_02_LSB
GeneralPurposeController_03_LSB
GeneralPurposeController_04_LSB
Undefined_05_LSB
Undefined_06_LSB
Undefined_07_LSB
Undefined_08_LSB
Undefined_09_LSB
Undefined_0A_LSB
Undefined_0B_LSB
Undefined_0C_LSB
Undefined_0D_LSB
Undefined_0E_LSB
Undefined_0F_LSB
Undefined_10_LSB
SustainPedal
PortamentoToggle
Sostenuto
SoftPedal
LegatoFootswitch
Hold_02
SoundController_01
SoundController_02
SoundController_03
SoundController_04
SoundController_05
SoundController_06
SoundController_07
SoundController_08
SoundController_09
SoundController_0A
GeneralPurposeController_05
GeneralPurposeController_06
GeneralPurposeController_07
GeneralPurposeController_08
PortamentoControl
Undefined_1A
Undefined_1B
Undefined_1C
Undefined_1D
Undefined_1E
Undefined_1F
Effects_01_Depth
Effects_02_Depth
Effects_03_Depth
Effects_04_Depth
Effects_05_Depth
DataIncrement
DataDecrement
NonRegisteredParameterNumber_LSB
NonRegisteredParameterNumber_MSB
RegisteredParameterNumber_LSB
RegisteredParameterNumber_MSB
Undefined_20
Undefined_21
Undefined_22
Undefined_23
Undefined_24
Undefined_25
Undefined_26
Undefined_27
Undefined_28
Undefined_29
Undefined_2A
Undefined_2B
Undefined_2C
Undefined_2D
Undefined_2E
Undefined_2F
Undefined_30
Undefined_31
AllSoundOff
ResetAll
LocalControl
AllNotesOff
OmniModeOff
OmniModeOn
MonoModeOn
PolyModeOn
Definition at line 16 of file ControllerMidiEvent.cs.
         {
             //
             // MSB of most continuous Controller data
             // [0x00, 0x1F]
             //
             BankSelect_MSB = 0x00,
             Modulation_MSB = 0x01,
             BreathController_MSB = 0x02,
             Undefined_01_MSB = 0x03,
             FootController_MSB = 0x04,
             PortamentoTime_MSB = 0x05,
             DataEntry_MSB = 0x06,
             ChannelVolume_MSB = 0x07,
             Balance_MSB = 0x08,
             Undefined_02_MSB = 0x09,
             Pan_MSB = 0x0A,
             ExpressionController_MSB = 0x0B,
             EffectControl_01_MSB = 0x0C,
             EffectControl_02_MSB = 0x0D,
             Undefined_03_MSB = 0x0E,
             Undefined_04_MSB = 0x0F,
             GeneralPurposeController_01_MSB = 0x10,
             GeneralPurposeController_02_MSB = 0x11,
             GeneralPurposeController_03_MSB = 0x12,
             GeneralPurposeController_04_MSB = 0x13,
             Undefined_05_MSB = 0x14,
             Undefined_06_MSB = 0x15,
             Undefined_07_MSB = 0x16,
             Undefined_08_MSB = 0x17,
             Undefined_09_MSB = 0x18,
             Undefined_0A_MSB = 0x19,
             Undefined_0B_MSB = 0x1A,
             Undefined_0C_MSB = 0x1B,
             Undefined_0D_MSB = 0x1C,
             Undefined_0E_MSB = 0x1D,
             Undefined_0F_MSB = 0x1E,
             Undefined_10_MSB = 0x1F,
             //
             // LSB for controllers 0 through 31
             // [0x20, 0x3F]
             //
             BankSelect_LSB = 0x20,
             Modulation_LSB = 0x21,
             BreathController_LSB = 0x22,
             Undefined_01_LSB = 0x23,
             FootController_LSB = 0x24,
             PortamentoTime_LSB = 0x25,
             DataEntry_LSB = 0x26,
             ChannelVolume_LSB = 0x27,
             Balance_LSB = 0x28,
             Undefined_02_LSB = 0x29,
             Pan_LSB = 0x2A,
             ExpressionController_LSB = 0x2B,
             EffectControl_01_LSB = 0x2C,
             EffectControl_02_LSB = 0x2D,
             Undefined_03_LSB = 0x2E,
             Undefined_04_LSB = 0x2F,
             GeneralPurposeController_01_LSB = 0x30,
             GeneralPurposeController_02_LSB = 0x31,
             GeneralPurposeController_03_LSB = 0x32,
             GeneralPurposeController_04_LSB = 0x33,
             Undefined_05_LSB = 0x34,
             Undefined_06_LSB = 0x35,
             Undefined_07_LSB = 0x36,
             Undefined_08_LSB = 0x37,
             Undefined_09_LSB = 0x38,
             Undefined_0A_LSB = 0x39,
             Undefined_0B_LSB = 0x3A,
             Undefined_0C_LSB = 0x3B,
             Undefined_0D_LSB = 0x3C,
             Undefined_0E_LSB = 0x3D,
             Undefined_0F_LSB = 0x3E,
             Undefined_10_LSB = 0x3F,
             //
             // Single-byte controllers
             // [0x40, 0x5F]
             //
             SustainPedal = 0x40,
             PortamentoToggle = 0x41,
             Sostenuto = 0x42,
             SoftPedal = 0x43,
             LegatoFootswitch = 0x44,
             Hold_02 = 0x45,
             SoundController_01 = 0x46, //Default: SoundVariation
             SoundController_02 = 0x47, //Default: Timbre
             SoundController_03 = 0x48, //Default: ReleaseTime
             SoundController_04 = 0x49, //Default: AttackTime
             SoundController_05 = 0x4A, //Default: Brightness
             SoundController_06 = 0x4B, //Default: None
             SoundController_07 = 0x4C, //Default: None
             SoundController_08 = 0x4D, //Default: None
             SoundController_09 = 0x4E, //Default: None
             SoundController_0A = 0x4F, //Default: None
             GeneralPurposeController_05 = 0x50,
             GeneralPurposeController_06 = 0x51,
             GeneralPurposeController_07 = 0x52,
             GeneralPurposeController_08 = 0x53,
             PortamentoControl = 0x54,
             Undefined_1A = 0x55,
             Undefined_1B = 0x56,
             Undefined_1C = 0x57,
             Undefined_1D = 0x58,
             Undefined_1E = 0x59,
             Undefined_1F = 0x5A,
             Effects_01_Depth = 0x5B, //Formerly: External Effects Depth
             Effects_02_Depth = 0x5C, //Formerly: Tremolo Depth
             Effects_03_Depth = 0x5D, //Formerly: Chorus Depth
             Effects_04_Depth = 0x5E, //Formerly: Detune Depth
             Effects_05_Depth = 0x5F, //Formerly: Phaser Depth
             //
             // Increment/Decrement and Parameter Numbers
             // [0x60, 0x65]
             //
             DataIncrement = 0x60,
             DataDecrement = 0x61,
             NonRegisteredParameterNumber_LSB = 0x62,
             NonRegisteredParameterNumber_MSB = 0x63,
             RegisteredParameterNumber_LSB = 0x64,
             RegisteredParameterNumber_MSB = 0x65,
             //
             // Undefined single-byte controllers
             // [0x66, 0x77]
             //
             Undefined_20 = 0x66,
             Undefined_21 = 0x67,
             Undefined_22 = 0x68,
             Undefined_23 = 0x69,
             Undefined_24 = 0x6A,
             Undefined_25 = 0x6B,
             Undefined_26 = 0x6C,
             Undefined_27 = 0x6D,
             Undefined_28 = 0x6E,
             Undefined_29 = 0x6F,
             Undefined_2A = 0x70,
             Undefined_2B = 0x71,
             Undefined_2C = 0x72,
             Undefined_2D = 0x73,
             Undefined_2E = 0x74,
             Undefined_2F = 0x75,
             Undefined_30 = 0x76,
             Undefined_31 = 0x77,
             //
             // Channel Mode Messages
             // [0x78, 0x7F]
             //
             AllSoundOff = 0x78,
             ResetAll = 0x79,
             LocalControl = 0x7A,
             AllNotesOff = 0x7B,
             OmniModeOff = 0x7C,
             OmniModeOn = 0x7D,
             MonoModeOn = 0x7E,
             PolyModeOn = 0x7F
         }
RegisteredParameters
enum BGC.Audio.Midi.Events.ControllerMidiEvent.RegisteredParameters strong
Combination of MSB and LSB from RegisteredParameterNumber message Documented in Midi 1.0 Detailed Specification 4.2, Table IIIa
Enumerator
PitchBendSensitivity
FineTuning
CoarseTuning
TuningProgramSelect
TuningBankSelect
Definition at line 182 of file ControllerMidiEvent.cs.
         {
             PitchBendSensitivity = 0x0000,
             FineTuning = 0x0001,
             CoarseTuning = 0x0002,
             TuningProgramSelect = 0x0003,
             TuningBankSelect = 0x0004
         }
Constructor & Destructor Documentation
ControllerMidiEvent() [1/2]
BGC.Audio.Midi.Events.ControllerMidiEvent.ControllerMidiEvent (int deltaTime, byte channel, byte controllerNumber, byte controllerValue) inline
Definition at line 202 of file ControllerMidiEvent.cs.
             : base(deltaTime, (byte)(0xB0 | channel))
         {
             this.channel = channel;
             dataA = controllerNumber;
             dataB = controllerValue;
         }
ControllerMidiEvent() [2/2]
BGC.Audio.Midi.Events.ControllerMidiEvent.ControllerMidiEvent (int deltaTime, ChannelModeMessageTypes channelModeMessageType, byte channel, byte value = 0x00) inline
Definition at line 214 of file ControllerMidiEvent.cs.
             : base(deltaTime, (byte)(0xB0 | channel))
         {
             this.channel = channel;
             dataA = (byte)channelModeMessageType;
             dataB = value;
         }
Member Function Documentation
ExecuteEvent()
override void BGC.Audio.Midi.Events.ControllerMidiEvent.ExecuteEvent (MidiTrack track) virtual
Implements BGC.Audio.Midi.Events.MidiEvent.
ParseControllerMidiEvent()
static ControllerMidiEvent BGC.Audio.Midi.Events.ControllerMidiEvent.ParseControllerMidiEvent (int deltaTime, byte typeCode, byte dataA, byte dataB) inline static
Definition at line 226 of file ControllerMidiEvent.cs.
Referenced by BGC.Audio.Midi.Events.ChannelMidiEvent.ParseChannelEvent().
         {
             return new ControllerMidiEvent(deltaTime, (byte)(typeCode & 0b1111), dataA, dataB);
         }
Serialize()
override void BGC.Audio.Midi.Events.ControllerMidiEvent.Serialize (Stream outputStream) inline protected virtual
Reimplemented from BGC.Audio.Midi.Events.ChannelMidiEvent.
Definition at line 235 of file ControllerMidiEvent.cs.
References BGC.Audio.Midi.MidiTrack.ExecuteRunningEvent().
         {
             base.Serialize(outputStream);
             outputStream.WriteByte(dataA);
             outputStream.WriteByte(dataB);
         }
ToString()
override string BGC.Audio.Midi.Events.ControllerMidiEvent.ToString ()
Field Documentation
channel
readonly byte BGC.Audio.Midi.Events.ControllerMidiEvent.channel
Definition at line 196 of file ControllerMidiEvent.cs.
dataA
readonly byte BGC.Audio.Midi.Events.ControllerMidiEvent.dataA
Definition at line 197 of file ControllerMidiEvent.cs.
dataB
readonly byte BGC.Audio.Midi.Events.ControllerMidiEvent.dataB
Definition at line 198 of file ControllerMidiEvent.cs.
EventName
override string BGC.Audio.Midi.Events.ControllerMidiEvent.EventName => $"Control({ModeMessageType})"
Definition at line 192 of file ControllerMidiEvent.cs.
EventType
override ChannelEventType BGC.Audio.Midi.Events.ControllerMidiEvent.EventType => ChannelEventType.Controller
Definition at line 193 of file ControllerMidiEvent.cs.
Length
override int BGC.Audio.Midi.Events.ControllerMidiEvent.Length => base.Length + 2
Definition at line 194 of file ControllerMidiEvent.cs.
ModeMessageType
ChannelModeMessageTypes BGC.Audio.Midi.Events.ControllerMidiEvent.ModeMessageType => (ChannelModeMessageTypes)dataA
Definition at line 200 of file ControllerMidiEvent.cs.
Referenced by BGC.Audio.Midi.MidiTrack.ExecuteRunningEvent().
The documentation for this class was generated from the following file:
Audio/Midi/Events/ControllerMidiEvent.cs