BGC Tools: BGC.Audio.Synthesis.STMAudioClip Class Reference
BGC.Audio.Synthesis.STMAudioClip Class Reference
Spectrotemporally modulated noise with the specified duration. AKA Ripples.
Public Types
enum RippleDirection { RippleDirection.Up = 0, RippleDirection.Down, RippleDirection.MAX }
enum AmplitudeDistribution {
AmplitudeDistribution.Violet = 0, AmplitudeDistribution.Blue, AmplitudeDistribution.White, AmplitudeDistribution.Pink,
AmplitudeDistribution.Brown, AmplitudeDistribution.MAX
}
Public Member Functions
delegate IEnumerable< ComplexCarrierTone > SideBandGenerator (double modulationDepth, ComplexCarrierTone carrierTone, Dictionary< int, double > sidebandAmplitudeCache, double modulationRate, double spectralPhase)
STMAudioClip (double duration, double freqLB, double freqUB, int frequencyCount, double modulationDepth, double spectralModulationRate, double temporalModulationRate, RippleDirection rippleDirection, AmplitudeDistribution distribution, Random randomizer=null)
STMAudioClip (double duration, IEnumerable< ComplexCarrierTone > carrierTones, double modulationDepth, double spectralModulationRate, double temporalModulationRate, SideBandGenerator sideBandGenerator, Random randomizer=null)
override int Read (float[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
override void Reset ()
Sets this internal state of this stream to the initial state
override void Seek (int position)
Seek to the indicated position in the stream
override IEnumerable< double > GetChannelRMS ()
The RMS amplitude of each channel
Public Member Functions inherited from BGC.Audio.BGCStream
void Initialize ()
Perform any calculations necessary to prepare the Stream
Data Fields
override int Channels => 1
override int TotalSamples => ChannelSamples
override int ChannelSamples => _channelSamples
Data Fields inherited from BGC.Audio.BGCAudioClip
float Duration => ChannelSamples / SamplingRate
override float SamplingRate => 44100f
Protected Member Functions
override void _Initialize ()
Private Member Functions
IEnumerable< ComplexCarrierTone > CreateSideBands (double freqLB, double freqUB, int count, AmplitudeDistribution distribution)
double GetFactor (AmplitudeDistribution amplitudeDistribution, double frequency)
IEnumerable< ComplexCarrierTone > ExpCarrierToneSideBands (double depth, ComplexCarrierTone carrierTone, Dictionary< int, double > sideBandAmplitudeCache, double modulationRate, double spectralPhase)
double GetExpBandAmplitude (double depth, Dictionary< int, double > sideBandAmplitudeCache, int band)
Static Private Member Functions
static double GetBandPhase (int band)
Private Attributes
int _channelSamples
readonly Random randomizer
readonly Bessel.DoubleBesselCache besselCache = new Bessel.DoubleBesselCache()
readonly Dictionary< int, double > sideBandAmplitudes = new Dictionary<int, double>()
readonly double modulationDepth
readonly double spectralModulationRate
readonly double temporalModulationRate
readonly IEnumerable< ComplexCarrierTone > carrierToneGenerator
readonly SideBandGenerator sideBandGenerator
Complex64[] fftBuffer = null
int position = 0
Additional Inherited Members
Protected Attributes inherited from BGC.Audio.BGCStream
bool initialized = false
Properties inherited from BGC.Audio.BGCStream
abstract int Channels [get]
abstract int TotalSamples [get]
abstract int ChannelSamples [get]
abstract float SamplingRate [get]
Properties inherited from BGC.Audio.IBGCStream
int Channels [get]
The number of underlying Channels of this BGCStream
int TotalSamples [get]
The total number of Samples of this BGCStream
int ChannelSamples [get]
The number of Samples of each channel for this BGCStream
float SamplingRate [get]
The sampling rate of the Stream
Detailed Description
Spectrotemporally modulated noise with the specified duration. AKA Ripples.
Definition at line 12 of file STMAudioClip.cs.
Member Enumeration Documentation
enum BGC.Audio.Synthesis.STMAudioClip.AmplitudeDistribution strong
Enumerator
Violet
Blue
White
Pink
Brown
MAX
Definition at line 21 of file STMAudioClip.cs.
         {
             Violet = 0,
             Blue,
             White,
             Pink,
             Brown,
             MAX
         }
enum BGC.Audio.Synthesis.STMAudioClip.RippleDirection strong
Enumerator
Up
Down
MAX
Definition at line 14 of file STMAudioClip.cs.
         {
             Up = 0,
             Down,
             MAX
         }
Constructor & Destructor Documentation
BGC.Audio.Synthesis.STMAudioClip.STMAudioClip (double duration, double freqLB, double freqUB, int frequencyCount, double modulationDepth, double spectralModulationRate, double temporalModulationRate, RippleDirection rippleDirection, AmplitudeDistribution distribution, Random randomizer = null) inline
Definition at line 56 of file STMAudioClip.cs.
References BGC.Mathematics.CustomRandom.Next().
         {
             if (randomizer == null)
             {
                 randomizer = new Random(CustomRandom.Next());
             }
             this.randomizer = randomizer;
             carrierToneGenerator = CreateSideBands(freqLB, freqUB, frequencyCount, distribution);
             sideBandGenerator = ExpCarrierToneSideBands;
             this.modulationDepth = modulationDepth;
             this.temporalModulationRate = temporalModulationRate;
             switch (rippleDirection)
             {
                 case RippleDirection.Up:
                     this.spectralModulationRate = spectralModulationRate;
                     break;
                 case RippleDirection.Down:
                     this.spectralModulationRate = -spectralModulationRate;
                     break;
                 default:
                     UnityEngine.Debug.LogError($"Unexpected RippleDirection: {rippleDirection}");
                     break;
             }
             _channelSamples = (int)Math.Ceiling(duration * SamplingRate);
         }
BGC.Audio.Synthesis.STMAudioClip.STMAudioClip (double duration, IEnumerable< ComplexCarrierTone > carrierTones, double modulationDepth, double spectralModulationRate, double temporalModulationRate, SideBandGenerator sideBandGenerator, Random randomizer = null) inline
Definition at line 98 of file STMAudioClip.cs.
References BGC.Mathematics.CustomRandom.Next().
         {
             if (randomizer == null)
             {
                 randomizer = new Random(CustomRandom.Next());
             }
             this.randomizer = randomizer;
             carrierToneGenerator = carrierTones;
             this.sideBandGenerator = sideBandGenerator;
             this.modulationDepth = modulationDepth;
             this.temporalModulationRate = temporalModulationRate;
             this.spectralModulationRate = spectralModulationRate;
             _channelSamples = (int)Math.Ceiling(duration * SamplingRate);
         }
Member Function Documentation
override void BGC.Audio.Synthesis.STMAudioClip._Initialize () inline protected virtual
Reimplemented from BGC.Audio.BGCStream.
Definition at line 123 of file STMAudioClip.cs.
References BGC.Audio.ComplexCarrierTone.amplitude, BGC.Audio.ComplexCarrierTone.frequency, BGC.Mathematics.Fourier.Inverse(), BGC.Mathematics.Complex64.Log(), and BGC.Audio.FrequencyDomain.Populate().
         {
             int fftBufferSize = _channelSamples.CeilingToPowerOfTwo();
             fftBuffer = new Complex64[fftBufferSize];
             sideBandAmplitudes.Clear();
             double spectralModulatorTerm = -2.0 * Math.PI * spectralModulationRate / Math.Log(2.0);
             double spectralStartingPhase = 2.0 * Math.PI * randomizer.NextDouble();
             foreach (ComplexCarrierTone carrierBaseTone in carrierToneGenerator)
             {
                 foreach (ComplexCarrierTone sideBand in sideBandGenerator(
                     modulationDepth: modulationDepth,
                     carrierTone: carrierBaseTone,
                     sidebandAmplitudeCache: sideBandAmplitudes,
                     modulationRate: temporalModulationRate,
                     spectralPhase: spectralStartingPhase + spectralModulatorTerm * Math.Log(carrierBaseTone.frequency)))
                 {
                     FrequencyDomain.Populate(
                         buffer: fftBuffer,
                         frequency: sideBand.frequency,
                         amplitude: sideBand.amplitude);
                 }
             }
             Fourier.Inverse(fftBuffer);
         }
IEnumerable<ComplexCarrierTone> BGC.Audio.Synthesis.STMAudioClip.CreateSideBands (double freqLB, double freqUB, int count, AmplitudeDistribution distribution) inline private
Definition at line 182 of file STMAudioClip.cs.
References BGC.Mathematics.Complex64.FromPolarCoordinates(), and BGC.Mathematics.CustomRandom.RayleighDistribution().
         {
             double freqRatio = Math.Pow((freqUB / freqLB), 1.0 / (count - 1.0));
             if (double.IsNaN(freqRatio) || double.IsInfinity(freqRatio))
             {
                 freqRatio = 1.0;
             }
             double freq = freqLB;
             for (int carrierTone = 0; carrierTone < count; carrierTone++)
             {
                 yield return new ComplexCarrierTone(frequency: freq,
                     amplitude: Complex64.FromPolarCoordinates(
                         magnitude: GetFactor(distribution, freq) * CustomRandom.RayleighDistribution(randomizer.NextDouble()),
                         phase: 2.0 * Math.PI * randomizer.NextDouble()));
                 freq *= freqRatio;
             }
         }
IEnumerable<ComplexCarrierTone> BGC.Audio.Synthesis.STMAudioClip.ExpCarrierToneSideBands (double depth, ComplexCarrierTone carrierTone, Dictionary< int, double > sideBandAmplitudeCache, double modulationRate, double spectralPhase) inline private
Definition at line 226 of file STMAudioClip.cs.
References BGC.Audio.ComplexCarrierTone.amplitude, BGC.Audio.ComplexCarrierTone.frequency, and BGC.Mathematics.Complex64.FromPolarCoordinates().
         {
             const int bandBounds = 5;
             for (int band = -1 * bandBounds; band <= bandBounds; band++)
             {
                 yield return new ComplexCarrierTone(
                     frequency: carrierTone.frequency + band * modulationRate,
                     amplitude: carrierTone.amplitude * Complex64.FromPolarCoordinates(
                         magnitude: GetExpBandAmplitude(depth, sideBandAmplitudeCache, band),
                         phase: band * spectralPhase + GetBandPhase(band)));
             }
         }
static double BGC.Audio.Synthesis.STMAudioClip.GetBandPhase (int band) inline static private
Definition at line 245 of file STMAudioClip.cs.
         {
             if (Math.Abs(band) % 2 == 1)
             {
                 //Add -pi/2 phase shift to odd bands
                 return -0.5 * Math.PI;
             }
             return 0.0;
         }
override IEnumerable<double> BGC.Audio.Synthesis.STMAudioClip.GetChannelRMS () virtual
The RMS amplitude of each channel
Implements BGC.Audio.BGCStream.
double BGC.Audio.Synthesis.STMAudioClip.GetExpBandAmplitude (double depth, Dictionary< int, double > sideBandAmplitudeCache, int band) inline private
Definition at line 256 of file STMAudioClip.cs.
References BGC.Mathematics.Bessel.Bessi().
         {
             if (sideBandAmplitudeCache.ContainsKey(band))
             {
                 return sideBandAmplitudeCache[band];
             }
             double amplitude;
             double argument = depth * Math.Log(10.0) / 20.0;
             if (band == 0)
             {
                 amplitude = Bessel.Bessi(
                     argument: argument,
                     order: 0,
                     cache: besselCache);
             }
             else if (Math.Abs(band) % 2 == 0)
             {
                 //Even
                 double sign = (Math.Abs(band) / 2) % 2 == 1 ? -1.0 : 1.0;
                 amplitude = sign * Bessel.Bessi(
                     argument: argument,
                     order: Math.Abs(band),
                     cache: besselCache);
             }
             else
             {
                 //Odd
                 double sign = ((Math.Abs(band) - 1) / 2) % 2 == 1 ? -1.0 : 1.0;
                 if (band > 0)
                 {
                     sign *= -1.0;
                 }
                 amplitude = sign * Bessel.Bessi(
                     argument: argument,
                     order: Math.Abs(band),
                     cache: besselCache);
             }
             sideBandAmplitudeCache[band] = amplitude;
             return amplitude;
         }
double BGC.Audio.Synthesis.STMAudioClip.GetFactor (AmplitudeDistribution amplitudeDistribution, double frequency) inline private
Definition at line 209 of file STMAudioClip.cs.
         {
             switch (amplitudeDistribution)
             {
                 case AmplitudeDistribution.Violet: return frequency * Math.Sqrt(frequency);
                 case AmplitudeDistribution.Blue: return frequency;
                 case AmplitudeDistribution.White: return Math.Sqrt(frequency);
                 case AmplitudeDistribution.Pink: return 1.0;
                 case AmplitudeDistribution.Brown: return 1.0 / Math.Sqrt(frequency);
                 case AmplitudeDistribution.MAX:
                 default:
                     UnityEngine.Debug.LogError($"Unexpected AmplitudeFactor: {amplitudeDistribution}");
                     return 1.0;
             }
         }
override int BGC.Audio.Synthesis.STMAudioClip.Read (float[] data, int offset, int count) inline virtual
Copy count samples into the Data buffer, starting at offset.
Returns
The number of samples copied
Implements BGC.Audio.BGCStream.
Definition at line 154 of file STMAudioClip.cs.
References BGC.Mathematics.GeneralMath.Clamp().
         {
             if (!initialized)
             {
                 Initialize();
             }
             //Read...
             int samplesToRead = Math.Min(count, _channelSamples - position);
             for (int i = 0; i < samplesToRead; i++)
             {
                 data[offset + i] = (float)fftBuffer[position + i].Real;
             }
             position += samplesToRead;
             return samplesToRead;
         }
override void BGC.Audio.Synthesis.STMAudioClip.Reset () virtual
Sets this internal state of this stream to the initial state
Implements BGC.Audio.BGCStream.
override void BGC.Audio.Synthesis.STMAudioClip.Seek (int position) virtual
Seek to the indicated position in the stream
Implements BGC.Audio.BGCStream.
delegate IEnumerable<ComplexCarrierTone> BGC.Audio.Synthesis.STMAudioClip.SideBandGenerator (double modulationDepth, ComplexCarrierTone carrierTone, Dictionary< int, double > sidebandAmplitudeCache, double modulationRate, double spectralPhase)
Field Documentation
int BGC.Audio.Synthesis.STMAudioClip._channelSamples private
Definition at line 35 of file STMAudioClip.cs.
readonly Bessel.DoubleBesselCache BGC.Audio.Synthesis.STMAudioClip.besselCache = new Bessel.DoubleBesselCache() private
Definition at line 40 of file STMAudioClip.cs.
readonly IEnumerable<ComplexCarrierTone> BGC.Audio.Synthesis.STMAudioClip.carrierToneGenerator private
Definition at line 47 of file STMAudioClip.cs.
override int BGC.Audio.Synthesis.STMAudioClip.Channels => 1
Definition at line 31 of file STMAudioClip.cs.
override int BGC.Audio.Synthesis.STMAudioClip.ChannelSamples => _channelSamples
Definition at line 36 of file STMAudioClip.cs.
Complex64 [] BGC.Audio.Synthesis.STMAudioClip.fftBuffer = null private
Definition at line 52 of file STMAudioClip.cs.
readonly double BGC.Audio.Synthesis.STMAudioClip.modulationDepth private
Definition at line 43 of file STMAudioClip.cs.
int BGC.Audio.Synthesis.STMAudioClip.position = 0 private
Definition at line 54 of file STMAudioClip.cs.
readonly Random BGC.Audio.Synthesis.STMAudioClip.randomizer private
Definition at line 38 of file STMAudioClip.cs.
readonly Dictionary<int, double> BGC.Audio.Synthesis.STMAudioClip.sideBandAmplitudes = new Dictionary<int, double>() private
Definition at line 41 of file STMAudioClip.cs.
readonly SideBandGenerator BGC.Audio.Synthesis.STMAudioClip.sideBandGenerator private
Definition at line 50 of file STMAudioClip.cs.
readonly double BGC.Audio.Synthesis.STMAudioClip.spectralModulationRate private
Definition at line 44 of file STMAudioClip.cs.
readonly double BGC.Audio.Synthesis.STMAudioClip.temporalModulationRate private
Definition at line 45 of file STMAudioClip.cs.
override int BGC.Audio.Synthesis.STMAudioClip.TotalSamples => ChannelSamples
Definition at line 33 of file STMAudioClip.cs.
The documentation for this class was generated from the following file:
Audio/Synthesis/STMAudioClip.cs