BGC Tools: BGC.DataStructures.EnumListContainer< TEnum > Class Template Reference
BGC.DataStructures.EnumListContainer< TEnum > Class Template Reference
A Serializeable List<EnumType> for 2D lists
Public Member Functions
EnumListContainer (List< int > list)
Constructor from raw int enum values
EnumListContainer (List< TEnum > list)
Constructor from List of enum values
EnumListContainer (JsonArray json)
Constructor from a JsonArray of Ints
EnumListContainer (JsonArray json, EnumSerialization serialization)
Constructor from a JsonArray of EnumStrings
EnumListContainer ()
Default constructor
void Add (TEnum element)
Adds an element of type TEnum to a list
bool Remove (TEnum element)
Removes an element of type TEnum from a list
bool Remove (EnumListContainer< TEnum > elc)
Remove all elements in another EnumListContainer Returns false if failed to remove one element
void Set (List< TEnum > list)
Set contained list
override bool Equals (object obj)
Check if two EnumListContainers are equal
override int GetHashCode ()
Returns HashCode
bool Contains (TEnum item)
Check if the list contains an item
new JsonArray Serialize ()
Serializes the list into a json array
Type GetEnumType ()
Returns the enum type
Public Member Functions inherited from BGC.DataStructures.IntListContainer
IntListContainer (List< int > list)
Constructor from a List
IntListContainer (JsonArray json)
Constructor from a JsonArray
IntListContainer ()
Default constructor
void Add (int element)
Adds an element to a list
void RemoveAt (int index)
Removes an element at specified index
bool Remove (int element)
Remove an element from a list
bool Remove (IntListContainer lw)
Remove all elements in another IntListContainer Returns false if failed to remove one element
void Set (List< int > list)
Set contained list
override bool Equals (object obj)
Check if two IntListContainers are equal
override int GetHashCode ()
Returns HashCode
void PrintSelf ()
Debug.Log to print out all values of the list
bool Contains (int item)
Check if the list Contains an item
JsonArray Serialize ()
Serializes the list into a json array
Data Fields
new EnumListContainer< TEnum > Clone => new EnumListContainer<TEnum>(new List<int>(list))
new TEnum RandomValue => (TEnum)Convert.ChangeType(list.RandomValue<int>(), typeof(TEnum))
Data Fields inherited from BGC.DataStructures.IntListContainer
List< int > list = new List<int>()
IntListContainer Clone => new IntListContainer(new List<int>(list))
int RandomValue => list.RandomValue<int>()
int Count => list.Count
Properties
new TEnum this[int i] [get, set]
Properties inherited from BGC.DataStructures.IntListContainer
int this[int i] [get, set]
Private Member Functions
void Deserialize (JsonArray array, EnumSerialization serialization)
Sets the list to a deserialized JsonArray
void CheckIfEnumType ()
Checks if the container is a valid enum type
Additional Inherited Members
Protected Member Functions inherited from BGC.DataStructures.IntListContainer
void Deserialize (JsonArray array)
Sets the list to a deserialized JsonArray
Detailed Description
A Serializeable List<EnumType> for 2D lists
Template Parameters
TEnum
Definition at line 15 of file EnumListContainer.cs.
Constructor & Destructor Documentation
BGC.DataStructures.EnumListContainer< TEnum >.EnumListContainer (List< int > list) inline
Constructor from raw int enum values
Parameters
list
Definition at line 36 of file EnumListContainer.cs.
 : base(list) { }
BGC.DataStructures.EnumListContainer< TEnum >.EnumListContainer (List< TEnum > list) inline
Constructor from List of enum values
Parameters
list
Definition at line 42 of file EnumListContainer.cs.
         {
             CheckIfEnumType();
             List<int> temp = new List<int>();
             for (int i = 0; i < list.Count; ++i)
             {
                 temp.Add((int)Convert.ChangeType(list[i], typeof(int)));
             }
             this.list = temp;
         }
BGC.DataStructures.EnumListContainer< TEnum >.EnumListContainer (JsonArray json) inline
Constructor from a JsonArray of Ints
Parameters
json
Definition at line 59 of file EnumListContainer.cs.
         {
             Deserialize(json);
         }
BGC.DataStructures.EnumListContainer< TEnum >.EnumListContainer (JsonArray json, EnumSerialization serialization) inline
Constructor from a JsonArray of EnumStrings
Parameters
json
serialization
Definition at line 69 of file EnumListContainer.cs.
         {
             Deserialize(json, serialization);
         }
BGC.DataStructures.EnumListContainer< TEnum >.EnumListContainer () inline
Default constructor
Definition at line 77 of file EnumListContainer.cs.
         {
             list = new List<int>();
         }
Member Function Documentation
void BGC.DataStructures.EnumListContainer< TEnum >.Add (TEnum element) inline
Adds an element of type TEnum to a list
Parameters
element
Definition at line 86 of file EnumListContainer.cs.
         {
             list.Add((int)Convert.ChangeType(element, typeof(int)));
         }
void BGC.DataStructures.EnumListContainer< TEnum >.CheckIfEnumType () inline private
Checks if the container is a valid enum type
Definition at line 203 of file EnumListContainer.cs.
         {
             if (!typeof(TEnum).IsEnum)
             {
                 throw new ArgumentException("TEnum for EnumListContainer must be an enumerated type");
             }
         }
bool BGC.DataStructures.EnumListContainer< TEnum >.Contains (TEnum item) inline
Check if the list contains an item
Parameters
item
Returns
Definition at line 163 of file EnumListContainer.cs.
         {
             return list.Contains((int)Convert.ChangeType(item, typeof(int)));
         }
void BGC.DataStructures.EnumListContainer< TEnum >.Deserialize (JsonArray array, EnumSerialization serialization) inline private
Sets the list to a deserialized JsonArray
Parameters
array
serialization
Definition at line 188 of file EnumListContainer.cs.
References LightJson.JsonArray.Add().
         {
             List<TEnum> list = array.JsonArrayToEnumList<TEnum>(serialization);
             List<int> temp = new List<int>();
             for (int i = 0; i < list.Count; ++i)
             {
                 temp.Add((int)Convert.ChangeType(list[i], typeof(int)));
             }
             this.list = temp;
         }
override bool BGC.DataStructures.EnumListContainer< TEnum >.Equals (object obj) inline
Check if two EnumListContainers are equal
Parameters
obj
Returns
Definition at line 139 of file EnumListContainer.cs.
         {
             if (obj == null || obj.GetType() != this.GetType())
             {
                 return false;
             }
             return ListExtension.ListsEquivalent(list, ((EnumListContainer<TEnum>)obj).list);
         }
Type BGC.DataStructures.EnumListContainer< TEnum >.GetEnumType () inline
Returns the enum type
Returns
Definition at line 215 of file EnumListContainer.cs.
         {
             return typeof(TEnum);
         }
override int BGC.DataStructures.EnumListContainer< TEnum >.GetHashCode () inline
Returns HashCode
Returns
Definition at line 153 of file EnumListContainer.cs.
         {
             return list.GetSequenceHashCode();
         }
bool BGC.DataStructures.EnumListContainer< TEnum >.Remove (TEnum element) inline
Removes an element of type TEnum from a list
Parameters
element
Returns
Definition at line 96 of file EnumListContainer.cs.
         {
             return list.Remove((int)Convert.ChangeType(element, typeof(int)));
         }
bool BGC.DataStructures.EnumListContainer< TEnum >.Remove (EnumListContainer< TEnum > elc) inline
Remove all elements in another EnumListContainer Returns false if failed to remove one element
Parameters
elc
Returns
Definition at line 107 of file EnumListContainer.cs.
References BGC.DataStructures.IntListContainer.Count.
         {
             bool removed = true;
             for (int i = 0; i < elc.Count; ++i)
             {
                 removed = Remove(elc[i]) && removed;
             }
             return removed;
         }
new JsonArray BGC.DataStructures.EnumListContainer< TEnum >.Serialize () inline
Serializes the list into a json array
Returns
Definition at line 172 of file EnumListContainer.cs.
References LightJson.JsonArray.Add().
Referenced by BGC.Extensions.EnumListContainerExtensions.EnumListContainerListToJsonArray< T >().
         {
             List<TEnum> enumList = new List<TEnum>();
             for (int i = 0; i < list.Count; ++i)
             {
                 enumList.Add((TEnum)Enum.ToObject(typeof(TEnum), list[i]));
             }
             return enumList.AnyListToStringJsonArray();
         }
void BGC.DataStructures.EnumListContainer< TEnum >.Set (List< TEnum > list) inline
Set contained list
Parameters
list
Definition at line 123 of file EnumListContainer.cs.
         {
             List<int> temp = new List<int>();
             for (int i = 0; i < list.Count; ++i)
             {
                 temp.Add((int)Convert.ChangeType(list[i], typeof(int)));
             }
             this.list = temp;
         }
Field Documentation
new EnumListContainer<TEnum> BGC.DataStructures.EnumListContainer< TEnum >.Clone => new EnumListContainer<TEnum>(new List<int>(list))
Definition at line 29 of file EnumListContainer.cs.
new TEnum BGC.DataStructures.EnumListContainer< TEnum >.RandomValue => (TEnum)Convert.ChangeType(list.RandomValue<int>(), typeof(TEnum))
Definition at line 30 of file EnumListContainer.cs.
Property Documentation
new TEnum BGC.DataStructures.EnumListContainer< TEnum >.this[int i] get set
Definition at line 18 of file EnumListContainer.cs.
The documentation for this class was generated from the following file:
DataStructures/Generic/EnumListContainer.cs