BGC Tools: BGC.Audio.Midi.MidiFileStream Class Reference
BGC.Audio.Midi.MidiFileStream Class Reference
Renders an underlying MidiFile
Public Member Functions
MidiFileStream (MidiFile midiFile)
void InsertTempoEvent (SetTempoMetaMidiEvent tempoEvent)
override IEnumerable< double > GetChannelRMS ()
The RMS amplitude of each channel
override int Read (float[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
override void Reset ()
Sets this internal state of this stream to the initial state
override void Seek (int position)
Seek to the indicated position in the stream
void ExecuteRunningEvent (ProgramMidiEvent programEvent)
byte GetChannelProgram (byte channel)
Public Member Functions inherited from BGC.Audio.SynthStream
void Initialize ()
Perform any calculations necessary to prepare the Stream
Data Fields
override int Channels => 1
override int TotalSamples => ChannelSamples
Data Fields inherited from BGC.Audio.SynthStream
float SamplingRate => 44100f
Protected Member Functions
override void _Initialize ()
Properties
override int ChannelSamples [get]
Properties inherited from BGC.Audio.SynthStream
abstract int Channels [get]
abstract int TotalSamples [get]
abstract int ChannelSamples [get]
Properties inherited from BGC.Audio.IBGCStream
int Channels [get]
The number of underlying Channels of this BGCStream
int TotalSamples [get]
The total number of Samples of this BGCStream
int ChannelSamples [get]
The number of Samples of each channel for this BGCStream
float SamplingRate [get]
The sampling rate of the Stream
Private Attributes
const int BUFFER_SIZE = 512
readonly float[] buffer = new float[BUFFER_SIZE]
readonly MidiFile midiFile
readonly Dictionary< byte, byte > programLookup = new Dictionary<byte, byte>()
Additional Inherited Members
Protected Attributes inherited from BGC.Audio.SynthStream
bool initialized = false
Detailed Description
Renders an underlying MidiFile
Definition at line 10 of file MidiFileStream.cs.
Constructor & Destructor Documentation
BGC.Audio.Midi.MidiFileStream.MidiFileStream (MidiFile midiFile) inline
Definition at line 24 of file MidiFileStream.cs.
References BGC.Audio.Midi.MidiFile.tracks.
         {
             this.midiFile = midiFile;
             midiFile.tracks.ForEach(x => x.Initialize(this));
             ChannelSamples = midiFile.tracks[0].SampleEstimate();
             //Handle tempo mapping:
             midiFile.tracks[0].events.ForEach(x =>
             {
                 if (x is SetTempoMetaMidiEvent tempoEvent)
                 {
                     InsertTempoEvent(tempoEvent);
                 }
             });
         }
Member Function Documentation
override void BGC.Audio.Midi.MidiFileStream._Initialize () inline protected virtual
Reimplemented from BGC.Audio.SynthStream.
Definition at line 56 of file MidiFileStream.cs.
         {
         }
void BGC.Audio.Midi.MidiFileStream.ExecuteRunningEvent (ProgramMidiEvent programEvent) inline
Definition at line 102 of file MidiFileStream.cs.
References BGC.Audio.Midi.Events.ProgramMidiEvent.channel, and BGC.Audio.Midi.Events.ProgramMidiEvent.value.
Referenced by BGC.Audio.Midi.MidiTrack.ExecuteRunningEvent().
         {
             if (programLookup.ContainsKey(programEvent.channel))
             {
                 programLookup[programEvent.channel] = programEvent.value;
             }
             else
             {
                 programLookup.Add(programEvent.channel, programEvent.value);
             }
         }
byte BGC.Audio.Midi.MidiFileStream.GetChannelProgram (byte channel) inline
Definition at line 114 of file MidiFileStream.cs.
Referenced by BGC.Audio.Midi.MidiTrack.ExecuteRunningEvent().
         {
             if (programLookup.ContainsKey(channel))
             {
                 return programLookup[channel];
             }
             return (byte)ReservedSoundSet.CrutchOrgan;
         }
override IEnumerable<double> BGC.Audio.Midi.MidiFileStream.GetChannelRMS () inline virtual
The RMS amplitude of each channel
Implements BGC.Audio.SynthStream.
Definition at line 51 of file MidiFileStream.cs.
         {
             yield return Math.Sqrt(0.5);
         }
void BGC.Audio.Midi.MidiFileStream.InsertTempoEvent (SetTempoMetaMidiEvent tempoEvent) inline
Definition at line 43 of file MidiFileStream.cs.
References BGC.Audio.Midi.Events.SetTempoMetaMidiEvent.tempo, and BGC.Audio.Midi.Events.MidiEvent.time.
         {
             for (int i = 1; i < midiFile.tracks.Count; i++)
             {
                 midiFile.tracks[i].Insert(new SetTempoMetaMidiEvent(0, tempoEvent.tempo), tempoEvent.time);
             }
         }
override int BGC.Audio.Midi.MidiFileStream.Read (float[] data, int offset, int count) inline virtual
Copy count samples into the Data buffer, starting at offset.
Returns
The number of samples copied
Implements BGC.Audio.SynthStream.
Definition at line 60 of file MidiFileStream.cs.
References BGC.Audio.Midi.MidiTrack.Read(), BGC.Audio.Midi.MidiTrack.Reset(), and BGC.Audio.Midi.MidiTrack.Seek().
         {
             int minRemainingSamples = count;
             Array.Clear(data, offset, count);
             foreach (MidiTrack track in midiFile.tracks)
             {
                 int trackRemainingSamples = count;
                 int trackOffset = offset;
                 while (trackRemainingSamples > 0)
                 {
                     int maxRead = Math.Min(BUFFER_SIZE, trackRemainingSamples);
                     int trackReadSamples = track.Read(buffer, 0, maxRead);
                     if (trackReadSamples == 0)
                     {
                         //Done with this track
                         break;
                     }
                     for (int i = 0; i < trackReadSamples; i++)
                     {
                         data[trackOffset + i] += buffer[i];
                     }
                     trackOffset += trackReadSamples;
                     trackRemainingSamples -= trackReadSamples;
                 }
                 minRemainingSamples = Math.Min(minRemainingSamples, trackRemainingSamples);
             }
             return count - minRemainingSamples;
         }
override void BGC.Audio.Midi.MidiFileStream.Reset () virtual
Sets this internal state of this stream to the initial state
Implements BGC.Audio.SynthStream.
override void BGC.Audio.Midi.MidiFileStream.Seek (int position) virtual
Seek to the indicated position in the stream
Implements BGC.Audio.SynthStream.
Field Documentation
readonly float [] BGC.Audio.Midi.MidiFileStream.buffer = new float[BUFFER_SIZE] private
Definition at line 19 of file MidiFileStream.cs.
const int BGC.Audio.Midi.MidiFileStream.BUFFER_SIZE = 512 private
Definition at line 18 of file MidiFileStream.cs.
override int BGC.Audio.Midi.MidiFileStream.Channels => 1
Definition at line 12 of file MidiFileStream.cs.
readonly MidiFile BGC.Audio.Midi.MidiFileStream.midiFile private
Definition at line 21 of file MidiFileStream.cs.
readonly Dictionary<byte, byte> BGC.Audio.Midi.MidiFileStream.programLookup = new Dictionary<byte, byte>() private
Definition at line 22 of file MidiFileStream.cs.
override int BGC.Audio.Midi.MidiFileStream.TotalSamples => ChannelSamples
Definition at line 14 of file MidiFileStream.cs.
Property Documentation
override int BGC.Audio.Midi.MidiFileStream.ChannelSamples get
Definition at line 16 of file MidiFileStream.cs.
The documentation for this class was generated from the following file:
Audio/Midi/MidiFileStream.cs