BGC Tools: BGC.Audio.Midi.MidiTrack Class Reference
BGC.Audio.Midi.MidiTrack Class Reference
Public Member Functions
MidiTrack (in HeaderInfo headerInfo, short sequenceNumber, bool retainAll=true)
MidiTrack (in HeaderInfo headerInfo, short sequenceNumber, IEnumerable< MidiEvent > events, bool retainAll=true)
MidiTrack (in HeaderInfo headerInfo, short sequenceNumber, Stream trackStream, bool retainAll=false)
Deserialization Constructor
void Add (MidiEvent midiEvent)
void Insert (MidiEvent midiEvent, int time)
void AddRange (IEnumerable< MidiEvent > midiEvents)
MidiEvent ParseEvent (Stream inputStream)
void Deserialize (Stream trackStream)
void Serialize (Stream outputStream)
void Initialize (MidiFileStream midiStream)
void SetTempo (int tempo)
int SampleEstimate ()
void ExecuteRunningEvent (PitchBendMidiEvent pitchBendEvent)
void ExecuteRunningEvent (ChannelPressureMidiEvent channelPressureEvent)
void ExecuteRunningEvent (ProgramMidiEvent programEvent)
void ExecuteRunningEvent (NoteMidiEvent noteEvent)
void ExecuteRunningEvent (ControllerMidiEvent controllerEvent)
int Read (float[] data, int offset, int count)
int ReadBuffered (float[] data, int offset, int count)
void Reset ()
void Seek (int position)
Data Fields
const string TRACK_CHUNK_NAME = "MTrk"
readonly List< MidiEvent > events = new List<MidiEvent>()
float SamplingRate => 44100f
Properties
string TrackName [get, set]
string InstrumentName = "" [get, set]
short SequenceNumber = "" [get, set]
int Length [get, set]
int Tempo = int.MaxValue [get, set]
int StartTime = 0x500000 [get, set]
int SignatureNumerator = 0 [get, set]
int SignatureDenominator = 3 [get, set]
int SignatureClockTicks = 4 [get, set]
int SignatureNoteRate = 24 [get, set]
int SharpFlatCount = 8 [get, set]
bool MajorKey = 0 [get, set]
Private Member Functions
void HandleIntegration (MidiEvent midiEvent, int index)
int int deltaT FindTimeIndex (int time)
Private Attributes
readonly bool retainAll
readonly HeaderInfo headerInfo
int index
byte lastEventCode = 0
double samplesPerTick
float [] sampleBuffer = new float[1]
int bufferCount = 0
int bufferIndex = 0
readonly ActiveNoteStream noteStream = new ActiveNoteStream()
MidiFileStream midiStream = null
MidiEvent NextEvent => eventIndex < events.Count ? events[eventIndex] : null
int eventIndex = 0
int currentTick
double currentSample = 0.0
Detailed Description
Definition at line 18 of file MidiTrack.cs.
Constructor & Destructor Documentation
MidiTrack() [1/3]
BGC.Audio.Midi.MidiTrack.MidiTrack (in HeaderInfo headerInfo, short sequenceNumber, bool retainAll = true) inline
Definition at line 58 of file MidiTrack.cs.
         {
             this.headerInfo = headerInfo;
             this.retainAll = retainAll;
             SequenceNumber = sequenceNumber;
         }
MidiTrack() [2/3]
BGC.Audio.Midi.MidiTrack.MidiTrack (in HeaderInfo headerInfo, short sequenceNumber, IEnumerable< MidiEvent > events, bool retainAll = true) inline
Definition at line 68 of file MidiTrack.cs.
             : this(headerInfo, sequenceNumber, retainAll)
         {
             AddRange(events);
         }
MidiTrack() [3/3]
BGC.Audio.Midi.MidiTrack.MidiTrack (in HeaderInfo headerInfo, short sequenceNumber, Stream trackStream, bool retainAll = false) inline
Deserialization Constructor
Definition at line 79 of file MidiTrack.cs.
             : this(headerInfo, sequenceNumber, retainAll)
         {
             Deserialize(trackStream);
         }
Member Function Documentation
Add()
void BGC.Audio.Midi.MidiTrack.Add (MidiEvent midiEvent) inline
Definition at line 125 of file MidiTrack.cs.
References BGC.Audio.Midi.Events.MidiEvent.Essential, and BGC.Audio.Midi.Events.MidiEvent.MessageClass.
         {
             if (midiEvent == null)
             {
                 return;
             }
             if (midiEvent.MessageClass == MidiMessageClass.MAX)
             {
                 Debug.Log($"Unrecognized MidiEvent Class {midiEvent.MessageClass}: {midiEvent}");
             }
             if (retainAll || midiEvent.Essential)
             {
                 events.Add(midiEvent);
             }
             HandleIntegration(midiEvent, events.Count - 1);
         }
AddRange()
void BGC.Audio.Midi.MidiTrack.AddRange (IEnumerable< MidiEvent > midiEvents) inline
Definition at line 179 of file MidiTrack.cs.
         {
             foreach (MidiEvent midiEvent in midiEvents)
             {
                 Add(midiEvent);
             }
         }
Deserialize()
void BGC.Audio.Midi.MidiTrack.Deserialize (Stream trackStream)
ExecuteRunningEvent() [1/5]
void BGC.Audio.Midi.MidiTrack.ExecuteRunningEvent (PitchBendMidiEvent pitchBendEvent) inline
Definition at line 332 of file MidiTrack.cs.
Referenced by BGC.Audio.Midi.Events.ChannelPressureMidiEvent.Serialize(), BGC.Audio.Midi.Events.PitchBendMidiEvent.Serialize(), BGC.Audio.Midi.Events.ProgramMidiEvent.Serialize(), BGC.Audio.Midi.Events.NoteMidiEvent.Serialize(), and BGC.Audio.Midi.Events.ControllerMidiEvent.Serialize().
         {
         }
ExecuteRunningEvent() [2/5]
void BGC.Audio.Midi.MidiTrack.ExecuteRunningEvent (ChannelPressureMidiEvent channelPressureEvent) inline
Definition at line 337 of file MidiTrack.cs.
         {
         }
ExecuteRunningEvent() [3/5]
void BGC.Audio.Midi.MidiTrack.ExecuteRunningEvent (ProgramMidiEvent programEvent) inline
Definition at line 342 of file MidiTrack.cs.
References BGC.Audio.Midi.MidiFileStream.ExecuteRunningEvent().
         {
             midiStream.ExecuteRunningEvent(programEvent);
         }
ExecuteRunningEvent() [4/5]
void BGC.Audio.Midi.MidiTrack.ExecuteRunningEvent (NoteMidiEvent noteEvent) inline
Definition at line 347 of file MidiTrack.cs.
References BGC.Audio.Midi.Events.NoteMidiEvent.channel, BGC.Audio.Midi.MidiFileStream.GetChannelProgram(), BGC.Audio.Midi.Synth.InstrumentLookup.GetNote(), BGC.Audio.Midi.Events.NoteMidiEvent.note, BGC.Audio.Midi.Events.NoteMidiEvent.noteEventType, and BGC.Audio.Midi.Events.NoteMidiEvent.param.
         {
             if (noteEvent.noteEventType == NoteMidiEvent.NoteEventType.NoteOff ||
                 noteEvent.noteEventType == NoteMidiEvent.NoteEventType.NoteOn && noteEvent.param == 0)
             {
                 noteStream.Release(noteEvent.note | noteEvent.channel << 8);
             }
             else
             {
                 noteStream.AddStream(
                     key: noteEvent.note | noteEvent.channel << 8,
                     stream: InstrumentLookup.GetNote(
                         noteEvent: noteEvent,
                         set: midiStream.GetChannelProgram(noteEvent.channel)));
             }
         }
ExecuteRunningEvent() [5/5]
void BGC.Audio.Midi.MidiTrack.ExecuteRunningEvent (ControllerMidiEvent controllerEvent) inline
Definition at line 364 of file MidiTrack.cs.
References BGC.Audio.Midi.Events.ControllerMidiEvent.ModeMessageType.
         {
             Debug.Log($"Executing ControllerEvent: {controllerEvent}");
             switch (controllerEvent.ModeMessageType)
             {
                 case ControllerMidiEvent.ChannelModeMessageTypes.BankSelect_MSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.BankSelect_LSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.Modulation_MSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.Modulation_LSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.BreathController_MSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.BreathController_LSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.FootController_MSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.FootController_LSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.PortamentoTime_MSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.PortamentoTime_LSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.DataEntry_MSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.DataEntry_LSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.ChannelVolume_MSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.ChannelVolume_LSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.Balance_MSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.Balance_LSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.Pan_MSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.Pan_LSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.ExpressionController_MSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.ExpressionController_LSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.EffectControl_01_MSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.EffectControl_01_LSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.EffectControl_02_MSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.EffectControl_02_LSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.GeneralPurposeController_01_MSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.GeneralPurposeController_01_LSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.GeneralPurposeController_02_MSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.GeneralPurposeController_02_LSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.GeneralPurposeController_03_MSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.GeneralPurposeController_03_LSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.GeneralPurposeController_04_MSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.GeneralPurposeController_04_LSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.GeneralPurposeController_05:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.GeneralPurposeController_06:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.GeneralPurposeController_07:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.GeneralPurposeController_08:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.SustainPedal:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.PortamentoToggle:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.Sostenuto:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.SoftPedal:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.LegatoFootswitch:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.Hold_02:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.SoundController_01:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.SoundController_02:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.SoundController_03:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.SoundController_04:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.SoundController_05:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.SoundController_06:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.SoundController_07:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.SoundController_08:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.SoundController_09:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.SoundController_0A:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.PortamentoControl:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.Effects_01_Depth:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.Effects_02_Depth:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.Effects_03_Depth:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.Effects_04_Depth:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.Effects_05_Depth:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.DataIncrement:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.DataDecrement:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.NonRegisteredParameterNumber_LSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.NonRegisteredParameterNumber_MSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.RegisteredParameterNumber_LSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.RegisteredParameterNumber_MSB:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.AllSoundOff:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.ResetAll:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.LocalControl:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.AllNotesOff:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.OmniModeOff:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.OmniModeOn:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.MonoModeOn:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.PolyModeOn:
                     break;
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_01_MSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_02_MSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_03_MSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_04_MSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_05_MSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_06_MSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_07_MSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_08_MSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_09_MSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_0A_MSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_0B_MSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_0C_MSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_0D_MSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_0E_MSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_0F_MSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_10_MSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_01_LSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_02_LSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_03_LSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_04_LSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_05_LSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_06_LSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_07_LSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_08_LSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_09_LSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_0A_LSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_0B_LSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_0C_LSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_0D_LSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_0E_LSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_0F_LSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_10_LSB:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_1A:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_1B:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_1C:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_1D:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_1E:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_1F:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_20:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_21:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_22:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_23:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_24:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_25:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_26:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_27:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_28:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_29:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_2A:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_2B:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_2C:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_2D:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_2E:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_2F:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_30:
                 case ControllerMidiEvent.ChannelModeMessageTypes.Undefined_31:
                     Debug.LogError($"Undefined MidiChannelEvent: {controllerEvent.ModeMessageType}");
                     return;
                 default:
                     Debug.LogError($"Unknown MidiChannelEvent: {controllerEvent.ModeMessageType}");
                     return;
             }
         }
FindTimeIndex()
int int deltaT BGC.Audio.Midi.MidiTrack.FindTimeIndex (int time) inline private
Definition at line 163 of file MidiTrack.cs.
         {
             int currentTime = 0;
             for (int i = 0; i < events.Count; i++)
             {
                 if (currentTime + events[i].deltaTime > time)
                 {
                     return (i, time - currentTime);
                 }
                 currentTime += events[i].deltaTime;
             }
             return (events.Count, time - currentTime);
         }
HandleIntegration()
void BGC.Audio.Midi.MidiTrack.HandleIntegration (MidiEvent midiEvent, int index) inline private
Definition at line 89 of file MidiTrack.cs.
References BGC.Audio.Midi.Events.MidiEvent.deltaTime, BGC.Audio.Midi.Events.MetaMidiEvent.Integrate(), BGC.Audio.Midi.Events.MidiEvent.MessageClass, and BGC.Audio.Midi.Events.MidiEvent.time.
         {
             if (midiEvent == null)
             {
                 return;
             }
             if (index == 0)
             {
                 midiEvent.time = midiEvent.deltaTime;
             }
             else
             {
                 midiEvent.time = events[index - 1].time + midiEvent.deltaTime;
             }
             switch (midiEvent.MessageClass)
             {
                 case MidiMessageClass.SysexEvent:
                 case MidiMessageClass.SysCommEvent:
                 case MidiMessageClass.SysRTEvent:
                     //Maybe insert the indicated calls?
                     break;
                 case MidiMessageClass.MetaEvent:
                     MetaMidiEvent metaEvent = midiEvent as MetaMidiEvent;
                     metaEvent?.Integrate(this);
                     break;
                 case MidiMessageClass.ChannelEvent:
                 default:
                     //Do nothing
                     break;
             }
         }
Initialize()
void BGC.Audio.Midi.MidiTrack.Initialize (MidiFileStream midiStream) inline
Definition at line 299 of file MidiTrack.cs.
         {
             this.midiStream = midiStream;
         }
Insert()
void BGC.Audio.Midi.MidiTrack.Insert (MidiEvent midiEvent, int time) inline
Definition at line 145 of file MidiTrack.cs.
References BGC.Audio.Midi.Events.MidiEvent.deltaTime, and BGC.Audio.Midi.Events.MidiEvent.Essential.
         {
             if (retainAll || midiEvent.Essential)
             {
                 (int index, int deltaT) = FindTimeIndex(time + midiEvent.deltaTime);
                 midiEvent.deltaTime = deltaT;
                 events.Insert(index, midiEvent);
                 if (index + 1 < events.Count)
                 {
                     events[index + 1].deltaTime -= deltaT;
                 }
                 HandleIntegration(midiEvent, index);
             }
         }
ParseEvent()
MidiEvent BGC.Audio.Midi.MidiTrack.ParseEvent (Stream inputStream) inline
Definition at line 189 of file MidiTrack.cs.
References BGC.Audio.Midi.Events.MidiEvent.MessageClass, and BGC.Audio.Midi.Events.MidiEvent.ParseEvent().
         {
             int deltaTime = inputStream.ReadVarQuantity();
             byte nextByte = (byte)inputStream.ReadByte();
             //If the nextByte is an EventCode, update the last event code
             if (nextByte >= 0b1000_0000)
             {
                 lastEventCode = nextByte;
                 nextByte = (byte)inputStream.ReadByte();
             }
             MidiEvent midiEvent = MidiEvent.ParseEvent(
                 inputStream: inputStream,
                 deltaTime: deltaTime,
                 eventCode: lastEventCode,
                 nextByte: nextByte);
             if (midiEvent != null)
             {
                 //Logger.WriteLine($"{_trackNum.ToString(),-2} {eventNum.ToString(),-3} {midiEvent.ToString()}");
                 if (midiEvent.MessageClass == MidiMessageClass.MAX)
                 {
                     midiEvent = null;
                 }
             }
             return midiEvent;
         }
Read()
int BGC.Audio.Midi.MidiTrack.Read (float [] data, int offset, int count) inline
Definition at line 604 of file MidiTrack.cs.
References BGC.Audio.Midi.Events.MidiEvent.ExecuteEvent(), and BGC.Audio.Midi.Events.MidiEvent.time.
Referenced by BGC.Audio.Midi.MidiFileStream.Read().
         {
             //When a read comes in, advance the system to the next whole tick, leaving
             //buffered samples
             int samplesRemaining = count;
             int bodySamplesRead = ReadBuffered(data, offset, count);
             samplesRemaining -= bodySamplesRead;
             offset += bodySamplesRead;
             while (samplesRemaining > 0)
             {
                 //Execute any Events at the current tick
                 while (NextEvent != null && NextEvent.time == currentTick)
                 {
                     NextEvent.ExecuteEvent(this);
                     eventIndex++;
                 }
                 if (NextEvent == null)
                 {
                     break;
                 }
                 int tickAdvance = Math.Min(
                     (int)Math.Ceiling(samplesRemaining / samplesPerTick),
                     NextEvent.time - currentTick);
                 double newSample = currentSample + tickAdvance * samplesPerTick;
                 int samplesInTick = (int)(newSample - currentSample);
                 int samplesToRead = Math.Min(samplesInTick, samplesRemaining);
                 //NoteStream always returns requested samples
                 noteStream.Read(data, offset, samplesToRead);
                 currentSample = newSample;
                 offset += samplesToRead;
                 samplesRemaining -= samplesToRead;
                 currentTick += tickAdvance;
                 //Advance stream to the end of the tick if we still had tick samples left
                 if (samplesInTick > samplesToRead)
                 {
                     bufferCount = samplesInTick - samplesToRead;
                     noteStream.Read(sampleBuffer, 0, bufferCount);
                     bufferIndex = 0;
                 }
             }
             return count - samplesRemaining;
         }
ReadBuffered()
int BGC.Audio.Midi.MidiTrack.ReadBuffered (float [] data, int offset, int count) inline
Definition at line 657 of file MidiTrack.cs.
         {
             int samplesWritten = Math.Max(0, Math.Min(count, bufferCount - bufferIndex));
             Array.Copy(
                 sourceArray: sampleBuffer,
                 sourceIndex: bufferIndex,
                 destinationArray: data,
                 destinationIndex: offset,
                 length: samplesWritten);
             bufferIndex += samplesWritten;
             return samplesWritten;
         }
Reset()
void BGC.Audio.Midi.MidiTrack.Reset () inline
Definition at line 673 of file MidiTrack.cs.
Referenced by BGC.Audio.Midi.MidiFileStream.Read().
         {
             eventIndex = 0;
             currentTick = 0;
             currentSample = 0.0;
             bufferIndex = 0;
             bufferCount = 0;
             noteStream.Clear();
         }
SampleEstimate()
int BGC.Audio.Midi.MidiTrack.SampleEstimate () inline
Definition at line 325 of file MidiTrack.cs.
References BGC.Audio.Midi.Synth.E.
         {
             double tempSamplesPerTick = 1E-6 * Tempo * SamplingRate / headerInfo.ticksPerQuarter;
             return (int)(Length * tempSamplesPerTick);
         }
Seek()
void BGC.Audio.Midi.MidiTrack.Seek (int position)
Referenced by BGC.Audio.Midi.MidiFileStream.Read().
Serialize()
void BGC.Audio.Midi.MidiTrack.Serialize (Stream outputStream) inline
Definition at line 223 of file MidiTrack.cs.
References BGC.Audio.Midi.Events.MidiEvent.eventCode, BGC.Audio.Midi.Events.MidiEvent.Length, BGC.Audio.Midi.Events.MidiEvent.MessageClass, and BGC.Audio.Midi.Events.MidiEvent.Serialize().
Referenced by BGC.Audio.Midi.MidiFile.Serialize().
         {
             int eventLengths = 0;
             byte lastEventCode = 0;
             foreach (MidiEvent midiEvent in events)
             {
                 switch (midiEvent.MessageClass)
                 {
                     case MidiMessageClass.ChannelEvent:
                         if (midiEvent.eventCode == lastEventCode)
{
                             eventLengths += midiEvent.Length - 1;
                         }
                         else
{
                             eventLengths += midiEvent.Length;
                         }
                         lastEventCode = midiEvent.eventCode;
                         break;
                     case MidiMessageClass.SysexEvent:
                     case MidiMessageClass.SysCommEvent:
                     case MidiMessageClass.SysRTEvent:
                     case MidiMessageClass.MetaEvent:
                     default:
                         eventLengths += midiEvent.Length;
                         lastEventCode = 0;
                         break;
                 }
             }
             outputStream.Write(Encoding.UTF8.GetBytes(TRACK_CHUNK_NAME), 0, 4);
             outputStream.WriteByte((byte)(eventLengths >> 24));
             outputStream.WriteByte((byte)((eventLengths >> 16) & 0b1111_1111));
             outputStream.WriteByte((byte)((eventLengths >> 8) & 0b1111_1111));
             outputStream.WriteByte((byte)(eventLengths & 0b1111_1111));
             foreach (MidiEvent midiEvent in events)
             {
                 switch (midiEvent.MessageClass)
                 {
                     case MidiMessageClass.ChannelEvent:
                         midiEvent.Serialize(outputStream, midiEvent.eventCode == lastEventCode);
                         lastEventCode = midiEvent.eventCode;
                         break;
                     case MidiMessageClass.SysexEvent:
                     case MidiMessageClass.MetaEvent:
                     case MidiMessageClass.SysCommEvent:
                     case MidiMessageClass.SysRTEvent:
                     default:
                         midiEvent.Serialize(outputStream, false);
                         lastEventCode = 0;
                         break;
                 }
             }
         }
SetTempo()
void BGC.Audio.Midi.MidiTrack.SetTempo (int tempo) inline
Definition at line 304 of file MidiTrack.cs.
References BGC.Audio.Midi.Synth.E.
Referenced by BGC.Audio.Midi.Events.SetTempoMetaMidiEvent.ExecuteEvent().
         {
             Tempo = tempo;
             samplesPerTick = 1E-6 * Tempo * SamplingRate / headerInfo.ticksPerQuarter;
             int bufferSize = (int)Math.Ceiling(samplesPerTick);
             if (bufferSize > sampleBuffer.Length)
             {
                 float[] newSampleBuffer = new float[bufferSize];
                 Array.Copy(
                     sourceArray: sampleBuffer,
                     destinationArray: newSampleBuffer,
                     length: sampleBuffer.Length);
                 sampleBuffer = newSampleBuffer;
             }
         }
Field Documentation
bufferCount
int BGC.Audio.Midi.MidiTrack.bufferCount = 0 private
Definition at line 287 of file MidiTrack.cs.
bufferIndex
int BGC.Audio.Midi.MidiTrack.bufferIndex = 0 private
Definition at line 288 of file MidiTrack.cs.
currentSample
double BGC.Audio.Midi.MidiTrack.currentSample = 0.0 private
Definition at line 297 of file MidiTrack.cs.
currentTick
int BGC.Audio.Midi.MidiTrack.currentTick private
Definition at line 296 of file MidiTrack.cs.
eventIndex
int BGC.Audio.Midi.MidiTrack.eventIndex = 0 private
Definition at line 295 of file MidiTrack.cs.
events
readonly List<MidiEvent> BGC.Audio.Midi.MidiTrack.events = new List<MidiEvent>()
Definition at line 22 of file MidiTrack.cs.
headerInfo
readonly HeaderInfo BGC.Audio.Midi.MidiTrack.headerInfo private
Definition at line 25 of file MidiTrack.cs.
index
int BGC.Audio.Midi.MidiTrack.index private
Definition at line 163 of file MidiTrack.cs.
lastEventCode
byte BGC.Audio.Midi.MidiTrack.lastEventCode = 0 private
Definition at line 187 of file MidiTrack.cs.
midiStream
MidiFileStream BGC.Audio.Midi.MidiTrack.midiStream = null private
Definition at line 290 of file MidiTrack.cs.
NextEvent
MidiEvent BGC.Audio.Midi.MidiTrack.NextEvent => eventIndex < events.Count ? events[eventIndex] : null private
Definition at line 293 of file MidiTrack.cs.
noteStream
readonly ActiveNoteStream BGC.Audio.Midi.MidiTrack.noteStream = new ActiveNoteStream() private
Definition at line 289 of file MidiTrack.cs.
retainAll
readonly bool BGC.Audio.Midi.MidiTrack.retainAll private
Definition at line 24 of file MidiTrack.cs.
sampleBuffer
float [] BGC.Audio.Midi.MidiTrack.sampleBuffer = new float[1] private
Definition at line 286 of file MidiTrack.cs.
samplesPerTick
double BGC.Audio.Midi.MidiTrack.samplesPerTick private
Definition at line 284 of file MidiTrack.cs.
SamplingRate
float BGC.Audio.Midi.MidiTrack.SamplingRate => 44100f
Definition at line 42 of file MidiTrack.cs.
TRACK_CHUNK_NAME
const string BGC.Audio.Midi.MidiTrack.TRACK_CHUNK_NAME = "MTrk"
Definition at line 20 of file MidiTrack.cs.
Referenced by BGC.Audio.Midi.MidiEncoding.LoadFile().
Property Documentation
InstrumentName
string BGC.Audio.Midi.MidiTrack.InstrumentName = "" get set
Definition at line 28 of file MidiTrack.cs.
Referenced by BGC.Audio.Midi.Events.TextMetaMidiEvent.Integrate().
Length
int BGC.Audio.Midi.MidiTrack.Length get set
Definition at line 30 of file MidiTrack.cs.
Referenced by BGC.Audio.Midi.Events.EndOfTrackMetaMidiEvent.Integrate().
MajorKey
bool BGC.Audio.Midi.MidiTrack.MajorKey = 0 get set
Definition at line 40 of file MidiTrack.cs.
Referenced by BGC.Audio.Midi.Events.KeySignatureMetaMidiEvent.Integrate().
SequenceNumber
short BGC.Audio.Midi.MidiTrack.SequenceNumber = "" get set
Definition at line 29 of file MidiTrack.cs.
Referenced by BGC.Audio.Midi.Events.SequenceNumberMetaMidiEvent.Integrate().
SharpFlatCount
int BGC.Audio.Midi.MidiTrack.SharpFlatCount = 8 get set
Definition at line 39 of file MidiTrack.cs.
Referenced by BGC.Audio.Midi.Events.KeySignatureMetaMidiEvent.Integrate().
SignatureClockTicks
int BGC.Audio.Midi.MidiTrack.SignatureClockTicks = 4 get set
Definition at line 36 of file MidiTrack.cs.
Referenced by BGC.Audio.Midi.Events.TimeSignatureMetaMidiEvent.Integrate().
SignatureDenominator
int BGC.Audio.Midi.MidiTrack.SignatureDenominator = 3 get set
Definition at line 35 of file MidiTrack.cs.
Referenced by BGC.Audio.Midi.Events.TimeSignatureMetaMidiEvent.Integrate().
SignatureNoteRate
int BGC.Audio.Midi.MidiTrack.SignatureNoteRate = 24 get set
Definition at line 37 of file MidiTrack.cs.
Referenced by BGC.Audio.Midi.Events.TimeSignatureMetaMidiEvent.Integrate().
SignatureNumerator
int BGC.Audio.Midi.MidiTrack.SignatureNumerator = 0 get set
Definition at line 34 of file MidiTrack.cs.
Referenced by BGC.Audio.Midi.Events.TimeSignatureMetaMidiEvent.Integrate().
StartTime
int BGC.Audio.Midi.MidiTrack.StartTime = 0x500000 get set
Definition at line 32 of file MidiTrack.cs.
Tempo
int BGC.Audio.Midi.MidiTrack.Tempo = int.MaxValue get set
Definition at line 31 of file MidiTrack.cs.
Referenced by BGC.Audio.Midi.Events.SetTempoMetaMidiEvent.Integrate().
TrackName
string BGC.Audio.Midi.MidiTrack.TrackName get set
Definition at line 27 of file MidiTrack.cs.
Referenced by BGC.Audio.Midi.Events.TextMetaMidiEvent.Integrate().
The documentation for this class was generated from the following file:
Audio/Midi/MidiTrack.cs