BGC Tools: BGC.Audio.Filters.PhaseVocoder Class Reference
BGC.Audio.Filters.PhaseVocoder Class Reference
Slows the playback speed by a factor between 1x and 0.5x without changing pitch
Public Member Functions
PhaseVocoder (IBGCStream stream, double speed)
override int Read (float[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
override void Reset ()
Sets this internal state of this stream to the initial state
override void Seek (int position)
Seek to the indicated position in the stream
override IEnumerable< double > GetChannelRMS ()
The RMS amplitude of each channel
Public Member Functions inherited from BGC.Audio.Filters.SimpleBGCFilter
SimpleBGCFilter (IBGCStream stream)
override void Seek (int position)
Seek to the indicated position in the stream
override void Reset ()
Sets this internal state of this stream to the initial state
override void Initialize ()
Perform any calculations necessary to prepare the Stream
Data Fields
override int Channels => stream.Channels
override int TotalSamples => Channels * ChannelSamples
Data Fields inherited from BGC.Audio.Filters.SimpleBGCFilter
override float SamplingRate => stream.SamplingRate
Properties
override int ChannelSamples [get]
Properties inherited from BGC.Audio.Filters.SimpleBGCFilter
override IEnumerable< IBGCStream > InternalStreams [get]
Properties inherited from BGC.Audio.Filters.BGCFilter
abstract int Channels [get]
abstract int TotalSamples [get]
abstract int ChannelSamples [get]
abstract float SamplingRate [get]
abstract IEnumerable< IBGCStream > InternalStreams [get]
Properties inherited from BGC.Audio.IBGCStream
int Channels [get]
The number of underlying Channels of this BGCStream
int TotalSamples [get]
The total number of Samples of this BGCStream
int ChannelSamples [get]
The number of Samples of each channel for this BGCStream
float SamplingRate [get]
The sampling rate of the Stream
Private Member Functions
int ReadBody (float[] buffer, int offset, int count)
void ClearBuffers ()
Private Attributes
const int BASE_FFT_SIZE = 12
const int EXPANDED_FFT_SIZE = BASE_FFT_SIZE + 1
const int OVERLAP_FACTOR = 32
readonly int halfFFTSamples
readonly int baseFFTSamples
readonly int expandedFFTSamples
readonly int outputSamples
readonly int stepSize
readonly int overlap
readonly int outputStep
readonly double effectiveSpeed
readonly double inputScalar
readonly double outputScalar
readonly float [] localSampleBuffer
Holds samples from underlying stream
readonly float [] cachedSampleBuffer
Store computed samples ready to deliver
readonly Complex64 [] phasors
readonly Complex64 [] phasorDeltas
readonly float [][] inputBuffers
readonly Complex64 [] fftBuffer
readonly Complex64 [] ifftBuffer
readonly float [] outputAccumulation
readonly double [] windowInput
readonly double [] windowOutput
int bufferIndex = 0
int bufferCount = 0
Additional Inherited Members
Protected Member Functions inherited from BGC.Audio.Filters.BGCFilter
virtual void _Initialize ()
Protected Attributes inherited from BGC.Audio.Filters.SimpleBGCFilter
readonly IBGCStream stream
Protected Attributes inherited from BGC.Audio.Filters.BGCFilter
bool initialized = false
Detailed Description
Slows the playback speed by a factor between 1x and 0.5x without changing pitch
Definition at line 10 of file PhaseVocoder.cs.
Constructor & Destructor Documentation
PhaseVocoder()
BGC.Audio.Filters.PhaseVocoder.PhaseVocoder (IBGCStream stream, double speed) inline
Definition at line 60 of file PhaseVocoder.cs.
References BGC.Audio.IBGCStream.ChannelSamples, BGC.Mathematics.Complex64.Cos(), and BGC.Mathematics.Complex64.FromPolarCoordinates().
             : base(stream)
         {
             baseFFTSamples = (int)Math.Pow(2, BASE_FFT_SIZE);
             expandedFFTSamples = 2 * baseFFTSamples;
             halfFFTSamples = baseFFTSamples / 2;
             stepSize = baseFFTSamples / OVERLAP_FACTOR;
             overlap = baseFFTSamples - stepSize;
             outputStep = ((int)(baseFFTSamples / speed)) / OVERLAP_FACTOR;
             outputSamples = outputStep * OVERLAP_FACTOR;
             effectiveSpeed = stepSize / (double)outputStep;
             localSampleBuffer = new float[Channels * stepSize];
             cachedSampleBuffer = new float[Channels * outputSamples];
             phasors = new Complex64[halfFFTSamples + 1];
             phasorDeltas = new Complex64[halfFFTSamples + 1];
             inputBuffers = new float[Channels][];
             outputAccumulation = new float[Channels * expandedFFTSamples];
             fftBuffer = new Complex64[baseFFTSamples];
             ifftBuffer = new Complex64[expandedFFTSamples];
             ChannelSamples = (int)(stream.ChannelSamples / effectiveSpeed);
             for (int i = 0; i < Channels; i++)
             {
                 inputBuffers[i] = new float[baseFFTSamples];
             }
             int deltaSteps = outputStep - stepSize;
             for (int i = 0; i <= halfFFTSamples; i++)
             {
                 //Initialize phasors to 2 so that it doubles the amplitudes on copy and rotation
                 phasors[i] = 2f;
                 phasorDeltas[i] = Complex64.FromPolarCoordinates(1.0, -i * deltaSteps / (double)baseFFTSamples);
             }
             //inputScalar = Math.Sqrt(baseFFTSamples);
             inputScalar = 1.0;
             outputScalar = 1.0 / OVERLAP_FACTOR;
             windowInput = new double[baseFFTSamples];
             windowOutput = new double[outputSamples];
             for (int i = 0; i < baseFFTSamples; i++)
             {
                 //Hamming
                 windowInput[i] = 0.54 - 0.46 * Math.Cos(2.0 * Math.PI * i / (baseFFTSamples - 1));
             }
             for (int i = 0; i < outputSamples; i++)
             {
                 //Square
                 windowOutput[i] = 1.0;
             }
         }
Member Function Documentation
ClearBuffers()
void BGC.Audio.Filters.PhaseVocoder.ClearBuffers () inline private
Definition at line 232 of file PhaseVocoder.cs.
         {
             bufferIndex = 0;
             bufferCount = 0;
             Array.Clear(outputAccumulation, 0, outputAccumulation.Length);
             for (int i = 0; i < Channels; i++)
             {
                 Array.Clear(inputBuffers[i], 0, inputBuffers[i].Length);
             }
             for (int i = 0; i <= halfFFTSamples; i++)
             {
                 //Initialize phasors to 2 so that it doubles the amplitudes on copy and rotation
                 phasors[i] = 2.0;
             }
         }
GetChannelRMS()
override IEnumerable<double> BGC.Audio.Filters.PhaseVocoder.GetChannelRMS () virtual
The RMS amplitude of each channel
Implements BGC.Audio.Filters.BGCFilter.
Read()
override int BGC.Audio.Filters.PhaseVocoder.Read (float [] data, int offset, int count) inline virtual
Copy count samples into the Data buffer, starting at offset.
Returns
The number of samples copied
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 121 of file PhaseVocoder.cs.
References BGC.Mathematics.Fourier.Forward(), and BGC.Mathematics.Fourier.Inverse().
         {
             int samplesWritten = ReadBody(data, offset, count);
             while (samplesWritten < count)
             {
                 int read = stream.Read(localSampleBuffer, 0, localSampleBuffer.Length);
                 if (read <= 0)
                 {
                     //Done
                     break;
                 }
                 else if (read < localSampleBuffer.Length)
                 {
                     //Set rest to zero
                     Array.Clear(localSampleBuffer, read, localSampleBuffer.Length - read);
                 }
                 bufferIndex = 0;
                 bufferCount = Channels * outputStep;
                 for (int channel = 0; channel < Channels; channel++)
                 {
                     //Slide input samples over
                     Array.Copy(
                         sourceArray: inputBuffers[channel],
                         sourceIndex: stepSize,
                         destinationArray: inputBuffers[channel],
                         destinationIndex: 0,
                         length: overlap);
                     //Copy new samples into buffer
                     for (int i = 0; i < stepSize; i++)
                     {
                         inputBuffers[channel][overlap + i] = localSampleBuffer[Channels * i + channel];
                     }
                     //Copy and Window into fftbuffer
                     for (int i = 0; i < baseFFTSamples; i++)
                     {
                         fftBuffer[i] = inputScalar * inputBuffers[channel][i] * windowInput[i];
                     }
                     //FFT
                     Fourier.Forward(fftBuffer);
                     //Clear IFFT Buffer
                     Array.Clear(ifftBuffer, 0, ifftBuffer.Length);
                     //Copy values into IFFT Buffer
                     for (int i = 0; i <= halfFFTSamples; i++)
                     {
                         ifftBuffer[2 * i] = fftBuffer[i] * phasors[i];
                     }
                     //IFFT
                     Fourier.Inverse(ifftBuffer);
                     //Accumualte the window samples
                     for (int i = 0; i < outputSamples; i++)
                     {
                         outputAccumulation[Channels * i + channel] += (float)(outputScalar * windowOutput[i] * ifftBuffer[i].Real);
                     }
                 }
                 //Advance phasor
                 for (int i = 0; i <= halfFFTSamples; i++)
                 {
                     phasors[i] *= phasorDeltas[i];
                 }
                 //Copy output samples to output buffer
                 Array.Copy(
                     sourceArray: outputAccumulation,
                     destinationArray: cachedSampleBuffer,
                     length: bufferCount);
                 //Slide down output accumulation
                 Array.Copy(
                     sourceArray: outputAccumulation,
                     sourceIndex: bufferCount,
                     destinationArray: outputAccumulation,
                     destinationIndex: 0,
                     length: outputAccumulation.Length - bufferCount);
                 //Clear empty output accumulation region
                 Array.Clear(outputAccumulation, outputAccumulation.Length - bufferCount, bufferCount);
                 samplesWritten += ReadBody(data, offset + samplesWritten, count - samplesWritten);
             }
             return samplesWritten;
         }
ReadBody()
int BGC.Audio.Filters.PhaseVocoder.ReadBody (float [] buffer, int offset, int count) inline private
Definition at line 216 of file PhaseVocoder.cs.
         {
             int samplesWritten = Math.Min(count, bufferCount - bufferIndex);
             Array.Copy(
                 sourceArray: cachedSampleBuffer,
                 sourceIndex: bufferIndex,
                 destinationArray: buffer,
                 destinationIndex: offset,
                 length: samplesWritten);
             bufferIndex += samplesWritten;
             return samplesWritten;
         }
Reset()
override void BGC.Audio.Filters.PhaseVocoder.Reset () inline virtual
Sets this internal state of this stream to the initial state
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 251 of file PhaseVocoder.cs.
         {
             ClearBuffers();
             stream.Reset();
         }
Seek()
override void BGC.Audio.Filters.PhaseVocoder.Seek (int position) inline virtual
Seek to the indicated position in the stream
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 257 of file PhaseVocoder.cs.
         {
             ClearBuffers();
             stream.Seek((int)(position * effectiveSpeed));
         }
Field Documentation
BASE_FFT_SIZE
const int BGC.Audio.Filters.PhaseVocoder.BASE_FFT_SIZE = 12 private
Definition at line 12 of file PhaseVocoder.cs.
baseFFTSamples
readonly int BGC.Audio.Filters.PhaseVocoder.baseFFTSamples private
Definition at line 17 of file PhaseVocoder.cs.
bufferCount
int BGC.Audio.Filters.PhaseVocoder.bufferCount = 0 private
Definition at line 52 of file PhaseVocoder.cs.
bufferIndex
int BGC.Audio.Filters.PhaseVocoder.bufferIndex = 0 private
Definition at line 51 of file PhaseVocoder.cs.
cachedSampleBuffer
readonly float [] BGC.Audio.Filters.PhaseVocoder.cachedSampleBuffer private
Store computed samples ready to deliver
Definition at line 38 of file PhaseVocoder.cs.
Channels
override int BGC.Audio.Filters.PhaseVocoder.Channels => stream.Channels
Definition at line 54 of file PhaseVocoder.cs.
effectiveSpeed
readonly double BGC.Audio.Filters.PhaseVocoder.effectiveSpeed private
Definition at line 26 of file PhaseVocoder.cs.
EXPANDED_FFT_SIZE
const int BGC.Audio.Filters.PhaseVocoder.EXPANDED_FFT_SIZE = BASE_FFT_SIZE + 1 private
Definition at line 13 of file PhaseVocoder.cs.
expandedFFTSamples
readonly int BGC.Audio.Filters.PhaseVocoder.expandedFFTSamples private
Definition at line 18 of file PhaseVocoder.cs.
fftBuffer
readonly Complex64 [] BGC.Audio.Filters.PhaseVocoder.fftBuffer private
Definition at line 43 of file PhaseVocoder.cs.
halfFFTSamples
readonly int BGC.Audio.Filters.PhaseVocoder.halfFFTSamples private
Definition at line 16 of file PhaseVocoder.cs.
ifftBuffer
readonly Complex64 [] BGC.Audio.Filters.PhaseVocoder.ifftBuffer private
Definition at line 44 of file PhaseVocoder.cs.
inputBuffers
readonly float [][] BGC.Audio.Filters.PhaseVocoder.inputBuffers private
Definition at line 42 of file PhaseVocoder.cs.
inputScalar
readonly double BGC.Audio.Filters.PhaseVocoder.inputScalar private
Definition at line 27 of file PhaseVocoder.cs.
localSampleBuffer
readonly float [] BGC.Audio.Filters.PhaseVocoder.localSampleBuffer private
Holds samples from underlying stream
Definition at line 33 of file PhaseVocoder.cs.
outputAccumulation
readonly float [] BGC.Audio.Filters.PhaseVocoder.outputAccumulation private
Definition at line 45 of file PhaseVocoder.cs.
outputSamples
readonly int BGC.Audio.Filters.PhaseVocoder.outputSamples private
Definition at line 20 of file PhaseVocoder.cs.
outputScalar
readonly double BGC.Audio.Filters.PhaseVocoder.outputScalar private
Definition at line 28 of file PhaseVocoder.cs.
outputStep
readonly int BGC.Audio.Filters.PhaseVocoder.outputStep private
Definition at line 24 of file PhaseVocoder.cs.
overlap
readonly int BGC.Audio.Filters.PhaseVocoder.overlap private
Definition at line 23 of file PhaseVocoder.cs.
OVERLAP_FACTOR
const int BGC.Audio.Filters.PhaseVocoder.OVERLAP_FACTOR = 32 private
Definition at line 14 of file PhaseVocoder.cs.
phasorDeltas
readonly Complex64 [] BGC.Audio.Filters.PhaseVocoder.phasorDeltas private
Definition at line 41 of file PhaseVocoder.cs.
phasors
readonly Complex64 [] BGC.Audio.Filters.PhaseVocoder.phasors private
Definition at line 40 of file PhaseVocoder.cs.
stepSize
readonly int BGC.Audio.Filters.PhaseVocoder.stepSize private
Definition at line 22 of file PhaseVocoder.cs.
TotalSamples
override int BGC.Audio.Filters.PhaseVocoder.TotalSamples => Channels * ChannelSamples
Definition at line 56 of file PhaseVocoder.cs.
windowInput
readonly double [] BGC.Audio.Filters.PhaseVocoder.windowInput private
Definition at line 47 of file PhaseVocoder.cs.
windowOutput
readonly double [] BGC.Audio.Filters.PhaseVocoder.windowOutput private
Definition at line 48 of file PhaseVocoder.cs.
Property Documentation
ChannelSamples
override int BGC.Audio.Filters.PhaseVocoder.ChannelSamples get
Definition at line 58 of file PhaseVocoder.cs.
The documentation for this class was generated from the following file:
Audio/Filters/PhaseVocoder.cs