BGC Tools: BGC.Audio.Filters.NormalizerFilter Class Reference
BGC.Audio.Filters.NormalizerFilter Class Reference
Scales an underlying stream to the desired level (dB SPL)
Public Member Functions
NormalizerFilter (IBGCStream stream, double leftFactor, double rightFactor)
NormalizerFilter (IBGCStream stream, double presentationLevel)
NormalizerFilter (IBGCStream stream,(double levelL, double levelR) presentationLevel)
NormalizerFilter (IBGCStream stream, double presentationLevel, Calibration.Source source)
override int Read (float[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
override IEnumerable< double > GetChannelRMS ()
The RMS amplitude of each channel
Public Member Functions inherited from BGC.Audio.Filters.SimpleBGCFilter
SimpleBGCFilter (IBGCStream stream)
override void Seek (int position)
Seek to the indicated position in the stream
override void Reset ()
Sets this internal state of this stream to the initial state
override void Initialize ()
Perform any calculations necessary to prepare the Stream
Data Fields
override int TotalSamples => stream.TotalSamples
override int ChannelSamples => stream.ChannelSamples
override int Channels => 2
Data Fields inherited from BGC.Audio.Filters.SimpleBGCFilter
override float SamplingRate => stream.SamplingRate
Protected Member Functions
override void _Initialize ()
Private Member Functions
readonly (double levelL, double levelR) presentationLevels
Private Attributes
bool factorsInitialized = false
float leftFactor
float rightFactor
readonly Calibration.Source source
const int BUFFER_SIZE = 512
readonly float [] buffer = new float[BUFFER_SIZE]
IEnumerable< double > _channelRMS = null
Additional Inherited Members
Protected Attributes inherited from BGC.Audio.Filters.SimpleBGCFilter
readonly IBGCStream stream
Protected Attributes inherited from BGC.Audio.Filters.BGCFilter
bool initialized = false
Properties inherited from BGC.Audio.Filters.SimpleBGCFilter
override IEnumerable< IBGCStream > InternalStreams [get]
Properties inherited from BGC.Audio.Filters.BGCFilter
abstract int Channels [get]
abstract int TotalSamples [get]
abstract int ChannelSamples [get]
abstract float SamplingRate [get]
abstract IEnumerable< IBGCStream > InternalStreams [get]
Properties inherited from BGC.Audio.IBGCStream
int Channels [get]
The number of underlying Channels of this BGCStream
int TotalSamples [get]
The total number of Samples of this BGCStream
int ChannelSamples [get]
The number of Samples of each channel for this BGCStream
float SamplingRate [get]
The sampling rate of the Stream
Detailed Description
Scales an underlying stream to the desired level (dB SPL)
Definition at line 10 of file NormalizerFilter.cs.
Constructor & Destructor Documentation
NormalizerFilter() [1/4]
BGC.Audio.Filters.NormalizerFilter.NormalizerFilter (IBGCStream stream, double leftFactor, double rightFactor) inline
Definition at line 27 of file NormalizerFilter.cs.
References BGC.Audio.IBGCStream.Channels.
             : base(stream)
         {
             if (stream.Channels != 2)
             {
                 throw new ArgumentException("NormalizerFilter inner stream but have two channels.");
             }
             this.leftFactor = (float)leftFactor;
             this.rightFactor = (float)rightFactor;
             presentationLevels = (0.0, 0.0);
             factorsInitialized = true;
             //Doesn't matter, we won't use this.
             source = Calibration.Source.MAX;
         }
NormalizerFilter() [2/4]
BGC.Audio.Filters.NormalizerFilter.NormalizerFilter (IBGCStream stream, double presentationLevel) inline
Definition at line 47 of file NormalizerFilter.cs.
References BGC.Audio.IBGCStream.Channels.
             : base(stream)
         {
             if (stream.Channels != 2)
             {
                 throw new ArgumentException("NormalizerFilter inner stream but have two channels.");
             }
             presentationLevels = (presentationLevel, presentationLevel);
             factorsInitialized = false;
             source = Calibration.Source.Custom;
         }
NormalizerFilter() [3/4]
BGC.Audio.Filters.NormalizerFilter.NormalizerFilter (IBGCStream stream, (double levelL, double levelR) presentationLevel) inline
Definition at line 63 of file NormalizerFilter.cs.
References BGC.Audio.IBGCStream.Channels.
             : base(stream)
         {
             if (stream.Channels != 2)
             {
                 throw new ArgumentException("NormalizerFilter inner stream but have two channels.");
             }
             presentationLevels = presentationLevel;
             factorsInitialized = false;
             source = Calibration.Source.Custom;
         }
NormalizerFilter() [4/4]
BGC.Audio.Filters.NormalizerFilter.NormalizerFilter (IBGCStream stream, double presentationLevel, Calibration.Source source) inline
Definition at line 79 of file NormalizerFilter.cs.
References BGC.Audio.IBGCStream.Channels.
             : base(stream)
         {
             if (stream.Channels != 2)
             {
                 throw new ArgumentException("NormalizerFilter inner stream but have two channels.");
             }
             presentationLevels = (presentationLevel, presentationLevel);
             factorsInitialized = false;
             this.source = source;
         }
Member Function Documentation
_Initialize()
override void BGC.Audio.Filters.NormalizerFilter._Initialize () inline protected virtual
Reimplemented from BGC.Audio.Filters.BGCFilter.
Definition at line 96 of file NormalizerFilter.cs.
References BGC.Audio.Normalization.GetRMSScalingFactors().
         {
             if (!factorsInitialized)
             {
                 factorsInitialized = true;
                 Normalization.GetRMSScalingFactors(
                     stream: stream,
                     desiredLevel: presentationLevels.levelL,
                     scalingFactorL: out double tempLeftFactor,
                     scalingFactorR: out double tempRightFactor,
                     source: source);
                 if (presentationLevels.levelL != presentationLevels.levelR)
                 {
                     Normalization.GetRMSScalingFactors(
                         stream: stream,
                         desiredLevel: presentationLevels.levelL,
                         scalingFactorL: out double _,
                         scalingFactorR: out tempRightFactor,
                         source: source);
                 }
                 leftFactor = (float)tempLeftFactor;
                 rightFactor = (float)tempRightFactor;
             }
         }
GetChannelRMS()
override IEnumerable<double> BGC.Audio.Filters.NormalizerFilter.GetChannelRMS () inline virtual
The RMS amplitude of each channel
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 159 of file NormalizerFilter.cs.
References BGC.Audio.IBGCStream.GetChannelRMS().
         {
             if (_channelRMS == null)
             {
                 double innerRMS = stream.GetChannelRMS().First();
                 _channelRMS = new double[2] { leftFactor * innerRMS, rightFactor * innerRMS };
             }
             return _channelRMS;
         }
Read()
override int BGC.Audio.Filters.NormalizerFilter.Read (float [] data, int offset, int count) inline virtual
Copy count samples into the Data buffer, starting at offset.
Returns
The number of samples copied
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 125 of file NormalizerFilter.cs.
References BGC.Audio.IBGCStream.Read().
         {
             if (!initialized)
             {
                 Initialize();
             }
             int samplesRemaining = count;
             while (samplesRemaining > 0)
             {
                 int samplesToRead = Math.Min(BUFFER_SIZE, samplesRemaining);
                 int samplesRead = stream.Read(buffer, 0, samplesToRead);
                 if (samplesRead == 0)
                 {
                     //We ran out of samples.
                     break;
                 }
                 for (int i = 0; i < samplesRead; i += 2)
                 {
                     data[offset + i] = leftFactor * buffer[i];
                     data[offset + i + 1] = rightFactor * buffer[i + 1];
                 }
                 offset += samplesRead;
                 samplesRemaining -= samplesRead;
             }
             return count - samplesRemaining;
         }
readonly()
BGC.Audio.Filters.NormalizerFilter.readonly (double levelL, double levelR) private
Field Documentation
_channelRMS
IEnumerable<double> BGC.Audio.Filters.NormalizerFilter._channelRMS = null private
Definition at line 158 of file NormalizerFilter.cs.
buffer
readonly float [] BGC.Audio.Filters.NormalizerFilter.buffer = new float[BUFFER_SIZE] private
Definition at line 25 of file NormalizerFilter.cs.
BUFFER_SIZE
const int BGC.Audio.Filters.NormalizerFilter.BUFFER_SIZE = 512 private
Definition at line 24 of file NormalizerFilter.cs.
Channels
override int BGC.Audio.Filters.NormalizerFilter.Channels => 2
Definition at line 15 of file NormalizerFilter.cs.
ChannelSamples
override int BGC.Audio.Filters.NormalizerFilter.ChannelSamples => stream.ChannelSamples
Definition at line 13 of file NormalizerFilter.cs.
factorsInitialized
bool BGC.Audio.Filters.NormalizerFilter.factorsInitialized = false private
Definition at line 17 of file NormalizerFilter.cs.
leftFactor
float BGC.Audio.Filters.NormalizerFilter.leftFactor private
Definition at line 18 of file NormalizerFilter.cs.
rightFactor
float BGC.Audio.Filters.NormalizerFilter.rightFactor private
Definition at line 19 of file NormalizerFilter.cs.
source
readonly Calibration.Source BGC.Audio.Filters.NormalizerFilter.source private
Definition at line 22 of file NormalizerFilter.cs.
TotalSamples
override int BGC.Audio.Filters.NormalizerFilter.TotalSamples => stream.TotalSamples
Definition at line 12 of file NormalizerFilter.cs.
The documentation for this class was generated from the following file:
Audio/Filters/NormalizerFilter.cs