BGC Tools: BGC.IO.Compression.Zip Class Reference
BGC.IO.Compression.Zip Class Reference
A collection of convenience methods to handle compression and decompression of zip files.
Static Public Member Functions
static bool CompressDirectory (string inputPath, string outputFilePath)
static bool DecompressMemory (byte[] compressedMemory, string outputPath)
static bool DecompressStream (Stream compressedStream, string outputPath)
static bool DecompressFile (string inputFilePath, string outputPath)
Detailed Description
A collection of convenience methods to handle compression and decompression of zip files.
Definition at line 14 of file Zip.cs.
Member Function Documentation
CompressDirectory()
static bool BGC.IO.Compression.Zip.CompressDirectory (string inputPath, string outputFilePath) inline static
Definition at line 16 of file Zip.cs.
Referenced by BGC.Tests.ZipTests.TestZip().
         {
             if (!Directory.Exists(inputPath))
             {
                 Debug.LogError($"Input Directory not found: {inputPath}");
                 return false;
             }
             try
             {
                 ZipFile.CreateFromDirectory(
                     sourceDirectoryName: inputPath,
                     destinationArchiveFileName: outputFilePath,
                     compressionLevel: CompressionLevel.Optimal,
                     includeBaseDirectory: false);
             }
             catch (Exception ex)
             {
                 Debug.LogError($"Exception Caught during processing: {ex}");
                 return false;
             }
             return true;
         }
DecompressFile()
static bool BGC.IO.Compression.Zip.DecompressFile (string inputFilePath, string outputPath) inline static
Definition at line 94 of file Zip.cs.
Referenced by BGC.Tests.ZipTests.TestZip().
         {
             if (!File.Exists(inputFilePath))
             {
                 Debug.LogError($"Input File not found: {inputFilePath}");
                 return false;
             }
             if (!Directory.Exists(outputPath))
             {
                 Directory.CreateDirectory(outputPath);
             }
             try
             {
                 ZipFile.ExtractToDirectory(inputFilePath, outputPath);
             }
             catch (Exception ex)
             {
                 Debug.LogError($"Exception Caught during processing of ZipFile: {ex}");
                 return false;
             }
             return true;
         }
DecompressMemory()
static bool BGC.IO.Compression.Zip.DecompressMemory (byte [] compressedMemory, string outputPath) inline static
Definition at line 43 of file Zip.cs.
Referenced by BGC.Audio.Spatialization.ImpulseExtraction.FinishedRunning().
         {
             if (!Directory.Exists(outputPath))
             {
                 Directory.CreateDirectory(outputPath);
             }
             try
             {
                 using (Stream data = new MemoryStream(compressedMemory))
                 using (ZipArchive archive = new ZipArchive(data, ZipArchiveMode.Read, false))
                 {
                     archive.ExtractToDirectory(outputPath);
                 }
             }
             catch (Exception ex)
             {
                 Debug.LogError($"Exception Caught during processing of Zip Memory: {ex}");
                 return false;
             }
             return true;
         }
DecompressStream()
static bool BGC.IO.Compression.Zip.DecompressStream (Stream compressedStream, string outputPath) inline static
Definition at line 69 of file Zip.cs.
         {
             if (!Directory.Exists(outputPath))
             {
                 Directory.CreateDirectory(outputPath);
             }
             try
             {
                 using (ZipArchive archive = new ZipArchive(compressedStream, ZipArchiveMode.Read, false))
                 {
                     archive.ExtractToDirectory(outputPath);
                 }
             }
             catch (Exception ex)
             {
                 Debug.LogError($"Exception Caught during processing of Zip Stream: {ex}");
                 return false;
             }
             return true;
         }
The documentation for this class was generated from the following file:
IO/Compression/Zip.cs