BGC Tools: BGC.Audio.Synthesis.SineWave Class Reference
BGC.Audio.Synthesis.SineWave Class Reference
Sine wave stream with specified amplitude, frequency, and initialPhase. One period is cached and the phase offset is tracked and applied as a complex number.
Public Member Functions
SineWave (double amplitude, double frequency, double initialPhase=0.0)
SineWave (Complex64 amplitude, double frequency)
SineWave (ComplexCarrierTone carrier)
override int Read (float[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
override void Reset ()
Sets this internal state of this stream to the initial state
override void Seek (int position)
Seek to the indicated position in the stream
override IEnumerable< double > GetChannelRMS ()
The RMS amplitude of each channel
Public Member Functions inherited from BGC.Audio.BGCStream
void Initialize ()
Perform any calculations necessary to prepare the Stream
Public Member Functions inherited from BGC.Audio.Envelopes.IBGCEnvelopeStream
void Initialize ()
Perform any calculations necessary to prepare the Stream
Data Fields
override int Channels => 1
override float SamplingRate => 44100f
override int TotalSamples => int.MaxValue
override int ChannelSamples => int.MaxValue
Private Member Functions
bool IBGCEnvelopeStream. HasMoreSamples ()
Returns if the BGCEnvelopeStream has more samples
float IBGCEnvelopeStream. ReadNextSample ()
Returns the next sample in the BGCEnvelopeStream
Private Attributes
readonly double amplitude
Complex64 partial
readonly double cyclePartial
readonly Complex64 [] samples
int position = 0
int cycles = 0
IEnumerable< double > _channelRMS = null
int IBGCEnvelopeStream. Samples => int.MaxValue
Additional Inherited Members
Protected Member Functions inherited from BGC.Audio.BGCStream
virtual void _Initialize ()
Protected Attributes inherited from BGC.Audio.BGCStream
bool initialized = false
Properties inherited from BGC.Audio.BGCStream
abstract int Channels [get]
abstract int TotalSamples [get]
abstract int ChannelSamples [get]
abstract float SamplingRate [get]
Properties inherited from BGC.Audio.IBGCStream
int Channels [get]
The number of underlying Channels of this BGCStream
int TotalSamples [get]
The total number of Samples of this BGCStream
int ChannelSamples [get]
The number of Samples of each channel for this BGCStream
float SamplingRate [get]
The sampling rate of the Stream
Properties inherited from BGC.Audio.Envelopes.IBGCEnvelopeStream
int Samples [get]
The total number of Samples of this BGCEnvelopeStream
float SamplingRate [get]
The sampling rate of the BGCEnvelopeStream
Detailed Description
Sine wave stream with specified amplitude, frequency, and initialPhase. One period is cached and the phase offset is tracked and applied as a complex number.
Definition at line 15 of file SineWave.cs.
Constructor & Destructor Documentation
SineWave() [1/3]
BGC.Audio.Synthesis.SineWave.SineWave (double amplitude, double frequency, double initialPhase = 0.0) inline
Definition at line 31 of file SineWave.cs.
References BGC.Mathematics.Complex64.FromPolarCoordinates().
         {
             if (frequency == 0.0)
             {
                 throw new ArgumentException($"Unable to render 0Hz Sine Wave");
             }
             this.amplitude = amplitude;
             double sampleCount = SamplingRate / frequency;
             int intSampleCount = (int)Ceiling(sampleCount) - 1;
             cyclePartial = (2 * PI * frequency / SamplingRate) * (intSampleCount - sampleCount);
             cycles = 0;
             partial = Complex64.FromPolarCoordinates(
                 magnitude: 1.0,
                 phase: cycles * cyclePartial);
             samples = new Complex64[intSampleCount];
             for (int i = 0; i < samples.Length; i++)
             {
                 samples[i] = Complex64.FromPolarCoordinates(
                     magnitude: amplitude,
                     phase: initialPhase + 2 * PI * i / sampleCount);
             }
         }
SineWave() [2/3]
BGC.Audio.Synthesis.SineWave.SineWave (Complex64 amplitude, double frequency) inline
Definition at line 60 of file SineWave.cs.
             : this (amplitude.Magnitude, frequency, amplitude.Phase)
         {
         }
SineWave() [3/3]
BGC.Audio.Synthesis.SineWave.SineWave (ComplexCarrierTone carrier) inline
Definition at line 65 of file SineWave.cs.
             : this(carrier.amplitude, carrier.frequency)
         {
         }
Member Function Documentation
GetChannelRMS()
override IEnumerable<double> BGC.Audio.Synthesis.SineWave.GetChannelRMS () virtual
The RMS amplitude of each channel
Implements BGC.Audio.BGCStream.
HasMoreSamples()
bool IBGCEnvelopeStream. BGC.Audio.Synthesis.SineWave.HasMoreSamples () private
Returns if the BGCEnvelopeStream has more samples
Implements BGC.Audio.Envelopes.IBGCEnvelopeStream.
Read()
override int BGC.Audio.Synthesis.SineWave.Read (float [] data, int offset, int count) inline virtual
Copy count samples into the Data buffer, starting at offset.
Returns
The number of samples copied
Implements BGC.Audio.BGCStream.
Definition at line 70 of file SineWave.cs.
References BGC.Mathematics.Complex64.FromPolarCoordinates().
         {
             int samplesToRead = count;
             while (samplesToRead > 0)
             {
                 int readingSamples = Min(samplesToRead, samples.Length - position);
                 for (int i = 0; i < readingSamples; i++)
                 {
                     data[offset + i] = (float)samples[position + i].RealProduct(partial);
                 }
                 samplesToRead -= readingSamples;
                 offset += readingSamples;
                 position += readingSamples;
                 if (position == samples.Length)
                 {
                     //Reset position and advance cycle
                     position = 0;
                     cycles++;
                     partial = Complex64.FromPolarCoordinates(
                         magnitude: 1.0,
                         phase: cycles * cyclePartial);
                 }
             }
             return count;
         }
ReadNextSample()
float IBGCEnvelopeStream. BGC.Audio.Synthesis.SineWave.ReadNextSample () inline private
Returns the next sample in the BGCEnvelopeStream
Returns
The next sample
Implements BGC.Audio.Envelopes.IBGCEnvelopeStream.
Definition at line 135 of file SineWave.cs.
References BGC.Mathematics.Complex64.FromPolarCoordinates().
         {
             float value = (float)samples[position++].RealProduct(partial);
             if (position == samples.Length)
             {
                 //Reset position and advance cycle
                 position = 0;
                 cycles++;
                 partial = Complex64.FromPolarCoordinates(
                     magnitude: 1.0,
                     phase: cycles * cyclePartial);
             }
             return value;
         }
Reset()
override void BGC.Audio.Synthesis.SineWave.Reset () inline virtual
Sets this internal state of this stream to the initial state
Implements BGC.Audio.BGCStream.
Definition at line 101 of file SineWave.cs.
References BGC.Mathematics.Complex64.FromPolarCoordinates().
         {
             position = 0;
             cycles = 0;
             partial = Complex64.FromPolarCoordinates(
                 magnitude: 1.0,
                 phase: cycles * cyclePartial);
         }
Seek()
override void BGC.Audio.Synthesis.SineWave.Seek (int position) inline virtual
Seek to the indicated position in the stream
Implements BGC.Audio.BGCStream.
Definition at line 110 of file SineWave.cs.
References BGC.Mathematics.Complex64.FromPolarCoordinates().
         {
             if (position >= 0)
             {
                 cycles = position / samples.Length;
             }
             else
             {
                 cycles = (position - samples.Length + 1) / samples.Length;
             }
             this.position = position - cycles * samples.Length;
             partial = Complex64.FromPolarCoordinates(
                 magnitude: 1.0,
                 phase: cycles * cyclePartial);
         }
Field Documentation
_channelRMS
IEnumerable<double> BGC.Audio.Synthesis.SineWave._channelRMS = null private
Definition at line 127 of file SineWave.cs.
amplitude
readonly double BGC.Audio.Synthesis.SineWave.amplitude private
Definition at line 23 of file SineWave.cs.
Channels
override int BGC.Audio.Synthesis.SineWave.Channels => 1
Definition at line 17 of file SineWave.cs.
ChannelSamples
override int BGC.Audio.Synthesis.SineWave.ChannelSamples => int.MaxValue
Definition at line 21 of file SineWave.cs.
cyclePartial
readonly double BGC.Audio.Synthesis.SineWave.cyclePartial private
Definition at line 26 of file SineWave.cs.
cycles
int BGC.Audio.Synthesis.SineWave.cycles = 0 private
Definition at line 29 of file SineWave.cs.
partial
Complex64 BGC.Audio.Synthesis.SineWave.partial private
Definition at line 25 of file SineWave.cs.
position
int BGC.Audio.Synthesis.SineWave.position = 0 private
Definition at line 28 of file SineWave.cs.
samples
readonly Complex64 [] BGC.Audio.Synthesis.SineWave.samples private
Definition at line 27 of file SineWave.cs.
Samples
int IBGCEnvelopeStream. BGC.Audio.Synthesis.SineWave.Samples => int.MaxValue private
Definition at line 133 of file SineWave.cs.
SamplingRate
override float BGC.Audio.Synthesis.SineWave.SamplingRate => 44100f
Definition at line 18 of file SineWave.cs.
TotalSamples
override int BGC.Audio.Synthesis.SineWave.TotalSamples => int.MaxValue
Definition at line 20 of file SineWave.cs.
The documentation for this class was generated from the following file:
Audio/Synthesis/SineWave.cs