BGC Tools: BGC.Mathematics.CustomRandom Class Reference
BGC.Mathematics.CustomRandom Class Reference
Static Public Member Functions
static double NextDouble ()
Returns a random double in the range [0.0 1.0)
static float NextFloat ()
Returns a random float in the range [0f 1f]. NOTE: 1 is inclusive, because of casting the double to a float rounding
static int Next ()
Returns a random integer
static int Next (int min, int max)
Returns a random integer in the range [min max)
static double RayleighDistribution (double input)
Translates an evenly distributed random number in the range [0,1) into a Rayleigh-Distributed one. Technically in the range [0, 8.49151] due to the largest double less than one. About half the range of inputs results in a value less than 1, and 85% are less than 2.
static float RayleighDistribution (float input)
Translates an evenly distributed random number in the range [0,1) into a Rayleigh-Distributed one. Technically in the range [0, 8.49151] due to the largest double less than one. About half the range of inputs results in a value less than 1, and 85% are less than 2.
static double NormalDistribution (double sigma, double mean, double input1, double input2)
Returns a normally distributed value with specified mean and deviation
static double NormalDistribution (double input1, double input2)
Returns a normally distributed value with mean 0 and sigma 1 https://en.wikipedia.org/wiki/Normal_distribution#Generating_values_from_normal_distribution
static float NextFloat (this Random random)
Retrieve the next double and cast it to a float.
Properties
static Random GlobalRand [get]
Static Private Attributes
static object randLock = new object()
Lock used to protect multi-thread access to random
static Random _globalRand
Detailed Description
Definition at line 7 of file CustomRandom.cs.
Member Function Documentation
static int BGC.Mathematics.CustomRandom.Next () inline static
Returns a random integer
Definition at line 54 of file CustomRandom.cs.
Referenced by BGC.Audio.AnalyticStreams.AnalyticNoiseStream.AnalyticNoiseStream(), BGC.Audio.Filters.CarlileShuffler.CarlileShuffler(), BGC.Audio.CrossFadingRefClip.CrossFadingRefClip(), BGC.Audio.Synthesis.NoiseAudioClip.NoiseAudioClip(), BGC.Audio.CrossFadingRefClip.Reset(), BGC.Audio.Synthesis.STMAudioClip.STMAudioClip(), BGC.Audio.Synthesis.SweepAudioClip.SweepAudioClip(), and BGC.Audio.Synthesis.WhiteNoiseStream.WhiteNoiseStream().
         {
             lock (randLock)
             {
                 return GlobalRand.Next();
             }
         }
static int BGC.Mathematics.CustomRandom.Next (int min, int max) inline static
Returns a random integer in the range [min max)
Definition at line 65 of file CustomRandom.cs.
         {
             lock (randLock)
             {
                 return GlobalRand.Next(min, max);
             }
         }
static double BGC.Mathematics.CustomRandom.NextDouble () inline static
Returns a random double in the range [0.0 1.0)
Definition at line 31 of file CustomRandom.cs.
         {
             lock (randLock)
             {
                 return GlobalRand.NextDouble();
             }
         }
static float BGC.Mathematics.CustomRandom.NextFloat () inline static
Returns a random float in the range [0f 1f]. NOTE: 1 is inclusive, because of casting the double to a float rounding
Definition at line 43 of file CustomRandom.cs.
         {
             lock (randLock)
             {
                 return GlobalRand.NextFloat();
             }
         }
static float BGC.Mathematics.CustomRandom.NextFloat (this Random random) static
Retrieve the next double and cast it to a float.
Parameters
random
Returns
static double BGC.Mathematics.CustomRandom.NormalDistribution (double sigma, double mean, double input1, double input2) static
Returns a normally distributed value with specified mean and deviation
static double BGC.Mathematics.CustomRandom.NormalDistribution (double input1, double input2) static
Returns a normally distributed value with mean 0 and sigma 1 https://en.wikipedia.org/wiki/Normal_distribution#Generating_values_from_normal_distribution
static double BGC.Mathematics.CustomRandom.RayleighDistribution (double input) static
Translates an evenly distributed random number in the range [0,1) into a Rayleigh-Distributed one. Technically in the range [0, 8.49151] due to the largest double less than one. About half the range of inputs results in a value less than 1, and 85% are less than 2.
Parameters
input Random input value. Should be in range [0 1]
Referenced by BGC.Audio.Synthesis.NoiseAudioClip.CreateSideBands(), BGC.Audio.AnalyticStreams.AnalyticNoiseStream.CreateSideBands(), and BGC.Audio.Synthesis.STMAudioClip.CreateSideBands().
static float BGC.Mathematics.CustomRandom.RayleighDistribution (float input) static
Translates an evenly distributed random number in the range [0,1) into a Rayleigh-Distributed one. Technically in the range [0, 8.49151] due to the largest double less than one. About half the range of inputs results in a value less than 1, and 85% are less than 2.
Parameters
input Random input value. Should be in range [0 1]
Field Documentation
Random BGC.Mathematics.CustomRandom._globalRand static private
Definition at line 14 of file CustomRandom.cs.
object BGC.Mathematics.CustomRandom.randLock = new object() static private
Lock used to protect multi-thread access to random
Definition at line 12 of file CustomRandom.cs.
Property Documentation
Random BGC.Mathematics.CustomRandom.GlobalRand static get private
Definition at line 16 of file CustomRandom.cs.
The documentation for this class was generated from the following file:
Mathematics/CustomRandom.cs