BGC Tools: BGC.Extensions.JsonExtensions Class Reference
BGC.Extensions.JsonExtensions Class Reference
Static Public Member Functions
static JsonArray TryGetArray (this JsonObject json, string key)
Tries to get array and returns an empty array if not found
static JsonValue TryGetValue (this JsonObject json, string key)
Try and get value, if key is not there it adds the key
static List< int > JsonArrayToIntList (this JsonArray jsonArray)
Converts a Json Array to a List of generic type T
static List< string > JsonaArrayToStringList (this JsonArray jsonArray)
static List< float > JsonArrayToFloatList (this JsonArray jsonArray)
Converts a Json Array to a List of floats
static List< T > JsonArrayToEnumList< T > (this JsonArray jsonArray, EnumSerialization enumSerialization)
Converts Any Json Array to a List of Enums
static JsonArray IntListToJsonArray (this IList< int > list)
Converts an int list to a Json Array of Int Values
static JsonArray FloatListToJsonArray (this IList< float > list)
Converts a float list to a Json Array of float values
static JsonArray AnyListToStringJsonArray< T > (this IList< T > list)
Converts any list to a json array of string values
static JsonArray ConvertToJsonArray< T > (this List< T > list, Func< T, JsonValue > convertToJsonValue)
Converts any list to a Json Array of user defined values
static List< T > JsonArrayToList< T > (this JsonArray jsonArray, Func< JsonValue, T > convertToObj)
Converts any JsonArray to List of user defined values
Detailed Description
Definition at line 9 of file JsonExtensions.cs.
Member Function Documentation
static JsonArray BGC.Extensions.JsonExtensions.AnyListToStringJsonArray< T > (this IList< T > list) inline static
Converts any list to a json array of string values
Definition at line 136 of file JsonExtensions.cs.
References LightJson.JsonArray.Add(), and LightJson.JsonArray.Count.
         {
             int size = list.Count;
             JsonArray jsonArray = new JsonArray();
             for (int i = 0; i < size; ++i)
             {
                 jsonArray.Add(list[i].ToString());
             }
             return jsonArray;
         }
static JsonArray BGC.Extensions.JsonExtensions.ConvertToJsonArray< T > (this List< T > list, Func< T, JsonValue > convertToJsonValue) inline static
Converts any list to a Json Array of user defined values
Definition at line 153 of file JsonExtensions.cs.
References LightJson.JsonArray.Add().
         {
             JsonArray array = new JsonArray();
             int length = list.Count;
             for(int i = 0; i < length; i++)
             {
                 array.Add(convertToJsonValue(list[i]));
             }
             return array;
         }
static JsonArray BGC.Extensions.JsonExtensions.FloatListToJsonArray (this IList< float > list) inline static
Converts a float list to a Json Array of float values
Definition at line 120 of file JsonExtensions.cs.
References LightJson.JsonArray.Add(), and LightJson.JsonArray.Count.
         {
             int size = list.Count;
             JsonArray jsonArray = new JsonArray();
             for (int i = 0; i < size; ++i)
             {
                 jsonArray.Add(list[i]);
             }
             return jsonArray;
         }
static JsonArray BGC.Extensions.JsonExtensions.IntListToJsonArray (this IList< int > list) inline static
Converts an int list to a Json Array of Int Values
Definition at line 104 of file JsonExtensions.cs.
References LightJson.JsonArray.Add(), and LightJson.JsonArray.Count.
         {
             int size = list.Count;
             JsonArray jsonArray = new JsonArray();
             for (int i = 0; i < size; ++i)
             {
                 jsonArray.Add(list[i]);
             }
             return jsonArray;
         }
static List<string> BGC.Extensions.JsonExtensions.JsonaArrayToStringList (this JsonArray jsonArray) inline static
Definition at line 56 of file JsonExtensions.cs.
References LightJson.JsonArray.Count.
         {
             List<string> stringList = new List<string>();
             int count = jsonArray.Count;
             for (int i = 0; i < count; ++i)
             {
                 stringList.Add(jsonArray[i]);
             }
             return stringList;
         }
static List<T> BGC.Extensions.JsonExtensions.JsonArrayToEnumList< T > (this JsonArray jsonArray, EnumSerialization enumSerialization) inline static
Converts Any Json Array to a List of Enums
Definition at line 88 of file JsonExtensions.cs.
         {
             int size = jsonArray.Count;
             List<T> enumList = new List<T>(size);
             for (int i = 0; i < size; ++i)
             {
                 enumList.Add(enumSerialization.StringToEnum<T>(jsonArray[i].AsString));
             }
             return enumList;
         }
static List<float> BGC.Extensions.JsonExtensions.JsonArrayToFloatList (this JsonArray jsonArray) inline static
Converts a Json Array to a List of floats
Definition at line 72 of file JsonExtensions.cs.
References LightJson.JsonArray.Count.
         {
             int size = jsonArray.Count;
             List<float> floatList = new List<float>(size);
             for (int i = 0; i < size; ++i)
             {
                 floatList.Add((float) jsonArray[i].AsNumber);
             }
             return floatList;
         }
static List<int> BGC.Extensions.JsonExtensions.JsonArrayToIntList (this JsonArray jsonArray) inline static
Converts a Json Array to a List of generic type T
Definition at line 48 of file JsonExtensions.cs.
References LightJson.JsonValue.AsInteger.
         {
             return jsonArray.JsonArrayToList((JsonValue val) =>
             {
                 return val.AsInteger;
             });
         }
static List<T> BGC.Extensions.JsonExtensions.JsonArrayToList< T > (this JsonArray jsonArray, Func< JsonValue, T > convertToObj) inline static
Converts any JsonArray to List of user defined values
Definition at line 169 of file JsonExtensions.cs.
References LightJson.JsonArray.Add().
         {
             List<T> list = new List<T>();
             for(int i = 0; i < jsonArray.Count; ++i)
             {
                 list.Add(convertToObj(jsonArray[i]));
             }
             return list;
         }
static JsonArray BGC.Extensions.JsonExtensions.TryGetArray (this JsonObject json, string key) inline static
Tries to get array and returns an empty array if not found
Definition at line 14 of file JsonExtensions.cs.
         {
             Assert.IsNotNull(json);
             Assert.IsFalse(string.IsNullOrEmpty(key));
             JsonArray jsonArr = json.TryGetValue(key);
             if(jsonArr == null)
             {
                 return new JsonArray();
             }
             return jsonArr;
         }
static JsonValue BGC.Extensions.JsonExtensions.TryGetValue (this JsonObject json, string key) inline static
Try and get value, if key is not there it adds the key
Definition at line 32 of file JsonExtensions.cs.
References LightJson.JsonObject.Add(), and LightJson.JsonObject.ContainsKey().
         {
             Assert.IsNotNull(json);
             Assert.IsFalse(string.IsNullOrEmpty(key));
             if (json.ContainsKey(key) == false)
             {
                 json.Add(key);
             }
             return json[key];
         }
The documentation for this class was generated from the following file:
Extensions/JsonExtensions.cs