BGC Tools: BGC.Tests.ZipTests Class Reference
BGC.Tests.ZipTests Class Reference
Public Member Functions
void TestZip ()
Detailed Description
Definition at line 13 of file ZipTests.cs.
Member Function Documentation
TestZip()
void BGC.Tests.ZipTests.TestZip () inline
Definition at line 16 of file ZipTests.cs.
References BGC.IO.Compression.Zip.CompressDirectory(), BGC.IO.Compression.Zip.DecompressFile(), BGC.IO.DataManagement.PathForDataFile(), and BGC.IO.DataManagement.PathForDataSubDirectory().
         {
             string compressedFilePath = DataManagement.PathForDataFile("Test", "ziptest.zip");
             string compressionPath = DataManagement.PathForDataSubDirectory("Test", "ZipTest");
             //Clear prior tests
             Directory.Delete(compressionPath, true);
             //
             //Create files with random contents
             //
             string[] fileNames = new string[]
             {
                 "Baron.txt",
                 "Silly test",
                 "Oh_Noes).asdf",
                 "Something is going to happen with this one maybe.int",
                 "What.bgc"
             };
             string[] subpaths = new string[]
             {
                 DataManagement.PathForDataSubDirectory("Test", "ZipTest"),
                 DataManagement.PathForDataSubDirectory("Test", "ZipTest", "SubA"),
                 DataManagement.PathForDataSubDirectory("Test", "ZipTest", "SubB")
             };
             string[,] fileContents = new string[subpaths.Length, 5];
             for (int p = 0; p < subpaths.Length; p++)
             {
                 string datapath = subpaths[p];
                 for (int i = 0; i < 5; i++)
                 {
                     fileContents[p, i] = $"{UnityEngine.Random.value}\n{UnityEngine.Random.value}";
                     File.WriteAllText(
                         Path.Combine(datapath, fileNames[i]),
                         fileContents[p, i]);
                 }
             }
             //
             //Compress contents
             //
             Zip.CompressDirectory(
                 inputPath: compressionPath,
                 outputFilePath: compressedFilePath);
             //
             //Delete Original Files
             //
             Directory.Delete(compressionPath, true);
             //
             //Decompress contents
             //
             Zip.DecompressFile(
                 inputFilePath: compressedFilePath,
                 outputPath: compressionPath);
             //
             //Verify Output
             //
             for (int p = 0; p < subpaths.Length; p++)
             {
                 string datapath = subpaths[p];
                 for (int i = 0; i < 5; i++)
                 {
                     Assert.IsTrue(File.Exists(Path.Combine(datapath, fileNames[i])));
                     string fileText = File.ReadAllText(Path.Combine(datapath, fileNames[i]));
                     Assert.IsTrue(fileContents[p, i] == fileText);
                 }
             }
             //
             //Delete Test Files
             //
             if (Directory.Exists(compressionPath))
             {
                 Directory.Delete(compressionPath, true);
             }
             //
             //Delete Zip File
             //
             if (File.Exists(compressedFilePath))
             {
                 File.Delete(compressedFilePath);
             }
         }
The documentation for this class was generated from the following file:
Editor/Tests/IO/Compression/ZipTests.cs