BGC Tools: BGC.Users.ProfileData Class Reference
BGC.Users.ProfileData Class Reference
Public Member Functions
ProfileData (string userName)
virtual void Clear ()
Clear all values and keys
void SetInt (string key, int value)
Set value at indicated key
void SetBool (string key, bool value)
Set value at indicated key
void SetString (string key, string value)
Set value at indicated key
void SetFloat (string key, float value)
Set value at indicated key
void SetDouble (string key, double value)
Set value at indicated key
void SetJsonValue (string key, JsonValue value)
Set value at indicated key
void SetJsonArray (string key, JsonArray value)
Set value at indicated key
int GetInt (string key, int defaultReturn=0)
Get value associated with indicated key
bool GetBool (string key, bool defaultReturn=false)
Get value associated with indicated key
float GetFloat (string key, float defaultReturn=0f)
Get value associated with indicated key
double GetDouble (string key, double defaultReturn=0.0)
Get value associated with indicated key
string GetString (string key, string defaultReturn="")
Get value associated with indicated key
JsonValue GetJsonValue (string key, JsonValue defaultReturn=default(JsonValue))
Get value associated with indicated key
JsonArray GetJsonArray (string key, JsonArray defaultReturn=default(JsonArray))
Get value associated with indicated key
bool HasKey (string key)
Get if any value is associated with indicated key
void RemoveKey (string key)
Remove any value is associated with indicated key
void Serialize ()
Save contents to file
bool Deserialize ()
Load user contents from file
virtual void DeletePlayerData ()
Protected Attributes
string PlayerFilePath
Path of the user datafile
Properties
string UserName [get]
abstract bool IsDefault [get]
Is this an instance of default data?
Private Attributes
JsonObject userData = new JsonObject()
const int userDataSerializationVersion = 1
Detailed Description
Definition at line 9 of file ProfileData.cs.
Constructor & Destructor Documentation
ProfileData()
BGC.Users.ProfileData.ProfileData (string userName) inline
Definition at line 17 of file ProfileData.cs.
         {
             UserName = userName;
         }
Member Function Documentation
Clear()
virtual void BGC.Users.ProfileData.Clear () inline virtual
Clear all values and keys
Definition at line 31 of file ProfileData.cs.
References LightJson.JsonObject.Clear().
         {
             userData.Clear();
         }
DeletePlayerData()
virtual void BGC.Users.ProfileData.DeletePlayerData () inline virtual
Reimplemented in BGC.Users.DefaultData.
Definition at line 312 of file ProfileData.cs.
Referenced by BGC.Users.PlayerData.DeleteUserData().
         {
             if (File.Exists(PlayerFilePath))
             {
                 File.Delete(PlayerFilePath);
             }
             Clear();
         }
Deserialize()
bool BGC.Users.ProfileData.Deserialize () inline
Load user contents from file
Definition at line 298 of file ProfileData.cs.
References LightJson.JsonObject.ContainsKey(), and BGC.IO.FileReader.ReadJsonFile().
Referenced by BGC.Users.PlayerData.DeleteUserData(), BGC.Users.PlayerData.GetMigrationData(), and BGC.Users.PlayerData.LogIn().
         {
             return FileReader.ReadJsonFile(
                 path: PlayerFilePath,
                 //If it is parsable, mark it as successfully loaded
                 successCallback: (JsonObject readData) =>
                 {
                     if (readData.ContainsKey("UserDicts"))
                     {
                         userData = readData["UserDicts"];
                     }
                 });
         }
GetBool()
bool BGC.Users.ProfileData.GetBool (string key, bool defaultReturn = false) inline
Get value associated with indicated key
Parameters
defaultReturn The value to return if the key is not present in dictionary
Definition at line 193 of file ProfileData.cs.
References LightJson.JsonObject.ContainsKey().
Referenced by BGC.Users.PlayerData.GetMigrationData().
         {
             if (userData.ContainsKey(key))
             {
                 if (userData[key].IsBoolean)
                 {
                     return userData[key].AsBoolean;
                 }
                 else if (userData[key].IsInteger)
                 {
                     return userData[key].AsInteger != 0;
                 }
             }
             return defaultReturn;
         }
GetDouble()
double BGC.Users.ProfileData.GetDouble (string key, double defaultReturn = 0.0) inline
Get value associated with indicated key
Parameters
defaultReturn The value to return if the key is not present in dictionary
Definition at line 224 of file ProfileData.cs.
References LightJson.JsonObject.ContainsKey().
         {
             if (userData.ContainsKey(key) && userData[key].IsNumber)
             {
                 return userData[key].AsNumber;
             }
             return defaultReturn;
         }
GetFloat()
float BGC.Users.ProfileData.GetFloat (string key, float defaultReturn = 0f) inline
Get value associated with indicated key
Parameters
defaultReturn The value to return if the key is not present in dictionary
Definition at line 212 of file ProfileData.cs.
References LightJson.JsonObject.ContainsKey().
         {
             if (userData.ContainsKey(key) && userData[key].IsNumber)
             {
                 return (float)userData[key].AsNumber;
             }
             return defaultReturn;
         }
GetInt()
int BGC.Users.ProfileData.GetInt (string key, int defaultReturn = 0) inline
Get value associated with indicated key
Parameters
defaultReturn The value to return if the key is not present in dictionary
Definition at line 181 of file ProfileData.cs.
References LightJson.JsonObject.ContainsKey().
         {
             if (userData.ContainsKey(key) && userData[key].IsInteger)
             {
                 return userData[key].AsInteger;
             }
             return defaultReturn;
         }
GetJsonArray()
JsonArray BGC.Users.ProfileData.GetJsonArray (string key, JsonArray defaultReturn = default(JsonArray)) inline
Get value associated with indicated key
Parameters
defaultReturn The value to return if the key is not present in dictionary
Definition at line 260 of file ProfileData.cs.
References LightJson.JsonObject.ContainsKey(), and LightJson.JsonObject.Remove().
         {
             if (userData.ContainsKey(key))
             {
                 return userData[key];
             }
             return defaultReturn;
         }
GetJsonValue()
JsonValue BGC.Users.ProfileData.GetJsonValue (string key, JsonValue defaultReturn = default(JsonValue)) inline
Get value associated with indicated key
Parameters
defaultReturn The value to return if the key is not present in dictionary
Definition at line 248 of file ProfileData.cs.
References LightJson.JsonObject.ContainsKey().
         {
             if (userData.ContainsKey(key))
             {
                 return userData[key];
             }
             return defaultReturn;
         }
GetString()
string BGC.Users.ProfileData.GetString (string key, string defaultReturn = "") inline
Get value associated with indicated key
Parameters
defaultReturn The value to return if the key is not present in dictionary
Definition at line 236 of file ProfileData.cs.
References LightJson.JsonObject.ContainsKey().
Referenced by BGC.Users.PlayerData.GetMigrationData().
         {
             if (userData.ContainsKey(key) && userData[key].IsString)
             {
                 return userData[key].AsString;
             }
             return defaultReturn;
         }
HasKey()
bool BGC.Users.ProfileData.HasKey (string key)
Get if any value is associated with indicated key
RemoveKey()
void BGC.Users.ProfileData.RemoveKey (string key)
Remove any value is associated with indicated key
Serialize()
void BGC.Users.ProfileData.Serialize () inline
Save contents to file
Definition at line 277 of file ProfileData.cs.
References BGC.IO.FileWriter.WriteJson().
Referenced by BGC.Users.PlayerData.AddUser().
         {
             //Don't serialize out blank usernames
             if (UserName.CompareTo("") == 0)
             {
                 Debug.LogError("Tried to serialize out a profile with a blank username.");
                 return;
             }
             FileWriter.WriteJson(
                 path: PlayerFilePath,
                 createJson: () => new JsonObject
                 {
                     { "Version", userDataSerializationVersion },
                     { "UserName", UserName },
                     { "UserDicts", userData }
                 },
                 pretty: true);
         }
SetBool()
void BGC.Users.ProfileData.SetBool (string key, bool value) inline
Set value at indicated key
Definition at line 59 of file ProfileData.cs.
References LightJson.JsonObject.Add(), and LightJson.JsonObject.ContainsKey().
         {
             if (userData.ContainsKey(key) == false)
             {
                 //Data did not exist - add it
                 userData.Add(key, value);
             }
             else
             {
                 //Check existing data for type match
                 if (userData[key].IsBoolean == false)
                 {
                     if (userData[key].IsInteger)
                     {
                         Debug.LogWarning($"PlayerData \"{key}\" Datatype changed from {userData[key].Type.ToString()} to Bool");
                     }
                     else
                     {
                         Debug.LogError($"PlayerData \"{key}\" Datatype changed from {userData[key].Type.ToString()} to Bool");
                     }
                 }
                 //Set data
                 userData[key] = value;
             }
         }
SetDouble()
void BGC.Users.ProfileData.SetDouble (string key, double value) inline
Set value at indicated key
Definition at line 129 of file ProfileData.cs.
References LightJson.JsonObject.Add(), and LightJson.JsonObject.ContainsKey().
         {
             if (userData.ContainsKey(key) == false)
             {
                 //Data did not exist - add it
                 userData.Add(key, value);
             }
             else
             {
                 //Check existing data for type match
                 if (userData[key].IsNumber == false)
                 {
                     Debug.LogError($"PlayerData \"{key}\" Datatype changed from {userData[key].Type.ToString()} to Number");
                 }
                 //Set data
                 userData[key] = value;
             }
         }
SetFloat()
void BGC.Users.ProfileData.SetFloat (string key, float value) inline
Set value at indicated key
Definition at line 108 of file ProfileData.cs.
References LightJson.JsonObject.Add(), and LightJson.JsonObject.ContainsKey().
         {
             if (userData.ContainsKey(key) == false)
             {
                 //Data did not exist - add it
                 userData.Add(key, value);
             }
             else
             {
                 //Check existing data for type match
                 if (userData[key].IsNumber == false)
                 {
                     Debug.LogError($"PlayerData \"{key}\" Datatype changed from {userData[key].Type.ToString()} to Number");
                 }
                 //Set data
                 userData[key] = value;
             }
         }
SetInt()
void BGC.Users.ProfileData.SetInt (string key, int value) inline
Set value at indicated key
Definition at line 37 of file ProfileData.cs.
References LightJson.JsonObject.Add(), and LightJson.JsonObject.ContainsKey().
         {
             if (userData.ContainsKey(key) == false)
             {
                 //Data did not exist - add it
                 userData.Add(key, value);
             }
             else
             {
                 //Check existing data for type match
                 if (userData[key].IsInteger == false)
                 {
                     Debug.LogError($"PlayerData \"{key}\" Datatype changed from {userData[key].Type.ToString()} to Int");
                 }
                 //Set data
                 userData[key] = value;
             }
         }
SetJsonArray()
void BGC.Users.ProfileData.SetJsonArray (string key, JsonArray value) inline
Set value at indicated key
Definition at line 165 of file ProfileData.cs.
References LightJson.JsonObject.Add(), and LightJson.JsonObject.ContainsKey().
         {
             if (userData.ContainsKey(key) == false)
             {
                 //Data did not exist - add it
                 userData.Add(key, value);
             }
             else
             {
                 //Set data
                 userData[key] = value;
             }
         }
SetJsonValue()
void BGC.Users.ProfileData.SetJsonValue (string key, JsonValue value) inline
Set value at indicated key
Definition at line 150 of file ProfileData.cs.
References LightJson.JsonObject.Add(), and LightJson.JsonObject.ContainsKey().
         {
             if (userData.ContainsKey(key) == false)
             {
                 //Data did not exist - add it
                 userData.Add(key, value);
             }
             else
             {
                 //Set data
                 userData[key] = value;
             }
         }
SetString()
void BGC.Users.ProfileData.SetString (string key, string value) inline
Set value at indicated key
Definition at line 87 of file ProfileData.cs.
References LightJson.JsonObject.Add(), and LightJson.JsonObject.ContainsKey().
         {
             if (userData.ContainsKey(key) == false)
             {
                 //Data did not exist - add it
                 userData.Add(key, value);
             }
             else
             {
                 //Check existing data for type match
                 if (userData[key].IsString == false)
                 {
                     Debug.LogError($"PlayerData \"{key}\" Datatype changed from {userData[key].Type.ToString()} to String");
                 }
                 //Set data
                 userData[key] = value;
             }
         }
Field Documentation
PlayerFilePath
string BGC.Users.ProfileData.PlayerFilePath protected
Initial value:
=> DataManagement.PathForDataFile(
            dataDirectory: PlayerData.UserDataDir,
            fileName: FileExtensions.AddJsonExtension(UserName))
Path of the user datafile
Definition at line 26 of file ProfileData.cs.
userData
JsonObject BGC.Users.ProfileData.userData = new JsonObject() private
Definition at line 13 of file ProfileData.cs.
userDataSerializationVersion
const int BGC.Users.ProfileData.userDataSerializationVersion = 1 private
Definition at line 15 of file ProfileData.cs.
Property Documentation
IsDefault
abstract bool BGC.Users.ProfileData.IsDefault get
Is this an instance of default data?
Definition at line 23 of file ProfileData.cs.
UserName
string BGC.Users.ProfileData.UserName get
Definition at line 11 of file ProfileData.cs.
Referenced by BGC.Users.PlayerData.GetMigrationData().
The documentation for this class was generated from the following file:
Users/ProfileData.cs