BGC Tools: BGC.Audio.Filters.StreamConcatenator Class Reference
BGC.Audio.Filters.StreamConcatenator Class Reference
Appends multiple streams, end-to-end. Expects each stream to have the same number of channels and sampling rate.
Public Member Functions
StreamConcatenator ()
StreamConcatenator (params IBGCStream[] streams)
StreamConcatenator (IEnumerable< IBGCStream > streams)
void AddStream (IBGCStream stream)
void AddStreams (IEnumerable< IBGCStream > streams)
override void Reset ()
Sets this internal state of this stream to the initial state
override int Read (float[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
override void Seek (int position)
Seek to the indicated position in the stream
override IEnumerable< double > GetChannelRMS ()
The RMS amplitude of each channel
Public Member Functions inherited from BGC.Audio.Filters.BGCFilter
virtual void Initialize ()
Perform any calculations necessary to prepare the Stream
Data Fields
override IEnumerable< IBGCStream > InternalStreams => streams
override int Channels => _channels
override int TotalSamples => Channels * ChannelSamples
override int ChannelSamples => _channelSampleCount
override float SamplingRate => _samplingRate
Properties
int CurrentClipIndex [get, private set]
int Position [get, private set]
Properties inherited from BGC.Audio.Filters.BGCFilter
abstract int Channels [get]
abstract int TotalSamples [get]
abstract int ChannelSamples [get]
abstract float SamplingRate [get]
abstract IEnumerable< IBGCStream > InternalStreams [get]
Properties inherited from BGC.Audio.IBGCStream
int Channels [get]
The number of underlying Channels of this BGCStream
int TotalSamples [get]
The total number of Samples of this BGCStream
int ChannelSamples [get]
The number of Samples of each channel for this BGCStream
float SamplingRate [get]
The sampling rate of the Stream
Private Member Functions
void UpdateStats ()
Private Attributes
readonly List< IBGCStream > streams = new List<IBGCStream>()
int _channels = 1
int _channelSampleCount = 0
float _samplingRate
IEnumerable< double > _channelRMS = null
Additional Inherited Members
Protected Member Functions inherited from BGC.Audio.Filters.BGCFilter
virtual void _Initialize ()
Protected Attributes inherited from BGC.Audio.Filters.BGCFilter
bool initialized = false
Detailed Description
Appends multiple streams, end-to-end. Expects each stream to have the same number of channels and sampling rate.
Definition at line 11 of file StreamConcatenator.cs.
Constructor & Destructor Documentation
BGC.Audio.Filters.StreamConcatenator.StreamConcatenator () inline
Definition at line 30 of file StreamConcatenator.cs.
         {
             UpdateStats();
         }
BGC.Audio.Filters.StreamConcatenator.StreamConcatenator (params IBGCStream[] streams) inline
Definition at line 35 of file StreamConcatenator.cs.
         {
             AddStreams(streams);
         }
BGC.Audio.Filters.StreamConcatenator.StreamConcatenator (IEnumerable< IBGCStream > streams) inline
Definition at line 40 of file StreamConcatenator.cs.
         {
             AddStreams(streams);
         }
Member Function Documentation
void BGC.Audio.Filters.StreamConcatenator.AddStream (IBGCStream stream) inline
Definition at line 45 of file StreamConcatenator.cs.
         {
             streams.Add(stream);
             UpdateStats();
         }
void BGC.Audio.Filters.StreamConcatenator.AddStreams (IEnumerable< IBGCStream > streams) inline
Definition at line 51 of file StreamConcatenator.cs.
         {
             this.streams.AddRange(streams);
             UpdateStats();
         }
override IEnumerable<double> BGC.Audio.Filters.StreamConcatenator.GetChannelRMS () inline virtual
The RMS amplitude of each channel
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 163 of file StreamConcatenator.cs.
References BGC.Audio.IBGCStream.ChannelSamples, and BGC.Audio.IBGCStream.GetChannelRMS().
         {
             if (_channelRMS == null)
             {
                 double[] rms = new double[Channels];
                 foreach (IBGCStream stream in streams)
                 {
                     double[] streamRMS = stream.GetChannelRMS().ToArray();
                     for (int i = 0; i < Channels; i++)
                     {
                         rms[i] += (stream.ChannelSamples / (double)ChannelSamples) * streamRMS[i];
                     }
                 }
                 for (int i = 0; i < Channels; i++)
                 {
                     rms[i] = Math.Sqrt(rms[i]);
                 }
                 _channelRMS = rms;
             }
             return _channelRMS;
         }
override int BGC.Audio.Filters.StreamConcatenator.Read (float[] data, int offset, int count) inline virtual
Copy count samples into the Data buffer, starting at offset.
Returns
The number of samples copied
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 64 of file StreamConcatenator.cs.
References BGC.Audio.IBGCStream.Read().
         {
             int remainingSamples = count;
             while (remainingSamples > 0)
             {
                 if (CurrentClipIndex >= streams.Count)
                 {
                     //Hit the end
                     break;
                 }
                 IBGCStream stream = streams[CurrentClipIndex];
                 int readSamples = stream.Read(data, offset, remainingSamples);
                 remainingSamples -= readSamples;
                 offset += readSamples;
                 Position += readSamples / Channels;
                 if (readSamples <= 0)
                 {
                     CurrentClipIndex++;
                     if (CurrentClipIndex < streams.Count)
                     {
                         //Reset on advancing allows a concatenator to hold multiple
                         //copies of the same clip
                         streams[CurrentClipIndex].Reset();
                     }
                 }
             }
             return count - remainingSamples;
         }
override void BGC.Audio.Filters.StreamConcatenator.Reset () inline virtual
Sets this internal state of this stream to the initial state
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 57 of file StreamConcatenator.cs.
         {
             CurrentClipIndex = 0;
             Position = 0;
             streams.ForEach(x => x.Reset());
         }
override void BGC.Audio.Filters.StreamConcatenator.Seek (int position) inline virtual
Seek to the indicated position in the stream
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 100 of file StreamConcatenator.cs.
References BGC.Audio.IBGCStream.ChannelSamples, BGC.Audio.IBGCStream.Reset(), and BGC.Audio.IBGCStream.Seek().
         {
             Position = position;
             CurrentClipIndex = streams.Count;
             for (int i = 0; i < streams.Count; i++)
             {
                 IBGCStream clip = streams[i];
                 if (position > 0)
                 {
                     //Seek
                     if (position > clip.ChannelSamples)
                     {
                         clip.Seek(clip.ChannelSamples);
                         position -= clip.ChannelSamples;
                     }
                     else
                     {
                         clip.Seek(position);
                         position = 0;
                         CurrentClipIndex = i;
                     }
                 }
                 else
                 {
                     clip.Reset();
                 }
             }
         }
void BGC.Audio.Filters.StreamConcatenator.UpdateStats () inline private
Definition at line 130 of file StreamConcatenator.cs.
         {
             if (streams.Count > 0)
             {
                 IEnumerable<int> channels = streams.Select(x => x.Channels);
                 _channels = channels.Max();
                 if (_channels != channels.Min())
                 {
                     throw new Exception("AudioClipConcatenator requires all streams have the same channel count.");
                 }
                 IEnumerable<float> samplingRates = streams.Select(x => x.SamplingRate);
                 _samplingRate = samplingRates.Max();
                 if (_samplingRate != samplingRates.Min())
                 {
                     throw new Exception("AudioClipConcatenator requires all streams have the same samplingRate.");
                 }
                 _channelSampleCount = streams.Select(x => x.ChannelSamples).Sum();
                 _channelRMS = null;
             }
             else
             {
                 _channels = 1;
                 _channelSampleCount = 0;
                 _samplingRate = 44100f;
                 _channelRMS = null;
             }
         }
Field Documentation
IEnumerable<double> BGC.Audio.Filters.StreamConcatenator._channelRMS = null private
Definition at line 162 of file StreamConcatenator.cs.
int BGC.Audio.Filters.StreamConcatenator._channels = 1 private
Definition at line 16 of file StreamConcatenator.cs.
int BGC.Audio.Filters.StreamConcatenator._channelSampleCount = 0 private
Definition at line 21 of file StreamConcatenator.cs.
float BGC.Audio.Filters.StreamConcatenator._samplingRate private
Definition at line 24 of file StreamConcatenator.cs.
override int BGC.Audio.Filters.StreamConcatenator.Channels => _channels
Definition at line 17 of file StreamConcatenator.cs.
override int BGC.Audio.Filters.StreamConcatenator.ChannelSamples => _channelSampleCount
Definition at line 22 of file StreamConcatenator.cs.
override IEnumerable<IBGCStream> BGC.Audio.Filters.StreamConcatenator.InternalStreams => streams
Definition at line 14 of file StreamConcatenator.cs.
override float BGC.Audio.Filters.StreamConcatenator.SamplingRate => _samplingRate
Definition at line 25 of file StreamConcatenator.cs.
readonly List<IBGCStream> BGC.Audio.Filters.StreamConcatenator.streams = new List<IBGCStream>() private
Definition at line 13 of file StreamConcatenator.cs.
override int BGC.Audio.Filters.StreamConcatenator.TotalSamples => Channels * ChannelSamples
Definition at line 19 of file StreamConcatenator.cs.
Property Documentation
int BGC.Audio.Filters.StreamConcatenator.CurrentClipIndex get private set
Definition at line 27 of file StreamConcatenator.cs.
int BGC.Audio.Filters.StreamConcatenator.Position get private set
Definition at line 28 of file StreamConcatenator.cs.
The documentation for this class was generated from the following file:
Audio/Filters/StreamConcatenator.cs