BGC Tools: BGC.Audio.Midi.Events.ChannelMidiEvent Class Reference
BGC.Audio.Midi.Events.ChannelMidiEvent Class Reference
Public Types
enum ChannelEventType {
ChannelEventType.Note = 0, ChannelEventType.Controller, ChannelEventType.Program, ChannelEventType.ChannelPressure,
ChannelEventType.PitchBend, ChannelEventType.Mode
}
Public Types inherited from BGC.Audio.Midi.Events.MidiEvent
enum MidiMessageClass {
MidiMessageClass.ChannelEvent = 0, MidiMessageClass.SysexEvent, MidiMessageClass.SysCommEvent, MidiMessageClass.SysRTEvent,
MidiMessageClass.MetaEvent, MidiMessageClass.MAX
}
Public Member Functions
ChannelMidiEvent (int deltaTime, byte eventCode)
Public Member Functions inherited from BGC.Audio.Midi.Events.MidiEvent
MidiEvent (int deltaTime, byte eventCode)
void Serialize (Stream outputStream, bool running)
abstract void ExecuteEvent (MidiTrack track)
override string ToString ()
Static Public Member Functions
static ChannelMidiEvent ParseChannelEvent (Stream inputStream, int deltaTime, byte eventCode, byte nextByte)
Static Public Member Functions inherited from BGC.Audio.Midi.Events.MidiEvent
static MidiEvent ParseEvent (Stream inputStream, int deltaTime, byte eventCode, byte nextByte)
Data Fields
override MidiMessageClass MessageClass => MidiMessageClass.ChannelEvent
Data Fields inherited from BGC.Audio.Midi.Events.MidiEvent
int time
int deltaTime
readonly byte eventCode
virtual bool Essential => true
virtual int Length => deltaTime.GetVarQuantitySize()
Protected Member Functions
override void Serialize (Stream outputStream)
Properties
abstract ChannelEventType EventType [get]
Properties inherited from BGC.Audio.Midi.Events.MidiEvent
abstract string EventName [get]
abstract MidiMessageClass MessageClass [get]
Detailed Description
Definition at line 6 of file ChannelMidiEvent.cs.
Member Enumeration Documentation
ChannelEventType
enum BGC.Audio.Midi.Events.ChannelMidiEvent.ChannelEventType strong
Enumerator
Note
Controller
Program
ChannelPressure
PitchBend
Mode
Definition at line 8 of file ChannelMidiEvent.cs.
         {
             Note = 0,
             Controller,
             Program,
             ChannelPressure,
             PitchBend,
             Mode
         }
Constructor & Destructor Documentation
ChannelMidiEvent()
BGC.Audio.Midi.Events.ChannelMidiEvent.ChannelMidiEvent (int deltaTime, byte eventCode) inline
Definition at line 21 of file ChannelMidiEvent.cs.
             : base(deltaTime, eventCode)
         {
         }
Member Function Documentation
ParseChannelEvent()
static ChannelMidiEvent BGC.Audio.Midi.Events.ChannelMidiEvent.ParseChannelEvent (Stream inputStream, int deltaTime, byte eventCode, byte nextByte) inline static
Definition at line 27 of file ChannelMidiEvent.cs.
References BGC.Audio.Midi.Events.ChannelPressureMidiEvent.ParseChannelPressureMidiEvent(), BGC.Audio.Midi.Events.ControllerMidiEvent.ParseControllerMidiEvent(), BGC.Audio.Midi.Events.NoteMidiEvent.ParseNoteMidiEvent(), BGC.Audio.Midi.Events.PitchBendMidiEvent.ParsePitchBendMidiEvent(), and BGC.Audio.Midi.Events.ProgramMidiEvent.ParseProgramMidiEvent().
Referenced by BGC.Audio.Midi.Events.MidiEvent.ParseEvent().
         {
             switch (eventCode & 0b1111_0000)
             {
                 case 0x80:
                 case 0x90:
                 case 0xA0:
                     return NoteMidiEvent.ParseNoteMidiEvent(deltaTime, eventCode, nextByte, (byte)inputStream.ReadByte());
                 case 0xB0:
                     return ControllerMidiEvent.ParseControllerMidiEvent(deltaTime, eventCode, nextByte, (byte)inputStream.ReadByte());
                 case 0xC0:
                     return ProgramMidiEvent.ParseProgramMidiEvent(deltaTime, eventCode, nextByte);
                 case 0xD0:
                     return ChannelPressureMidiEvent.ParseChannelPressureMidiEvent(deltaTime, eventCode, nextByte);
                 case 0xE0:
                     return PitchBendMidiEvent.ParsePitchBendMidiEvent(inputStream, deltaTime, eventCode, nextByte);
                 default:
                     throw new MidiParsingException($"Encountered Unknown Channel Midi Event: {eventCode:X2}");
             }
         }
Serialize()
override void BGC.Audio.Midi.Events.ChannelMidiEvent.Serialize (Stream outputStream) inline protected virtual
Implements BGC.Audio.Midi.Events.MidiEvent.
Reimplemented in BGC.Audio.Midi.Events.ControllerMidiEvent, BGC.Audio.Midi.Events.NoteMidiEvent, BGC.Audio.Midi.Events.ProgramMidiEvent, BGC.Audio.Midi.Events.PitchBendMidiEvent, and BGC.Audio.Midi.Events.ChannelPressureMidiEvent.
Definition at line 57 of file ChannelMidiEvent.cs.
 { }
Field Documentation
MessageClass
override MidiMessageClass BGC.Audio.Midi.Events.ChannelMidiEvent.MessageClass => MidiMessageClass.ChannelEvent
Definition at line 19 of file ChannelMidiEvent.cs.
Property Documentation
EventType
abstract ChannelEventType BGC.Audio.Midi.Events.ChannelMidiEvent.EventType get
Definition at line 18 of file ChannelMidiEvent.cs.
The documentation for this class was generated from the following file:
Audio/Midi/Events/ChannelMidiEvent.cs