BGC Tools: BGC.Utility.BgcToJson Class Reference
BGC.Utility.BgcToJson Class Reference
Data Structures
class RequiredFields
Static Public Member Functions
static JsonObject ConvertBgcToJson (string bgc, char separator= '\n', bool verbose=false)
Convert complete string of bgc to json
static JsonObject ConvertBGCToJson (string[] bgc, bool verbose=false)
Convert lines of bgc to complete json
Static Private Member Functions
static bool MetaDataHasCorrectFields (JsonObject metaData, bool verbose)
Test to see whether or not the meta data has all the correct fields
static void RemoveRedundantMetaData (JsonObject metaData)
Remove any redundant meta data fields from the json object
static JsonObject ConvertLine (JsonObject metaData, string[] splitBy, string line)
Convert every line into a json object based on the meta data
Detailed Description
Definition at line 8 of file BgcToJson.cs.
Member Function Documentation
static JsonObject BGC.Utility.BgcToJson.ConvertBgcToJson (string bgc, char separator = '\n', bool verbose = false) inline static
Convert complete string of bgc to json
Parameters
bgc
verbose
Returns
Definition at line 41 of file BgcToJson.cs.
Referenced by BGC.Web.AWSServer.PostBGCToJSonToAWS().
         {
             return ConvertBGCToJson(bgc.Split(separator), verbose);
         }
static JsonObject BGC.Utility.BgcToJson.ConvertBGCToJson (string[] bgc, bool verbose = false) inline static
Convert lines of bgc to complete json
Parameters
bgc
verbose
Returns
Definition at line 52 of file BgcToJson.cs.
References LightJson.JsonObject.Add(), LightJson.JsonArray.Add(), BGC.Utility.BgcToJson.RequiredFields.Data, BGC.IO.Logging.LoggingKeys.Delimiter, BGC.Utility.BgcToJson.RequiredFields.MetaData, LightJson.Serialization.JsonReader.Parse(), and LightJson.String.
         {
             JsonObject json = new JsonObject();
             JsonObject metaData = LightJson.Serialization.JsonReader.Parse(bgc[0]);
             Assert.IsTrue(MetaDataHasCorrectFields(metaData, verbose));
             JsonArray data = new JsonArray();
             string[] delimiter = new string[] { metaData[LoggingKeys.Delimiter].AsString };
             for (int i = 1; i < bgc.Length; ++i)
             {
                 if (String.IsNullOrEmpty(bgc[i]) == false)
                 {
                     data.Add(ConvertLine(metaData, delimiter, bgc[i]));
                 }
             }
             RemoveRedundantMetaData(metaData);
             json.Add(RequiredFields.MetaData, metaData);
             json.Add(RequiredFields.Data, data);
             return json;
         }
static JsonObject BGC.Utility.BgcToJson.ConvertLine (JsonObject metaData, string[] splitBy, string line) inline static private
Convert every line into a json object based on the meta data
Parameters
metaData
splitBy
line
Returns
Json object representing the line based on the colum manpping
Definition at line 124 of file BgcToJson.cs.
References LightJson.JsonObject.Add(), BGC.IO.Logging.LoggingKeys.ColumnMapping, LightJson.JsonObject.ContainsKey(), LightJson.JsonArray.Count, BGC.IO.Logging.LoggingKeys.DefaultColumn, LightJson.JsonObject.ToString(), and BGC.IO.Logging.LoggingKeys.ValueMapping.
         {
             JsonObject jsonData = new JsonObject();
             string[] data = line.Split(splitBy, StringSplitOptions.None);
             string columnMappingKey;
             if (metaData[LoggingKeys.ColumnMapping].AsJsonObject.ContainsKey(data[0]))
             {
                 columnMappingKey = data[0];
             }
             else
             {
                 columnMappingKey = LoggingKeys.DefaultColumn;
             }
             JsonArray columnMapping = metaData[LoggingKeys.ColumnMapping][columnMappingKey];
             Assert.AreEqual(data.Length, columnMapping.Count);
             bool b;
             int intNum;
             float floatNum;
             for (int i = 0; i < data.Length; ++i)
             {
                 if (bool.TryParse(data[i], out b))
                 {
                     jsonData.Add(columnMapping[i], b);
                 }
                 else if (int.TryParse(data[i], out intNum))
                 {
                     jsonData.Add(columnMapping[i], intNum);
                 }
                 else if (float.TryParse(data[i], out floatNum))
                 {
                     jsonData.Add(columnMapping[i], floatNum);
                 }
                 else
                 {
                     jsonData.Add(columnMapping[i], data[i]);
                 }
                 JsonObject valueMapping = metaData[LoggingKeys.ValueMapping];
                 if (valueMapping.ContainsKey(columnMapping[i]))
                 {
                     JsonObject mapping = valueMapping[columnMapping[i]];
                     string key = jsonData[columnMapping[i]].AsInteger.ToString();
                     if (mapping.ContainsKey(key))
                     {
                         jsonData[columnMapping[i]] = mapping[key];
                     }
                 }
             }
             return jsonData;
         }
static bool BGC.Utility.BgcToJson.MetaDataHasCorrectFields (JsonObject metaData, bool verbose) inline static private
Test to see whether or not the meta data has all the correct fields
Parameters
metaData
verbose
Returns
True if the meta data has all the correct fields
Definition at line 81 of file BgcToJson.cs.
References LightJson.JsonObject.ContainsKey(), and BGC.Utility.BgcToJson.RequiredFields.MetaDataFields.
         {
             bool hasRequiredFields = true;
             for (int i = 0; i < RequiredFields.MetaDataFields.Length; ++i)
             {
                 if (metaData.ContainsKey(RequiredFields.MetaDataFields[i]) == false)
                 {
                     if (verbose)
                     {
                         Console.WriteLine($"Required meta data field \"{RequiredFields.MetaDataFields[i]}\" not found.");
                     }
                     hasRequiredFields = false;
                     break;
                 }
             }
             return hasRequiredFields;
         }
static void BGC.Utility.BgcToJson.RemoveRedundantMetaData (JsonObject metaData) inline static private
Remove any redundant meta data fields from the json object
Parameters
metaData
Definition at line 106 of file BgcToJson.cs.
References LightJson.JsonObject.ContainsKey(), BGC.Utility.BgcToJson.RequiredFields.RedundantFields, and LightJson.JsonObject.Remove().
         {
             for (int i = 0; i < RequiredFields.RedundantFields.Length; ++i)
             {
                 if (metaData.ContainsKey(RequiredFields.RedundantFields[i]))
                 {
                     metaData.Remove(RequiredFields.RedundantFields[i]);
                 }
             }
         }
The documentation for this class was generated from the following file:
Utility/BgcToJson.cs