BGC Tools: BGC.StateMachine.Transition< TBoolEnum, TTriggerEnum > Class Template Reference
BGC.StateMachine.Transition< TBoolEnum, TTriggerEnum > Class Template Reference
This defines a transition between two states with the required transition conditions for the transition to occur
Public Member Functions
Transition (State targetState, params TransitionCondition< TBoolEnum, TTriggerEnum >[] transitionConditions)
Construct abstract transtion to define path
void SetStateDataRetrievers (ITransitionDataRetriever< TBoolEnum, TTriggerEnum > stateMachine)
Add state machine data which is required for checking info
bool ShouldTransition ()
Test whether or not this transition should occur
void OnTransition ()
Right before a transition this function is called so the transition and clean anything it has done up. For example: deactivating any triggers it has used is required
Data Fields
readonly State TargetState
Get name of the state this transition goes to
Protected Attributes
ITransitionDataRetriever< TBoolEnum, TTriggerEnum > stateMachine
Private Attributes
readonly TransitionCondition< TBoolEnum, TTriggerEnum > [] transitionConditions
Detailed Description
This defines a transition between two states with the required transition conditions for the transition to occur
Type Constraints
TBoolEnum : Enum
TTriggerEnum : Enum
Definition at line 9 of file Transition.cs.
Constructor & Destructor Documentation
Transition()
BGC.StateMachine.Transition< TBoolEnum, TTriggerEnum >.Transition (State targetState, params TransitionCondition< TBoolEnum, TTriggerEnum > [] transitionConditions) inline
Construct abstract transtion to define path
Definition at line 25 of file Transition.cs.
         {
             TargetState = targetState ?? throw new ArgumentNullException(
                 paramName: nameof(targetState),
                 message: "Transition target state cannot be null.");
             this.transitionConditions = transitionConditions ?? throw new ArgumentNullException(
                 paramName: nameof(transitionConditions),
                 message: "Transition conditions cannot be null.");
             for (int i = 0; i < transitionConditions.Length; ++i)
             {
                 if (transitionConditions[i] == null)
                 {
                     throw new ArgumentNullException(
                         paramName: nameof(transitionConditions),
                         message: $"Transition conditions element {i} is null and should not be.");
                 }
             }
         }
Member Function Documentation
OnTransition()
void BGC.StateMachine.Transition< TBoolEnum, TTriggerEnum >.OnTransition () inline
Right before a transition this function is called so the transition and clean anything it has done up. For example: deactivating any triggers it has used is required
Definition at line 88 of file Transition.cs.
Referenced by BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >.ExecuteTransitions().
         {
             for (int i = 0; i < transitionConditions.Length; ++i)
             {
                 transitionConditions[i].OnTransition();
             }
         }
SetStateDataRetrievers()
void BGC.StateMachine.Transition< TBoolEnum, TTriggerEnum >.SetStateDataRetrievers (ITransitionDataRetriever< TBoolEnum, TTriggerEnum > stateMachine) inline
Add state machine data which is required for checking info
Definition at line 51 of file Transition.cs.
Referenced by BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >.AddAnyStateTransition(), and BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >.AddTransition().
         {
             this.stateMachine = stateMachine ?? throw new ArgumentNullException(
                 paramName: nameof(stateMachine),
                 message: "stateMachine argument cannot be null.");
             for (int i = 0; i < transitionConditions.Length; ++i)
             {
                 transitionConditions[i].SetStateMachineFunctions(stateMachine);
             }
         }
ShouldTransition()
bool BGC.StateMachine.Transition< TBoolEnum, TTriggerEnum >.ShouldTransition () inline
Test whether or not this transition should occur
Returns
True if a transition should occur
Definition at line 67 of file Transition.cs.
         {
             bool shouldTransfer = true;
             for (int i = 0; i < transitionConditions.Length; ++i)
             {
                 shouldTransfer &= transitionConditions[i].ShouldTransition();
                 if (shouldTransfer == false)
                 {
                     break;
                 }
             }
             return shouldTransfer;
         }
Field Documentation
stateMachine
ITransitionDataRetriever<TBoolEnum, TTriggerEnum> BGC.StateMachine.Transition< TBoolEnum, TTriggerEnum >.stateMachine protected
Definition at line 15 of file Transition.cs.
TargetState
readonly State BGC.StateMachine.Transition< TBoolEnum, TTriggerEnum >.TargetState
Get name of the state this transition goes to
Definition at line 20 of file Transition.cs.
Referenced by BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >.ExecuteTransitions().
transitionConditions
readonly TransitionCondition<TBoolEnum, TTriggerEnum> [] BGC.StateMachine.Transition< TBoolEnum, TTriggerEnum >.transitionConditions private
Definition at line 13 of file Transition.cs.
The documentation for this class was generated from the following file:
StateMachine/Transition.cs