BGC Tools: BGC.Audio.Visualization.SpectralDecomp Class Reference
BGC.Audio.Visualization.SpectralDecomp Class Reference
Public Member Functions
SpectralDecomp (double minFreq, double maxFreq, int windowSize, int windowCount)
void Add (int window, Complex64[] fftBuffer)
double Linterp (int window, double frequency)
Data Fields
double MinFreq => freqs[0]
double MaxFreq => freqs[freqs.Length - 1]
double[,] spectralValues
double[] freqs
double minAmplitude
double maxAmplitude
Private Attributes
readonly int fftMinFreqBin
readonly int fftMaxFreqBin
readonly double amplitudeAdjustant
Detailed Description
Definition at line 89 of file Spectrogram.cs.
Constructor & Destructor Documentation
BGC.Audio.Visualization.SpectralDecomp.SpectralDecomp (double minFreq, double maxFreq, int windowSize, int windowCount) inline
Definition at line 104 of file Spectrogram.cs.
References BGC.Audio.FrequencyDomain.GetComplexFrequencyBin(), and BGC.Audio.FrequencyDomain.GetComplexSampleFrequency().
         {
             fftMinFreqBin = FrequencyDomain.GetComplexFrequencyBin(windowSize, minFreq);
             //+2 to round outward AND to act as an exclusive upperbound
             fftMaxFreqBin = FrequencyDomain.GetComplexFrequencyBin(windowSize, maxFreq) + 2;
             fftMaxFreqBin = Math.Min(fftMaxFreqBin, windowSize / 2);
             spectralValues = new double[windowCount, fftMaxFreqBin - fftMinFreqBin];
             freqs = new double[fftMaxFreqBin - fftMinFreqBin];
             for (int i = 0; i < freqs.Length; i++)
             {
                 freqs[i] = FrequencyDomain.GetComplexSampleFrequency(windowSize, fftMinFreqBin + i);
             }
             amplitudeAdjustant = 10.0 * Math.Log10(windowSize);
             minAmplitude = double.PositiveInfinity;
             maxAmplitude = double.NegativeInfinity;
         }
Member Function Documentation
void BGC.Audio.Visualization.SpectralDecomp.Add (int window, Complex64[] fftBuffer) inline
Definition at line 127 of file Spectrogram.cs.
Referenced by BGC.Audio.Visualization.Spectrogram.Decompose().
         {
             //Copy the data into the output array
             for (int i = 0; i < freqs.Length; i++)
             {
                 spectralValues[window, i] = amplitudeAdjustant + 10.0 * Math.Log10(fftBuffer[fftMinFreqBin + i].Magnitude);
                 if (spectralValues[window, i] > maxAmplitude && spectralValues[window, i] != double.PositiveInfinity)
                 {
                     maxAmplitude = spectralValues[window, i];
                 }
                 if (spectralValues[window, i] < minAmplitude && spectralValues[window, i] != double.NegativeInfinity)
                 {
                     minAmplitude = spectralValues[window, i];
                 }
             }
         }
double BGC.Audio.Visualization.SpectralDecomp.Linterp (int window, double frequency) inline
Definition at line 146 of file Spectrogram.cs.
References BGC.Mathematics.GeneralMath.Lerp().
         {
             int lowerBound = freqs.BinarySearchLowerBound(frequency);
             if (lowerBound == -1)
             {
                 return spectralValues[window, 0];
             }
             if (lowerBound == freqs.Length - 1)
             {
                 return spectralValues[window, lowerBound];
             }
             return GeneralMath.Lerp(
                 spectralValues[window, lowerBound],
                 spectralValues[window, lowerBound + 1],
                 (frequency - freqs[lowerBound]) / (freqs[lowerBound + 1] - freqs[lowerBound]));
         }
Field Documentation
readonly double BGC.Audio.Visualization.SpectralDecomp.amplitudeAdjustant private
Definition at line 102 of file Spectrogram.cs.
readonly int BGC.Audio.Visualization.SpectralDecomp.fftMaxFreqBin private
Definition at line 101 of file Spectrogram.cs.
readonly int BGC.Audio.Visualization.SpectralDecomp.fftMinFreqBin private
Definition at line 100 of file Spectrogram.cs.
double [] BGC.Audio.Visualization.SpectralDecomp.freqs
Definition at line 95 of file Spectrogram.cs.
double BGC.Audio.Visualization.SpectralDecomp.maxAmplitude
Definition at line 98 of file Spectrogram.cs.
double BGC.Audio.Visualization.SpectralDecomp.MaxFreq => freqs[freqs.Length - 1]
Definition at line 92 of file Spectrogram.cs.
double BGC.Audio.Visualization.SpectralDecomp.minAmplitude
Definition at line 97 of file Spectrogram.cs.
double BGC.Audio.Visualization.SpectralDecomp.MinFreq => freqs[0]
Definition at line 91 of file Spectrogram.cs.
double [,] BGC.Audio.Visualization.SpectralDecomp.spectralValues
Definition at line 94 of file Spectrogram.cs.
The documentation for this class was generated from the following file:
Audio/Spectrogram/Spectrogram.cs