BGC Tools: BGC.Study.SessionElement Class Reference
BGC.Study.SessionElement Class Reference abstract
Public Member Functions
SessionElement (JsonObject data)
SessionElement ()
JsonObject SerializeElement ()
abstract void ExecuteElement (bool resuming=false)
virtual void CleanupElement ()
Static Public Member Functions
static void HardClear ()
Data Fields
readonly int id
JsonObject envVals
Protected Member Functions
abstract void _PopulateJSONObject (JsonObject jsonObject)
Properties
abstract string ElementType [get]
Static Private Attributes
static int nextElementID = 1
Detailed Description
Definition at line 6 of file SessionElement.cs.
Constructor & Destructor Documentation
SessionElement() [1/2]
BGC.Study.SessionElement.SessionElement (JsonObject data) inline
Definition at line 16 of file SessionElement.cs.
References LightJson.JsonObject.ContainsKey(), BGC.Study.ProtocolKeys.SessionElement.EnvironmentValues, and BGC.Study.ProtocolKeys.SessionElement.Id.
         {
             id = data[ProtocolKeys.SessionElement.Id];
             if (nextElementID <= id)
             {
                 nextElementID = id + 1;
             }
             if (data.ContainsKey(ProtocolKeys.SessionElement.EnvironmentValues))
             {
                 envVals = data[ProtocolKeys.SessionElement.EnvironmentValues].AsJsonObject;
             }
             else
             {
                 envVals = new JsonObject();
             }
         }
SessionElement() [2/2]
BGC.Study.SessionElement.SessionElement () inline
Definition at line 35 of file SessionElement.cs.
References BGC.Study.ProtocolManager.sessionElementDictionary.
         {
             id = nextElementID++;
             envVals = new JsonObject();
             ProtocolManager.sessionElementDictionary.Add(id, this);
         }
Member Function Documentation
_PopulateJSONObject()
abstract void BGC.Study.SessionElement._PopulateJSONObject (JsonObject jsonObject) protected pure virtual
CleanupElement()
virtual void BGC.Study.SessionElement.CleanupElement () inline virtual
Definition at line 65 of file SessionElement.cs.
Referenced by BGC.Study.ProtocolManager.ExecuteNextElement().
 { }
ExecuteElement()
abstract void BGC.Study.SessionElement.ExecuteElement (bool resuming = false) pure virtual
Referenced by BGC.Study.ProtocolManager.ExecuteNextElement().
HardClear()
static void BGC.Study.SessionElement.HardClear () inline static
Definition at line 67 of file SessionElement.cs.
Referenced by BGC.Study.ProtocolManager.HardClearAll().
         {
             nextElementID = 1;
         }
SerializeElement()
JsonObject BGC.Study.SessionElement.SerializeElement () inline
Definition at line 44 of file SessionElement.cs.
References LightJson.JsonObject.Add(), LightJson.JsonObject.Count, BGC.Study.ProtocolKeys.SessionElement.ElementType, BGC.Study.ProtocolKeys.SessionElement.EnvironmentValues, and BGC.Study.ProtocolKeys.SessionElement.Id.
Referenced by BGC.Study.ProtocolManager.SerializeSessionElements().
         {
             JsonObject sessionElement = new JsonObject()
             {
                 { ProtocolKeys.SessionElement.Id, id },
                 { ProtocolKeys.SessionElement.ElementType, ElementType }
             };
             if (envVals.Count > 0)
             {
                 sessionElement.Add(ProtocolKeys.SessionElement.EnvironmentValues, envVals);
             }
             _PopulateJSONObject(sessionElement);
             return sessionElement;
         }
Field Documentation
envVals
JsonObject BGC.Study.SessionElement.envVals
Definition at line 13 of file SessionElement.cs.
Referenced by BGC.Study.ProtocolManager.GetEnvValue().
id
readonly int BGC.Study.SessionElement.id
Definition at line 11 of file SessionElement.cs.
Referenced by BGC.Study.ProtocolManager.DeserializeSessionElements(), and BGC.Study.SessionElementID.SessionElementID().
nextElementID
int BGC.Study.SessionElement.nextElementID = 1 static private
Definition at line 8 of file SessionElement.cs.
Property Documentation
ElementType
abstract string BGC.Study.SessionElement.ElementType get
Definition at line 10 of file SessionElement.cs.
The documentation for this class was generated from the following file:
Study/SessionElement.cs