BGC Tools: BGC.Audio.Filters.CarlileShuffler Class Reference
BGC.Audio.Filters.CarlileShuffler Class Reference
A Decorator class for BGCAudioClips that applies the Carlile noise-generation technique
Public Member Functions
CarlileShuffler (IBGCStream stream, double freqLowerBound=20.0, double freqUpperBound=16000.0, int bandCount=22, bool recalculateRMS=false, System.Random randomizer=null)
CarlileShuffler (IBGCStream stream, IEnumerable< double > frequencyDistribution, bool recalculateRMS=false, System.Random randomizer=null)
override int Read (float[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
override void Reset ()
Sets this internal state of this stream to the initial state
override void Seek (int position)
Seek to the indicated position in the stream
override IEnumerable< double > GetChannelRMS ()
The RMS amplitude of each channel
Public Member Functions inherited from BGC.Audio.Filters.SimpleBGCFilter
SimpleBGCFilter (IBGCStream stream)
override void Seek (int position)
Seek to the indicated position in the stream
override void Reset ()
Sets this internal state of this stream to the initial state
override void Initialize ()
Perform any calculations necessary to prepare the Stream
Data Fields
override int Channels => 1
override int TotalSamples => stream.TotalSamples
override int ChannelSamples => stream.ChannelSamples
override float SamplingRate => stream.SamplingRate
Data Fields inherited from BGC.Audio.Filters.SimpleBGCFilter
override float SamplingRate => stream.SamplingRate
Protected Member Functions
override void _Initialize ()
Properties
int Position [get, private set]
float [] Samples = 0 [get, private set]
Properties inherited from BGC.Audio.Filters.SimpleBGCFilter
override IEnumerable< IBGCStream > InternalStreams [get]
Properties inherited from BGC.Audio.Filters.BGCFilter
abstract int Channels [get]
abstract int TotalSamples [get]
abstract int ChannelSamples [get]
abstract float SamplingRate [get]
abstract IEnumerable< IBGCStream > InternalStreams [get]
Properties inherited from BGC.Audio.IBGCStream
int Channels [get]
The number of underlying Channels of this BGCStream
int TotalSamples [get]
The total number of Samples of this BGCStream
int ChannelSamples [get]
The number of Samples of each channel for this BGCStream
float SamplingRate [get]
The sampling rate of the Stream
Private Member Functions
IEnumerable< double > GetExponentialDistribution (double freqLowerBound, double freqUpperBound, int bandCount)
Private Attributes
int RemainingSamples => ChannelSamples - Position
readonly bool recalculateRMS = null
readonly System.Random randomizer
readonly IEnumerable< double > frequencyDistribution
IEnumerable< double > _channelRMS = null
Additional Inherited Members
Protected Attributes inherited from BGC.Audio.Filters.SimpleBGCFilter
readonly IBGCStream stream
Protected Attributes inherited from BGC.Audio.Filters.BGCFilter
bool initialized = false
Detailed Description
A Decorator class for BGCAudioClips that applies the Carlile noise-generation technique
Definition at line 10 of file CarlileShuffler.cs.
Constructor & Destructor Documentation
CarlileShuffler() [1/2]
BGC.Audio.Filters.CarlileShuffler.CarlileShuffler (IBGCStream stream, double freqLowerBound = 20.0, double freqUpperBound = 16000.0, int bandCount = 22, bool recalculateRMS = false, System.Random randomizer = null) inline
Definition at line 31 of file CarlileShuffler.cs.
References BGC.Mathematics.CustomRandom.Next().
             : base(stream)
         {
             this.randomizer = randomizer ?? new System.Random(CustomRandom.Next());
             this.recalculateRMS = recalculateRMS;
             frequencyDistribution = GetExponentialDistribution(freqLowerBound, freqUpperBound, bandCount);
         }
CarlileShuffler() [2/2]
BGC.Audio.Filters.CarlileShuffler.CarlileShuffler (IBGCStream stream, IEnumerable< double > frequencyDistribution, bool recalculateRMS = false, System.Random randomizer = null) inline
Definition at line 46 of file CarlileShuffler.cs.
References BGC.Mathematics.CustomRandom.Next().
             : base(stream)
         {
             this.randomizer = randomizer ?? new System.Random(CustomRandom.Next());
             this.recalculateRMS = recalculateRMS;
             this.frequencyDistribution = frequencyDistribution;
         }
Member Function Documentation
_Initialize()
override void BGC.Audio.Filters.CarlileShuffler._Initialize () inline protected virtual
Reimplemented from BGC.Audio.Filters.BGCFilter.
Definition at line 59 of file CarlileShuffler.cs.
References BGC.Mathematics.Fourier.Forward(), BGC.Mathematics.Complex64.FromPolarCoordinates(), BGC.Audio.FrequencyDomain.GetComplexFrequencyBin(), and BGC.Mathematics.Fourier.Inverse().
         {
             Complex64[] samples = stream.ComplexSamples();
             int bufferLength = samples.Length;
             Fourier.Forward(samples);
             IEnumerator<double> distribution = frequencyDistribution.GetEnumerator();
             distribution.MoveNext();
             int lowerBound = FrequencyDomain.GetComplexFrequencyBin(bufferLength, distribution.Current);
             while (distribution.MoveNext())
             {
                 int upperBound = FrequencyDomain.GetComplexFrequencyBin(bufferLength, distribution.Current);
                 //Generate random offset for the range
                 double offset = 2 * Math.PI * randomizer.NextDouble();
                 for (int i = lowerBound; i < upperBound; i++)
                 {
                     samples[i] *= Complex64.FromPolarCoordinates(2.0, i * offset);
                 }
                 lowerBound = upperBound;
             }
             for (int i = bufferLength / 2; i < bufferLength; i++)
             {
                 samples[i] = 0.0;
             }
             Fourier.Inverse(samples);
             Samples = new float[bufferLength];
             for (int i = 0; i < bufferLength; i++)
             {
                 Samples[i] = (float)samples[i].Real;
             }
         }
GetChannelRMS()
override IEnumerable<double> BGC.Audio.Filters.CarlileShuffler.GetChannelRMS () inline virtual
The RMS amplitude of each channel
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 127 of file CarlileShuffler.cs.
         {
             if (_channelRMS == null)
             {
                 if (recalculateRMS)
                 {
                     _channelRMS = this.CalculateRMS();
                 }
                 else
                 {
                     _channelRMS = stream.GetChannelRMS();
                 }
             }
             return _channelRMS;
         }
GetExponentialDistribution()
IEnumerable<double> BGC.Audio.Filters.CarlileShuffler.GetExponentialDistribution (double freqLowerBound, double freqUpperBound, int bandCount) inline private
Definition at line 146 of file CarlileShuffler.cs.
         {
             double freqRatio = Math.Pow((freqUpperBound / freqLowerBound), 1.0 / bandCount);
             if (double.IsNaN(freqRatio) || double.IsInfinity(freqRatio))
             {
                 freqRatio = 1.0;
             }
             double freq = freqLowerBound;
             for (int carrierTone = 0; carrierTone < bandCount + 1; carrierTone++)
             {
                 yield return freq;
                 freq *= freqRatio;
             }
         }
Read()
override int BGC.Audio.Filters.CarlileShuffler.Read (float [] data, int offset, int count) inline virtual
Copy count samples into the Data buffer, starting at offset.
Returns
The number of samples copied
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 101 of file CarlileShuffler.cs.
         {
             if (!initialized)
             {
                 Initialize();
             }
             int samplesToCopy = Math.Min(count, RemainingSamples);
             Array.Copy(
                 sourceArray: Samples,
                 sourceIndex: Position,
                 destinationArray: data,
                 destinationIndex: offset,
                 length: samplesToCopy);
             Position += samplesToCopy;
             return samplesToCopy;
         }
Reset()
override void BGC.Audio.Filters.CarlileShuffler.Reset () virtual
Sets this internal state of this stream to the initial state
Implements BGC.Audio.Filters.BGCFilter.
Seek()
override void BGC.Audio.Filters.CarlileShuffler.Seek (int position) virtual
Seek to the indicated position in the stream
Implements BGC.Audio.Filters.BGCFilter.
Field Documentation
_channelRMS
IEnumerable<double> BGC.Audio.Filters.CarlileShuffler._channelRMS = null private
Definition at line 126 of file CarlileShuffler.cs.
Channels
override int BGC.Audio.Filters.CarlileShuffler.Channels => 1
Definition at line 12 of file CarlileShuffler.cs.
ChannelSamples
override int BGC.Audio.Filters.CarlileShuffler.ChannelSamples => stream.ChannelSamples
Definition at line 16 of file CarlileShuffler.cs.
frequencyDistribution
readonly IEnumerable<double> BGC.Audio.Filters.CarlileShuffler.frequencyDistribution private
Definition at line 29 of file CarlileShuffler.cs.
randomizer
readonly System.Random BGC.Audio.Filters.CarlileShuffler.randomizer private
Definition at line 27 of file CarlileShuffler.cs.
recalculateRMS
readonly bool BGC.Audio.Filters.CarlileShuffler.recalculateRMS = null private
Definition at line 23 of file CarlileShuffler.cs.
RemainingSamples
int BGC.Audio.Filters.CarlileShuffler.RemainingSamples => ChannelSamples - Position private
Definition at line 20 of file CarlileShuffler.cs.
SamplingRate
override float BGC.Audio.Filters.CarlileShuffler.SamplingRate => stream.SamplingRate
Definition at line 18 of file CarlileShuffler.cs.
TotalSamples
override int BGC.Audio.Filters.CarlileShuffler.TotalSamples => stream.TotalSamples
Definition at line 14 of file CarlileShuffler.cs.
Property Documentation
Position
int BGC.Audio.Filters.CarlileShuffler.Position get private set
Definition at line 22 of file CarlileShuffler.cs.
Samples
float [] BGC.Audio.Filters.CarlileShuffler.Samples = 0 get private set
Definition at line 23 of file CarlileShuffler.cs.
The documentation for this class was generated from the following file:
Audio/Filters/CarlileShuffler.cs