BGC Tools: BGC.Audio.Filters.FrequencyModulationFilter Class Reference
BGC.Audio.Filters.FrequencyModulationFilter Class Reference
Applies FrequencyModulation to the underlying stream, in the frequency domain. Initial Analytic signal generation based on "An Efficient Analytic Signal Generator" by Clay S. Turner http://www.claysturner.com/dsp/asg.pdf
Public Member Functions
FrequencyModulationFilter (IBGCStream stream, double modRate, double modDepth)
override int Read (float[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
override void Reset ()
Sets this internal state of this stream to the initial state
override void Seek (int position)
Seek to the indicated position in the stream
override IEnumerable< double > GetChannelRMS ()
The RMS amplitude of each channel
Public Member Functions inherited from BGC.Audio.Filters.SimpleBGCFilter
SimpleBGCFilter (IBGCStream stream)
override void Seek (int position)
Seek to the indicated position in the stream
override void Reset ()
Sets this internal state of this stream to the initial state
override void Initialize ()
Perform any calculations necessary to prepare the Stream
Data Fields
override int Channels => 1
override int TotalSamples => stream.TotalSamples
override int ChannelSamples => stream.ChannelSamples
Data Fields inherited from BGC.Audio.Filters.SimpleBGCFilter
override float SamplingRate => stream.SamplingRate
Private Attributes
const double A = 0.00125
const double W_1 = 0.49875
const double W_2 = 0.00125
const int FILTER_LENGTH = 129
readonly IBGCStream convStream
readonly Complex64 [] modulator
readonly int modulatorPeriodSamples
int modulatorPosition = 0
const int BUFFER_SIZE = 512
readonly float [] buffer = new float[BUFFER_SIZE]
Additional Inherited Members
Protected Member Functions inherited from BGC.Audio.Filters.BGCFilter
virtual void _Initialize ()
Protected Attributes inherited from BGC.Audio.Filters.SimpleBGCFilter
readonly IBGCStream stream
Protected Attributes inherited from BGC.Audio.Filters.BGCFilter
bool initialized = false
Properties inherited from BGC.Audio.Filters.SimpleBGCFilter
override IEnumerable< IBGCStream > InternalStreams [get]
Properties inherited from BGC.Audio.Filters.BGCFilter
abstract int Channels [get]
abstract int TotalSamples [get]
abstract int ChannelSamples [get]
abstract float SamplingRate [get]
abstract IEnumerable< IBGCStream > InternalStreams [get]
Properties inherited from BGC.Audio.IBGCStream
int Channels [get]
The number of underlying Channels of this BGCStream
int TotalSamples [get]
The total number of Samples of this BGCStream
int ChannelSamples [get]
The number of Samples of each channel for this BGCStream
float SamplingRate [get]
The sampling rate of the Stream
Detailed Description
Applies FrequencyModulation to the underlying stream, in the frequency domain. Initial Analytic signal generation based on "An Efficient Analytic Signal Generator" by Clay S. Turner http://www.claysturner.com/dsp/asg.pdf
Definition at line 15 of file FrequencyModulationFilter.cs.
Constructor & Destructor Documentation
FrequencyModulationFilter()
BGC.Audio.Filters.FrequencyModulationFilter.FrequencyModulationFilter (IBGCStream stream, double modRate, double modDepth) inline
Definition at line 38 of file FrequencyModulationFilter.cs.
References BGC.Mathematics.Complex64.FromPolarCoordinates().
             : base(stream)
         {
             double[] realConvolutionFilter = new double[FILTER_LENGTH];
             double[] imagConvolutionFilter = new double[FILTER_LENGTH];
             const double twoPiSq = 2f * PI * PI;
             const double fourASq = 4f * A * A;
             const double piSq = PI * PI;
             const double piOv4 = PI / 4f;
             const double piOv4A = PI / (4f * A);
             double N_0 = (FILTER_LENGTH - 1.0) / 2.0;
             for (int i = 1; i < FILTER_LENGTH - 1; i++)
             {
                 if (i == N_0)
                 {
                     continue;
                 }
                 double t = 2 * PI * (i - N_0);
                 double prefactor = twoPiSq * Cos(A * t) / (t * (fourASq * t * t - piSq));
                 realConvolutionFilter[i] = prefactor * (Sin(W_1 * t + piOv4) - Sin(W_2 * t + piOv4));
             }
             realConvolutionFilter[0] = A * (Sin(piOv4A * (A - 2f * W_1)) - Sin(piOv4A * (A - 2f * W_2)));
             realConvolutionFilter[FILTER_LENGTH - 1] = A * (Sin(piOv4A * (A + 2f * W_2)) - Sin(piOv4A * (A + 2f * W_1)));
             if (FILTER_LENGTH % 2 == 1)
             {
                 realConvolutionFilter[(int)N_0] = Sqrt(2f) * (W_2 - W_1);
             }
             for (int i = 0; i < FILTER_LENGTH; i++)
             {
                 imagConvolutionFilter[i] = realConvolutionFilter[FILTER_LENGTH - 1 - i];
             }
             convStream = new MultiConvolutionFilter(stream, realConvolutionFilter, imagConvolutionFilter);
             modulatorPeriodSamples = (int)Abs(Round(SamplingRate / modRate));
             modRate = Sign(modRate) * SamplingRate / (double)modulatorPeriodSamples;
             modulator = new Complex64[modulatorPeriodSamples];
             for (int i = 0; i < modulatorPeriodSamples; i++)
             {
                 modulator[i] = Complex64.FromPolarCoordinates(
                     magnitude: 1.0,
                     phase: (modDepth / modRate) * Sin(2.0 * PI * i / modulatorPeriodSamples));
             }
         }
Member Function Documentation
GetChannelRMS()
override IEnumerable<double> BGC.Audio.Filters.FrequencyModulationFilter.GetChannelRMS () virtual
The RMS amplitude of each channel
Implements BGC.Audio.Filters.BGCFilter.
Read()
override int BGC.Audio.Filters.FrequencyModulationFilter.Read (float [] data, int offset, int count) inline virtual
Copy count samples into the Data buffer, starting at offset.
Returns
The number of samples copied
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 97 of file FrequencyModulationFilter.cs.
References BGC.Mathematics.Complex64.RealProduct().
         {
             int samplesRemaining = count;
             while (samplesRemaining > 0)
             {
                 int maxReadCount = Min(2 * samplesRemaining, BUFFER_SIZE);
                 int sampleReadCount = convStream.Read(buffer, 0, maxReadCount);
                 if (sampleReadCount == 0)
                 {
                     break;
                 }
                 sampleReadCount /= 2;
                 for (int i = 0; i < sampleReadCount; i++)
                 {
                     data[offset + i] = (float)new Complex64(buffer[2 * i], buffer[2 * i + 1])
                         .RealProduct(modulator[modulatorPosition++]);
                     if (modulatorPosition == modulatorPeriodSamples)
                     {
                         modulatorPosition = 0;
                     }
                 }
                 samplesRemaining -= sampleReadCount;
                 offset += sampleReadCount;
             }
             return count - samplesRemaining;
         }
Reset()
override void BGC.Audio.Filters.FrequencyModulationFilter.Reset () inline virtual
Sets this internal state of this stream to the initial state
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 131 of file FrequencyModulationFilter.cs.
         {
             modulatorPosition = 0;
             convStream.Reset();
         }
Seek()
override void BGC.Audio.Filters.FrequencyModulationFilter.Seek (int position) inline virtual
Seek to the indicated position in the stream
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 137 of file FrequencyModulationFilter.cs.
References BGC.Mathematics.GeneralMath.Clamp().
         {
             position = GeneralMath.Clamp(position, 0, ChannelSamples);
             convStream.Seek(position);
             modulatorPosition = position % modulatorPeriodSamples;
         }
Field Documentation
A
const double BGC.Audio.Filters.FrequencyModulationFilter.A = 0.00125 private
Definition at line 17 of file FrequencyModulationFilter.cs.
buffer
readonly float [] BGC.Audio.Filters.FrequencyModulationFilter.buffer = new float[BUFFER_SIZE] private
Definition at line 36 of file FrequencyModulationFilter.cs.
BUFFER_SIZE
const int BGC.Audio.Filters.FrequencyModulationFilter.BUFFER_SIZE = 512 private
Definition at line 35 of file FrequencyModulationFilter.cs.
Channels
override int BGC.Audio.Filters.FrequencyModulationFilter.Channels => 1
Definition at line 22 of file FrequencyModulationFilter.cs.
ChannelSamples
override int BGC.Audio.Filters.FrequencyModulationFilter.ChannelSamples => stream.ChannelSamples
Definition at line 26 of file FrequencyModulationFilter.cs.
convStream
readonly IBGCStream BGC.Audio.Filters.FrequencyModulationFilter.convStream private
Definition at line 28 of file FrequencyModulationFilter.cs.
FILTER_LENGTH
const int BGC.Audio.Filters.FrequencyModulationFilter.FILTER_LENGTH = 129 private
Definition at line 20 of file FrequencyModulationFilter.cs.
modulator
readonly Complex64 [] BGC.Audio.Filters.FrequencyModulationFilter.modulator private
Definition at line 30 of file FrequencyModulationFilter.cs.
modulatorPeriodSamples
readonly int BGC.Audio.Filters.FrequencyModulationFilter.modulatorPeriodSamples private
Definition at line 31 of file FrequencyModulationFilter.cs.
modulatorPosition
int BGC.Audio.Filters.FrequencyModulationFilter.modulatorPosition = 0 private
Definition at line 33 of file FrequencyModulationFilter.cs.
TotalSamples
override int BGC.Audio.Filters.FrequencyModulationFilter.TotalSamples => stream.TotalSamples
Definition at line 24 of file FrequencyModulationFilter.cs.
W_1
const double BGC.Audio.Filters.FrequencyModulationFilter.W_1 = 0.49875 private
Definition at line 18 of file FrequencyModulationFilter.cs.
W_2
const double BGC.Audio.Filters.FrequencyModulationFilter.W_2 = 0.00125 private
Definition at line 19 of file FrequencyModulationFilter.cs.
The documentation for this class was generated from the following file:
Audio/Filters/FrequencyModulationFilter.cs