BGC Tools: BGC.Audio.Midi.MidiEncoding Class Reference
BGC.Audio.Midi.MidiEncoding Class Reference
Data Structures
struct HeaderInfo
Public Types
enum Format : ushort { Format.SingleTrack = 0x0000, Format.TempoMapped = 0x0001, Format.SequenceContainer = 0x0002, Format.UNDEFINED = 0xFFFF }
Static Public Member Functions
static bool LoadFile (string filePath, out MidiFile midiFile, bool retainAll=false)
Method to load a MIDI file an parse the data
static bool SaveFile (string filePath, MidiFile midiFile, bool overwrite=false)
Detailed Description
Definition at line 13 of file MIDIEncoding.cs.
Member Enumeration Documentation
Format
enum BGC.Audio.Midi.MidiEncoding.Format : ushort strong
Enumerator
SingleTrack
TempoMapped
SequenceContainer
UNDEFINED
Definition at line 15 of file MIDIEncoding.cs.
                            : ushort
         {
             SingleTrack = 0x0000,
             TempoMapped = 0x0001,
             SequenceContainer = 0x0002,
             UNDEFINED = 0xFFFF
         }
Member Function Documentation
LoadFile()
static bool BGC.Audio.Midi.MidiEncoding.LoadFile (string filePath, out MidiFile midiFile, bool retainAll = false) inline static
Method to load a MIDI file an parse the data
Definition at line 77 of file MIDIEncoding.cs.
References BGC.Audio.Midi.MidiFile.HEADER_CHUNK_NAME, and BGC.Audio.Midi.MidiTrack.TRACK_CHUNK_NAME.
Referenced by BGC.Tests.MidiEncodingTests.TestLoadSaveMidiBare(), BGC.Tests.MidiEncodingTests.TestLoadSaveMidiFull(), BGC.Tests.MidiEncodingTests.TestRenderMidi(), and BGC.Tests.MidiEncodingTests.TestRenderToccataMidi().
         {
             midiFile = null;
             if (!File.Exists(filePath))
             {
                 Debug.LogError($"File {filePath} does not exist.");
                 return false;
             }
             try
             {
                 using (FileStream fileStream = File.OpenRead(filePath))
                 {
                     //Now Read Chunks
                     //Each chunk starts with an 8 byte header, so we probably reached padding if
                     //there is less than that remaining
                     while (fileStream.CanRead && (fileStream.Length - fileStream.Position) >= 8)
                     {
                         byte[] smallBuffer = new byte[8];
                         fileStream.Read(smallBuffer, 0, 8);
                         string chunkID = Encoding.UTF8.GetString(smallBuffer, 0, 4).Trim();
                         int chunkSize =
                             smallBuffer[4] << 24 |
                             smallBuffer[5] << 16 |
                             smallBuffer[6] << 8 |
                             smallBuffer[7];
                         using (Stream chunkStream = new SubStream(fileStream, chunkSize, ownsStream: false))
{
                             switch (chunkID)
{
                                 case MidiFile.HEADER_CHUNK_NAME:
                                     midiFile = new MidiFile(chunkStream, retainAll);
                                     break;
                                 case MidiTrack.TRACK_CHUNK_NAME:
                                     if (midiFile == null)
{
                                         throw new MidiParsingException($"\"{MidiFile.HEADER_CHUNK_NAME}\" chunk not found before \"{MidiTrack.TRACK_CHUNK_NAME}\".");
                                     }
                                     midiFile.ReadTrack(chunkStream);
                                     break;
                                 default:
                                     Debug.Log($"Skipping unexpected Chunk in File {filePath}: {chunkID}.");
                                     //Do nothing with it
                                     break;
                             }
                         }
                     }
                     if (midiFile == null)
                     {
                         throw new MidiParsingException($"Finished parsing file without locating Header or Track chunks");
                     }
                     if (midiFile.tracks.Count == 0)
                     {
                         midiFile = null;
                         throw new MidiParsingException($"Finished parsing file without locating Track chunks");
                     }
                 }
             }
             catch (MidiParsingException excp)
             {
                 Debug.LogException(new MidiParsingException($"Error parsing Midi file \"{filePath}\"", excp));
                 midiFile = null;
                 return false;
             }
             return midiFile != null;
         }
SaveFile()
static bool BGC.Audio.Midi.MidiEncoding.SaveFile (string filePath, MidiFile midiFile, bool overwrite = false) inline static
Definition at line 155 of file MIDIEncoding.cs.
References BGC.IO.DataManagement.NextAvailableFilePath(), and BGC.Audio.Midi.MidiFile.Serialize().
Referenced by BGC.Tests.MidiEncodingTests.TestLoadSaveMidiBare(), and BGC.Tests.MidiEncodingTests.TestLoadSaveMidiFull().
         {
             try
             {
                 if (File.Exists(filePath))
                 {
                     if (overwrite)
                     {
                         File.Delete(filePath);
                     }
                     else
                     {
                         filePath = DataManagement.NextAvailableFilePath(filePath);
                     }
                 }
                 using (FileStream fileStream = new FileStream(filePath, FileMode.Create))
                 {
                     midiFile.Serialize(fileStream);
                 }
                 return true;
             }
             catch (IOException excp)
             {
                 Debug.LogException(excp);
                 return false;
             }
         }
The documentation for this class was generated from the following file:
Audio/Midi/MIDIEncoding.cs