BGC Tools: BGC.Audio.Synthesis.NoiseAudioClip Class Reference
BGC.Audio.Synthesis.NoiseAudioClip Class Reference
Limited duration noise stream
Public Types
enum AmplitudeDistribution {
AmplitudeDistribution.Violet = 0, AmplitudeDistribution.Blue, AmplitudeDistribution.White, AmplitudeDistribution.Pink,
AmplitudeDistribution.Brown, AmplitudeDistribution.MAX
}
Public Member Functions
NoiseAudioClip (double duration, double rms, double freqLB, double freqUB, int frequencyCount, AmplitudeDistribution distribution, Random randomizer=null)
override int Read (float[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
override void Reset ()
Sets this internal state of this stream to the initial state
override void Seek (int position)
Seek to the indicated position in the stream
override IEnumerable< double > GetChannelRMS ()
The RMS amplitude of each channel
Public Member Functions inherited from BGC.Audio.BGCStream
void Initialize ()
Perform any calculations necessary to prepare the Stream
Data Fields
override int Channels => 1
override int TotalSamples => ChannelSamples
override int ChannelSamples => _channelSamples
Data Fields inherited from BGC.Audio.BGCAudioClip
float Duration => ChannelSamples / SamplingRate
override float SamplingRate => 44100f
Protected Member Functions
override void _Initialize ()
Private Member Functions
IEnumerable< ComplexCarrierTone > CreateSideBands (double freqLB, double freqUB, int count, AmplitudeDistribution distribution)
double GetFactor (AmplitudeDistribution amplitudeDistribution, double frequency)
Private Attributes
int _channelSamples
readonly Random randomizer
readonly AmplitudeDistribution distribution
readonly double rms
readonly double freqLB
readonly double freqUB
readonly int frequencyCount
Complex64 [] fftBuffer = null
int position = 0
Additional Inherited Members
Protected Attributes inherited from BGC.Audio.BGCStream
bool initialized = false
Properties inherited from BGC.Audio.BGCStream
abstract int Channels [get]
abstract int TotalSamples [get]
abstract int ChannelSamples [get]
abstract float SamplingRate [get]
Properties inherited from BGC.Audio.IBGCStream
int Channels [get]
The number of underlying Channels of this BGCStream
int TotalSamples [get]
The total number of Samples of this BGCStream
int ChannelSamples [get]
The number of Samples of each channel for this BGCStream
float SamplingRate [get]
The sampling rate of the Stream
Detailed Description
Limited duration noise stream
Definition at line 10 of file NoiseAudioClip.cs.
Member Enumeration Documentation
AmplitudeDistribution
enum BGC.Audio.Synthesis.NoiseAudioClip.AmplitudeDistribution strong
Enumerator
Violet
Blue
White
Pink
Brown
MAX
Definition at line 12 of file NoiseAudioClip.cs.
         {
             Violet = 0,
             Blue,
             White,
             Pink,
             Brown,
             MAX
         }
Constructor & Destructor Documentation
NoiseAudioClip()
BGC.Audio.Synthesis.NoiseAudioClip.NoiseAudioClip (double duration, double rms, double freqLB, double freqUB, int frequencyCount, AmplitudeDistribution distribution, Random randomizer = null) inline
Definition at line 41 of file NoiseAudioClip.cs.
References BGC.Mathematics.CustomRandom.Next().
         {
             if (randomizer == null)
             {
                 randomizer = new Random(CustomRandom.Next());
             }
             this.randomizer = randomizer;
             this.rms = rms;
             this.freqLB = freqLB;
             this.freqUB = freqUB;
             this.frequencyCount = frequencyCount;
             this.distribution = distribution;
             _channelSamples = (int)Math.Ceiling(duration * SamplingRate);
         }
Member Function Documentation
_Initialize()
override void BGC.Audio.Synthesis.NoiseAudioClip._Initialize () inline protected virtual
Reimplemented from BGC.Audio.BGCStream.
Definition at line 66 of file NoiseAudioClip.cs.
References BGC.Audio.ComplexCarrierTone.amplitude, BGC.Audio.ComplexCarrierTone.frequency, BGC.Mathematics.Fourier.Inverse(), BGC.Audio.FrequencyDomain.Populate(), and BGC.Mathematics.Complex64.Real.
         {
             int fftBufferSize = _channelSamples.CeilingToPowerOfTwo();
             fftBuffer = new Complex64[fftBufferSize];
             foreach (ComplexCarrierTone carrierTone in CreateSideBands(freqLB, freqUB, frequencyCount, distribution))
             {
                 FrequencyDomain.Populate(
                     buffer: fftBuffer,
                     frequency: carrierTone.frequency,
                     amplitude: carrierTone.amplitude);
             }
             Fourier.Inverse(fftBuffer);
             double currentRMS = 0.0;
             for (int i = 0; i < fftBufferSize; i++)
             {
                 currentRMS += fftBuffer[i].Real * fftBuffer[i].Real;
             }
             currentRMS = Math.Sqrt(currentRMS / fftBufferSize);
             double factor = rms / currentRMS;
             for (int i = 0; i < fftBufferSize; i++)
             {
                 fftBuffer[i] *= factor;
             }
         }
CreateSideBands()
IEnumerable<ComplexCarrierTone> BGC.Audio.Synthesis.NoiseAudioClip.CreateSideBands (double freqLB, double freqUB, int count, AmplitudeDistribution distribution) inline private
Definition at line 129 of file NoiseAudioClip.cs.
References BGC.Mathematics.Complex64.FromPolarCoordinates(), and BGC.Mathematics.CustomRandom.RayleighDistribution().
         {
             double freqRatio = Math.Pow((freqUB / freqLB), 1.0 / (count - 1));
             if (double.IsNaN(freqRatio) || double.IsInfinity(freqRatio))
             {
                 freqRatio = 1.0;
             }
             double freq = freqLB;
             for (int carrierTone = 0; carrierTone < count; carrierTone++)
             {
                 yield return new ComplexCarrierTone(
                     frequency: freq,
                     amplitude: Complex64.FromPolarCoordinates(
                         magnitude: GetFactor(distribution, freq) * CustomRandom.RayleighDistribution(randomizer.NextDouble()),
                         phase: 2.0 * Math.PI * randomizer.NextDouble()));
                 freq *= freqRatio;
             }
         }
GetChannelRMS()
override IEnumerable<double> BGC.Audio.Synthesis.NoiseAudioClip.GetChannelRMS () inline virtual
The RMS amplitude of each channel
Implements BGC.Audio.BGCStream.
Definition at line 124 of file NoiseAudioClip.cs.
         {
             yield return rms;
         }
GetFactor()
double BGC.Audio.Synthesis.NoiseAudioClip.GetFactor (AmplitudeDistribution amplitudeDistribution, double frequency) inline private
Definition at line 157 of file NoiseAudioClip.cs.
         {
             switch (amplitudeDistribution)
             {
                 case AmplitudeDistribution.Violet: return frequency * Math.Sqrt(frequency);
                 case AmplitudeDistribution.Blue: return frequency;
                 case AmplitudeDistribution.White: return Math.Sqrt(frequency);
                 case AmplitudeDistribution.Pink: return 1.0;
                 case AmplitudeDistribution.Brown: return 1.0 / Math.Sqrt(frequency);
                 case AmplitudeDistribution.MAX:
                 default:
                     UnityEngine.Debug.LogError($"Unexpected AmplitudeFactor: {amplitudeDistribution}");
                     return 1.0;
             }
         }
Read()
override int BGC.Audio.Synthesis.NoiseAudioClip.Read (float [] data, int offset, int count) inline virtual
Copy count samples into the Data buffer, starting at offset.
Returns
The number of samples copied
Implements BGC.Audio.BGCStream.
Definition at line 98 of file NoiseAudioClip.cs.
References BGC.Mathematics.GeneralMath.Clamp().
         {
             if (!initialized)
             {
                 Initialize();
             }
             //Read...
             int samplesToRead = Math.Min(count, _channelSamples - position);
             for (int i = 0; i < samplesToRead; i++)
             {
                 data[offset + i] = (float)fftBuffer[position + i].Real;
             }
             position += samplesToRead;
             return samplesToRead;
         }
Reset()
override void BGC.Audio.Synthesis.NoiseAudioClip.Reset () virtual
Sets this internal state of this stream to the initial state
Implements BGC.Audio.BGCStream.
Seek()
override void BGC.Audio.Synthesis.NoiseAudioClip.Seek (int position) virtual
Seek to the indicated position in the stream
Implements BGC.Audio.BGCStream.
Field Documentation
_channelSamples
int BGC.Audio.Synthesis.NoiseAudioClip._channelSamples private
Definition at line 26 of file NoiseAudioClip.cs.
Channels
override int BGC.Audio.Synthesis.NoiseAudioClip.Channels => 1
Definition at line 22 of file NoiseAudioClip.cs.
ChannelSamples
override int BGC.Audio.Synthesis.NoiseAudioClip.ChannelSamples => _channelSamples
Definition at line 27 of file NoiseAudioClip.cs.
distribution
readonly AmplitudeDistribution BGC.Audio.Synthesis.NoiseAudioClip.distribution private
Definition at line 31 of file NoiseAudioClip.cs.
fftBuffer
Complex64 [] BGC.Audio.Synthesis.NoiseAudioClip.fftBuffer = null private
Definition at line 37 of file NoiseAudioClip.cs.
freqLB
readonly double BGC.Audio.Synthesis.NoiseAudioClip.freqLB private
Definition at line 33 of file NoiseAudioClip.cs.
freqUB
readonly double BGC.Audio.Synthesis.NoiseAudioClip.freqUB private
Definition at line 34 of file NoiseAudioClip.cs.
frequencyCount
readonly int BGC.Audio.Synthesis.NoiseAudioClip.frequencyCount private
Definition at line 35 of file NoiseAudioClip.cs.
position
int BGC.Audio.Synthesis.NoiseAudioClip.position = 0 private
Definition at line 39 of file NoiseAudioClip.cs.
randomizer
readonly Random BGC.Audio.Synthesis.NoiseAudioClip.randomizer private
Definition at line 29 of file NoiseAudioClip.cs.
rms
readonly double BGC.Audio.Synthesis.NoiseAudioClip.rms private
Definition at line 32 of file NoiseAudioClip.cs.
TotalSamples
override int BGC.Audio.Synthesis.NoiseAudioClip.TotalSamples => ChannelSamples
Definition at line 24 of file NoiseAudioClip.cs.
The documentation for this class was generated from the following file:
Audio/Synthesis/NoiseAudioClip.cs