BGC Tools: BGC.StateMachine.TransitionCondition Class Reference
BGC.StateMachine.TransitionCondition Class Reference abstract
Public Member Functions
void SetStateMachineFunctions (Func< string, bool > getBool, Func< string, bool > getTrigger, Action< string > consumeTrigger)
abstract void OnTransition ()
Called before the transition for anything useful to be done such as consumeing triggers
abstract bool ShouldTransition ()
Protected Member Functions
abstract void StateMachineFunctionsSet ()
Protected Attributes
Func< string, bool > getBool
Func< string, bool > getTrigger
Action< string > consumeTrigger
Detailed Description
Definition at line 5 of file TransitionCondition.cs.
Member Function Documentation
abstract void BGC.StateMachine.TransitionCondition.OnTransition () pure virtual
Called before the transition for anything useful to be done such as consumeing triggers
Implemented in BGC.StateMachine.OrConjunction, BGC.StateMachine.BoolCondition, and BGC.StateMachine.TriggerCondition.
Referenced by BGC.StateMachine.OrConjunction.OnTransition(), and BGC.StateMachine.Transition.OnTransition().
void BGC.StateMachine.TransitionCondition.SetStateMachineFunctions (Func< string, bool > getBool, Func< string, bool > getTrigger, Action< string > consumeTrigger) inline
Definition at line 12 of file TransitionCondition.cs.
Referenced by BGC.StateMachine.Transition.SetStateDataRetrievers(), and BGC.StateMachine.OrConjunction.StateMachineFunctionsSet().
         {
             this.getBool = getBool;
             this.getTrigger = getTrigger;
             this.consumeTrigger = consumeTrigger;
             StateMachineFunctionsSet();
         }
abstract bool BGC.StateMachine.TransitionCondition.ShouldTransition () pure virtual
Implemented in BGC.StateMachine.OrConjunction, BGC.StateMachine.BoolCondition, and BGC.StateMachine.TriggerCondition.
Referenced by BGC.StateMachine.Transition.ShouldTransition().
abstract void BGC.StateMachine.TransitionCondition.StateMachineFunctionsSet () protected pure virtual
Implemented in BGC.StateMachine.OrConjunction, BGC.StateMachine.BoolCondition, and BGC.StateMachine.TriggerCondition.
Field Documentation
Action<string> BGC.StateMachine.TransitionCondition.consumeTrigger protected
Definition at line 9 of file TransitionCondition.cs.
Func<string, bool> BGC.StateMachine.TransitionCondition.getBool protected
Definition at line 7 of file TransitionCondition.cs.
Func<string, bool> BGC.StateMachine.TransitionCondition.getTrigger protected
Definition at line 8 of file TransitionCondition.cs.
The documentation for this class was generated from the following file:
StateMachine/TransitionCondition.cs