BGC Tools: BGC.Audio.Filters.ConvolutionFilter Class Reference
BGC.Audio.Filters.ConvolutionFilter Class Reference
Performs a convolution on the underlying stream, using Overlap-And-Add
Public Member Functions
ConvolutionFilter (IBGCStream stream, float[] filter, bool recalculateRMS=false)
ConvolutionFilter (IBGCStream stream, IBGCStream filter, bool recalculateRMS=false)
override int Read (float[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
override void Reset ()
Sets this internal state of this stream to the initial state
override void Seek (int position)
Seek to the indicated position in the stream
override IEnumerable< double > GetChannelRMS ()
The RMS amplitude of each channel
Public Member Functions inherited from BGC.Audio.Filters.SimpleBGCFilter
SimpleBGCFilter (IBGCStream stream)
override void Seek (int position)
Seek to the indicated position in the stream
override void Reset ()
Sets this internal state of this stream to the initial state
override void Initialize ()
Perform any calculations necessary to prepare the Stream
Data Fields
override int Channels => stream.Channels
Data Fields inherited from BGC.Audio.Filters.SimpleBGCFilter
override float SamplingRate => stream.SamplingRate
Protected Member Functions
override void _Initialize ()
Properties
override int TotalSamples [get]
override int ChannelSamples [get]
Properties inherited from BGC.Audio.Filters.SimpleBGCFilter
override IEnumerable< IBGCStream > InternalStreams [get]
Properties inherited from BGC.Audio.Filters.BGCFilter
abstract int Channels [get]
abstract int TotalSamples [get]
abstract int ChannelSamples [get]
abstract float SamplingRate [get]
abstract IEnumerable< IBGCStream > InternalStreams [get]
Properties inherited from BGC.Audio.IBGCStream
int Channels [get]
The number of underlying Channels of this BGCStream
int TotalSamples [get]
The total number of Samples of this BGCStream
int ChannelSamples [get]
The number of Samples of each channel for this BGCStream
float SamplingRate [get]
The sampling rate of the Stream
Private Member Functions
int ReadBody (float[] buffer, int offset, int count)
void ClearBuffers ()
Private Attributes
const int FFT_EXP_MIN = 9
const int FFT_SIZE_BUMP = 1
readonly float [] inputBuffer
readonly Complex64 [] filterFD
readonly Complex64 [] fftBuffer
readonly float [] outputAccumulation
readonly int fftLength
readonly int samplesPerOverlap
readonly int filterLength
int bufferIndex = 0
int bufferCount = 0
readonly bool recalculateRMS
IEnumerable< double > _channelRMS = null
Additional Inherited Members
Protected Attributes inherited from BGC.Audio.Filters.SimpleBGCFilter
readonly IBGCStream stream
Protected Attributes inherited from BGC.Audio.Filters.BGCFilter
bool initialized = false
Detailed Description
Performs a convolution on the underlying stream, using Overlap-And-Add
Definition at line 11 of file ConvolutionFilter.cs.
Constructor & Destructor Documentation
ConvolutionFilter() [1/2]
BGC.Audio.Filters.ConvolutionFilter.ConvolutionFilter (IBGCStream stream, float [] filter, bool recalculateRMS = false) inline
Definition at line 36 of file ConvolutionFilter.cs.
References BGC.Audio.IBGCStream.ChannelSamples.
             : base(stream)
         {
             filterLength = filter.Length;
             int fftSize = Math.Max(FFT_EXP_MIN, filterLength.ToNextExponentOf2() + FFT_SIZE_BUMP);
             fftLength = 1 << fftSize;
             samplesPerOverlap = fftLength - filterLength;
             //Protect against infinite streams
             if (stream.ChannelSamples == int.MaxValue)
             {
                 ChannelSamples = int.MaxValue;
                 TotalSamples = int.MaxValue;
             }
             else
             {
                 ChannelSamples = filterLength + stream.ChannelSamples - 1;
                 TotalSamples = Channels * ChannelSamples;
             }
             inputBuffer = new float[Channels * samplesPerOverlap];
             outputAccumulation = new float[Channels * fftLength];
             fftBuffer = new Complex64[fftLength];
             filterFD = new Complex64[fftLength];
             for (int i = 0; i < filterLength; i++)
             {
                 filterFD[i] = filter[i];
             }
             initialized = false;
             this.recalculateRMS = recalculateRMS;
         }
ConvolutionFilter() [2/2]
BGC.Audio.Filters.ConvolutionFilter.ConvolutionFilter (IBGCStream stream, IBGCStream filter, bool recalculateRMS = false) inline
Definition at line 76 of file ConvolutionFilter.cs.
References BGC.Audio.IBGCStream.Channels, and BGC.Audio.IBGCStream.ChannelSamples.
             : base(stream)
         {
             Debug.Assert(filter.Channels == 1);
             filterLength = filter.ChannelSamples;
             int fftSize = Math.Max(FFT_EXP_MIN, filterLength.ToNextExponentOf2() + FFT_SIZE_BUMP);
             fftLength = 1 << fftSize;
             samplesPerOverlap = fftLength - filterLength;
             //Protect against infinite streams
             if (stream.ChannelSamples == int.MaxValue)
             {
                 ChannelSamples = int.MaxValue;
                 TotalSamples = int.MaxValue;
             }
             else
             {
                 ChannelSamples = filterLength + stream.ChannelSamples - 1;
                 TotalSamples = Channels * ChannelSamples;
             }
             inputBuffer = new float[Channels * samplesPerOverlap];
             outputAccumulation = new float[Channels * fftLength];
             fftBuffer = new Complex64[fftLength];
             filterFD = filter.ComplexSamples(fftLength);
             initialized = false;
             this.recalculateRMS = recalculateRMS;
         }
Member Function Documentation
_Initialize()
override void BGC.Audio.Filters.ConvolutionFilter._Initialize () inline protected virtual
Reimplemented from BGC.Audio.Filters.BGCFilter.
Definition at line 113 of file ConvolutionFilter.cs.
References BGC.Mathematics.Fourier.Forward().
         {
             Fourier.Forward(filterFD);
             double factor = filterLength;
             for (int i = 0; i < filterLength; i++)
             {
                 filterFD[i] *= factor;
             }
         }
ClearBuffers()
void BGC.Audio.Filters.ConvolutionFilter.ClearBuffers () inline private
Definition at line 221 of file ConvolutionFilter.cs.
         {
             bufferIndex = 0;
             bufferCount = 0;
             Array.Clear(outputAccumulation, 0, outputAccumulation.Length);
             Array.Clear(inputBuffer, 0, inputBuffer.Length);
         }
GetChannelRMS()
override IEnumerable<double> BGC.Audio.Filters.ConvolutionFilter.GetChannelRMS () inline virtual
The RMS amplitude of each channel
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 243 of file ConvolutionFilter.cs.
         {
             if (_channelRMS == null)
             {
                 if (recalculateRMS)
                 {
                     _channelRMS = this.CalculateRMS();
                 }
                 else
                 {
                     _channelRMS = stream.GetChannelRMS();
                 }
             }
             return _channelRMS;
         }
Read()
override int BGC.Audio.Filters.ConvolutionFilter.Read (float [] data, int offset, int count) inline virtual
Copy count samples into the Data buffer, starting at offset.
Returns
The number of samples copied
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 125 of file ConvolutionFilter.cs.
References BGC.Mathematics.Fourier.Forward(), and BGC.Mathematics.Fourier.Inverse().
         {
             if (!initialized)
             {
                 Initialize();
             }
             int samplesWritten = ReadBody(data, offset, count);
             while (samplesWritten < count)
             {
                 int read = stream.Read(inputBuffer, 0, inputBuffer.Length);
                 if (read <= 0)
                 {
                     //Done, No samples left to work with
                     break;
                 }
                 //Slide output samples over to accumulate on the remainder
                 Array.Copy(
                     sourceArray: outputAccumulation,
                     sourceIndex: bufferCount,
                     destinationArray: outputAccumulation,
                     destinationIndex: 0,
                     length: outputAccumulation.Length - bufferCount);
                 Array.Clear(
                     array: outputAccumulation,
                     index: outputAccumulation.Length - bufferCount,
                     length: bufferCount);
                 bufferIndex = 0;
                 bufferCount = Channels * samplesPerOverlap;
                 if (read < inputBuffer.Length)
                 {
                     //Copy all the remaining samples
                     //We are guaranteed to have enough room because the output buffer's
                     //length is Channels * (inputBuffer.Length + fftLength)
                     bufferCount = read + Channels * (filterLength - 1);
                     //Set rest of inputBuffer to zero
                     Array.Clear(inputBuffer, read, inputBuffer.Length - read);
                 }
                 for (int channel = 0; channel < Channels; channel++)
                 {
                     for (int i = 0; i < samplesPerOverlap; i++)
                     {
                         fftBuffer[i] = inputBuffer[Channels * i + channel];
                     }
                     Array.Clear(fftBuffer, samplesPerOverlap, fftLength - samplesPerOverlap);
                     //FFT
                     Fourier.Forward(fftBuffer);
                     for (int i = 0; i < fftLength; i++)
                     {
                         fftBuffer[i] *= filterFD[i];
                     }
                     //IFFT
                     Fourier.Inverse(fftBuffer);
                     //Accumualte the window samples
                     for (int i = 0; i < fftLength; i++)
                     {
                         outputAccumulation[Channels * i + channel] += (float)fftBuffer[i].Real;
                     }
                 }
                 samplesWritten += ReadBody(data, offset + samplesWritten, count - samplesWritten);
             }
             return samplesWritten;
         }
ReadBody()
int BGC.Audio.Filters.ConvolutionFilter.ReadBody (float [] buffer, int offset, int count) inline private
Definition at line 205 of file ConvolutionFilter.cs.
         {
             int samplesWritten = Math.Max(0, Math.Min(count, bufferCount - bufferIndex));
             Array.Copy(
                 sourceArray: outputAccumulation,
                 sourceIndex: bufferIndex,
                 destinationArray: buffer,
                 destinationIndex: offset,
                 length: samplesWritten);
             bufferIndex += samplesWritten;
             return samplesWritten;
         }
Reset()
override void BGC.Audio.Filters.ConvolutionFilter.Reset () inline virtual
Sets this internal state of this stream to the initial state
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 230 of file ConvolutionFilter.cs.
         {
             ClearBuffers();
             stream.Reset();
         }
Seek()
override void BGC.Audio.Filters.ConvolutionFilter.Seek (int position) inline virtual
Seek to the indicated position in the stream
Implements BGC.Audio.Filters.BGCFilter.
Definition at line 236 of file ConvolutionFilter.cs.
         {
             ClearBuffers();
             stream.Seek(position);
         }
Field Documentation
_channelRMS
IEnumerable<double> BGC.Audio.Filters.ConvolutionFilter._channelRMS = null private
Definition at line 242 of file ConvolutionFilter.cs.
bufferCount
int BGC.Audio.Filters.ConvolutionFilter.bufferCount = 0 private
Definition at line 27 of file ConvolutionFilter.cs.
bufferIndex
int BGC.Audio.Filters.ConvolutionFilter.bufferIndex = 0 private
Definition at line 26 of file ConvolutionFilter.cs.
Channels
override int BGC.Audio.Filters.ConvolutionFilter.Channels => stream.Channels
Definition at line 30 of file ConvolutionFilter.cs.
FFT_EXP_MIN
const int BGC.Audio.Filters.ConvolutionFilter.FFT_EXP_MIN = 9 private
Definition at line 13 of file ConvolutionFilter.cs.
FFT_SIZE_BUMP
const int BGC.Audio.Filters.ConvolutionFilter.FFT_SIZE_BUMP = 1 private
Definition at line 14 of file ConvolutionFilter.cs.
fftBuffer
readonly Complex64 [] BGC.Audio.Filters.ConvolutionFilter.fftBuffer private
Definition at line 18 of file ConvolutionFilter.cs.
fftLength
readonly int BGC.Audio.Filters.ConvolutionFilter.fftLength private
Definition at line 21 of file ConvolutionFilter.cs.
filterFD
readonly Complex64 [] BGC.Audio.Filters.ConvolutionFilter.filterFD private
Definition at line 17 of file ConvolutionFilter.cs.
filterLength
readonly int BGC.Audio.Filters.ConvolutionFilter.filterLength private
Definition at line 24 of file ConvolutionFilter.cs.
inputBuffer
readonly float [] BGC.Audio.Filters.ConvolutionFilter.inputBuffer private
Definition at line 16 of file ConvolutionFilter.cs.
outputAccumulation
readonly float [] BGC.Audio.Filters.ConvolutionFilter.outputAccumulation private
Definition at line 19 of file ConvolutionFilter.cs.
recalculateRMS
readonly bool BGC.Audio.Filters.ConvolutionFilter.recalculateRMS private
Definition at line 28 of file ConvolutionFilter.cs.
samplesPerOverlap
readonly int BGC.Audio.Filters.ConvolutionFilter.samplesPerOverlap private
Definition at line 22 of file ConvolutionFilter.cs.
Property Documentation
ChannelSamples
override int BGC.Audio.Filters.ConvolutionFilter.ChannelSamples get
Definition at line 34 of file ConvolutionFilter.cs.
TotalSamples
override int BGC.Audio.Filters.ConvolutionFilter.TotalSamples get
Definition at line 32 of file ConvolutionFilter.cs.
The documentation for this class was generated from the following file:
Audio/Filters/ConvolutionFilter.cs