BGC Tools: LightJson.JsonArray Class Reference
LightJson.JsonArray Class Reference
Represents an ordered collection of JsonValues.
Data Structures
class JsonArrayDebugView
Public Member Functions
JsonArray ()
Initializes a new instance of JsonArray.
JsonArray (params JsonValue[] values)
Initializes a new instance and adds the given values to the collection.
JsonArray Add (JsonValue value)
Adds the given value to this collection.
JsonArray AddIfNotNull (JsonValue value)
Adds the given value to this collection only if the value is not null.
JsonArray Insert (int index, JsonValue value)
Inserts the given value at the given index in this collection.
JsonArray InsertIfNotNull (int index, JsonValue value)
Inserts the given value at the given index in this collection if it is not null.
JsonArray Remove (int index)
Removes the value at the given index.
JsonArray Clear ()
Clears the contents of this collection.
bool Contains (JsonValue item)
Determines whether the given item is in the JsonArray.
int IndexOf (JsonValue item)
Determines the index of the given item in this JsonArray.
IEnumerator< JsonValue > GetEnumerator ()
Returns an enumerator that iterates through the collection.
override string ToString ()
Returns a JSON string representing the state of the array.
string ToString (bool pretty)
Returns a JSON string representing the state of the array.
Data Fields
int Count => items.Count
The number of values in this collection.
Properties
JsonValue this[int index] [get, set]
The value at the given index.
Private Member Functions
System.Collections.IEnumerator System.Collections.IEnumerable. GetEnumerator ()
Returns an enumerator that iterates through the collection.
Private Attributes
List< JsonValue > items = new List<JsonValue>()
Detailed Description
Represents an ordered collection of JsonValues.
Definition at line 11 of file JsonArray.cs.
Constructor & Destructor Documentation
JsonArray() [1/2]
LightJson.JsonArray.JsonArray () inline
Initializes a new instance of JsonArray.
Definition at line 41 of file JsonArray.cs.
 { }
JsonArray() [2/2]
LightJson.JsonArray.JsonArray (params JsonValue [] values) inline
Initializes a new instance and adds the given values to the collection.
Parameters
values The values to be added to this collection.
Definition at line 47 of file JsonArray.cs.
                                                     : this()
         {
             if (values == null)
             {
                 throw new ArgumentNullException(nameof(values));
             }
             foreach (JsonValue value in values)
             {
                 items.Add(value);
             }
         }
Member Function Documentation
Add()
JsonArray LightJson.JsonArray.Add (JsonValue value) inline
Adds the given value to this collection.
Parameters
value The value to be added.
Returns
Returns this collection.
Definition at line 65 of file JsonArray.cs.
References LightJson.JsonArray.Add().
Referenced by LightJson.JsonArray.Add(), LightJson.JsonArray.AddIfNotNull(), BGC.Extensions.JsonExtensions.AnyListToStringJsonArray< T >(), BGC.Extensions.JsonExtensions.ConvertToJsonArray< T >(), BGC.DataStructures.EnumListContainer< TEnum >.Deserialize(), BGC.DataStructures.IntListContainer.Deserialize(), BGC.Extensions.JsonExtensions.FloatListToJsonArray(), BGC.Extensions.JsonExtensions.IntListToJsonArray(), BGC.Extensions.JsonExtensions.JsonArrayToList< T >(), LightJson.Serialization.JsonReader.ReadArray(), BGC.Audio.Calibration.SerializeCalibration(), BGC.Utility.JsonUtility.ToJsonArray(), and BGC.Utility.JsonUtility.ToJsonArray< T >().
         {
             items.Add(value);
             return this;
         }
AddIfNotNull()
JsonArray LightJson.JsonArray.AddIfNotNull (JsonValue value) inline
Adds the given value to this collection only if the value is not null.
Parameters
value The value to be added.
Returns
Returns this collection.
Definition at line 76 of file JsonArray.cs.
References LightJson.JsonArray.Add(), and LightJson.JsonValue.IsNull.
         {
             if (!value.IsNull)
             {
                 Add(value);
             }
             return this;
         }
Clear()
JsonArray LightJson.JsonArray.Clear () inline
Clears the contents of this collection.
Returns
Returns this collection.
Definition at line 129 of file JsonArray.cs.
References LightJson.JsonArray.Clear(), LightJson.JsonArray.Contains(), LightJson.JsonArray.GetEnumerator(), LightJson.JsonArray.IndexOf(), LightJson.Serialization.JsonWriter.Serialize(), and LightJson.JsonArray.ToString().
Referenced by LightJson.JsonArray.Clear().
         {
             items.Clear();
             return this;
         }
Contains()
bool LightJson.JsonArray.Contains (JsonValue item)
Determines whether the given item is in the JsonArray.
Parameters
item The item to locate in the JsonArray.
Returns
Returns true if the item is found; otherwise, false.
Referenced by LightJson.JsonArray.Clear().
GetEnumerator() [1/2]
IEnumerator<JsonValue> LightJson.JsonArray.GetEnumerator ()
Returns an enumerator that iterates through the collection.
Referenced by LightJson.JsonArray.Clear(), and LightJson.Serialization.JsonWriter.Render().
GetEnumerator() [2/2]
System.Collections.IEnumerator System.Collections.IEnumerable. LightJson.JsonArray.GetEnumerator () private
Returns an enumerator that iterates through the collection.
IndexOf()
int LightJson.JsonArray.IndexOf (JsonValue item)
Determines the index of the given item in this JsonArray.
Parameters
item The item to locate in this JsonArray.
Returns
The index of the item, if found. Otherwise, returns -1.
Referenced by LightJson.JsonArray.Clear().
Insert()
JsonArray LightJson.JsonArray.Insert (int index, JsonValue value) inline
Inserts the given value at the given index in this collection.
Parameters
index The index where the given value will be inserted.
value The value to be inserted into this collection.
Returns
Returns this collection.
Definition at line 92 of file JsonArray.cs.
References LightJson.JsonArray.Insert().
Referenced by LightJson.JsonArray.Insert(), and LightJson.JsonArray.InsertIfNotNull().
         {
             items.Insert(index, value);
             return this;
         }
InsertIfNotNull()
JsonArray LightJson.JsonArray.InsertIfNotNull (int index, JsonValue value) inline
Inserts the given value at the given index in this collection if it is not null.
Parameters
index The index where the given value will be inserted.
value The value to be inserted into this collection.
Returns
Returns this collection.
Definition at line 104 of file JsonArray.cs.
References LightJson.JsonArray.Insert(), and LightJson.JsonValue.IsNull.
         {
             if (!value.IsNull)
             {
                 Insert(index, value);
             }
             return this;
         }
Remove()
JsonArray LightJson.JsonArray.Remove (int index) inline
Removes the value at the given index.
Parameters
index The index of the value to be removed.
Returns
Return this collection.
Definition at line 119 of file JsonArray.cs.
         {
             items.RemoveAt(index);
             return this;
         }
ToString() [1/2]
override string LightJson.JsonArray.ToString ()
Returns a JSON string representing the state of the array.
The resulting string is safe to be inserted as is into dynamically generated JavaScript or JSON code.
Referenced by LightJson.JsonArray.Clear().
ToString() [2/2]
string LightJson.JsonArray.ToString (bool pretty)
Returns a JSON string representing the state of the array.
The resulting string is safe to be inserted as is into dynamically generated JavaScript or JSON code.
Parameters
pretty Indicates whether the resulting string should be formatted for human-readability.
Field Documentation
Count
int LightJson.JsonArray.Count => items.Count
The number of values in this collection.
Definition at line 16 of file JsonArray.cs.
Referenced by BGC.Extensions.JsonExtensions.AnyListToStringJsonArray< T >(), BGC.DataStructures.IntListContainer.Deserialize(), BGC.Audio.Calibration.DeserializeCalibration(), BGC.Extensions.JsonExtensions.FloatListToJsonArray(), BGC.IO.ResourceInfo.InitializeResourceInfo(), BGC.Extensions.JsonExtensions.IntListToJsonArray(), BGC.Extensions.JsonExtensions.JsonaArrayToStringList(), BGC.Extensions.JsonExtensions.JsonArrayToFloatList(), BGC.Extensions.IntListContainerExtensions.JsonArrayToIntListContainerList(), BGC.Tests.IntListContainerTests.TestJsonArray(), BGC.Tests.IntListContainerTests.TestJsonArrayConstructor(), and BGC.Utility.JsonUtility.ToIntArray().
items
List<JsonValue> LightJson.JsonArray.items = new List<JsonValue>() private
Definition at line 13 of file JsonArray.cs.
Property Documentation
this[int index]
JsonValue LightJson.JsonArray.this[int index] get set
The value at the given index.
Parameters
index The zero-based index of the value.
Will return JsonValue.Null if the given index is out of range.
Definition at line 22 of file JsonArray.cs.
The documentation for this class was generated from the following file:
LightJSON/JsonArray.cs