BGC Tools: BGC.Audio.Calibration Class Reference
BGC.Audio.Calibration Class Reference
Manages calibration values and processes
Data Structures
struct CalibrationPoint
class Keys
Public Types
enum Tone {
Tone._250Hz = 0, Tone._500Hz, Tone._1000Hz, Tone._2000Hz,
Tone._4000Hz, Tone._8000Hz, Tone.Noise, Tone.MAX
}
enum Source {
Source.Default = 0, Source.Custom, Source.Results, Source.InProgress,
Source.MAX
}
Static Public Member Functions
static void Initialize ()
static void Serialize ()
static void FinishCalibration ()
static void InitiateCalibration (int[] testLevels)
static void SubmitCalibrationValue (int step, AudioChannel channel, double offset)
static void PushCalibrationResults ()
static void DropCalibrationResults (Source source)
static Source GetSourceForVerificationPanel ()
static void GetLevelOffset (double level, out double levelOffsetL, out double levelOffsetR, Source source=Source.Custom)
static string GetToneName (this Tone tone)
static double GetFrequency (this Tone tone)
Static Private Member Functions
static void DeserializeCalibration (JsonObject parsedValue)
static JsonObject SerializeCalibration ()
Static Private Attributes
static List< CalibrationPoint > customCalibration = null
static List< CalibrationPoint > resultsCalibration = null
static List< CalibrationPoint > inProgressCalibration = null
static readonly string dataDir = "System"
static readonly string configFileName = "Calibration.json"
static bool initialized = false
Detailed Description
Manages calibration values and processes
Definition at line 13 of file Calibration.cs.
Member Enumeration Documentation
enum BGC.Audio.Calibration.Source strong
Enumerator
Default
Custom
Results
InProgress
MAX
Definition at line 36 of file Calibration.cs.
         {
             Default = 0,
             Custom,
             Results,
             InProgress,
             MAX
         }
enum BGC.Audio.Calibration.Tone strong
Enumerator
_250Hz
_500Hz
_1000Hz
_2000Hz
_4000Hz
_8000Hz
Noise
MAX
Definition at line 24 of file Calibration.cs.
         {
             _250Hz = 0,
             _500Hz,
             _1000Hz,
             _2000Hz,
             _4000Hz,
             _8000Hz,
             Noise,
             MAX
         }
Member Function Documentation
static void BGC.Audio.Calibration.DeserializeCalibration (JsonObject parsedValue) inline static private
Definition at line 69 of file Calibration.cs.
References LightJson.JsonObject.Add(), LightJson.JsonArray.Count, BGC.Audio.Calibration.Keys.CustomCalibration, BGC.Audio.Calibration.Keys.LAdjustment, BGC.Audio.Calibration.Keys.Level, and BGC.Audio.Calibration.Keys.RAdjustment.
         {
             JsonArray calibrationValues = parsedValue[Keys.CustomCalibration].AsJsonArray;
             if (calibrationValues.Count == 0)
             {
                 return;
             }
             customCalibration = new List<CalibrationPoint>(calibrationValues.Count);
             foreach (JsonObject calibrationPoint in calibrationValues)
             {
                 customCalibration.Add(new CalibrationPoint(
                     levelIn: calibrationPoint[Keys.Level],
                     levelOffsetL: calibrationPoint[Keys.LAdjustment].AsNumber,
                     levelOffsetR: calibrationPoint[Keys.RAdjustment].AsNumber));
             }
         }
static void BGC.Audio.Calibration.DropCalibrationResults (Source source) inline static
Definition at line 200 of file Calibration.cs.
         {
             switch (source)
             {
                 case Source.Custom:
                     customCalibration = null;
                     Serialize();
                     break;
                 case Source.Results:
                     resultsCalibration = null;
                     break;
                 case Source.InProgress:
                     inProgressCalibration = null;
                     break;
                 case Source.Default:
                 default:
                     Debug.LogError($"Unexpected Source: {source}");
                     break;
             }
         }
static void BGC.Audio.Calibration.FinishCalibration () inline static
Definition at line 118 of file Calibration.cs.
         {
             resultsCalibration = inProgressCalibration;
             inProgressCalibration = null;
         }
static double BGC.Audio.Calibration.GetFrequency (this Tone tone) inline static
Definition at line 339 of file Calibration.cs.
         {
             switch (tone)
             {
                 case Tone._250Hz: return 250;
                 case Tone._500Hz: return 500;
                 case Tone._1000Hz: return 1000;
                 case Tone._2000Hz: return 2000;
                 case Tone._4000Hz: return 4000;
                 case Tone._8000Hz: return 8000;
                 default:
                     Debug.LogError($"Unexpected Tone: {tone}");
                     return 100;
             }
         }
static void BGC.Audio.Calibration.GetLevelOffset (double level, out double levelOffsetL, out double levelOffsetR, Source source = Source.Custom) inline static
Definition at line 238 of file Calibration.cs.
References BGC.Mathematics.GeneralMath.Lerp().
Referenced by BGC.Audio.Normalization.CalculateRMSLevel(), and BGC.Audio.Normalization.SPLToAdjustmentDB().
         {
             List<CalibrationPoint> points;
             switch (source)
             {
                 case Source.InProgress:
                     if (inProgressCalibration == null || inProgressCalibration.Count == 0)
                     {
                         goto case Source.Results;
                     }
                     points = inProgressCalibration;
                     break;
                 case Source.Results:
                     if (resultsCalibration == null || resultsCalibration.Count == 0)
                     {
                         goto case Source.Custom;
                     }
                     points = resultsCalibration;
                     break;
                 case Source.Custom:
                     if (customCalibration == null || customCalibration.Count == 0)
                     {
                         goto case Source.Default;
                     }
                     points = customCalibration;
                     break;
                 case Source.Default:
                     levelOffsetL = 0.0;
                     levelOffsetR = 0.0;
                     return;
                 default:
                     Debug.LogError($"Unexpected Source: {source}");
                     goto case Source.Default;
             }
             if (points.Count == 1)
             {
                 levelOffsetL = points[0].levelOffsetL;
                 levelOffsetR = points[0].levelOffsetR;
                 return;
             }
             //If the requested level is before the first or after the last, use its assocaited offset
             if (level <= points[0].levelIn)
             {
                 levelOffsetL = points[0].levelOffsetL;
                 levelOffsetR = points[0].levelOffsetR;
                 return;
             }
             //Else, we will LERP between the surrounding offsets
             for (int index = 0; index < points.Count - 1; index++)
             {
                 if (level >= points[index].levelIn && level < points[index + 1].levelIn)
                 {
                     levelOffsetL = GeneralMath.Lerp(points[index].levelOffsetL,
                         points[index + 1].levelOffsetL,
                         (level - points[index].levelIn) / (points[index + 1].levelIn - points[index].levelIn));
                     levelOffsetR = GeneralMath.Lerp(points[index].levelOffsetR,
                         points[index + 1].levelOffsetR,
                         (level - points[index].levelIn) / (points[index + 1].levelIn - points[index].levelIn));
                     return;
                 }
             }
             //Else, we return the last value
             levelOffsetL = points[points.Count - 1].levelOffsetL;
             levelOffsetR = points[points.Count - 1].levelOffsetR;
         }
static Source BGC.Audio.Calibration.GetSourceForVerificationPanel () inline static
Definition at line 224 of file Calibration.cs.
         {
             if (resultsCalibration != null)
             {
                 return Source.Results;
             }
             else if (customCalibration != null)
             {
                 return Source.Custom;
             }
             return Source.Default;
         }
static string BGC.Audio.Calibration.GetToneName (this Tone tone) inline static
Definition at line 320 of file Calibration.cs.
         {
             switch (tone)
             {
                 case Tone._250Hz: return "250 Hz";
                 case Tone._500Hz: return "500 Hz";
                 case Tone._1000Hz: return "1000 Hz";
                 case Tone._2000Hz: return "2000 Hz";
                 case Tone._4000Hz: return "4000 Hz";
                 case Tone._8000Hz: return "8000 Hz";
                 case Tone.Noise: return "Noise";
                 case Tone.MAX: return "";
                 default:
                     Debug.LogError($"Unexpected Tone: {tone}");
                     return "";
             }
         }
static void BGC.Audio.Calibration.Initialize () inline static
Definition at line 54 of file Calibration.cs.
References BGC.IO.DataManagement.PathForDataFile(), and BGC.IO.FileReader.ReadJsonFile().
Referenced by BGC.Tests.SynthesisTests.FMTestBell(), BGC.Tests.SynthesisTests.FMTestBrass(), BGC.Tests.SynthesisTests.FMTestDrum(), BGC.Tests.SynthesisTests.FMTestOvertones(), BGC.Tests.SynthesisTests.FMTestPiano(), BGC.Tests.SynthesisTests.FMTestTrianglePiano(), BGC.Tests.SynthesisTests.SmallAnalyticFMTest(), BGC.Tests.SynthesisTests.SmallSineFMTest(), BGC.Tests.SynthesisTests.TestAllPassFilterSpeech(), BGC.Tests.SynthesisTests.TestAllPassFilterSynth(), BGC.Tests.SynthesisTests.TestBiQuadFilters(), BGC.Tests.SynthesisTests.TestCarrierModifiedFakeVoices(), BGC.Tests.MidiEncodingTests.TestContinuousFilter(), BGC.Tests.SynthesisTests.TestFakeVoice(), BGC.Tests.MidiEncodingTests.TestFlute(), BGC.Tests.SynthesisTests.TestFMFilterSynth(), BGC.Tests.SynthesisTests.TestFMFilterVoice(), BGC.Tests.SynthesisTests.TestFrequencyShifter(), BGC.Tests.SynthesisTests.TestFunFakeVoice(), BGC.Tests.MidiEncodingTests.TestGuitar(), BGC.Tests.MidiEncodingTests.TestOrgan(), BGC.Tests.MidiEncodingTests.TestPulses(), BGC.Tests.MidiEncodingTests.TestRenderMidi(), BGC.Tests.MidiEncodingTests.TestRenderToccataMidi(), BGC.Tests.SynthesisTests.TestSawtoothWave(), BGC.Tests.SynthesisTests.TestSineWave(), BGC.Tests.SynthesisTests.TestSquareWave(), and BGC.Tests.SynthesisTests.TestTriangleWave().
         {
             if (!initialized)
             {
                 initialized = true;
                 FileReader.ReadJsonFile(
                     path: DataManagement.PathForDataFile(dataDir, configFileName),
                     successCallback: DeserializeCalibration,
                     failCallback: Serialize,
                     fileNotFoundCallback: Serialize);
             }
         }
static void BGC.Audio.Calibration.InitiateCalibration (int[] testLevels) inline static
Definition at line 124 of file Calibration.cs.
         {
             //Make a new inProgressList that's a copy of the appropriate values
             switch (GetSourceForVerificationPanel())
             {
                 case Source.Custom:
                     inProgressCalibration = new List<CalibrationPoint>(customCalibration);
                     break;
                 case Source.Results:
                     inProgressCalibration = new List<CalibrationPoint>(resultsCalibration);
                     break;
                 case Source.Default:
                     inProgressCalibration = new List<CalibrationPoint>(testLevels.Length);
                     foreach (int level in testLevels)
                     {
                         inProgressCalibration.Add(new CalibrationPoint(
                             levelIn: level,
                             levelOffsetL: 0.0,
                             levelOffsetR: 0.0));
                     }
                     break;
                 case Source.InProgress:
                 default:
                     Debug.LogError($"Unexpected Source: {GetSourceForVerificationPanel()}");
                     break;
             }
         }
static void BGC.Audio.Calibration.PushCalibrationResults () inline static
Definition at line 186 of file Calibration.cs.
         {
             if (resultsCalibration == null)
             {
                 Debug.LogError("Null results calibration");
                 return;
             }
             customCalibration = resultsCalibration;
             resultsCalibration = null;
             Serialize();
         }
static void BGC.Audio.Calibration.Serialize () inline static
Definition at line 88 of file Calibration.cs.
References BGC.IO.DataManagement.PathForDataFile(), and BGC.IO.FileWriter.WriteJson().
         {
             FileWriter.WriteJson(
                 path: DataManagement.PathForDataFile(dataDir, configFileName),
                 createJson: SerializeCalibration,
                 pretty: true);
         }
static JsonObject BGC.Audio.Calibration.SerializeCalibration () inline static private
Definition at line 96 of file Calibration.cs.
References LightJson.JsonArray.Add(), BGC.Audio.Calibration.Keys.CustomCalibration, BGC.Audio.Calibration.Keys.LAdjustment, BGC.Audio.Calibration.Keys.Level, BGC.Audio.Calibration.CalibrationPoint.levelIn, BGC.Audio.Calibration.CalibrationPoint.levelOffsetL, BGC.Audio.Calibration.CalibrationPoint.levelOffsetR, and BGC.Audio.Calibration.Keys.RAdjustment.
         {
             JsonArray jsonCalibrationArray = new JsonArray();
             if (customCalibration != null)
             {
                 foreach (CalibrationPoint point in customCalibration)
                 {
                     jsonCalibrationArray.Add(new JsonObject()
                     {
                         { Keys.Level, point.levelIn },
                         { Keys.LAdjustment, point.levelOffsetL },
                         { Keys.RAdjustment, point.levelOffsetR }
                     });
                 }
             }
             return new JsonObject()
             {
                 { Keys.CustomCalibration, jsonCalibrationArray }
             };
         }
static void BGC.Audio.Calibration.SubmitCalibrationValue (int step, AudioChannel channel, double offset) inline static
Definition at line 156 of file Calibration.cs.
         {
             double left = inProgressCalibration[step].levelOffsetL;
             double right = inProgressCalibration[step].levelOffsetR;
             switch (channel)
             {
                 case AudioChannel.Left:
                     left += offset;
                     break;
                 case AudioChannel.Right:
                     right += offset;
                     break;
                 default:
                     Debug.LogError($"Unexpected Channel: {channel}");
                     break;
             }
             inProgressCalibration[step] = new CalibrationPoint(
                 levelIn: inProgressCalibration[step].levelIn,
                 levelOffsetL: left,
                 levelOffsetR: right);
         }
Field Documentation
readonly string BGC.Audio.Calibration.configFileName = "Calibration.json" static private
Definition at line 50 of file Calibration.cs.
List<CalibrationPoint> BGC.Audio.Calibration.customCalibration = null static private
Definition at line 45 of file Calibration.cs.
readonly string BGC.Audio.Calibration.dataDir = "System" static private
Definition at line 49 of file Calibration.cs.
bool BGC.Audio.Calibration.initialized = false static private
Definition at line 52 of file Calibration.cs.
List<CalibrationPoint> BGC.Audio.Calibration.inProgressCalibration = null static private
Definition at line 47 of file Calibration.cs.
List<CalibrationPoint> BGC.Audio.Calibration.resultsCalibration = null static private
Definition at line 46 of file Calibration.cs.
The documentation for this class was generated from the following file:
Audio/Calibration.cs