BGC Tools: BGC.Audio.Synthesis.FrequencyDomainToneComposer Class Reference
BGC.Audio.Synthesis.FrequencyDomainToneComposer Class Reference
Suboptimal attempt to do frame-based rendering of a set of carrier tones.
Public Member Functions
FrequencyDomainToneComposer (IEnumerable< ComplexCarrierTone > carrierTones, int frameSize=(1<< 11), int overlapFactor=8)
override int Read (float[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
override void Reset ()
Sets this internal state of this stream to the initial state
override void Seek (int position)
Seek to the indicated position in the stream
override IEnumerable< double > GetChannelRMS ()
The RMS amplitude of each channel
Public Member Functions inherited from BGC.Audio.BGCStream
void Initialize ()
Perform any calculations necessary to prepare the Stream
Data Fields
override int Channels => 1
override float SamplingRate => 44100f
override int TotalSamples => int.MaxValue
override int ChannelSamples => int.MaxValue
Private Member Functions
int ReadBody (float[] buffer, int offset, int count)
void ClearBuffers ()
Private Attributes
readonly ComplexCarrierTone [] carrierTones
readonly int frameSize
readonly int windowingSamples
readonly int overlapFactor
readonly int stepSize
readonly int overlap
readonly double timePerStep
readonly double outputScalar
readonly Complex64 [] ifftBuffer
readonly float [] outputAccumulation
readonly float [] cachedSampleBuffer
readonly double [] window
int leadingFrames = 0
int frame = 0
int bufferIndex = 0
int bufferCount = 0
IEnumerable< double > _channelRMS = null
Additional Inherited Members
Protected Member Functions inherited from BGC.Audio.BGCStream
virtual void _Initialize ()
Protected Attributes inherited from BGC.Audio.BGCStream
bool initialized = false
Properties inherited from BGC.Audio.BGCStream
abstract int Channels [get]
abstract int TotalSamples [get]
abstract int ChannelSamples [get]
abstract float SamplingRate [get]
Properties inherited from BGC.Audio.IBGCStream
int Channels [get]
The number of underlying Channels of this BGCStream
int TotalSamples [get]
The total number of Samples of this BGCStream
int ChannelSamples [get]
The number of Samples of each channel for this BGCStream
float SamplingRate [get]
The sampling rate of the Stream
Detailed Description
Suboptimal attempt to do frame-based rendering of a set of carrier tones.
Definition at line 13 of file FrequencyDomainToneComposer.cs.
Constructor & Destructor Documentation
FrequencyDomainToneComposer()
BGC.Audio.Synthesis.FrequencyDomainToneComposer.FrequencyDomainToneComposer (IEnumerable< ComplexCarrierTone > carrierTones, int frameSize = (1 << 11), int overlapFactor = 8) inline
Definition at line 44 of file FrequencyDomainToneComposer.cs.
         {
             this.carrierTones = carrierTones.ToArray();
             this.frameSize = frameSize;
             this.overlapFactor = overlapFactor;
             windowingSamples = frameSize / 2;
             stepSize = frameSize / overlapFactor;
             overlap = frameSize - stepSize;
             timePerStep = stepSize / (double)SamplingRate;
             //outputScalar = 1.0 / OVERLAP_FACTOR;
             outputScalar = 2.0 / (overlapFactor * Sqrt(frameSize));
             ifftBuffer = new Complex64[frameSize];
             outputAccumulation = new float[frameSize];
             cachedSampleBuffer = new float[stepSize];
             window = new double[frameSize];
             for (int i = 0; i < windowingSamples; i++)
             {
                 window[i] = 0.54 - 0.46 * Cos(i * PI / windowingSamples);
                 window[frameSize - i - 1] = window[i];
             }
             for (int i = windowingSamples; i < frameSize - windowingSamples; i++)
             {
                 window[i] = 1.0;
             }
             leadingFrames = -(overlapFactor - 1);
         }
Member Function Documentation
ClearBuffers()
void BGC.Audio.Synthesis.FrequencyDomainToneComposer.ClearBuffers () inline private
Definition at line 170 of file FrequencyDomainToneComposer.cs.
         {
             bufferIndex = 0;
             bufferCount = 0;
             leadingFrames = -(overlapFactor - 1);
             Array.Clear(outputAccumulation, 0, frameSize);
         }
GetChannelRMS()
override IEnumerable<double> BGC.Audio.Synthesis.FrequencyDomainToneComposer.GetChannelRMS () inline virtual
The RMS amplitude of each channel
Implements BGC.Audio.BGCStream.
Definition at line 196 of file FrequencyDomainToneComposer.cs.
         {
             if (_channelRMS is null)
             {
                 double rms = carrierTones.Select(x => 0.5 * x.amplitude.MagnitudeSquared).Sum();
                 _channelRMS = new double[] { Sqrt(rms) };
             }
             return _channelRMS;
         }
Read()
override int BGC.Audio.Synthesis.FrequencyDomainToneComposer.Read (float [] data, int offset, int count) inline virtual
Copy count samples into the Data buffer, starting at offset.
Returns
The number of samples copied
Implements BGC.Audio.BGCStream.
Definition at line 99 of file FrequencyDomainToneComposer.cs.
References BGC.Mathematics.Fourier.Inverse(), BGC.Audio.FrequencyDomain.Populate(), and BGC.Audio.ComplexCarrierTone.TimeShift().
         {
             int samplesWritten = ReadBody(data, offset, count);
             while (samplesWritten < count)
             {
                 bufferIndex = 0;
                 bufferCount = stepSize;
                 //Clear IFFT Buffer
                 Array.Clear(ifftBuffer, 0, ifftBuffer.Length);
                 //If there are any leading frames...
                 double timeShiftDeltaT = (frame + leadingFrames) * timePerStep;
                 bool isLeadingFrame = leadingFrames < 0;
                 foreach (ComplexCarrierTone carrierTone in carrierTones)
                 {
                     FrequencyDomain.Populate(
                         buffer: ifftBuffer,
                         carrierTone: carrierTone.TimeShift(timeShiftDeltaT));
                 }
                 //IFFT
                 Fourier.Inverse(ifftBuffer);
                 //Accumualte the window samples
                 for (int i = 0; i < frameSize; i++)
                 {
                     outputAccumulation[i] += (float)(outputScalar * window[i] * ifftBuffer[i].Real);
                 }
                 //Advance Frame
                 if (isLeadingFrame)
                 {
                     leadingFrames++;
                 }
                 else
                 {
                     frame++;
                 }
                 //Copy output samples to output buffer
                 Array.Copy(
                     sourceArray: outputAccumulation,
                     destinationArray: cachedSampleBuffer,
                     length: stepSize);
                 //Slide down output accumulation
                 Array.Copy(
                     sourceArray: outputAccumulation,
                     sourceIndex: stepSize,
                     destinationArray: outputAccumulation,
                     destinationIndex: 0,
                     length: overlap);
                 //Clear empty output accumulation region
                 Array.Clear(
                     array: outputAccumulation,
                     index: overlap,
                     length: stepSize);
                 if (!isLeadingFrame)
                 {
                     samplesWritten += ReadBody(data, offset + samplesWritten, count - samplesWritten);
                 }
             }
             return count;
         }
ReadBody()
int BGC.Audio.Synthesis.FrequencyDomainToneComposer.ReadBody (float [] buffer, int offset, int count) inline private
Definition at line 83 of file FrequencyDomainToneComposer.cs.
         {
             int samplesWritten = Min(count, bufferCount - bufferIndex);
             Array.Copy(
                 sourceArray: cachedSampleBuffer,
                 sourceIndex: bufferIndex,
                 destinationArray: buffer,
                 destinationIndex: offset,
                 length: samplesWritten);
             bufferIndex += samplesWritten;
             return samplesWritten;
         }
Reset()
override void BGC.Audio.Synthesis.FrequencyDomainToneComposer.Reset () inline virtual
Sets this internal state of this stream to the initial state
Implements BGC.Audio.BGCStream.
Definition at line 179 of file FrequencyDomainToneComposer.cs.
         {
             ClearBuffers();
             frame = 0;
         }
Seek()
override void BGC.Audio.Synthesis.FrequencyDomainToneComposer.Seek (int position) inline virtual
Seek to the indicated position in the stream
Implements BGC.Audio.BGCStream.
Definition at line 185 of file FrequencyDomainToneComposer.cs.
         {
             ClearBuffers();
             frame = position / stepSize;
             int scanSamples = position - stepSize * frame;
             float[] temp = new float[scanSamples];
             Read(temp, 0, scanSamples);
         }
Field Documentation
_channelRMS
IEnumerable<double> BGC.Audio.Synthesis.FrequencyDomainToneComposer._channelRMS = null private
Definition at line 195 of file FrequencyDomainToneComposer.cs.
bufferCount
int BGC.Audio.Synthesis.FrequencyDomainToneComposer.bufferCount = 0 private
Definition at line 42 of file FrequencyDomainToneComposer.cs.
bufferIndex
int BGC.Audio.Synthesis.FrequencyDomainToneComposer.bufferIndex = 0 private
Definition at line 41 of file FrequencyDomainToneComposer.cs.
cachedSampleBuffer
readonly float [] BGC.Audio.Synthesis.FrequencyDomainToneComposer.cachedSampleBuffer private
Definition at line 35 of file FrequencyDomainToneComposer.cs.
carrierTones
readonly ComplexCarrierTone [] BGC.Audio.Synthesis.FrequencyDomainToneComposer.carrierTones private
Definition at line 21 of file FrequencyDomainToneComposer.cs.
Channels
override int BGC.Audio.Synthesis.FrequencyDomainToneComposer.Channels => 1
Definition at line 15 of file FrequencyDomainToneComposer.cs.
ChannelSamples
override int BGC.Audio.Synthesis.FrequencyDomainToneComposer.ChannelSamples => int.MaxValue
Definition at line 19 of file FrequencyDomainToneComposer.cs.
frame
int BGC.Audio.Synthesis.FrequencyDomainToneComposer.frame = 0 private
Definition at line 39 of file FrequencyDomainToneComposer.cs.
frameSize
readonly int BGC.Audio.Synthesis.FrequencyDomainToneComposer.frameSize private
Definition at line 23 of file FrequencyDomainToneComposer.cs.
ifftBuffer
readonly Complex64 [] BGC.Audio.Synthesis.FrequencyDomainToneComposer.ifftBuffer private
Definition at line 33 of file FrequencyDomainToneComposer.cs.
leadingFrames
int BGC.Audio.Synthesis.FrequencyDomainToneComposer.leadingFrames = 0 private
Definition at line 38 of file FrequencyDomainToneComposer.cs.
outputAccumulation
readonly float [] BGC.Audio.Synthesis.FrequencyDomainToneComposer.outputAccumulation private
Definition at line 34 of file FrequencyDomainToneComposer.cs.
outputScalar
readonly double BGC.Audio.Synthesis.FrequencyDomainToneComposer.outputScalar private
Definition at line 31 of file FrequencyDomainToneComposer.cs.
overlap
readonly int BGC.Audio.Synthesis.FrequencyDomainToneComposer.overlap private
Definition at line 28 of file FrequencyDomainToneComposer.cs.
overlapFactor
readonly int BGC.Audio.Synthesis.FrequencyDomainToneComposer.overlapFactor private
Definition at line 26 of file FrequencyDomainToneComposer.cs.
SamplingRate
override float BGC.Audio.Synthesis.FrequencyDomainToneComposer.SamplingRate => 44100f
Definition at line 16 of file FrequencyDomainToneComposer.cs.
stepSize
readonly int BGC.Audio.Synthesis.FrequencyDomainToneComposer.stepSize private
Definition at line 27 of file FrequencyDomainToneComposer.cs.
timePerStep
readonly double BGC.Audio.Synthesis.FrequencyDomainToneComposer.timePerStep private
Definition at line 30 of file FrequencyDomainToneComposer.cs.
TotalSamples
override int BGC.Audio.Synthesis.FrequencyDomainToneComposer.TotalSamples => int.MaxValue
Definition at line 18 of file FrequencyDomainToneComposer.cs.
window
readonly double [] BGC.Audio.Synthesis.FrequencyDomainToneComposer.window private
Definition at line 36 of file FrequencyDomainToneComposer.cs.
windowingSamples
readonly int BGC.Audio.Synthesis.FrequencyDomainToneComposer.windowingSamples private
Definition at line 24 of file FrequencyDomainToneComposer.cs.
The documentation for this class was generated from the following file:
Audio/Synthesis/FrequencyDomainToneComposer.cs