BGC Tools: BGC.DataStructures.IntListContainer Class Reference
BGC.DataStructures.IntListContainer Class Reference
A Serializeable List<int> for lists of lists
Public Member Functions
IntListContainer (List< int > list)
Constructor from a List
IntListContainer (params int[] list)
Constructor from paramater list
IntListContainer (JsonArray json)
Constructor from a JsonArray
IntListContainer ()
Default empty constructor
void Add (int element)
Adds an element to a list
void RemoveAt (int index)
Removes an element at specified index
bool Remove (int element)
Remove an element from a list
bool Remove (IntListContainer lw)
Remove all elements in another IntListContainer Returns false if failed to remove one element
override bool Equals (object obj)
Check if two IntListContainers are equal
override int GetHashCode ()
Returns HashCode
void PrintSelf ()
Debug.Log to print out all values of the list
bool Contains (int item)
Check if the list Contains an item
Data Fields
List< int > list = new List<int>()
JsonArray JsonArray => list.IntListToJsonArray()
Get json array representation of the list
IntListContainer Clone => new IntListContainer(new List<int>(list))
Get a clean clone of this as a new int list container
int RandomValue => list.RandomValue<int>()
Get a random value in the list
int Count => list.Count
Get the number of elements in the list
Protected Member Functions
void Deserialize (JsonArray array)
Sets the list to a deserialized JsonArray
Properties
int this[int i] [get, set]
Get value at index i
Detailed Description
A Serializeable List<int> for lists of lists
Definition at line 13 of file IntListContainer.cs.
Constructor & Destructor Documentation
IntListContainer() [1/4]
BGC.DataStructures.IntListContainer.IntListContainer (List< int > list) inline
Constructor from a List
Parameters
list
Definition at line 59 of file IntListContainer.cs.
         {
             if (list == null)
             {
                 this.list = new List<int>();
             }
             else
             {
                 this.list = new List<int>(list);
             }
         }
IntListContainer() [2/4]
BGC.DataStructures.IntListContainer.IntListContainer (params int [] list) inline
Constructor from paramater list
Parameters
list
Definition at line 75 of file IntListContainer.cs.
         {
             if (list == null)
             {
                 this.list = new List<int>();
             }
             else
             {
                 this.list = new List<int>(list);
             }
         }
IntListContainer() [3/4]
BGC.DataStructures.IntListContainer.IntListContainer (JsonArray json) inline
Constructor from a JsonArray
Parameters
json
Definition at line 91 of file IntListContainer.cs.
         {
             if (json == null)
             {
                 list = new List<int>();
             }
             else
             {
                 Deserialize(json);
             }
         }
IntListContainer() [4/4]
BGC.DataStructures.IntListContainer.IntListContainer () inline
Default empty constructor
Definition at line 106 of file IntListContainer.cs.
         {
             list = new List<int>();
         }
Member Function Documentation
Add()
void BGC.DataStructures.IntListContainer.Add (int element) inline
Adds an element to a list
Parameters
element
Definition at line 115 of file IntListContainer.cs.
Referenced by BGC.Tests.IntListContainerTests.TestAdd().
         {
             list.Add(element);
         }
Contains()
bool BGC.DataStructures.IntListContainer.Contains (int item) inline
Check if the list Contains an item
Parameters
item
Returns
Definition at line 204 of file IntListContainer.cs.
Referenced by BGC.Tests.IntListContainerTests.TestContains(), BGC.Tests.IntListContainerTests.TestRemoveInt(), and BGC.Tests.IntListContainerTests.TestRemoveList().
         {
             return list.Contains(item);
         }
Deserialize()
void BGC.DataStructures.IntListContainer.Deserialize (JsonArray array) inline protected
Sets the list to a deserialized JsonArray
Parameters
array
Definition at line 213 of file IntListContainer.cs.
References LightJson.JsonArray.Add(), LightJson.JsonValue.AsInteger, LightJson.JsonArray.Count, and LightJson.JsonValue.IsInteger.
         {
             list = new List<int>();
             int count = array.Count;
             JsonValue arrayValue;
             for (int i = 0; i < count; ++i)
             {
                 arrayValue = array[i];
                 if (arrayValue.IsInteger)
                 {
                     list.Add(arrayValue.AsInteger);
                 }
                 else
                 {
                     throw new ArgumentException("Json array must be composed of only integers");
                 }
             }
         }
Equals()
override bool BGC.DataStructures.IntListContainer.Equals (object obj) inline
Check if two IntListContainers are equal
Parameters
obj
Returns
Definition at line 162 of file IntListContainer.cs.
Referenced by BGC.Tests.IntListContainerTests.TestClone(), and BGC.Tests.IntListContainerTests.TestEquals().
         {
             if(obj == null)
             {
                 return false;
             }
             if (obj.GetType() != GetType())
             {
                 if(obj.GetType() == typeof(List<int>))
                 {
                     return ListExtension.ListsEquivalent(list, (List<int>)obj);
                 }
                 return false;
             }
             return ListExtension.ListsEquivalent(list, ((IntListContainer)obj).list);
         }
GetHashCode()
override int BGC.DataStructures.IntListContainer.GetHashCode () inline
Returns HashCode
Returns
Definition at line 186 of file IntListContainer.cs.
Referenced by BGC.Tests.IntListContainerTests.TestGetHashCode().
         {
             return list.GetSequenceHashCode();
         }
PrintSelf()
void BGC.DataStructures.IntListContainer.PrintSelf () inline
Debug.Log to print out all values of the list
Definition at line 194 of file IntListContainer.cs.
Referenced by BGC.Tests.IntListContainerTests.TestPrintSelf().
         {
             list.PrintSelf();
         }
Remove() [1/2]
bool BGC.DataStructures.IntListContainer.Remove (int element) inline
Remove an element from a list
Parameters
element
Returns
Definition at line 134 of file IntListContainer.cs.
Referenced by BGC.Extensions.IntListContainerExtensions.RemoveValuesAboveValue(), BGC.Extensions.IntListContainerExtensions.RemoveValuesBelowValue(), BGC.Tests.IntListContainerTests.TestRemoveInt(), and BGC.Tests.IntListContainerTests.TestRemoveList().
         {
             return list.Remove(element);
         }
Remove() [2/2]
bool BGC.DataStructures.IntListContainer.Remove (IntListContainer lw) inline
Remove all elements in another IntListContainer Returns false if failed to remove one element
Parameters
lw
Returns
Definition at line 145 of file IntListContainer.cs.
References BGC.DataStructures.IntListContainer.Count.
         {
             bool removed = true;
             for (int i = 0; i < lw.Count; ++i)
             {
                 removed = Remove(lw[i]) && removed;
             }
             return removed;
         }
RemoveAt()
void BGC.DataStructures.IntListContainer.RemoveAt (int index) inline
Removes an element at specified index
Parameters
index
Definition at line 124 of file IntListContainer.cs.
Referenced by BGC.Tests.IntListContainerTests.TestRemoveAt().
         {
             list.RemoveAt(index);
         }
Field Documentation
Clone
IntListContainer BGC.DataStructures.IntListContainer.Clone => new IntListContainer(new List<int>(list))
Get a clean clone of this as a new int list container
Definition at line 43 of file IntListContainer.cs.
Referenced by BGC.Tests.IntListContainerTests.TestClone().
Count
int BGC.DataStructures.IntListContainer.Count => list.Count
Get the number of elements in the list
Definition at line 53 of file IntListContainer.cs.
Referenced by BGC.DataStructures.EnumListContainer< TEnum >.Remove(), BGC.DataStructures.IntListContainer.Remove(), BGC.Extensions.IntListContainerExtensions.RemoveValuesAboveValue(), BGC.Extensions.IntListContainerExtensions.RemoveValuesBelowValue(), BGC.Tests.IntListContainerTests.TestAdd(), BGC.Tests.IntListContainerTests.TestArrayConstructor(), BGC.Tests.IntListContainerTests.TestBracketAccess(), BGC.Tests.IntListContainerTests.TestCount(), BGC.Tests.IntListContainerTests.TestJsonArray(), BGC.Tests.IntListContainerTests.TestJsonArrayConstructor(), BGC.Tests.IntListContainerTests.TestListConstructor(), and BGC.Tests.IntListContainerTests.TestRemoveAt().
JsonArray
JsonArray BGC.DataStructures.IntListContainer.JsonArray => list.IntListToJsonArray()
Get json array representation of the list
Definition at line 38 of file IntListContainer.cs.
Referenced by BGC.Extensions.IntListContainerExtensions.IntListContainerListToJsonArray().
list
List<int> BGC.DataStructures.IntListContainer.list = new List<int>()
Definition at line 16 of file IntListContainer.cs.
Referenced by BGC.Tests.IntListContainerTests.TestEquals().
RandomValue
int BGC.DataStructures.IntListContainer.RandomValue => list.RandomValue<int>()
Get a random value in the list
Definition at line 48 of file IntListContainer.cs.
Referenced by BGC.Tests.IntListContainerTests.TestRandomValue().
Property Documentation
this[int i]
int BGC.DataStructures.IntListContainer.this[int i] get set
Get value at index i
Parameters
i
Returns
Definition at line 24 of file IntListContainer.cs.
The documentation for this class was generated from the following file:
DataStructures/Generic/IntListContainer.cs