BGC Tools: BGC.Audio.AnalyticStreams.AnalyticNoiseStream Class Reference
BGC.Audio.AnalyticStreams.AnalyticNoiseStream Class Reference
Public Types
enum AmplitudeDistribution {
AmplitudeDistribution.Violet = 0, AmplitudeDistribution.Blue, AmplitudeDistribution.White, AmplitudeDistribution.Pink,
AmplitudeDistribution.Brown, AmplitudeDistribution.MAX
}
Public Member Functions
AnalyticNoiseStream (double rms, double freqLB, double freqUB, int frequencyCount, AmplitudeDistribution distribution, Random randomizer=null)
void Initialize ()
Perform any calculations necessary to prepare the Stream
int Read (Complex64[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
void Reset ()
Sets this internal state of this stream to the initial state
void Seek (int position)
Seek to the indicated position in the stream
double GetRMS ()
The RMS amplitude of the stream (real component)
Data Fields
double SamplingRate => 44100.0
Private Member Functions
IEnumerable< ComplexCarrierTone > CreateSideBands (double freqLB, double freqUB, int count, AmplitudeDistribution distribution)
double GetFactor (AmplitudeDistribution amplitudeDistribution, double frequency)
Private Attributes
int IAnalyticStream. Samples => int.MaxValue
readonly Random randomizer
readonly AmplitudeDistribution distribution
readonly double rms
readonly double freqLB
readonly double freqUB
readonly int frequencyCount
Complex64 [] fftBuffer = null
int position = 0
int fftBufferSize
bool initialized = false
Additional Inherited Members
Properties inherited from BGC.Audio.AnalyticStreams.IAnalyticStream
int Samples [get]
The total number of Samples of this AnalyticStream
double SamplingRate [get]
The sampling rate of the Stream
Detailed Description
Definition at line 7 of file AnalyticNoiseClip.cs.
Member Enumeration Documentation
AmplitudeDistribution
enum BGC.Audio.AnalyticStreams.AnalyticNoiseStream.AmplitudeDistribution strong
Enumerator
Violet
Blue
White
Pink
Brown
MAX
Definition at line 9 of file AnalyticNoiseClip.cs.
         {
             Violet = 0,
             Blue,
             White,
             Pink,
             Brown,
             MAX
         }
Constructor & Destructor Documentation
AnalyticNoiseStream()
BGC.Audio.AnalyticStreams.AnalyticNoiseStream.AnalyticNoiseStream (double rms, double freqLB, double freqUB, int frequencyCount, AmplitudeDistribution distribution, Random randomizer = null) inline
Definition at line 35 of file AnalyticNoiseClip.cs.
References BGC.Mathematics.CustomRandom.Next().
         {
             if (randomizer == null)
             {
                 randomizer = new Random(CustomRandom.Next());
             }
             this.randomizer = randomizer;
             this.rms = rms;
             this.freqLB = freqLB;
             this.freqUB = freqUB;
             this.frequencyCount = frequencyCount;
             this.distribution = distribution;
         }
Member Function Documentation
CreateSideBands()
IEnumerable<ComplexCarrierTone> BGC.Audio.AnalyticStreams.AnalyticNoiseStream.CreateSideBands (double freqLB, double freqUB, int count, AmplitudeDistribution distribution) inline private
Definition at line 144 of file AnalyticNoiseClip.cs.
References BGC.Mathematics.Complex64.FromPolarCoordinates(), and BGC.Mathematics.CustomRandom.RayleighDistribution().
         {
             double freqRatio = Math.Pow((freqUB / freqLB), 1.0 / (count - 1));
             if (double.IsNaN(freqRatio) || double.IsInfinity(freqRatio))
             {
                 freqRatio = 1.0;
             }
             double freq = freqLB;
             for (int carrierTone = 0; carrierTone < count; carrierTone++)
             {
                 yield return new ComplexCarrierTone(
                     frequency: freq,
                     amplitude: Complex64.FromPolarCoordinates(
                         magnitude: GetFactor(distribution, freq) * CustomRandom.RayleighDistribution(randomizer.NextDouble()),
                         phase: 2.0 * Math.PI * randomizer.NextDouble()));
                 freq *= freqRatio;
             }
         }
GetFactor()
double BGC.Audio.AnalyticStreams.AnalyticNoiseStream.GetFactor (AmplitudeDistribution amplitudeDistribution, double frequency) inline private
Definition at line 172 of file AnalyticNoiseClip.cs.
         {
             switch (amplitudeDistribution)
             {
                 case AmplitudeDistribution.Violet: return frequency * Math.Sqrt(frequency);
                 case AmplitudeDistribution.Blue: return frequency;
                 case AmplitudeDistribution.White: return Math.Sqrt(frequency);
                 case AmplitudeDistribution.Pink: return 1.0;
                 case AmplitudeDistribution.Brown: return 1.0 / Math.Sqrt(frequency);
                 case AmplitudeDistribution.MAX:
                 default:
                     UnityEngine.Debug.LogError($"Unexpected AmplitudeFactor: {amplitudeDistribution}");
                     return 1.0;
             }
         }
GetRMS()
double BGC.Audio.AnalyticStreams.AnalyticNoiseStream.GetRMS ()
The RMS amplitude of the stream (real component)
Implements BGC.Audio.AnalyticStreams.IAnalyticStream.
Initialize()
void BGC.Audio.AnalyticStreams.AnalyticNoiseStream.Initialize () inline
Perform any calculations necessary to prepare the Stream
Implements BGC.Audio.AnalyticStreams.IAnalyticStream.
Definition at line 59 of file AnalyticNoiseClip.cs.
References BGC.Audio.ComplexCarrierTone.amplitude, BGC.Audio.ComplexCarrierTone.frequency, BGC.Mathematics.Fourier.Inverse(), BGC.Audio.FrequencyDomain.Populate(), and BGC.Mathematics.Complex64.Real.
         {
             if (initialized)
             {
                 return;
             }
             initialized = true;
             //Min of 10 periods of lowest frequency
             int bufferSizeLowerBound = (int)Math.Ceiling(SamplingRate * 10.0 / freqLB);
             fftBufferSize = bufferSizeLowerBound.CeilingToPowerOfTwo();
             fftBuffer = new Complex64[fftBufferSize];
             foreach (ComplexCarrierTone carrierTone in CreateSideBands(freqLB, freqUB, frequencyCount, distribution))
             {
                 FrequencyDomain.Populate(
                     buffer: fftBuffer,
                     frequency: carrierTone.frequency,
                     amplitude: carrierTone.amplitude);
             }
             Fourier.Inverse(fftBuffer);
             double currentRMS = 0.0;
             for (int i = 0; i < fftBufferSize; i++)
             {
                 currentRMS += fftBuffer[i].Real * fftBuffer[i].Real;
             }
             currentRMS = Math.Sqrt(currentRMS / fftBufferSize);
             double factor = rms / currentRMS;
             for (int i = 0; i < fftBufferSize; i++)
             {
                 fftBuffer[i] *= factor;
             }
         }
Read()
int BGC.Audio.AnalyticStreams.AnalyticNoiseStream.Read (Complex64 [] data, int offset, int count) inline
Copy count samples into the Data buffer, starting at offset.
Returns
The number of samples copied
Implements BGC.Audio.AnalyticStreams.IAnalyticStream.
Definition at line 99 of file AnalyticNoiseClip.cs.
         {
             if (!initialized)
             {
                 Initialize();
             }
             //Read...
             int samplesToRead = count;
             while (samplesToRead > 0)
             {
                 int readingSamples = Math.Min(samplesToRead, fftBufferSize - position);
                 for (int i = 0; i < readingSamples; i++)
                 {
                     data[offset + i] = fftBuffer[position + i];
                 }
                 samplesToRead -= readingSamples;
                 offset += readingSamples;
                 position += readingSamples;
                 if (position == fftBufferSize)
                 {
                     position = 0;
                 }
             }
             return count;
         }
Reset()
void BGC.Audio.AnalyticStreams.AnalyticNoiseStream.Reset ()
Sets this internal state of this stream to the initial state
Implements BGC.Audio.AnalyticStreams.IAnalyticStream.
Seek()
void BGC.Audio.AnalyticStreams.AnalyticNoiseStream.Seek (int position) inline
Seek to the indicated position in the stream
Implements BGC.Audio.AnalyticStreams.IAnalyticStream.
Definition at line 133 of file AnalyticNoiseClip.cs.
         {
             this.position = position % fftBufferSize;
             if (this.position < 0)
             {
                 this.position += fftBufferSize;
             }
         }
Field Documentation
distribution
readonly AmplitudeDistribution BGC.Audio.AnalyticStreams.AnalyticNoiseStream.distribution private
Definition at line 24 of file AnalyticNoiseClip.cs.
fftBuffer
Complex64 [] BGC.Audio.AnalyticStreams.AnalyticNoiseStream.fftBuffer = null private
Definition at line 30 of file AnalyticNoiseClip.cs.
fftBufferSize
int BGC.Audio.AnalyticStreams.AnalyticNoiseStream.fftBufferSize private
Definition at line 33 of file AnalyticNoiseClip.cs.
freqLB
readonly double BGC.Audio.AnalyticStreams.AnalyticNoiseStream.freqLB private
Definition at line 26 of file AnalyticNoiseClip.cs.
freqUB
readonly double BGC.Audio.AnalyticStreams.AnalyticNoiseStream.freqUB private
Definition at line 27 of file AnalyticNoiseClip.cs.
frequencyCount
readonly int BGC.Audio.AnalyticStreams.AnalyticNoiseStream.frequencyCount private
Definition at line 28 of file AnalyticNoiseClip.cs.
initialized
bool BGC.Audio.AnalyticStreams.AnalyticNoiseStream.initialized = false private
Definition at line 57 of file AnalyticNoiseClip.cs.
position
int BGC.Audio.AnalyticStreams.AnalyticNoiseStream.position = 0 private
Definition at line 32 of file AnalyticNoiseClip.cs.
randomizer
readonly Random BGC.Audio.AnalyticStreams.AnalyticNoiseStream.randomizer private
Definition at line 22 of file AnalyticNoiseClip.cs.
rms
readonly double BGC.Audio.AnalyticStreams.AnalyticNoiseStream.rms private
Definition at line 25 of file AnalyticNoiseClip.cs.
Samples
int IAnalyticStream. BGC.Audio.AnalyticStreams.AnalyticNoiseStream.Samples => int.MaxValue private
Definition at line 19 of file AnalyticNoiseClip.cs.
SamplingRate
double BGC.Audio.AnalyticStreams.AnalyticNoiseStream.SamplingRate => 44100.0
Definition at line 20 of file AnalyticNoiseClip.cs.
The documentation for this class was generated from the following file:
Audio/AnalyticStreams/AnalyticNoiseClip.cs