BGC Tools: BGC.Tests.IntListContainerTests Class Reference
BGC.Tests.IntListContainerTests Class Reference
Public Member Functions
void TestBracketAccess ()
void TestCount ()
void TestEquals ()
void TestListConstructor ()
void TestArrayConstructor ()
void TestJsonArrayConstructor ()
void TestEmptyConstructor ()
void TestClone ()
void TestRandomValue ()
void TestAdd ()
void TestRemoveAt ()
void TestJsonArray ()
void TestRemoveInt ()
void TestRemoveList ()
void TestGetHashCode ()
void TestPrintSelf ()
void TestContains ()
Detailed Description
Definition at line 12 of file IntListContainerTests.cs.
Member Function Documentation
TestAdd()
void BGC.Tests.IntListContainerTests.TestAdd () inline
Definition at line 177 of file IntListContainerTests.cs.
References BGC.DataStructures.IntListContainer.Add(), and BGC.DataStructures.IntListContainer.Count.
         {
             IntListContainer list = new IntListContainer();
             list.Add(0);
             Assert.AreEqual(1, list.Count);
             Assert.AreEqual(0, list[0]);
             list.Add(1);
             Assert.AreEqual(2, list.Count);
             Assert.AreEqual(1, list[1]);
         }
TestArrayConstructor()
void BGC.Tests.IntListContainerTests.TestArrayConstructor () inline
Definition at line 74 of file IntListContainerTests.cs.
References BGC.DataStructures.IntListContainer.Count.
         {
             int[] test1 = new int[] { 10, 5, 3 };
             int[] test2 = new int[] { };
             int[] nullTest = null;
             IntListContainer list1 = new IntListContainer(test1);
             IntListContainer list2 = new IntListContainer(test2);
             IntListContainer nullList = new IntListContainer(nullTest);
             IntListContainer paramTest = new IntListContainer(10, 5, 3);
             int count = test1.Length;
             int i;
             Assert.AreEqual(count, list1.Count);
             for (i = 0; i < count; ++i)
             {
                 Assert.AreEqual(test1[i], list1[i]);
             }
             Assert.AreEqual(0, list2.Count);
             Assert.AreEqual(0, nullList.Count);
             Assert.AreEqual(count, paramTest.Count);
             for (i = 0; i < count; ++i)
             {
                 Assert.AreEqual(list1[i], paramTest[i]);
             }
         }
TestBracketAccess()
void BGC.Tests.IntListContainerTests.TestBracketAccess () inline
Definition at line 15 of file IntListContainerTests.cs.
References BGC.DataStructures.IntListContainer.Count.
         {
             IntListContainer lw = new IntListContainer(0, 1, 2, 3, 4, 5, 6, 7);
             for (int i = 0; i < lw.Count; ++i)
             {
                 Assert.AreEqual(i, lw[i]);
             }
         }
TestClone()
void BGC.Tests.IntListContainerTests.TestClone () inline
Definition at line 147 of file IntListContainerTests.cs.
References BGC.DataStructures.IntListContainer.Clone, and BGC.DataStructures.IntListContainer.Equals().
         {
             IntListContainer list1 = new IntListContainer(1, 2, 3, 4, 5, 6, 7);
             IntListContainer clone = list1.Clone;
             Assert.IsTrue(list1.Equals(clone));
             list1[0] = 100;
             Assert.IsFalse(list1.Equals(clone));
         }
TestContains()
void BGC.Tests.IntListContainerTests.TestContains () inline
Definition at line 282 of file IntListContainerTests.cs.
References BGC.DataStructures.IntListContainer.Contains().
         {
             IntListContainer list1 = new IntListContainer(1, 2, 3, 4, 5, 65, 6, 8);
             IntListContainer list2 = new IntListContainer();
             Assert.IsTrue(list1.Contains(1));
             Assert.IsTrue(list1.Contains(65));
             Assert.IsFalse(list1.Contains(-1));
             Assert.IsFalse(list2.Contains(0));
         }
TestCount()
void BGC.Tests.IntListContainerTests.TestCount () inline
Definition at line 25 of file IntListContainerTests.cs.
References BGC.DataStructures.IntListContainer.Count.
         {
             IntListContainer lw = new IntListContainer(0, 1, 2, 3, 3, 4, 5, 5, 6, 7);
             Assert.AreEqual(10, lw.Count);
             lw = new IntListContainer();
             Assert.AreEqual(0, lw.Count);
         }
TestEmptyConstructor()
void BGC.Tests.IntListContainerTests.TestEmptyConstructor () inline
Definition at line 141 of file IntListContainerTests.cs.
         {
             Assert.AreEqual(0, new IntListContainer().Count);
         }
TestEquals()
void BGC.Tests.IntListContainerTests.TestEquals () inline
Definition at line 35 of file IntListContainerTests.cs.
References BGC.DataStructures.IntListContainer.Equals(), and BGC.DataStructures.IntListContainer.list.
         {
             IntListContainer lw1 = new IntListContainer(0, 1, 2, 3, 3, 4);
             IntListContainer lw2 = new IntListContainer(0, 6, 7);
             Assert.AreNotEqual(lw1.list, lw2.list);
             Assert.AreNotEqual(lw1, lw2);
             Assert.IsFalse(lw1.Equals(lw2));
             lw1 = new IntListContainer(0, 1, 2, 3, 3, 4, 5, 5, 6, 7);
             lw2 = new IntListContainer(0, 1, 2, 3, 3, 4, 5, 5, 6, 7);
             Assert.AreEqual(lw1.list, lw2.list);
             Assert.AreEqual(lw1, lw2);
             Assert.IsTrue(lw1.Equals(lw2));
         }
TestGetHashCode()
void BGC.Tests.IntListContainerTests.TestGetHashCode () inline
Definition at line 254 of file IntListContainerTests.cs.
References BGC.DataStructures.IntListContainer.GetHashCode().
         {
             IntListContainer list1 = new IntListContainer(0, 5123, 12, 1234, 1234, 1234, 1234, 12, 2, 5);
             List<int> list = new List<int>() { 0, 5123, 12, 1234, 1234, 1234, 1234, 12, 2, 5 };
             Assert.AreEqual(list.GetSequenceHashCode(), list1.GetHashCode());
             Assert.AreEqual(new List<int>().GetSequenceHashCode(), new IntListContainer().GetHashCode());
         }
TestJsonArray()
void BGC.Tests.IntListContainerTests.TestJsonArray () inline
Definition at line 203 of file IntListContainerTests.cs.
References LightJson.JsonArray.Count, and BGC.DataStructures.IntListContainer.Count.
         {
             IntListContainer list1 = new IntListContainer(0, 1, 2, 3, 4, 5, 6);
             IntListContainer list2 = new IntListContainer();
             JsonArray array1 = new JsonArray() { 0, 1, 2, 3, 4, 5, 6 };
             JsonArray array2 = new JsonArray();
             Assert.AreEqual(array1.Count, list1.Count);
             for (int i = 0; i < list1.Count; ++i)
             {
                 Assert.AreEqual(array1[i].AsInteger, list1[i]);
             }
             Assert.AreEqual(array2.Count, list2.Count);
         }
TestJsonArrayConstructor()
void BGC.Tests.IntListContainerTests.TestJsonArrayConstructor () inline
Definition at line 105 of file IntListContainerTests.cs.
References LightJson.JsonArray.Count, and BGC.DataStructures.IntListContainer.Count.
         {
             JsonArray test1 = new JsonArray() { 1123, 5, 33, 5, 10 };
             JsonArray test2 = new JsonArray();
             JsonArray test3 = null;
             JsonArray test4 = new JsonArray() { "hi", "world", new JsonObject() { { "uh", "oh" } } };
             IntListContainer list1 = new IntListContainer(test1);
             IntListContainer list2 = new IntListContainer(test2);
             IntListContainer list3 = new IntListContainer(test3);
             int count = test1.Count;
             Assert.AreEqual(count, list1.Count);
             for (int i = 0; i < count; ++i)
             {
                 Assert.AreEqual(test1[i].AsInteger, list1[i]);
             }
             Assert.AreEqual(0, list2.Count);
             Assert.AreEqual(0, list3.Count);
             try
             {
 #pragma warning disable 0219
                 IntListContainer list4 = new IntListContainer(test4);
 #pragma warning restore 0219
                 Assert.Fail();
             }
             catch (ArgumentException)
             {
                 Assert.Pass();
             }
         }
TestListConstructor()
void BGC.Tests.IntListContainerTests.TestListConstructor () inline
Definition at line 51 of file IntListContainerTests.cs.
References BGC.DataStructures.IntListContainer.Count.
         {
             List<int> testList1 = new List<int>() { 1, 2, 3, 4, 5, 6, 7, 8, 9, 0 };
             List<int> testList2 = new List<int>();
             List<int> nullList = null;
             IntListContainer list1 = new IntListContainer(testList1);
             IntListContainer list2 = new IntListContainer(testList2);
             IntListContainer list3 = new IntListContainer(nullList);
             int count = testList1.Count;
             int i;
             Assert.AreEqual(count, list1.Count);
             for (i = 0; i < count; ++i)
             {
                 Assert.AreEqual(testList1[i], list1[i]);
             }
             Assert.AreEqual(0, list2.Count);
             Assert.AreEqual(0, list3.Count);
         }
TestPrintSelf()
void BGC.Tests.IntListContainerTests.TestPrintSelf () inline
Definition at line 264 of file IntListContainerTests.cs.
References BGC.DataStructures.IntListContainer.PrintSelf().
         {
             IntListContainer list1 = new IntListContainer(0, 1, 2, 3, 4, 5);
             IntListContainer list2 = new IntListContainer();
             LogAssert.Expect(LogType.Log, "0) 0");
             LogAssert.Expect(LogType.Log, "1) 1");
             LogAssert.Expect(LogType.Log, "2) 2");
             LogAssert.Expect(LogType.Log, "3) 3");
             LogAssert.Expect(LogType.Log, "4) 4");
             LogAssert.Expect(LogType.Log, "5) 5");
             list1.PrintSelf();
             LogAssert.NoUnexpectedReceived();
             list2.PrintSelf();
         }
TestRandomValue()
void BGC.Tests.IntListContainerTests.TestRandomValue () inline
Definition at line 158 of file IntListContainerTests.cs.
References BGC.DataStructures.IntListContainer.RandomValue.
         {
             IntListContainer list = new IntListContainer(0, 1, 2, 3, 4, 5, 6, 76, 8, 98, 10);
             int randomValue = list.RandomValue;
             bool passed = false;
             for (int i = 0; i < 1000; ++i)
             {
                 if (randomValue != list.RandomValue)
                 {
                     passed = true;
                     break;
                 }
             }
             Assert.IsTrue(passed);
         }
TestRemoveAt()
void BGC.Tests.IntListContainerTests.TestRemoveAt () inline
Definition at line 190 of file IntListContainerTests.cs.
References BGC.DataStructures.IntListContainer.Count, and BGC.DataStructures.IntListContainer.RemoveAt().
         {
             IntListContainer list = new IntListContainer(0, 1, 2, 77, 3, 4);
             list.RemoveAt(3);
             Assert.AreEqual(5, list.Count);
             for (int i = 0; i < 5; ++i)
             {
                 Assert.AreEqual(i, list[i]);
             }
         }
TestRemoveInt()
void BGC.Tests.IntListContainerTests.TestRemoveInt () inline
Definition at line 221 of file IntListContainerTests.cs.
References BGC.DataStructures.IntListContainer.Contains(), and BGC.DataStructures.IntListContainer.Remove().
         {
             IntListContainer list1 = new IntListContainer(0, 1, 2, 3, 4, 5, 6, 6);
             Assert.IsTrue(list1.Remove(6));
             Assert.IsTrue(list1.Remove(6));
             Assert.IsFalse(list1.Contains(6));
             IntListContainer list2 = new IntListContainer();
             Assert.IsFalse(list2.Remove(0));
         }
TestRemoveList()
void BGC.Tests.IntListContainerTests.TestRemoveList () inline
Definition at line 233 of file IntListContainerTests.cs.
References BGC.DataStructures.IntListContainer.Contains(), and BGC.DataStructures.IntListContainer.Remove().
         {
             IntListContainer list1 = new IntListContainer(0, 1, 2, 3, 4, 5, 6, 6, 7);
             IntListContainer blackList = new IntListContainer(6, 7, 6);
             Assert.IsTrue(list1.Remove(blackList));
             Assert.IsFalse(list1.Contains(6));
             Assert.IsFalse(list1.Contains(7));
             for (int i = 0; i < 6; ++i)
             {
                 Assert.IsTrue(list1.Contains(i));
             }
             list1.Remove(new IntListContainer());
             for (int i = 0; i < 6; ++i)
             {
                 Assert.IsTrue(list1.Contains(i));
             }
         }
The documentation for this class was generated from the following file:
Editor/Tests/DataStructures/Generic/IntListContainerTests.cs