BGC Tools: BGC.IO.FileReader Class Reference
BGC.IO.FileReader Class Reference
Static Public Member Functions
static bool ReadJsonFile (string path, Action< JsonObject > successCallback, Action failCallback=null, Action fileNotFoundCallback=null, Action< string, Exception > overrideExceptionHandling=null)
Offers two error callbacks for when a file is not found and for when a file failed to parse correctly, and one for when the file has been succesfully parsed into a json object. With the latter, you can use the parsed object to build out whatever you need.
static JsonValue ReadJsonStream (TextReader jsonReader, Action< Exception > exceptionHandler=null)
Tries reading Json from a TextReader and returns the parsed JsonValue. Includes an optional exceptionHandler argument
static JsonValue SafeReadJsonString (string jsonText, Action< Exception > exceptionHandler=null)
Tries reading a Json string and returns the parsed JsonValue. Includes an optional exceptionHandler argument.
Static Private Member Functions
static void HandleException (string path, Exception excp)
static void HandleExceptionFiles (string path, string[] errorMessage)
Detailed Description
Definition at line 9 of file FileReader.cs.
Member Function Documentation
HandleException()
static void BGC.IO.FileReader.HandleException (string path, Exception excp) inline static private
Definition at line 125 of file FileReader.cs.
         {
             string[] errorMessage;
             if (excp is ParsingException parsingExcp)
             {
                 errorMessage = new string[]
                 {
                     "Internal parsing error.",
                     "",
                     parsingExcp.Message,
                     "",
                     "Suggested corrective action:",
                     parsingExcp.correctiveAction
                 };
             }
             else if (excp is JsonParseException jsonExcp)
             {
                 errorMessage = new string[]
                 {
                     "JSON parsing error",
                     "",
                     jsonExcp.Message,
                     "",
                     "Error Location:",
                     $"Line {jsonExcp.Position.line + 1}, Column {jsonExcp.Position.column + 1}"
                 };
             }
             else
             {
                 errorMessage = new string[]
                 {
                     "Exception Encountered",
                     "",
                     excp.Message,
                 };
             }
             HandleExceptionFiles(path, errorMessage);
         }
HandleExceptionFiles()
static void BGC.IO.FileReader.HandleExceptionFiles (string path, string [] errorMessage) inline static private
Definition at line 166 of file FileReader.cs.
         {
             string fileName = Path.GetFileName(path);
             string directoryPath = Path.GetDirectoryName(path);
             string directoryName = Path.GetFileName(directoryPath);
             string errorDirectory = $"Error{directoryName}";
             string errorDirectoryPath = Path.Combine(Path.GetDirectoryName(directoryPath), errorDirectory);
             string errorFilePath = Path.Combine(errorDirectoryPath, fileName);
             string errorLogPath = $"{errorFilePath}_error.txt";
             if (!Directory.Exists(errorDirectoryPath))
             {
                 Directory.CreateDirectory(errorDirectoryPath);
             }
             if (File.Exists(errorFilePath))
             {
                 File.Delete(errorFilePath);
             }
             File.Move(path, errorFilePath);
             if (File.Exists(errorLogPath))
             {
                 File.Delete(errorLogPath);
             }
             File.WriteAllLines(errorLogPath, errorMessage);
         }
ReadJsonFile()
static bool BGC.IO.FileReader.ReadJsonFile (string path, Action< JsonObject > successCallback, Action failCallback = null, Action fileNotFoundCallback = null, Action< string, Exception > overrideExceptionHandling = null) inline static
Offers two error callbacks for when a file is not found and for when a file failed to parse correctly, and one for when the file has been succesfully parsed into a json object. With the latter, you can use the parsed object to build out whatever you need.
There is also an optional override for exception handling.
Parameters
path File Path to load
successCallback Executed only on successful read
failCallback Notifies caller of failure
fileNotFoundCallback Notifies caller of failure to locate file
overrideExceptionHandling Optionally replaces default exception handling
Returns
Whether the json file was successfully read
Definition at line 24 of file FileReader.cs.
References LightJson.Serialization.JsonReader.ParseFile().
Referenced by BGC.Users.ProfileData.Deserialize(), BGC.Audio.Calibration.Initialize(), and BGC.Study.ProtocolManager.LoadProtocolSet().
         {
             bool jsonFileRead = false;
             try
             {
                 if (!File.Exists(path))
                 {
                     Debug.LogError($"Unable to find Json file at path \"{path}\"");
                     fileNotFoundCallback?.Invoke();
                 }
                 else
                 {
                     successCallback(JsonReader.ParseFile(path));
                     //If the above callback itself throws an exception, it will be caught here and
                     //ultimately the method will return false.
                     jsonFileRead = true;
                 }
             }
             catch (Exception excp)
             {
                 Debug.LogError($"Error parsing file at {path}: {excp.Message}");
                 failCallback?.Invoke();
                 if (overrideExceptionHandling != null)
                 {
                     overrideExceptionHandling.Invoke(path, excp);
                 }
                 else
                 {
                     HandleException(path, excp);
                 }
             }
             return jsonFileRead;
         }
ReadJsonStream()
static JsonValue BGC.IO.FileReader.ReadJsonStream (TextReader jsonReader, Action< Exception > exceptionHandler = null) inline static
Tries reading Json from a TextReader and returns the parsed JsonValue. Includes an optional exceptionHandler argument
Parameters
jsonReader As reader containing serialized Json
exceptionHandler An optional exception handler
Returns
Whether the json was successfully read
Definition at line 74 of file FileReader.cs.
References LightJson.JsonValue.Null, and LightJson.Serialization.JsonReader.Parse().
         {
             Debug.Assert(jsonReader != null);
             JsonValue parsedJson;
             try
             {
                 parsedJson = JsonReader.Parse(jsonReader);
             }
             catch (Exception excp)
             {
                 Debug.LogError($"Error parsing Json by text: {excp.Message}");
                 parsedJson = JsonValue.Null;
                 exceptionHandler?.Invoke(excp);
             }
             return parsedJson;
         }
SafeReadJsonString()
static JsonValue BGC.IO.FileReader.SafeReadJsonString (string jsonText, Action< Exception > exceptionHandler = null) inline static
Tries reading a Json string and returns the parsed JsonValue. Includes an optional exceptionHandler argument.
Parameters
jsonText As string containing deserialized Json
exceptionHandler An optional exception handler
Returns
Whether the json was successfully read
Definition at line 103 of file FileReader.cs.
References LightJson.JsonValue.Null, and LightJson.Serialization.JsonReader.Parse().
         {
             Debug.Assert(string.IsNullOrEmpty(jsonText) == false);
             JsonValue parsedJson;
             try
             {
                 parsedJson = JsonReader.Parse(jsonText);
             }
             catch (Exception excp)
             {
                 Debug.LogError($"Error parsing Json by text: {excp.Message}");
                 parsedJson = JsonValue.Null;
                 exceptionHandler?.Invoke(excp);
             }
             return parsedJson;
         }
The documentation for this class was generated from the following file:
IO/FileReader.cs