BGC Tools: BGC.Study.Session Class Reference
BGC.Study.Session Class Reference
Public Member Functions
Session ()
Session (JsonObject sessionData)
Deserialization Constructor Deserialized Sessions are not added to the Session dictionary
void Add (SessionElement element)
void AddRange (IEnumerable< SessionElement > elements)
JsonObject SerializeSession ()
Static Public Member Functions
static void HardClear ()
Data Fields
readonly int id
List< SessionElementID > sessionElements
JsonObject envVals
int Count => sessionElements.Count
SessionElement this[int i] => sessionElements[i].Element
Private Member Functions
IEnumerator< SessionElementID > IEnumerable< SessionElementID >. GetEnumerator ()
IEnumerator IEnumerable. GetEnumerator ()
Static Private Attributes
static int nextSessionID = 1
Detailed Description
Definition at line 75 of file Protocol.cs.
Constructor & Destructor Documentation
Session() [1/2]
BGC.Study.Session.Session () inline
Definition at line 84 of file Protocol.cs.
References BGC.Study.ProtocolManager.sessionDictionary.
         {
             id = nextSessionID++;
             sessionElements = new List<SessionElementID>();
             envVals = new JsonObject();
             ProtocolManager.sessionDictionary.Add(id, this);
         }
Session() [2/2]
BGC.Study.Session.Session (JsonObject sessionData) inline
Deserialization Constructor Deserialized Sessions are not added to the Session dictionary
Definition at line 97 of file Protocol.cs.
References LightJson.JsonObject.Add(), BGC.Study.ProtocolKeys.Session.EnvironmentValues, BGC.Study.ProtocolKeys.Session.Id, and BGC.Study.ProtocolKeys.Session.SessionElementIDs.
         {
             id = sessionData[ProtocolKeys.Session.Id];
             if (nextSessionID <= id)
             {
                 nextSessionID = id + 1;
             }
             sessionElements = new List<SessionElementID>();
             foreach (int sessionElementID in sessionData[ProtocolKeys.Session.SessionElementIDs].AsJsonArray)
             {
                 sessionElements.Add(sessionElementID);
             }
             if (sessionData.ContainsKey(ProtocolKeys.Session.EnvironmentValues))
             {
                 envVals = sessionData[ProtocolKeys.Session.EnvironmentValues].AsJsonObject;
             }
             else
             {
                 envVals = new JsonObject();
             }
         }
Member Function Documentation
Add()
void BGC.Study.Session.Add (SessionElement element) inline
Definition at line 125 of file Protocol.cs.
         {
             //It was supremely convenient for constructing tasks to allow for (and block)
             //  null session elements
             if (element != null)
             {
                 sessionElements.Add(element);
             }
         }
AddRange()
void BGC.Study.Session.AddRange (IEnumerable< SessionElement > elements) inline
Definition at line 135 of file Protocol.cs.
         {
             foreach (SessionElement element in elements)
             {
                 //It was supremely convenient for constructing tasks to allow for (and block)
                 //  null session elements
                 if (element != null)
                 {
                     sessionElements.Add(element);
                 }
             }
         }
GetEnumerator() [1/2]
IEnumerator<SessionElementID> IEnumerable<SessionElementID>. BGC.Study.Session.GetEnumerator () private
GetEnumerator() [2/2]
IEnumerator IEnumerable. BGC.Study.Session.GetEnumerator () private
HardClear()
static void BGC.Study.Session.HardClear () inline static
Definition at line 170 of file Protocol.cs.
Referenced by BGC.Study.ProtocolManager.HardClearAll().
         {
             nextSessionID = 1;
         }
SerializeSession()
JsonObject BGC.Study.Session.SerializeSession () inline
Definition at line 148 of file Protocol.cs.
References LightJson.JsonObject.Add(), LightJson.JsonObject.Count, BGC.Study.ProtocolKeys.Session.EnvironmentValues, BGC.Study.ProtocolKeys.Session.Id, BGC.Study.SessionElementID.id, and BGC.Study.ProtocolKeys.Session.SessionElementIDs.
Referenced by BGC.Study.ProtocolManager.SerializeSessions().
         {
             JsonArray jsonElementsIDs = new JsonArray();
             foreach (SessionElementID elementID in sessionElements)
             {
                 jsonElementsIDs.Add(elementID.id);
             }
             JsonObject newSession = new JsonObject()
             {
                 { ProtocolKeys.Session.Id, id },
                 { ProtocolKeys.Session.SessionElementIDs, jsonElementsIDs }
             };
             if (envVals.Count > 0)
             {
                 newSession.Add(ProtocolKeys.Session.EnvironmentValues, envVals);
             }
             return newSession;
         }
Field Documentation
Count
int BGC.Study.Session.Count => sessionElements.Count
Definition at line 122 of file Protocol.cs.
Referenced by BGC.Study.ProtocolManager.ExecuteNextElement(), and BGC.Study.ProtocolManager.SetSession().
envVals
JsonObject BGC.Study.Session.envVals
Definition at line 81 of file Protocol.cs.
Referenced by BGC.Study.ProtocolManager.GetEnvValue().
id
readonly int BGC.Study.Session.id
Definition at line 78 of file Protocol.cs.
Referenced by BGC.Study.ProtocolManager.DeserializeSessions(), and BGC.Study.SessionID.SessionID().
nextSessionID
int BGC.Study.Session.nextSessionID = 1 static private
Definition at line 77 of file Protocol.cs.
sessionElements
List<SessionElementID> BGC.Study.Session.sessionElements
Definition at line 80 of file Protocol.cs.
this[int i]
SessionElement BGC.Study.Session.this[int i] => sessionElements[i].Element
Definition at line 123 of file Protocol.cs.
The documentation for this class was generated from the following file:
Study/Protocol.cs