BGC Tools: BGC.Tests.BagTests Class Reference
BGC.Tests.BagTests Class Reference
Public Member Functions
void PsEmptyTests ()
void PullTests ()
void PullAutoResetTests ()
Private Attributes
readonly List< int > sampleList = new List<int>() { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 }
Detailed Description
Definition at line 7 of file DepletableBagTests.cs.
Member Function Documentation
void BGC.Tests.BagTests.PsEmptyTests () inline
Definition at line 12 of file DepletableBagTests.cs.
References BGC.DataStructures.Generic.DepletableBag< T >.Count, and BGC.DataStructures.Generic.DepletableBag< T >.PopNext().
         {
             DepletableBag<int> bag = new DepletableBag<int>(sampleList);
             Assert.IsFalse(bag.Count <= 0);
             for (int i = 0; i < sampleList.Count - 1; ++i)
             {
                 bag.PopNext();
                 Assert.IsFalse(bag.Count <= 0);
             }
             bag.PopNext();
             Assert.IsTrue(bag.Count <= 0);
         }
void BGC.Tests.BagTests.PullAutoResetTests () inline
Definition at line 58 of file DepletableBagTests.cs.
References BGC.DataStructures.Generic.DepletableBag< T >.AutoRefill, and BGC.DataStructures.Generic.DepletableBag< T >.PopNext().
         {
             DepletableBag<int> bag = new DepletableBag<int>(sampleList);
             bag.AutoRefill = true;
             for (int i = 0; i < 100; ++i)
             {
                 Assert.AreNotEqual(default(int), bag.PopNext());
             }
         }
void BGC.Tests.BagTests.PullTests () inline
Definition at line 28 of file DepletableBagTests.cs.
References BGC.DataStructures.Generic.DepletableBag< T >.Add(), BGC.DataStructures.Generic.DepletableBag< T >.Count, and BGC.DataStructures.Generic.DepletableBag< T >.PopNext().
         {
             DepletableBag<int> bag = new DepletableBag<int>(sampleList);
             Dictionary<int, bool> dictionary = new Dictionary<int, bool>();
             for (int i = 0; i < sampleList.Count; ++i)
             {
                 dictionary.Add(i, false);
             }
             while (bag.Count > 0)
             {
                 dictionary[bag.PopNext()] = true;
             }
             for (int i = 0; i < sampleList.Count; ++i)
             {
                 Assert.IsTrue(dictionary[i + 1]);
             }
             for (int i = 0; i < 100; ++i)
             {
                 if (i >= sampleList.Count)
                 {
                     Assert.AreEqual(default(int), bag.PopNext());
                 }
             }
         }
Field Documentation
readonly List<int> BGC.Tests.BagTests.sampleList = new List<int>() { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 } private
Definition at line 9 of file DepletableBagTests.cs.
The documentation for this class was generated from the following file:
Editor/Tests/DataStructures/Generic/DepletableBagTests.cs