BGC Tools: BGC.Audio.Spatial Class Reference
BGC.Audio.Spatial Class Reference
A collection of common operations related to Spatialization of Audio
Static Public Member Functions
static int NearestValidOffset (double offset)
static IBGCStream GetFilter (double angle)
Static Private Member Functions
static string GetFilterFilename (int position)
Private Attributes
const string HRTFDirectory = "HRTF"
Detailed Description
A collection of common operations related to Spatialization of Audio
Definition at line 11 of file Spatial.cs.
Member Function Documentation
static IBGCStream BGC.Audio.Spatial.GetFilter (double angle) inline static
Definition at line 26 of file Spatial.cs.
References BGC.Audio.WaveEncoding.LoadBGCStream().
Referenced by BGC.Audio.BGCStreamExtensions.Spatialize().
         {
             int position = NearestValidOffset(angle);
             string path = GetFilterFilename(position);
             bool loadSuccess = WaveEncoding.LoadBGCStream(
                 filepath: path,
                 stream: out IBGCStream filter);
             if (!loadSuccess)
             {
                 Debug.LogError($"Failed to load impulse response function from path {path}");
                 return null;
             }
             return filter;
         }
static string BGC.Audio.Spatial.GetFilterFilename (int position) inline static private
Definition at line 45 of file Spatial.cs.
References BGC.IO.DataManagement.PathForDataFile().
         {
             string filePrefix;
             if (position == 0)
             {
                 filePrefix = "0";
             }
             else
             {
                 string directionPrefix = (position > 0) ? "pos" : "neg";
                 position = Math.Abs(position);
                 int decimalPlace = position % 10;
                 int integralPlace = position / 10;
                 filePrefix = $"{directionPrefix}{integralPlace}p{decimalPlace}";
             }
             return DataManagement.PathForDataFile(HRTFDirectory, $"{filePrefix}_impulse.wav");
         }
static int BGC.Audio.Spatial.NearestValidOffset (double offset) inline static
Definition at line 15 of file Spatial.cs.
References BGC.Mathematics.GeneralMath.Clamp().
         {
             if (offset < -90.0 || offset > 90.0)
             {
                 Debug.LogError($"Spatialization offset ({offset})is outside of bounds [-90.0,90.0].  Clamping.");
                 offset = GeneralMath.Clamp(offset, -90.0, 90.0);
             }
             return (int)Math.Round(10.0 * offset);
         }
Field Documentation
const string BGC.Audio.Spatial.HRTFDirectory = "HRTF" private
Definition at line 13 of file Spatial.cs.
The documentation for this class was generated from the following file:
Audio/Spatial.cs