BGC Tools: BGC.Audio.BGCStreamExtensions Class Reference
BGC.Audio.BGCStreamExtensions Class Reference
Contains convenience extensions for BGCStreams, to support linear concatenation of filters
Static Public Member Functions
static IEnumerable< double > CalculateRMS (this IBGCStream stream)
Slowest Backup Alternative for calculating RMS
static double Duration (this IBGCStream stream)
Calculates the effective Duration of the stream
static IEnumerable< IBGCStream > EqualizeAndCenter (this IEnumerable< IBGCStream > streams, double minimumDuration=0.0)
Lengthen and center each BGCStream in streams so they are all the same duration
static IBGCStream StreamCache (this IBGCStream stream)
static IBGCStream Center (this IBGCStream stream, double minimumDuration=0.0)
Returns a stream at least minimumDuration in duration, with the clip centered in it
static IBGCStream Center (this IBGCStream stream, int preDelaySamples, int postDelaySamples)
static IBGCStream ContinuousFilter (this IBGCStream stream, IBGCEnvelopeStream envelopeStream, ContinuousFilter.FilterType filterType, double freqLB, double freqUB, double qFactor=double.NaN)
static IBGCStream ADSR (this IBGCStream stream, double timeToPeak, double timeToSustain, double sustainAmplitude, double sustainDecayTime)
static IBGCStream ADSR (this IBGCStream stream, double timeToPeak, double timeToSustain, double sustainAmplitude, double sustainDecayTime, double releaseDecayTime)
static IBGCStream ADSR (this IBGCStream stream, double timeToPeak, double timeToSustain, double timeToRelease, double sustainAmplitude, double sustainDecayTime, double releaseDecayTime)
static IBGCStream AddWith (this IBGCStream stream, IBGCStream other)
static IBGCStream AddWith (this IBGCStream stream, params IBGCStream[] others)
static IBGCStream AddTogether (this IEnumerable< IBGCStream > streams)
static IBGCStream Window (this IBGCStream stream, double totalDuration, Windowing.Function function=Windowing.Function.Hamming, int smoothingSamples=1000)
static IBGCStream Window (this IBGCStream stream, Windowing.Function function=Windowing.Function.Hamming, int smoothingSamples=1000)
static IBGCStream Window (this IBGCStream stream, Windowing.Function openingFunction, Windowing.Function closingFunction, int openingSmoothingSamples=1000, int closingSmoothingSamples=1000, int sampleShift=0, int totalChannelSamples=-1)
static IBGCStream Truncate (this IBGCStream stream, double totalDuration, int offset=0, bool recalculateRMS=false)
static IBGCStream Truncate (this IBGCStream stream, int totalChannelSamples, int offset=0, bool recalculateRMS=false)
static IBGCStream IsolateChannel (this IBGCStream stream, int channelIndex)
static IBGCStream Spatialize (this IBGCStream stream, double angle)
static IBGCStream MultiConvolve (this IBGCStream stream, IBGCStream filter, bool recalculateRMS=false)
static IBGCStream MultiConvolve (this IBGCStream stream, float[] filter1, float[] filter2, bool recalculateRMS=false)
static IBGCStream MultiConvolve (this IBGCStream stream, double[] filter1, double[] filter2, bool recalculateRMS=false)
static IBGCStream Normalize (this IBGCStream stream, double presentationLevel)
static IBGCStream Normalize (this IBGCStream stream,(double levelL, double levelR) presentationLevels)
static IBGCStream SlowRangeFitter (this IBGCStream stream)
static IBGCStream UpChannel (this IBGCStream stream, int channelCount=2)
static IBGCStream SelectiveUpChannel (this IBGCStream stream, AudioChannel channels)
static IBGCStream PhaseVocode (this IBGCStream stream, double speed)
static IBGCStream CarlileShuffle (this IBGCStream stream, double freqLowerBound=20.0, double freqUpperBound=16000.0, int bandCount=22, bool recalculateRMS=false, System.Random randomizer=null)
static IBGCStream CarlileShuffle (this IBGCStream stream, IEnumerable< double > frequencyDistribution, bool recalculateRMS=false, System.Random randomizer=null)
static IBGCStream AllPass (this IBGCStream stream, in Complex64 coefficient, int delay)
static IBGCStream FrequencyModulation (this IBGCStream stream, double modulationRate, double modulationDepth)
static IBGCStream StandardizeRMS (this IBGCStream stream, double rms=(1.0/128.0))
static IBGCStream Fork (this IBGCStream stream, out IBGCStream forkedStream)
static IBGCStream Split (this IBGCStream stream, out IBGCStream splitStream)
static IBGCStream ParallelInitialize (this IBGCStream stream)
static IBGCStream ApplyEnvelope (this IBGCStream stream, IBGCEnvelopeStream envelope, bool recalculateRMS=false)
static IBGCStream TimeShift (this IBGCStream stream, double timeShift)
static IBGCStream SinglePassPhaseReencode (this IBGCStream stream, double leftTimeShift, double rightTimeShift)
static IBGCStream Loop (this IBGCStream stream)
static IBGCStream ToStream (this ComplexCarrierTone carrierTone)
static IBGCStream ToStream (this IEnumerable< ComplexCarrierTone > carrierTones)
static Complex64 [] ComplexSamples (this IBGCStream stream, int sampleCount=-1)
Immediately collect all of the underlying samples and return as a Complex array
static Complex64 [] ComplexSamples (this IBGCStream stream, int channelIndex, int sampleCount=-1)
Immediately collect all of the underlying samples and return as a Complex array
static SimpleAudioClip Cache (this IBGCStream stream)
Immediately collect all of the underlying samples and return a SimpleAudioClip that contains them all
static SimpleAudioClip SafeCache (this IBGCStream stream)
Immediately collect all of the underlying samples and return a SimpleAudioClip that contains them all
Detailed Description
Contains convenience extensions for BGCStreams, to support linear concatenation of filters
Definition at line 16 of file BGCStreamExtensions.cs.
Member Function Documentation
AddTogether()
static IBGCStream BGC.Audio.BGCStreamExtensions.AddTogether (this IEnumerable< IBGCStream > streams) inline static
Definition at line 183 of file BGCStreamExtensions.cs.
         {
             return new StreamAdder(streams);
         }
AddWith() [1/2]
static IBGCStream BGC.Audio.BGCStreamExtensions.AddWith (this IBGCStream stream, IBGCStream other) inline static
Definition at line 167 of file BGCStreamExtensions.cs.
         {
             return new StreamAdder(stream, other);
         }
AddWith() [2/2]
static IBGCStream BGC.Audio.BGCStreamExtensions.AddWith (this IBGCStream stream, params IBGCStream [] others) inline static
Definition at line 174 of file BGCStreamExtensions.cs.
References BGC.Audio.Filters.StreamAdder.AddStreams().
         {
             StreamAdder adder = new StreamAdder(stream);
             adder.AddStreams(others);
             return adder;
         }
ADSR() [1/3]
static IBGCStream BGC.Audio.BGCStreamExtensions.ADSR (this IBGCStream stream, double timeToPeak, double timeToSustain, double sustainAmplitude, double sustainDecayTime) inline static
Definition at line 115 of file BGCStreamExtensions.cs.
         {
             return new ADSREnvelope(
                 stream: stream,
                 timeToPeak: timeToPeak,
                 timeToSustain: timeToSustain,
                 sustainAmplitude: sustainAmplitude,
                 sustainDecayTime: sustainDecayTime,
                 releaseDecayTime: sustainDecayTime);
         }
ADSR() [2/3]
static IBGCStream BGC.Audio.BGCStreamExtensions.ADSR (this IBGCStream stream, double timeToPeak, double timeToSustain, double sustainAmplitude, double sustainDecayTime, double releaseDecayTime) inline static
Definition at line 131 of file BGCStreamExtensions.cs.
         {
             return new ADSREnvelope(
                 stream: stream,
                 timeToPeak: timeToPeak,
                 timeToSustain: timeToSustain,
                 sustainAmplitude: sustainAmplitude,
                 sustainDecayTime: sustainDecayTime,
                 releaseDecayTime: releaseDecayTime);
         }
ADSR() [3/3]
static IBGCStream BGC.Audio.BGCStreamExtensions.ADSR (this IBGCStream stream, double timeToPeak, double timeToSustain, double timeToRelease, double sustainAmplitude, double sustainDecayTime, double releaseDecayTime) inline static
Definition at line 148 of file BGCStreamExtensions.cs.
         {
             return new ADSREnvelope(
                 stream: stream,
                 timeToPeak: timeToPeak,
                 timeToSustain: timeToSustain,
                 timeToRelease: timeToRelease,
                 sustainAmplitude: sustainAmplitude,
                 sustainDecayTime: sustainDecayTime,
                 releaseDecayTime: releaseDecayTime);
         }
AllPass()
static IBGCStream BGC.Audio.BGCStreamExtensions.AllPass (this IBGCStream stream, in Complex64 coefficient, int delay) inline static
Definition at line 379 of file BGCStreamExtensions.cs.
         {
             return new AllPassFilter(stream, coefficient, delay);
         }
ApplyEnvelope()
static IBGCStream BGC.Audio.BGCStreamExtensions.ApplyEnvelope (this IBGCStream stream, IBGCEnvelopeStream envelope, bool recalculateRMS = false) inline static
Definition at line 421 of file BGCStreamExtensions.cs.
         {
             return new StreamEnveloper(stream, envelope, recalculateRMS);
         }
Cache()
static SimpleAudioClip BGC.Audio.BGCStreamExtensions.Cache (this IBGCStream stream) inline static
Immediately collect all of the underlying samples and return a SimpleAudioClip that contains them all
Returns
New cached audio clip
Definition at line 569 of file BGCStreamExtensions.cs.
References BGC.Audio.IBGCStream.Channels, BGC.Audio.IBGCStream.Read(), BGC.Audio.IBGCStream.Reset(), and BGC.Audio.IBGCStream.TotalSamples.
         {
             stream.Reset();
             float[] samples = new float[stream.TotalSamples];
             stream.Read(samples, 0, stream.TotalSamples);
             stream.Reset();
             return new SimpleAudioClip(samples, stream.Channels);
         }
CalculateRMS()
static IEnumerable<double> BGC.Audio.BGCStreamExtensions.CalculateRMS (this IBGCStream stream) inline static
Slowest Backup Alternative for calculating RMS
Definition at line 21 of file BGCStreamExtensions.cs.
References BGC.Audio.IBGCStream.Channels, BGC.Audio.IBGCStream.ChannelSamples, BGC.Audio.IBGCStream.Read(), BGC.Audio.IBGCStream.Reset(), and BGC.Audio.IBGCStream.SamplingRate.
         {
             double[] rms = new double[stream.Channels];
             int readSamples;
             const int BUFFER_SIZE = 512;
             float[] buffer = new float[BUFFER_SIZE];
             stream.Reset();
             do
             {
                 readSamples = stream.Read(buffer, 0, BUFFER_SIZE);
                 for (int i = 0; i < readSamples; i++)
                 {
                     rms[i % stream.Channels] += buffer[i] * buffer[i];
                 }
             }
             while (readSamples > 0);
             stream.Reset();
             for (int i = 0; i < stream.Channels; i++)
             {
                 rms[i] = Math.Sqrt(rms[i] / stream.ChannelSamples);
             }
             return rms;
         }
CarlileShuffle() [1/2]
static IBGCStream BGC.Audio.BGCStreamExtensions.CarlileShuffle (this IBGCStream stream, double freqLowerBound = 20.0, double freqUpperBound = 16000.0, int bandCount = 22, bool recalculateRMS = false, System.Random randomizer = null) inline static
Definition at line 349 of file BGCStreamExtensions.cs.
         {
             return new CarlileShuffler(
                 stream: stream,
                 freqLowerBound: freqLowerBound,
                 freqUpperBound: freqUpperBound,
                 bandCount: bandCount,
                 recalculateRMS: recalculateRMS,
                 randomizer: randomizer);
         }
CarlileShuffle() [2/2]
static IBGCStream BGC.Audio.BGCStreamExtensions.CarlileShuffle (this IBGCStream stream, IEnumerable< double > frequencyDistribution, bool recalculateRMS = false, System.Random randomizer = null) inline static
Definition at line 366 of file BGCStreamExtensions.cs.
         {
             return new CarlileShuffler(
                 stream: stream,
                 frequencyDistribution: frequencyDistribution,
                 recalculateRMS: recalculateRMS,
                 randomizer: randomizer);
         }
Center() [1/2]
static IBGCStream BGC.Audio.BGCStreamExtensions.Center (this IBGCStream stream, double minimumDuration = 0.0) inline static
Returns a stream at least minimumDuration in duration, with the clip centered in it
Definition at line 83 of file BGCStreamExtensions.cs.
         {
             return new StreamCenterer(stream, Math.Max(stream.Duration(), minimumDuration));
         }
Center() [2/2]
static IBGCStream BGC.Audio.BGCStreamExtensions.Center (this IBGCStream stream, int preDelaySamples, int postDelaySamples) inline static
Definition at line 90 of file BGCStreamExtensions.cs.
         {
             return new StreamCenterer(stream, preDelaySamples, postDelaySamples);
         }
ComplexSamples() [1/2]
static Complex64 [] BGC.Audio.BGCStreamExtensions.ComplexSamples (this IBGCStream stream, int sampleCount = -1) inline static
Immediately collect all of the underlying samples and return as a Complex array
Definition at line 481 of file BGCStreamExtensions.cs.
References BGC.Audio.IBGCStream.Channels, BGC.Audio.IBGCStream.ChannelSamples, BGC.Audio.IBGCStream.Read(), and BGC.Audio.IBGCStream.Reset().
         {
             Debug.Assert(stream.Channels == 1);
             if (sampleCount == -1)
             {
                 sampleCount = stream.ChannelSamples;
             }
             const int BUFFER_SIZE = 512;
             float[] buffer = new float[BUFFER_SIZE];
             Complex64[] complexSamples = new Complex64[sampleCount];
             int readSamples;
             int offset = 0;
             stream.Reset();
             do
             {
                 int samplesToRead = Math.Min(BUFFER_SIZE, sampleCount - offset);
                 readSamples = stream.Read(buffer, 0, samplesToRead);
                 for (int i = 0; i < readSamples; i++)
                 {
                     complexSamples[offset + i] = buffer[i];
                 }
                 offset += readSamples;
             }
             while (readSamples > 0);
             stream.Reset();
             return complexSamples;
         }
ComplexSamples() [2/2]
static Complex64 [] BGC.Audio.BGCStreamExtensions.ComplexSamples (this IBGCStream stream, int channelIndex, int sampleCount = -1) inline static
Immediately collect all of the underlying samples and return as a Complex array
Definition at line 523 of file BGCStreamExtensions.cs.
References BGC.Audio.IBGCStream.Channels, BGC.Audio.IBGCStream.ChannelSamples, BGC.Audio.IBGCStream.Read(), and BGC.Audio.IBGCStream.Reset().
         {
             Debug.Assert(stream.Channels > channelIndex);
             if (sampleCount == -1)
             {
                 sampleCount = stream.ChannelSamples;
             }
             const int BUFFER_SIZE = 512;
             float[] buffer = new float[BUFFER_SIZE];
             Complex64[] complexSamples = new Complex64[sampleCount];
             int readSamples;
             int offset = 0;
             stream.Reset();
             do
             {
                 int samplesToRead = Math.Min(BUFFER_SIZE, stream.Channels * (sampleCount - offset));
                 readSamples = stream.Read(buffer, 0, samplesToRead);
                 int readChannelSamples = readSamples / stream.Channels;
                 for (int i = 0; i < readChannelSamples; i++)
                 {
                     complexSamples[offset + i] = buffer[stream.Channels * i + channelIndex];
                 }
                 offset += readChannelSamples;
             }
             while (readSamples > 0);
             stream.Reset();
             return complexSamples;
         }
ContinuousFilter()
static IBGCStream BGC.Audio.BGCStreamExtensions.ContinuousFilter (this IBGCStream stream, IBGCEnvelopeStream envelopeStream, ContinuousFilter.FilterType filterType, double freqLB, double freqUB, double qFactor = double.NaN) inline static
Definition at line 98 of file BGCStreamExtensions.cs.
         {
             return new ContinuousFilter(
                 stream: stream,
                 filterEnvelope: envelopeStream,
                 filterType: filterType,
                 freqLB: freqLB,
                 freqUB: freqUB,
                 qFactor: qFactor);
         }
Duration()
static double BGC.Audio.BGCStreamExtensions.Duration (this IBGCStream stream) static
Calculates the effective Duration of the stream
EqualizeAndCenter()
static IEnumerable<IBGCStream> BGC.Audio.BGCStreamExtensions.EqualizeAndCenter (this IEnumerable< IBGCStream > streams, double minimumDuration = 0.0) inline static
Lengthen and center each BGCStream in streams so they are all the same duration
Parameters
minimumDuration The minimum duration of each stream after lengthening
Returns
Each BGCStream, wrapped in a ClipCenterer
Definition at line 62 of file BGCStreamExtensions.cs.
         {
             double length = Math.Max(streams.Max(x => x.Duration()), minimumDuration);
             foreach (IBGCStream stream in streams)
             {
                 yield return new StreamCenterer(stream, length);
             }
         }
Fork()
static IBGCStream BGC.Audio.BGCStreamExtensions.Fork (this IBGCStream stream, out IBGCStream forkedStream) inline static
Definition at line 402 of file BGCStreamExtensions.cs.
         {
             return new StreamFork(stream, out forkedStream);
         }
FrequencyModulation()
static IBGCStream BGC.Audio.BGCStreamExtensions.FrequencyModulation (this IBGCStream stream, double modulationRate, double modulationDepth) inline static
Definition at line 387 of file BGCStreamExtensions.cs.
         {
             return new FrequencyModulationFilter(stream, modulationRate, modulationDepth);
         }
IsolateChannel()
static IBGCStream BGC.Audio.BGCStreamExtensions.IsolateChannel (this IBGCStream stream, int channelIndex) inline static
Definition at line 250 of file BGCStreamExtensions.cs.
         {
             return new ChannelIsolaterFilter(stream, channelIndex);
         }
Loop()
static IBGCStream BGC.Audio.BGCStreamExtensions.Loop (this IBGCStream stream) inline static
Definition at line 444 of file BGCStreamExtensions.cs.
         {
             return new StreamRepeater(stream);
         }
MultiConvolve() [1/3]
static IBGCStream BGC.Audio.BGCStreamExtensions.MultiConvolve (this IBGCStream stream, IBGCStream filter, bool recalculateRMS = false) inline static
Definition at line 264 of file BGCStreamExtensions.cs.
         {
             return new MultiConvolutionFilter(stream, filter, recalculateRMS);
         }
MultiConvolve() [2/3]
static IBGCStream BGC.Audio.BGCStreamExtensions.MultiConvolve (this IBGCStream stream, float [] filter1, float [] filter2, bool recalculateRMS = false) inline static
Definition at line 272 of file BGCStreamExtensions.cs.
         {
             return new MultiConvolutionFilter(stream, filter1, filter2, recalculateRMS);
         }
MultiConvolve() [3/3]
static IBGCStream BGC.Audio.BGCStreamExtensions.MultiConvolve (this IBGCStream stream, double [] filter1, double [] filter2, bool recalculateRMS = false) inline static
Definition at line 281 of file BGCStreamExtensions.cs.
         {
             return new MultiConvolutionFilter(stream, filter1, filter2, recalculateRMS);
         }
Normalize() [1/2]
static IBGCStream BGC.Audio.BGCStreamExtensions.Normalize (this IBGCStream stream, double presentationLevel) inline static
Definition at line 290 of file BGCStreamExtensions.cs.
References BGC.Audio.IBGCStream.Channels.
         {
             if (stream.Channels == 1)
             {
                 return new NormalizerMonoFilter(stream, presentationLevel);
             }
             else if (stream.Channels == 2)
             {
                 return new NormalizerFilter(stream, presentationLevel);
             }
             throw new NotSupportedException("Cannot normalize stream of more than 2 channels");
         }
Normalize() [2/2]
static IBGCStream BGC.Audio.BGCStreamExtensions.Normalize (this IBGCStream stream, (double levelL, double levelR) presentationLevels) inline static
Definition at line 306 of file BGCStreamExtensions.cs.
References BGC.Audio.IBGCStream.Channels.
         {
             if (stream.Channels == 1)
             {
                 return new NormalizerMonoFilter(stream, presentationLevels);
             }
             else if (stream.Channels == 2)
             {
                 return new NormalizerFilter(stream, presentationLevels);
             }
             throw new NotSupportedException("Cannot normalize stream of more than 2 channels");
         }
ParallelInitialize()
static IBGCStream BGC.Audio.BGCStreamExtensions.ParallelInitialize (this IBGCStream stream) inline static
Definition at line 415 of file BGCStreamExtensions.cs.
         {
             return new ParallelInitializer(stream);
         }
PhaseVocode()
static IBGCStream BGC.Audio.BGCStreamExtensions.PhaseVocode (this IBGCStream stream, double speed) inline static
Definition at line 342 of file BGCStreamExtensions.cs.
         {
             return new PhaseVocoder(stream, speed);
         }
SafeCache()
static SimpleAudioClip BGC.Audio.BGCStreamExtensions.SafeCache (this IBGCStream stream) inline static
Immediately collect all of the underlying samples and return a SimpleAudioClip that contains them all
Returns
New cached audio clip
Definition at line 584 of file BGCStreamExtensions.cs.
References BGC.Audio.IBGCStream.Channels, BGC.Audio.IBGCStream.Read(), and BGC.Audio.IBGCStream.Reset().
         {
             List<float> samples = new List<float>();
             const int BUFFER_SIZE = 512;
             float[] buffer = new float[BUFFER_SIZE];
             int readSamples;
             stream.Reset();
             do
             {
                 readSamples = stream.Read(buffer, 0, BUFFER_SIZE);
                 for (int i = 0; i < readSamples; i++)
                 {
                     samples.Add(buffer[i]);
                 }
             }
             while (readSamples > 0);
             stream.Reset();
             return new SimpleAudioClip(samples.ToArray(), stream.Channels);
         }
SelectiveUpChannel()
static IBGCStream BGC.Audio.BGCStreamExtensions.SelectiveUpChannel (this IBGCStream stream, AudioChannel channels) inline static
Definition at line 335 of file BGCStreamExtensions.cs.
         {
             return new StreamSelectiveUpChanneler(stream, channels);
         }
SinglePassPhaseReencode()
static IBGCStream BGC.Audio.BGCStreamExtensions.SinglePassPhaseReencode (this IBGCStream stream, double leftTimeShift, double rightTimeShift) inline static
Definition at line 436 of file BGCStreamExtensions.cs.
         {
             return new SinglePassPhaseReencoder(stream, leftTimeShift, rightTimeShift);
         }
SlowRangeFitter()
static IBGCStream BGC.Audio.BGCStreamExtensions.SlowRangeFitter (this IBGCStream stream) inline static
Definition at line 322 of file BGCStreamExtensions.cs.
         {
             return new SlowRangeFitterFilter(stream);
         }
Spatialize()
static IBGCStream BGC.Audio.BGCStreamExtensions.Spatialize (this IBGCStream stream, double angle) inline static
Definition at line 257 of file BGCStreamExtensions.cs.
References BGC.Audio.Spatial.GetFilter().
         {
             return new MultiConvolutionFilter(stream, Spatial.GetFilter(angle), false);
         }
Split()
static IBGCStream BGC.Audio.BGCStreamExtensions.Split (this IBGCStream stream, out IBGCStream splitStream) inline static
Definition at line 408 of file BGCStreamExtensions.cs.
         {
             return new StreamChannelSplitter(stream, out splitStream);
         }
StandardizeRMS()
static IBGCStream BGC.Audio.BGCStreamExtensions.StandardizeRMS (this IBGCStream stream, double rms = (1.0 / 128.0)) inline static
Definition at line 395 of file BGCStreamExtensions.cs.
         {
             return new StreamRMSStandardizer(stream, rms);
         }
StreamCache()
static IBGCStream BGC.Audio.BGCStreamExtensions.StreamCache (this IBGCStream stream) inline static
Definition at line 74 of file BGCStreamExtensions.cs.
         {
             return new StreamCacher(stream);
         }
TimeShift()
static IBGCStream BGC.Audio.BGCStreamExtensions.TimeShift (this IBGCStream stream, double timeShift) inline static
Definition at line 429 of file BGCStreamExtensions.cs.
         {
             return new StreamTimeShiftFilter(stream, timeShift);
         }
ToStream() [1/2]
static IBGCStream BGC.Audio.BGCStreamExtensions.ToStream (this ComplexCarrierTone carrierTone) inline static
Definition at line 449 of file BGCStreamExtensions.cs.
         {
             return new SineWave(carrierTone);
         }
ToStream() [2/2]
static IBGCStream BGC.Audio.BGCStreamExtensions.ToStream (this IEnumerable< ComplexCarrierTone > carrierTones) inline static
Definition at line 455 of file BGCStreamExtensions.cs.
         {
             int carrierToneCount = carrierTones.Count();
             if (carrierToneCount == 0)
             {
                 return new PerpetualSilence();
             }
             if (carrierToneCount == 1)
             {
                 return new SineWave(carrierTones.First());
             }
             if (carrierToneCount < 10)
             {
                 return new StreamAdder(carrierTones.Select(x => x.ToStream()));
             }
             return new FrequencyDomainToneComposer(carrierTones);
         }
Truncate() [1/2]
static IBGCStream BGC.Audio.BGCStreamExtensions.Truncate (this IBGCStream stream, double totalDuration, int offset = 0, bool recalculateRMS = false) inline static
Definition at line 232 of file BGCStreamExtensions.cs.
         {
             return new StreamTruncator(stream, totalDuration, offset, recalculateRMS);
         }
Truncate() [2/2]
static IBGCStream BGC.Audio.BGCStreamExtensions.Truncate (this IBGCStream stream, int totalChannelSamples, int offset = 0, bool recalculateRMS = false) inline static
Definition at line 241 of file BGCStreamExtensions.cs.
         {
             return new StreamTruncator(stream, totalChannelSamples, offset, recalculateRMS);
         }
UpChannel()
static IBGCStream BGC.Audio.BGCStreamExtensions.UpChannel (this IBGCStream stream, int channelCount = 2) inline static
Definition at line 328 of file BGCStreamExtensions.cs.
         {
             return new UpChannelMonoFilter(stream, channelCount);
         }
Window() [1/3]
static IBGCStream BGC.Audio.BGCStreamExtensions.Window (this IBGCStream stream, double totalDuration, Windowing.Function function = Windowing.Function.Hamming, int smoothingSamples = 1000) inline static
Definition at line 189 of file BGCStreamExtensions.cs.
         {
             return new StreamWindower(
                 stream: stream,
                 function: function,
                 totalDuration: totalDuration,
                 smoothingSamples: smoothingSamples);
         }
Window() [2/3]
static IBGCStream BGC.Audio.BGCStreamExtensions.Window (this IBGCStream stream, Windowing.Function function = Windowing.Function.Hamming, int smoothingSamples = 1000) inline static
Definition at line 202 of file BGCStreamExtensions.cs.
         {
             return new StreamWindower(
                 stream: stream,
                 function: function,
                 smoothingSamples: smoothingSamples);
         }
Window() [3/3]
static IBGCStream BGC.Audio.BGCStreamExtensions.Window (this IBGCStream stream, Windowing.Function openingFunction, Windowing.Function closingFunction, int openingSmoothingSamples = 1000, int closingSmoothingSamples = 1000, int sampleShift = 0, int totalChannelSamples = -1) inline static
Definition at line 213 of file BGCStreamExtensions.cs.
         {
             return new StreamWindower(
                 stream: stream,
                 openingFunction: openingFunction,
                 closingFunction: closingFunction,
                 openingSmoothingSamples: openingSmoothingSamples,
                 closingSmoothingSamples: closingSmoothingSamples,
                 sampleShift: sampleShift,
                 totalChannelSamples: totalChannelSamples);
         }
The documentation for this class was generated from the following file:
Audio/BGCStreamExtensions.cs