BGC Tools: BGC.UI.Panels.ModePanel Class Reference
BGC.UI.Panels.ModePanel Class Reference abstract
Public Member Functions
abstract void FocusAcquired ()
abstract void FocusLost ()
void ImmediateStateSet (bool visible)
Data Fields
RectTransform RectTransform => _rt ?? (_rt = GetComponent<RectTransform>())
RectTransform ParentRectTransform => _parentRT ?? (_parentRT = RectTransform.parent.GetComponent<RectTransform>())
ModePanelLerpedActionChannel LerpHandler
Private Attributes
RectTransform _rt = null
RectTransform _parentRT = null
ModePanelLerpedActionChannel _lerpHandler = null
Detailed Description
Definition at line 5 of file ModePanel.cs.
Member Function Documentation
FocusAcquired()
abstract void BGC.UI.Panels.ModePanel.FocusAcquired () pure virtual
Implemented in BGC.UI.Panels.CopyPanel.
Referenced by BGC.UI.Panels.ModePanelManager.ImmediatePanelSet(), BGC.UI.Panels.ModePanelManager.SetPanelActive(), BGC.UI.Panels.ModePanelManager.SpecialSetPanelActive(), and BGC.UI.Panels.ModePanelManager.Start().
FocusLost()
abstract void BGC.UI.Panels.ModePanel.FocusLost () pure virtual
Implemented in BGC.UI.Panels.CopyPanel.
Referenced by BGC.UI.Panels.ModePanelManager.ImmediatePanelSet(), BGC.UI.Panels.ModePanelManager.SetPanelActive(), and BGC.UI.Panels.ModePanelManager.SpecialSetPanelActive().
ImmediateStateSet()
void BGC.UI.Panels.ModePanel.ImmediateStateSet (bool visible) inline
Definition at line 16 of file ModePanel.cs.
Referenced by BGC.UI.Panels.ModePanelManager.ImmediatePanelSet(), BGC.UI.Panels.ModePanelManager.SpecialSetPanelActive(), and BGC.UI.Panels.ModePanelManager.Start().
         {
             RectTransform.pivot = ParentRectTransform.pivot;
             RectTransform.localPosition = visible ? Vector2.zero : new Vector2(Screen.width, Screen.height);
         }
Field Documentation
_lerpHandler
ModePanelLerpedActionChannel BGC.UI.Panels.ModePanel._lerpHandler = null private
Definition at line 22 of file ModePanel.cs.
_parentRT
RectTransform BGC.UI.Panels.ModePanel._parentRT = null private
Definition at line 10 of file ModePanel.cs.
_rt
RectTransform BGC.UI.Panels.ModePanel._rt = null private
Definition at line 7 of file ModePanel.cs.
LerpHandler
ModePanelLerpedActionChannel BGC.UI.Panels.ModePanel.LerpHandler
Initial value:
=> _lerpHandler ??
            (_lerpHandler = GetComponent<ModePanelLerpedActionChannel>()) ??
            (_lerpHandler = gameObject.AddComponent<ModePanelLerpedActionChannel>())
Definition at line 23 of file ModePanel.cs.
Referenced by BGC.UI.Panels.ModePanelManager.SetPanelActive(), and BGC.UI.Panels.ModePanelManager.SpecialSetPanelActive().
ParentRectTransform
RectTransform BGC.UI.Panels.ModePanel.ParentRectTransform => _parentRT ?? (_parentRT = RectTransform.parent.GetComponent<RectTransform>())
Definition at line 11 of file ModePanel.cs.
RectTransform
RectTransform BGC.UI.Panels.ModePanel.RectTransform => _rt ?? (_rt = GetComponent<RectTransform>())
Definition at line 8 of file ModePanel.cs.
Referenced by BGC.UI.Panels.ModePanelManager.SpecialSetPanelActive().
The documentation for this class was generated from the following file:
UI/Panels/ModePanel.cs