BGC Tools: BGC.Audio.AnalyticStreams.IAnalyticStream Interface Reference
BGC.Audio.AnalyticStreams.IAnalyticStream Interface Reference
Public Member Functions
void Initialize ()
Perform any calculations necessary to prepare the Stream
int Read (Complex64[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
void Reset ()
Sets this internal state of this stream to the initial state
void Seek (int position)
Seek to the indicated position in the stream
double GetRMS ()
The RMS amplitude of the stream (real component)
Properties
int Samples [get]
The total number of Samples of this AnalyticStream
double SamplingRate [get]
The sampling rate of the Stream
Detailed Description
Definition at line 7 of file IAnalyticStream.cs.
Member Function Documentation
GetRMS()
double BGC.Audio.AnalyticStreams.IAnalyticStream.GetRMS ()
The RMS amplitude of the stream (real component)
Implemented in BGC.Audio.AnalyticStreams.AnalyticStreamFork.InternalStreamFork, BGC.Audio.AnalyticStreams.AnalyticADSREnvelope, BGC.Audio.AnalyticStreams.AnalyticNoiseStream, BGC.Audio.AnalyticStreams.AnalyticStreamWindower, BGC.Audio.AnalyticStreams.AnalyticStreamFork, BGC.Audio.AnalyticStreams.AnalyticStreamAdder, BGC.Audio.AnalyticStreams.AnalyticStreamConverter, BGC.Audio.AnalyticStreams.AnalyticWave, BGC.Audio.AnalyticStreams.AnalyticStreamCenterer, BGC.Audio.AnalyticStreams.AnalyticStreamFrequencyShifter, BGC.Audio.AnalyticStreams.AnalyticFrequencyModulationFilter, and BGC.Audio.AnalyticStreams.AnalyticFilter.
Initialize()
void BGC.Audio.AnalyticStreams.IAnalyticStream.Initialize ()
Perform any calculations necessary to prepare the Stream
Implemented in BGC.Audio.AnalyticStreams.AnalyticStreamConverter, BGC.Audio.AnalyticStreams.AnalyticNoiseStream, BGC.Audio.AnalyticStreams.AnalyticWave, and BGC.Audio.AnalyticStreams.AnalyticFilter.
Referenced by BGC.Audio.AnalyticStreams.AnalyticStreamConverter.AnalyticStreamConverter(), and BGC.Audio.AnalyticStreams.AnalyticFilter.Initialize().
Read()
int BGC.Audio.AnalyticStreams.IAnalyticStream.Read (Complex64 [] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
Returns
The number of samples copied
Implemented in BGC.Audio.AnalyticStreams.AnalyticStreamFork.InternalStreamFork, BGC.Audio.AnalyticStreams.AnalyticADSREnvelope, BGC.Audio.AnalyticStreams.AnalyticNoiseStream, BGC.Audio.AnalyticStreams.AnalyticStreamConverter, BGC.Audio.AnalyticStreams.AnalyticStreamWindower, BGC.Audio.AnalyticStreams.AnalyticStreamAdder, BGC.Audio.AnalyticStreams.AnalyticWave, BGC.Audio.AnalyticStreams.AnalyticStreamFrequencyShifter, BGC.Audio.AnalyticStreams.AnalyticStreamCenterer, BGC.Audio.AnalyticStreams.AnalyticFrequencyModulationFilter, BGC.Audio.AnalyticStreams.AnalyticStreamFork, and BGC.Audio.AnalyticStreams.AnalyticFilter.
Referenced by BGC.Audio.AnalyticStreams.AnalyticStreamExtensions.CalculateRMS(), and BGC.Audio.AnalyticStreams.AnalyticStreamAdder.Read().
Reset()
void BGC.Audio.AnalyticStreams.IAnalyticStream.Reset ()
Sets this internal state of this stream to the initial state
Implemented in BGC.Audio.AnalyticStreams.AnalyticStreamFork.InternalStreamFork, BGC.Audio.AnalyticStreams.AnalyticADSREnvelope, BGC.Audio.AnalyticStreams.AnalyticNoiseStream, BGC.Audio.AnalyticStreams.AnalyticStreamConverter, BGC.Audio.AnalyticStreams.AnalyticStreamCenterer, BGC.Audio.AnalyticStreams.AnalyticWave, BGC.Audio.AnalyticStreams.AnalyticStreamFrequencyShifter, BGC.Audio.AnalyticStreams.AnalyticStreamWindower, BGC.Audio.AnalyticStreams.AnalyticStreamFork, BGC.Audio.AnalyticStreams.AnalyticFrequencyModulationFilter, BGC.Audio.AnalyticStreams.AnalyticStreamAdder, BGC.Audio.AnalyticStreams.SimpleAnalyticFilter, and BGC.Audio.AnalyticStreams.AnalyticFilter.
Referenced by BGC.Audio.AnalyticStreams.AnalyticStreamExtensions.CalculateRMS().
Seek()
void BGC.Audio.AnalyticStreams.IAnalyticStream.Seek (int position)
Seek to the indicated position in the stream
Implemented in BGC.Audio.AnalyticStreams.AnalyticStreamFork.InternalStreamFork, BGC.Audio.AnalyticStreams.AnalyticADSREnvelope, BGC.Audio.AnalyticStreams.AnalyticNoiseStream, BGC.Audio.AnalyticStreams.AnalyticStreamConverter, BGC.Audio.AnalyticStreams.AnalyticStreamAdder, BGC.Audio.AnalyticStreams.AnalyticStreamCenterer, BGC.Audio.AnalyticStreams.AnalyticWave, BGC.Audio.AnalyticStreams.AnalyticStreamFrequencyShifter, BGC.Audio.AnalyticStreams.AnalyticStreamWindower, BGC.Audio.AnalyticStreams.AnalyticStreamFork, BGC.Audio.AnalyticStreams.AnalyticFrequencyModulationFilter, BGC.Audio.AnalyticStreams.SimpleAnalyticFilter, and BGC.Audio.AnalyticStreams.AnalyticFilter.
Referenced by BGC.Audio.AnalyticStreams.SimpleAnalyticFilter.SimpleAnalyticFilter().
Property Documentation
Samples
int BGC.Audio.AnalyticStreams.IAnalyticStream.Samples get
The total number of Samples of this AnalyticStream
Definition at line 12 of file IAnalyticStream.cs.
Referenced by BGC.Audio.AnalyticStreams.AnalyticStreamExtensions.ADSR(), BGC.Audio.AnalyticStreams.AnalyticStreamCenterer.AnalyticStreamCenterer(), BGC.Audio.AnalyticStreams.AnalyticStreamWindower.AnalyticStreamWindower(), and BGC.Audio.AnalyticStreams.AnalyticStreamExtensions.CalculateRMS().
SamplingRate
double BGC.Audio.AnalyticStreams.IAnalyticStream.SamplingRate get
The sampling rate of the Stream
Definition at line 17 of file IAnalyticStream.cs.
Referenced by BGC.Audio.AnalyticStreams.AnalyticStreamExtensions.ADSR().
The documentation for this interface was generated from the following file:
Audio/AnalyticStreams/IAnalyticStream.cs