BGC Tools: BGC.Audio.IBGCStream Interface Reference
BGC.Audio.IBGCStream Interface Reference
Public Member Functions
void Initialize ()
Perform any calculations necessary to prepare the Stream
int Read (float[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
void Reset ()
Sets this internal state of this stream to the initial state
void Seek (int position)
Seek to the indicated position in the stream
IEnumerable< double > GetChannelRMS ()
The RMS amplitude of each channel
Properties
int Channels [get]
The number of underlying Channels of this BGCStream
int TotalSamples [get]
The total number of Samples of this BGCStream
int ChannelSamples [get]
The number of Samples of each channel for this BGCStream
float SamplingRate [get]
The sampling rate of the Stream
Detailed Description
Definition at line 6 of file IBGCStream.cs.
Member Function Documentation
GetChannelRMS()
IEnumerable<double> BGC.Audio.IBGCStream.GetChannelRMS ()
The RMS amplitude of each channel
Implemented in BGC.Audio.Filters.StreamChannelSplitter.InternalStreamSplit, BGC.Audio.Filters.StreamFork.InternalStreamFork, BGC.Audio.Filters.FramedPhaseReencoder, BGC.Audio.Filters.MultiConvolutionFilter, BGC.Audio.Filters.PhaseVocoder, BGC.Audio.Synthesis.ADSREnvelope, BGC.Audio.Filters.ConvolutionFilter, BGC.Audio.Filters.StreamWindower, BGC.Audio.Filters.SinglePassPhaseReencoder, BGC.Audio.Synthesis.FrequencyDomainToneComposer, BGC.Audio.Synthesis.STMAudioClip, BGC.Audio.Synthesis.SquareWave, BGC.Audio.Synthesis.ActiveNoteStream, BGC.Audio.Filters.StreamConcatenator, BGC.Audio.Filters.StreamChannelSplitter, BGC.Audio.Filters.NormalizerFilter, BGC.Audio.CrossFadingRefClip, BGC.Audio.Filters.StreamTruncator, BGC.Audio.Filters.StreamMergeFilter, BGC.Audio.Filters.AllPassFilter, BGC.Audio.Filters.FrequencyModulationFilter, BGC.Audio.Synthesis.TriangleWave, BGC.Audio.Filters.StreamFork, BGC.Audio.Filters.StreamAdder, BGC.Audio.Synthesis.SweepAudioClip, BGC.Audio.Synthesis.SineWave, BGC.Audio.Filters.CarlileShuffler, BGC.Audio.Filters.NormalizerMonoFilter, BGC.Audio.Synthesis.NoiseAudioClip, BGC.Audio.Filters.StreamCacher, BGC.Audio.Filters.StreamCenterer, BGC.Audio.Filters.StreamTimeShiftFilter, BGC.Audio.Filters.StreamEnveloper, BGC.Audio.Synthesis.WhiteNoiseStream, BGC.Audio.NormalizedMonoClip, BGC.Audio.Filters.StreamSelectiveUpChanneler, BGC.Audio.Synthesis.SawtoothWave, BGC.Audio.Filters.UpChannelMonoFilter, BGC.Audio.Synthesis.ContinuousWhiteNoiseStream, BGC.Audio.Filters.ChannelIsolaterFilter, BGC.Audio.Filters.SlowRangeFitterFilter, BGC.Audio.Filters.StreamRepeater, BGC.Audio.InterlacingAudioClip, BGC.Audio.Filters.StreamRMSStandardizer, BGC.Audio.SimpleAudioClip, BGC.Audio.Filters.ContinuousFilter, BGC.Audio.Midi.MidiFileStream, BGC.Audio.Filters.ParallelInitializer, BGC.Audio.Synthesis.SilenceStream, BGC.Audio.Synthesis.PerpetualSilence, BGC.Audio.Filters.BiQuadFilter, BGC.Audio.AnalyticStreams.AnalyticStreamEnvelopeConverter, BGC.Audio.Filters.BGCFilter, BGC.Audio.AnalyticStreams.BGCStreamConverter, BGC.Audio.BGCStream, and BGC.Audio.SynthStream.
Referenced by BGC.Audio.Filters.StreamRMSStandardizer._Initialize(), BGC.Audio.Filters.NormalizerMonoFilter.GetChannelRMS(), BGC.Audio.Filters.NormalizerFilter.GetChannelRMS(), BGC.Audio.Filters.StreamConcatenator.GetChannelRMS(), BGC.Audio.Normalization.GetRMSScalingFactors(), and BGC.Audio.Filters.FramedPhaseReencoder.Seek().
Initialize()
void BGC.Audio.IBGCStream.Initialize ()
Perform any calculations necessary to prepare the Stream
Implemented in BGC.Audio.Filters.ParallelInitializer, BGC.Audio.AnalyticStreams.AnalyticStreamEnvelopeConverter, BGC.Audio.AnalyticStreams.BGCStreamConverter, BGC.Audio.Filters.BGCFilter, BGC.Audio.Filters.SimpleBGCFilter, BGC.Audio.SynthStream, and BGC.Audio.BGCStream.
Referenced by BGC.Audio.AnalyticStreams.AnalyticStreamEnvelopeConverter.AnalyticStreamEnvelopeConverter(), BGC.Audio.AnalyticStreams.BGCStreamConverter.BGCStreamConverter(), and BGC.Audio.Filters.BGCFilter.Initialize().
Read()
int BGC.Audio.IBGCStream.Read (float [] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
Returns
The number of samples copied
Implemented in BGC.Audio.Filters.StreamChannelSplitter.InternalStreamSplit, BGC.Audio.Filters.StreamFork.InternalStreamFork, BGC.Audio.Filters.BiQuadFilter, BGC.Audio.Filters.SinglePassPhaseReencoder, BGC.Audio.Filters.MultiConvolutionFilter, BGC.Audio.Filters.FramedPhaseReencoder, BGC.Audio.Synthesis.ADSREnvelope, BGC.Audio.Filters.StreamWindower, BGC.Audio.Synthesis.STMAudioClip, BGC.Audio.Filters.ConvolutionFilter, BGC.Audio.Filters.NormalizerFilter, BGC.Audio.Filters.StreamTruncator, BGC.Audio.Filters.PhaseVocoder, BGC.Audio.Synthesis.SweepAudioClip, BGC.Audio.Synthesis.SquareWave, BGC.Audio.Filters.ContinuousFilter, BGC.Audio.Filters.CarlileShuffler, BGC.Audio.Synthesis.FrequencyDomainToneComposer, BGC.Audio.Synthesis.NoiseAudioClip, BGC.Audio.Filters.FrequencyModulationFilter, BGC.Audio.Filters.NormalizerMonoFilter, BGC.Audio.Synthesis.ActiveNoteStream, BGC.Audio.Synthesis.TriangleWave, BGC.Audio.CrossFadingRefClip, BGC.Audio.Synthesis.SineWave, BGC.Audio.Filters.StreamAdder, BGC.Audio.Filters.StreamConcatenator, BGC.Audio.Filters.StreamTimeShiftFilter, BGC.Audio.Synthesis.WhiteNoiseStream, BGC.Audio.NormalizedMonoClip, BGC.Audio.Midi.MidiFileStream, BGC.Audio.Filters.StreamMergeFilter, BGC.Audio.Filters.StreamEnveloper, BGC.Audio.Filters.AllPassFilter, BGC.Audio.Filters.StreamCenterer, BGC.Audio.Filters.SlowRangeFitterFilter, BGC.Audio.Synthesis.ContinuousWhiteNoiseStream, BGC.Audio.Filters.StreamChannelSplitter, BGC.Audio.Filters.StreamFork, BGC.Audio.Filters.StreamRMSStandardizer, BGC.Audio.Filters.UpChannelMonoFilter, BGC.Audio.InterlacingAudioClip, BGC.Audio.Filters.ChannelIsolaterFilter, BGC.Audio.SimpleAudioClip, BGC.Audio.AnalyticStreams.AnalyticStreamEnvelopeConverter, BGC.Audio.Filters.ParallelInitializer, BGC.Audio.Synthesis.SawtoothWave, BGC.Audio.Filters.StreamRepeater, BGC.Audio.Filters.StreamSelectiveUpChanneler, BGC.Audio.AnalyticStreams.BGCStreamConverter, BGC.Audio.Filters.StreamCacher, BGC.Audio.BGCStream, BGC.Audio.Synthesis.SilenceStream, BGC.Audio.Synthesis.PerpetualSilence, BGC.Audio.Filters.BGCFilter, and BGC.Audio.SynthStream.
Referenced by BGC.Audio.BGCStreamExtensions.Cache(), BGC.Audio.BGCStreamExtensions.CalculateRMS(), BGC.Audio.BGCStreamExtensions.ComplexSamples(), BGC.Audio.BGCClipPlayer.OnAudioFilterRead(), BGC.Audio.Filters.StreamRMSStandardizer.Read(), BGC.Audio.Filters.StreamConcatenator.Read(), BGC.Audio.Filters.StreamAdder.Read(), BGC.Audio.Synthesis.ActiveNoteStream.Read(), BGC.Audio.Filters.NormalizerMonoFilter.Read(), BGC.Audio.Filters.NormalizerFilter.Read(), BGC.Audio.Filters.FramedPhaseReencoder.Read(), BGC.Audio.BGCStreamExtensions.SafeCache(), and BGC.Audio.WaveEncoding.StreamWriter().
Reset()
void BGC.Audio.IBGCStream.Reset ()
Sets this internal state of this stream to the initial state
Implemented in BGC.Audio.Filters.StreamChannelSplitter.InternalStreamSplit, BGC.Audio.Filters.StreamFork.InternalStreamFork, BGC.Audio.Filters.FramedPhaseReencoder, BGC.Audio.Filters.MultiConvolutionFilter, BGC.Audio.Filters.PhaseVocoder, BGC.Audio.Filters.ConvolutionFilter, BGC.Audio.Filters.SinglePassPhaseReencoder, BGC.Audio.Synthesis.ADSREnvelope, BGC.Audio.Filters.ContinuousFilter, BGC.Audio.Synthesis.FrequencyDomainToneComposer, BGC.Audio.Synthesis.STMAudioClip, BGC.Audio.Synthesis.SquareWave, BGC.Audio.Filters.StreamWindower, BGC.Audio.Filters.AllPassFilter, BGC.Audio.Filters.FrequencyModulationFilter, BGC.Audio.Synthesis.SweepAudioClip, BGC.Audio.Synthesis.TriangleWave, BGC.Audio.Filters.CarlileShuffler, BGC.Audio.Synthesis.NoiseAudioClip, BGC.Audio.Filters.StreamTruncator, BGC.Audio.Filters.StreamCenterer, BGC.Audio.Synthesis.SineWave, BGC.Audio.Midi.MidiFileStream, BGC.Audio.Filters.StreamMergeFilter, BGC.Audio.Synthesis.WhiteNoiseStream, BGC.Audio.NormalizedMonoClip, BGC.Audio.Filters.StreamCacher, BGC.Audio.Synthesis.ActiveNoteStream, BGC.Audio.Filters.StreamChannelSplitter, BGC.Audio.Filters.StreamFork, BGC.Audio.Synthesis.ContinuousWhiteNoiseStream, BGC.Audio.CrossFadingRefClip, BGC.Audio.Synthesis.SawtoothWave, BGC.Audio.Filters.StreamAdder, BGC.Audio.AnalyticStreams.AnalyticStreamEnvelopeConverter, BGC.Audio.AnalyticStreams.BGCStreamConverter, BGC.Audio.InterlacingAudioClip, BGC.Audio.Filters.StreamConcatenator, BGC.Audio.SimpleAudioClip, BGC.Audio.Filters.StreamEnveloper, BGC.Audio.Filters.StreamTimeShiftFilter, BGC.Audio.Synthesis.SilenceStream, BGC.Audio.Filters.ParallelInitializer, BGC.Audio.BGCStream, BGC.Audio.Synthesis.PerpetualSilence, BGC.Audio.Filters.SimpleBGCFilter, BGC.Audio.Filters.StreamRepeater, BGC.Audio.Filters.BGCFilter, and BGC.Audio.SynthStream.
Referenced by BGC.Audio.BGCStreamExtensions.Cache(), BGC.Audio.BGCStreamExtensions.CalculateRMS(), BGC.Audio.BGCStreamExtensions.ComplexSamples(), BGC.Audio.BGCClipPlayer.Play(), BGC.Audio.Synthesis.ActiveNoteStream.Reset(), BGC.Audio.Filters.FramedPhaseReencoder.Reset(), BGC.Audio.BGCStreamExtensions.SafeCache(), BGC.Audio.Filters.StreamConcatenator.Seek(), and BGC.Audio.WaveEncoding.StreamWriter().
Seek()
void BGC.Audio.IBGCStream.Seek (int position)
Seek to the indicated position in the stream
Implemented in BGC.Audio.Filters.StreamChannelSplitter.InternalStreamSplit, BGC.Audio.Filters.StreamFork.InternalStreamFork, BGC.Audio.Filters.FramedPhaseReencoder, BGC.Audio.Filters.MultiConvolutionFilter, BGC.Audio.Filters.PhaseVocoder, BGC.Audio.Filters.ConvolutionFilter, BGC.Audio.Filters.SinglePassPhaseReencoder, BGC.Audio.Synthesis.ADSREnvelope, BGC.Audio.Filters.ContinuousFilter, BGC.Audio.Synthesis.FrequencyDomainToneComposer, BGC.Audio.Synthesis.STMAudioClip, BGC.Audio.Synthesis.ActiveNoteStream, BGC.Audio.Filters.StreamWindower, BGC.Audio.CrossFadingRefClip, BGC.Audio.Synthesis.SquareWave, BGC.Audio.Filters.FrequencyModulationFilter, BGC.Audio.Synthesis.SweepAudioClip, BGC.Audio.Synthesis.TriangleWave, BGC.Audio.Filters.CarlileShuffler, BGC.Audio.Synthesis.NoiseAudioClip, BGC.Audio.Filters.StreamTruncator, BGC.Audio.Filters.StreamCenterer, BGC.Audio.Synthesis.SineWave, BGC.Audio.Filters.StreamAdder, BGC.Audio.Filters.StreamConcatenator, BGC.Audio.Midi.MidiFileStream, BGC.Audio.Filters.AllPassFilter, BGC.Audio.Filters.StreamMergeFilter, BGC.Audio.Synthesis.WhiteNoiseStream, BGC.Audio.Filters.StreamCacher, BGC.Audio.NormalizedMonoClip, BGC.Audio.Filters.StreamChannelSplitter, BGC.Audio.Filters.StreamFork, BGC.Audio.Synthesis.SawtoothWave, BGC.Audio.Synthesis.ContinuousWhiteNoiseStream, BGC.Audio.AnalyticStreams.AnalyticStreamEnvelopeConverter, BGC.Audio.AnalyticStreams.BGCStreamConverter, BGC.Audio.InterlacingAudioClip, BGC.Audio.SimpleAudioClip, BGC.Audio.Filters.StreamTimeShiftFilter, BGC.Audio.Filters.StreamEnveloper, BGC.Audio.Synthesis.SilenceStream, BGC.Audio.BGCStream, BGC.Audio.Filters.ParallelInitializer, BGC.Audio.Synthesis.PerpetualSilence, BGC.Audio.Filters.StreamRepeater, BGC.Audio.Filters.SimpleBGCFilter, BGC.Audio.Filters.BGCFilter, and BGC.Audio.SynthStream.
Referenced by BGC.Audio.Filters.ParallelInitializer.ParallelInitializer(), BGC.Audio.Filters.StreamConcatenator.Seek(), BGC.Audio.Synthesis.ActiveNoteStream.Seek(), BGC.Audio.Filters.FramedPhaseReencoder.Seek(), and BGC.Audio.Filters.SimpleBGCFilter.SimpleBGCFilter().
Property Documentation
Channels
int BGC.Audio.IBGCStream.Channels get
The number of underlying Channels of this BGCStream
Definition at line 11 of file IBGCStream.cs.
Referenced by BGC.Audio.Synthesis.ADSREnvelope.ADSREnvelope(), BGC.Audio.Filters.AllPassFilter.AllPassFilter(), BGC.Audio.Filters.BiQuadFilter.BiQuadFilter(), BGC.Audio.BGCStreamExtensions.Cache(), BGC.Audio.BGCStreamExtensions.CalculateRMS(), BGC.Audio.Filters.ChannelIsolaterFilter.ChannelIsolaterFilter(), BGC.Audio.BGCStreamExtensions.ComplexSamples(), BGC.Audio.Filters.ContinuousFilter.ContinuousFilter(), BGC.Audio.Filters.ConvolutionFilter.ConvolutionFilter(), BGC.Audio.Visualization.Spectrogram.Decompose(), BGC.Audio.Filters.FramedPhaseReencoder.FramedPhaseReencoder(), BGC.Audio.Filters.MultiConvolutionFilter.MultiConvolutionFilter(), BGC.Audio.BGCStreamExtensions.Normalize(), BGC.Audio.Filters.NormalizerFilter.NormalizerFilter(), BGC.Audio.Filters.NormalizerMonoFilter.NormalizerMonoFilter(), BGC.Audio.BGCClipPlayer.OnAudioFilterRead(), BGC.Audio.BGCStreamExtensions.SafeCache(), BGC.Audio.WaveEncoding.SaveStream(), BGC.Audio.Filters.SinglePassPhaseReencoder.SinglePassPhaseReencoder(), BGC.Audio.Filters.FramedPhaseReencoder.StereoifyStream(), BGC.Audio.Filters.StreamChannelSplitter.StreamChannelSplitter(), BGC.Audio.Filters.StreamRMSStandardizer.StreamRMSStandardizer(), BGC.Audio.Filters.StreamSelectiveUpChanneler.StreamSelectiveUpChanneler(), and BGC.Audio.Filters.UpChannelMonoFilter.UpChannelMonoFilter().
ChannelSamples
int BGC.Audio.IBGCStream.ChannelSamples get
The number of Samples of each channel for this BGCStream
Definition at line 21 of file IBGCStream.cs.
Referenced by BGC.Audio.BGCStreamExtensions.CalculateRMS(), BGC.Audio.BGCStreamExtensions.ComplexSamples(), BGC.Audio.Filters.ConvolutionFilter.ConvolutionFilter(), BGC.Audio.Filters.FramedPhaseReencoder.FramedPhaseReencoder(), BGC.Audio.Filters.StreamConcatenator.GetChannelRMS(), BGC.Audio.Filters.MultiConvolutionFilter.MultiConvolutionFilter(), BGC.Audio.Filters.PhaseVocoder.PhaseVocoder(), BGC.Audio.Filters.StreamConcatenator.Seek(), BGC.Audio.Filters.SinglePassPhaseReencoder.SinglePassPhaseReencoder(), BGC.Audio.Filters.StreamCenterer.StreamCenterer(), BGC.Audio.Filters.StreamEnveloper.StreamEnveloper(), BGC.Audio.Filters.StreamTimeShiftFilter.StreamTimeShiftFilter(), BGC.Audio.Filters.StreamTruncator.StreamTruncator(), and BGC.Audio.Filters.StreamWindower.StreamWindower().
SamplingRate
float BGC.Audio.IBGCStream.SamplingRate get
The sampling rate of the Stream
Definition at line 26 of file IBGCStream.cs.
Referenced by BGC.Audio.Filters.BiQuadFilter.BandpassFilter(), BGC.Audio.BGCStreamExtensions.CalculateRMS(), BGC.Audio.Filters.ContinuousFilter.ContinuousFilter(), BGC.Audio.Filters.BiQuadFilter.HighpassFilter(), BGC.Audio.Filters.BiQuadFilter.HighShelfFilter(), BGC.Audio.Filters.BiQuadFilter.LowpassFilter(), BGC.Audio.Filters.BiQuadFilter.LowShelfFilter(), and BGC.Audio.Filters.BiQuadFilter.NotchFilter().
TotalSamples
int BGC.Audio.IBGCStream.TotalSamples get
The total number of Samples of this BGCStream
Definition at line 16 of file IBGCStream.cs.
Referenced by BGC.Audio.BGCStreamExtensions.Cache(), BGC.Audio.Filters.StreamCacher.StreamCacher(), and BGC.Audio.WaveEncoding.StreamWriter().
The documentation for this interface was generated from the following file:
Audio/IBGCStream.cs