BGC Tools: BGC.StateMachine.IStateTrigger< TTriggerEnum > Interface Template Reference
BGC.StateMachine.IStateTrigger< TTriggerEnum > Interface Template Reference
Public Member Functions
void ActivateTrigger (TTriggerEnum key)
bool GetTrigger (TTriggerEnum key)
Detailed Description
Type Constraints
TTriggerEnum : Enum
Definition at line 5 of file IStateTrigger.cs.
Member Function Documentation
ActivateTrigger()
void BGC.StateMachine.IStateTrigger< TTriggerEnum >.ActivateTrigger (TTriggerEnum key)
Implemented in BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >.
Referenced by BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >.ExecuteTransitions(), BGC.StateMachine.TriggeringState< TTriggerEnum >.SetStateMachineFunctions(), and BGC.StateMachine.CoordinatingState< TBoolEnum, TTriggerEnum >.SetStateMachineFunctions().
GetTrigger()
bool BGC.StateMachine.IStateTrigger< TTriggerEnum >.GetTrigger (TTriggerEnum key)
Implemented in BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >, and BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >.
Referenced by BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >.ExecuteTransitions().
The documentation for this interface was generated from the following file:
StateMachine/IStateTrigger.cs