BGC Tools: BGC.StateMachine.IStateDataBool< TBoolEnum > Interface Template Reference
BGC.StateMachine.IStateDataBool< TBoolEnum > Interface Template Reference
Public Member Functions
bool GetBool (TBoolEnum key)
void SetBool (TBoolEnum key, bool value)
Detailed Description
Type Constraints
TBoolEnum : Enum
Definition at line 5 of file IStateBool.cs.
Member Function Documentation
GetBool()
bool BGC.StateMachine.IStateDataBool< TBoolEnum >.GetBool (TBoolEnum key)
Implemented in BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >, and BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >.
Referenced by BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >.ExecuteTransitions(), and BGC.StateMachine.CoordinatingState< TBoolEnum, TTriggerEnum >.SetStateMachineFunctions().
SetBool()
void BGC.StateMachine.IStateDataBool< TBoolEnum >.SetBool (TBoolEnum key, bool value)
Implemented in BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >.
Referenced by BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >.ExecuteTransitions(), and BGC.StateMachine.CoordinatingState< TBoolEnum, TTriggerEnum >.SetStateMachineFunctions().
The documentation for this interface was generated from the following file:
StateMachine/IStateBool.cs