BGC Tools: BGC.StateMachine.ITransitionDataRetriever< TBoolEnum, TTriggerEnum > Interface Template Reference
BGC.StateMachine.ITransitionDataRetriever< TBoolEnum, TTriggerEnum > Interface Template Reference
Public Member Functions
bool GetBool (TBoolEnum key)
bool GetTrigger (TTriggerEnum key)
void ConsumeTrigger (TTriggerEnum key)
Detailed Description
Type Constraints
TBoolEnum : Enum
TTriggerEnum : Enum
Definition at line 5 of file ITransitionDataRetriever.cs.
Member Function Documentation
ConsumeTrigger()
void BGC.StateMachine.ITransitionDataRetriever< TBoolEnum, TTriggerEnum >.ConsumeTrigger (TTriggerEnum key)
Implemented in BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >.
Referenced by BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >.ExecuteTransitions().
GetBool()
bool BGC.StateMachine.ITransitionDataRetriever< TBoolEnum, TTriggerEnum >.GetBool (TBoolEnum key)
Implemented in BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >, and BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >.
Referenced by BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >.ExecuteTransitions().
GetTrigger()
bool BGC.StateMachine.ITransitionDataRetriever< TBoolEnum, TTriggerEnum >.GetTrigger (TTriggerEnum key)
Implemented in BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >, and BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >.
Referenced by BGC.StateMachine.StateMachine< TBoolEnum, TTriggerEnum >.ExecuteTransitions().
The documentation for this interface was generated from the following file:
StateMachine/ITransitionDataRetriever.cs