BGC Tools: BGC.Audio.Envelopes.IBGCEnvelopeStream Interface Reference
BGC.Audio.Envelopes.IBGCEnvelopeStream Interface Reference
Public Member Functions
void Initialize ()
Perform any calculations necessary to prepare the Stream
int Read (float[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
bool HasMoreSamples ()
Returns if the BGCEnvelopeStream has more samples
float ReadNextSample ()
Returns the next sample in the BGCEnvelopeStream
void Reset ()
Sets this internal state of this stream to the initial state
void Seek (int position)
Seek to the indicated position in the stream
Properties
int Samples [get]
The total number of Samples of this BGCEnvelopeStream
float SamplingRate [get]
The sampling rate of the BGCEnvelopeStream
Detailed Description
Definition at line 6 of file IBGCEnvelopeStream.cs.
Member Function Documentation
bool BGC.Audio.Envelopes.IBGCEnvelopeStream.HasMoreSamples ()
Returns if the BGCEnvelopeStream has more samples
Implemented in BGC.Audio.Envelopes.GaussianEnvelope, BGC.Audio.Synthesis.SineWave, BGC.Audio.Synthesis.SquareWave, BGC.Audio.Synthesis.TriangleWave, BGC.Audio.Envelopes.LinearEnvelope, BGC.Audio.Envelopes.CosineEnvelope, BGC.Audio.Synthesis.SawtoothWave, BGC.Audio.Envelopes.ConstantEnvelope, BGC.Audio.Envelopes.EnvelopeConcatenator, BGC.Audio.Envelopes.SigmoidEnvelope, BGC.Audio.Synthesis.PerpetualSilence, BGC.Audio.Envelopes.BGCEnvelopeStream, and BGC.Audio.Envelopes.BGCEnvelopeFilter.
Referenced by BGC.Audio.Envelopes.EnvelopeConcatenator.ReadNextSample().
void BGC.Audio.Envelopes.IBGCEnvelopeStream.Initialize ()
Perform any calculations necessary to prepare the Stream
Implemented in BGC.Audio.Envelopes.BGCEnvelopeFilter, and BGC.Audio.Envelopes.BGCEnvelopeStream.
Referenced by BGC.Audio.Envelopes.BGCEnvelopeFilter.Initialize().
int BGC.Audio.Envelopes.IBGCEnvelopeStream.Read (float[] data, int offset, int count)
Copy count samples into the Data buffer, starting at offset.
Returns
The number of samples copied
Implemented in BGC.Audio.Envelopes.EnvelopeConcatenator, BGC.Audio.Envelopes.GaussianEnvelope, BGC.Audio.Envelopes.CosineEnvelope, BGC.Audio.Synthesis.SineWave, BGC.Audio.Synthesis.SquareWave, BGC.Audio.Envelopes.ConstantEnvelope, BGC.Audio.Synthesis.TriangleWave, BGC.Audio.Synthesis.SawtoothWave, BGC.Audio.Envelopes.LinearEnvelope, BGC.Audio.Envelopes.BGCEnvelopeStream, BGC.Audio.Envelopes.SigmoidEnvelope, BGC.Audio.Synthesis.PerpetualSilence, and BGC.Audio.Envelopes.BGCEnvelopeFilter.
Referenced by BGC.Audio.Envelopes.EnvelopeConcatenator.Read().
float BGC.Audio.Envelopes.IBGCEnvelopeStream.ReadNextSample ()
Returns the next sample in the BGCEnvelopeStream
Returns
The next sample
Implemented in BGC.Audio.Envelopes.GaussianEnvelope, BGC.Audio.Synthesis.SineWave, BGC.Audio.Synthesis.SquareWave, BGC.Audio.Synthesis.TriangleWave, BGC.Audio.Envelopes.LinearEnvelope, BGC.Audio.Envelopes.CosineEnvelope, BGC.Audio.Synthesis.SawtoothWave, BGC.Audio.Envelopes.ConstantEnvelope, BGC.Audio.Envelopes.EnvelopeConcatenator, BGC.Audio.Envelopes.SigmoidEnvelope, BGC.Audio.Synthesis.PerpetualSilence, BGC.Audio.Envelopes.BGCEnvelopeStream, and BGC.Audio.Envelopes.BGCEnvelopeFilter.
Referenced by BGC.Audio.Visualization.Spectrogram.Decompose(), and BGC.Audio.Envelopes.EnvelopeConcatenator.ReadNextSample().
void BGC.Audio.Envelopes.IBGCEnvelopeStream.Reset ()
Sets this internal state of this stream to the initial state
Implemented in BGC.Audio.Envelopes.GaussianEnvelope, BGC.Audio.Synthesis.SquareWave, BGC.Audio.Synthesis.SineWave, BGC.Audio.Envelopes.LinearEnvelope, BGC.Audio.Synthesis.TriangleWave, BGC.Audio.Envelopes.CosineEnvelope, BGC.Audio.Synthesis.SawtoothWave, BGC.Audio.Envelopes.ConstantEnvelope, BGC.Audio.Envelopes.EnvelopeConcatenator, BGC.Audio.Envelopes.SigmoidEnvelope, BGC.Audio.Synthesis.PerpetualSilence, BGC.Audio.Envelopes.BGCEnvelopeStream, and BGC.Audio.Envelopes.BGCEnvelopeFilter.
Referenced by BGC.Audio.Visualization.Spectrogram.Decompose(), BGC.Audio.Envelopes.EnvelopeConcatenator.ReadNextSample(), and BGC.Audio.Envelopes.EnvelopeConcatenator.Seek().
void BGC.Audio.Envelopes.IBGCEnvelopeStream.Seek (int position)
Seek to the indicated position in the stream
Implemented in BGC.Audio.Envelopes.GaussianEnvelope, BGC.Audio.Envelopes.EnvelopeConcatenator, BGC.Audio.Synthesis.SineWave, BGC.Audio.Synthesis.SquareWave, BGC.Audio.Synthesis.TriangleWave, BGC.Audio.Envelopes.LinearEnvelope, BGC.Audio.Envelopes.CosineEnvelope, BGC.Audio.Synthesis.SawtoothWave, BGC.Audio.Envelopes.ConstantEnvelope, BGC.Audio.Envelopes.SigmoidEnvelope, BGC.Audio.Envelopes.BGCEnvelopeStream, BGC.Audio.Synthesis.PerpetualSilence, and BGC.Audio.Envelopes.BGCEnvelopeFilter.
Referenced by BGC.Audio.Envelopes.EnvelopeConcatenator.Seek().
Property Documentation
int BGC.Audio.Envelopes.IBGCEnvelopeStream.Samples get
The total number of Samples of this BGCEnvelopeStream
Definition at line 11 of file IBGCEnvelopeStream.cs.
Referenced by BGC.Audio.Envelopes.EnvelopeConcatenator.Seek(), and BGC.Audio.Filters.StreamEnveloper.StreamEnveloper().
float BGC.Audio.Envelopes.IBGCEnvelopeStream.SamplingRate get
The sampling rate of the BGCEnvelopeStream
Definition at line 16 of file IBGCEnvelopeStream.cs.
The documentation for this interface was generated from the following file:
Audio/Envelopes/IBGCEnvelopeStream.cs