BGC Tools: BGC.Mathematics.Complex32 Struct Reference
BGC.Mathematics.Complex32 Struct Reference
Represents a complex number with single-precision floating point components
Public Member Functions
Complex32 (float real, float imaginary)
Initializes a new Complex32 structure using the specified real and imaginary values.
Complex32 Square ()
The Square (power 2) of this Complex32
Complex32 Rotation (float phase)
Retuns the Complex32 number, rotated by phase radians, or exp(i*phase)
float RealRotation (float phase)
Retuns the real value of the Complex32 number after rotation by phase radians, or exp(i*phase)
bool Equals (in Complex32 value)
Returns a value that indicates whether the current instance and a specified complex number have the same value.
bool IEquatable< Complex32 >. Equals (Complex32 other)
Returns a value that indicates whether the current instance and a specified complex number have the same value.
override bool Equals (object obj)
Returns a value that indicates whether the current instance and a specified object have the same value.
override int GetHashCode ()
Returns the hash code for the current Complex32 object.
string ToString (string format)
Converts the value of the current complex number to its equivalent string representation in Cartesian form by using the specified format for its real and imaginary parts.
string ToString (IFormatProvider provider)
Converts the value of the current complex number to its equivalent string representation in Cartesian form by using the specified culture-specific formatting information.
string ToString (string format, IFormatProvider provider)
Converts the value of the current complex number to its equivalent string representation in Cartesian form by using the specified format and culture-specific format information for its real and imaginary parts.
override string ToString ()
Converts the value of the current complex number to its equivalent string representation in Cartesian form.
bool IsReal ()
Gets a value indicating whether the provided Complex32 is real.
bool IsRealNonNegative ()
Gets a value indicating whether the provided Complex32 is real and not negative, that is >= 0.
bool IsZero ()
Gets a value indicating whether the Complex32 is zero.
bool IsOne ()
Gets a value indicating whether the Complex32 is one.
bool IsImaginaryOne ()
Gets a value indicating whether the Complex32 is the imaginary unit.
bool IsInfinity ()
Gets a value indicating whether the provided Complex32 evaluates to an infinite value.
bool IsNaN ()
Gets a value indicating whether the provided Complex32evaluates to a value that is not a number.
Complex32 Power (in Complex32 exponent)
Raise this Complex32 to the given value.
Complex32 NaturalLogarithm ()
Natural Logarithm of this Complex32 (Base E).
Complex32 CommonLogarithm ()
Common Logarithm of this Complex32 (Base 10).
Complex32 Logarithm (float baseValue)
Logarithm of this Complex32 with custom base.
Complex32 Exponential ()
Exponential of this Complex32 (exp(x), E^x).
float RealProduct (in Complex32 other)
Returns the real component of the product of this Complex32 with other.
Complex32 Conjugate ()
Computes the conjugate of a complex number and returns the result.
Complex32 Reciprocal ()
Returns the multiplicative inverse of a complex number.
Complex32 SquareRoot ()
The Square Root (power 1/2) of this Complex32
Static Public Member Functions
static float Abs (in Complex32 value)
Gets the absolute value (or magnitude) of a complex number.
static Complex32 Acos (in Complex32 value)
Trigonometric principal Arc Cosine of this Complex32 number.
static Complex32 Add (in Complex32 left, in Complex32 right)
Returns the sum of the two Complex32 inputs
static Complex32 Asin (in Complex32 value)
Trigonometric principal Arc Sine of this Complex32 number.
static Complex32 Atan (in Complex32 value)
Trigonometric principal Arc Tangent of this Complex32 number.
static Complex32 Conjugate (in Complex32 value)
Computes the conjugate of a complex number and returns the result.
static Complex32 Cos (in Complex32 value)
Trigonometric Cosine of a Complex32 number.
static Complex32 Cosh (in Complex32 value)
Hyperbolic Cosine of a Complex32 number.
static Complex32 Divide (in Complex32 dividend, in Complex32 divisor)
Divides one complex number by another and returns the result.
static Complex32 Exp (in Complex32 value)
Returns e raised to the power specified by a complex number.
static Complex32 FromPolarCoordinates (float magnitude, float phase)
Creates a complex number from a point's polar coordinates.
static Complex32 FromPolarCoordinates (double magnitude, double phase)
Creates a complex number from a point's polar coordinates.
static Complex32 Log (in Complex32 value)
Returns the natural (base e) logarithm of a specified complex number.
static Complex32 Log (in Complex32 value, float baseValue)
Returns the logarithm of a specified complex number in a specified base.
static Complex32 Log10 (in Complex32 value)
Returns the base-10 logarithm of a specified complex number.
static Complex32 Multiply (in Complex32 left, in Complex32 right)
Returns the product of two complex numbers.
static Complex32 Negate (in Complex32 value)
Returns the additive inverse of a specified complex number.
static Complex32 Pow (in Complex32 value, float power)
Returns a specified complex number raised to a power specified by a float-precision floating-point number.
static Complex32 Pow (in Complex32 value, in Complex32 power)
Returns a specified complex number raised to a power specified by a complex number.
static Complex32 Reciprocal (in Complex32 value)
Returns the multiplicative inverse of a complex number.
static Complex32 Sin (in Complex32 value)
Trigonometric Sine of a Complex32 number.
static Complex32 Sinh (in Complex32 value)
Hyperbolic Sine of a Complex32 number.
static Complex32 Sqrt (in Complex32 value)
The Square Root of a complex number
static Complex32 Subtract (in Complex32 left, Complex32 right)
The difference between two Complex32 numbers;
static Complex32 Tan (in Complex32 value)
Trigonometric Tangent of a Complex32 number.
static Complex32 Tanh (in Complex32 value)
Hyperbolic Tangent of a Complex32 number.
static Complex32 operator+ (in Complex32 left, in Complex32 right)
Adds two complex numbers.
static Complex32 operator- (in Complex32 value)
Returns the additive inverse of a specified complex number.
static Complex32 operator- (in Complex32 left, in Complex32 right)
Subtracts a complex number from another complex number.
static Complex32 operator* (in Complex32 left, in Complex32 right)
Multiplies two specified complex numbers.
static Complex32 operator/ (in Complex32 dividend, in Complex32 divisor)
Divides a specified complex number by another specified complex number.
static bool operator== (in Complex32 left, in Complex32 right)
Returns a value that indicates whether two complex numbers are equal.
static bool operator!= (in Complex32 left, in Complex32 right)
Returns a value that indicates whether two complex numbers are not equal.
static implicit operator Complex32 (byte value)
Defines an implicit conversion of an unsigned byte to a complex number.
static implicit operator Complex32 (float value)
Defines an implicit conversion of a single-precision floating-point number to a complex number.
static implicit operator Complex32 (double value)
Defines an implicit conversion of a double-precision floating-point number to a complex number.
static implicit operator Complex32 (sbyte value)
Defines an implicit conversion of a signed byte to a complex number.
static implicit operator Complex32 (ulong value)
Defines an implicit conversion of a 64-bit unsigned integer to a complex number.
static implicit operator Complex32 (uint value)
Defines an implicit conversion of a 32-bit unsigned integer to a complex number.
static implicit operator Complex32 (ushort value)
Defines an implicit conversion of a 16-bit unsigned integer to a complex number.
static implicit operator Complex32 (long value)
Defines an implicit conversion of a 64-bit signed integer to a complex number.
static implicit operator Complex32 (int value)
Defines an implicit conversion of a 32-bit signed integer to a complex number.
static implicit operator Complex32 (short value)
Defines an implicit conversion of a 16-bit signed integer to a complex number.
static operator Complex32 (decimal value)
Defines an explicit conversion of a System.Decimal value to a complex number.
Data Fields
float Imaginary => _imag
Gets the imaginary component of the current System.Numerics.Complex32 object.
float Real => _real
Gets the real component of the current System.Numerics.Complex32 object.
float Phase => _imag == 0f && _real < 0f ? Mathf.PI : Mathf.Atan2(_imag, _real)
Gets the phase of a complex number in radians.
float MagnitudeSquared => (_real * _real) + (_imag * _imag)
Gets the squared magnitude (or squared absolute value) of a complex number.
Static Public Attributes
static readonly Complex32 Zero = new Complex32(0f, 0f)
Returns a new Complex32 instance with a real number equal to zero and an imaginary number equal to zero.
static readonly Complex32 One = new Complex32(1f, 0f)
Returns a new Complex32 instance with a real number equal to one and an imaginary number equal to zero.
static readonly Complex32 ImaginaryOne = new Complex32(0f, 1f)
Returns a new Complex32 instance with a real number equal to zero and an imaginary number equal to one.
static readonly Complex32 PositiveInfinity = new Complex32(float.PositiveInfinity, float.PositiveInfinity)
Returns a new Complex32 instance with real and imaginary numbers positive infinite.
static readonly Complex32 NaN = new Complex32(float.NaN, float.NaN)
Returns a new Complex32 instance with real and imaginary numbers not a number.
Properties
float Magnitude [get]
Gets the magnitude (or absolute value) of a complex number.
Static Private Member Functions
static Complex32 InternalDiv (float a, float b, float c, float d, bool swapped)
Helper method for dividing.
Private Attributes
readonly float _real
The real component of the complex number.
readonly float _imag
The imaginary component of the complex number.
Detailed Description
Represents a complex number with single-precision floating point components
Definition at line 41 of file Complex32.cs.
Constructor & Destructor Documentation
BGC.Mathematics.Complex32.Complex32 (float real, float imaginary) inline
Initializes a new Complex32 structure using the specified real and imaginary values.
Definition at line 84 of file Complex32.cs.
         {
             _real = real;
             _imag = imaginary;
         }
Member Function Documentation
static float BGC.Mathematics.Complex32.Abs (in Complex32 value) static
Gets the absolute value (or magnitude) of a complex number.
Referenced by BGC.Mathematics.Complex32.SquareRoot().
static Complex32 BGC.Mathematics.Complex32.Acos (in Complex32 value) inline static
Trigonometric principal Arc Cosine of this Complex32 number.
Parameters
value The complex value.
Returns
The arc cosine of a complex number.
Definition at line 155 of file Complex32.cs.
         {
             if (value.Imaginary < 0f || value.Imaginary == 0f && value.Real > 0f)
             {
                 return Mathf.PI - Acos(-value);
             }
             return -ImaginaryOne * (value + (ImaginaryOne * (1f - value.Square()).SquareRoot())).NaturalLogarithm();
         }
static Complex32 BGC.Mathematics.Complex32.Add (in Complex32 left, in Complex32 right) static
Returns the sum of the two Complex32 inputs
static Complex32 BGC.Mathematics.Complex32.Asin (in Complex32 value) inline static
Trigonometric principal Arc Sine of this Complex32 number.
Parameters
value The complex value.
Returns
The arc sine of a complex number.
Definition at line 176 of file Complex32.cs.
         {
             if (value.Imaginary > 0f || value.Imaginary == 0f && value.Real < 0f)
             {
                 return -Asin(-value);
             }
             return -ImaginaryOne * ((1f - value.Square()).SquareRoot() + (ImaginaryOne * value)).NaturalLogarithm();
         }
static Complex32 BGC.Mathematics.Complex32.Atan (in Complex32 value) inline static
Trigonometric principal Arc Tangent of this Complex32 number.
Parameters
value The complex value.
Returns
The arc tangent of a complex number.
Definition at line 192 of file Complex32.cs.
References BGC.Mathematics.Complex32.Conjugate().
         {
             Complex32 iz = new Complex32(-value.Imaginary, value.Real); // I*this
             return new Complex32(0f, 0.5f) * ((1f - iz).NaturalLogarithm() - (1f + iz).NaturalLogarithm());
         }
Complex32 BGC.Mathematics.Complex32.CommonLogarithm () inline
Common Logarithm of this Complex32 (Base 10).
Returns
The common logarithm of this complex number.
Definition at line 771 of file Complex32.cs.
References BGC.Mathematics.Complex32.Log().
Referenced by BGC.Mathematics.Complex32.Cosh().
         {
             if (IsRealNonNegative())
             {
                 return new Complex32(Mathf.Log10(_real), 0f);
             }
             return new Complex32(0.5f * Mathf.Log10(MagnitudeSquared), Phase);
         }
static Complex32 BGC.Mathematics.Complex32.Conjugate (in Complex32 value) static
Computes the conjugate of a complex number and returns the result.
Referenced by BGC.Mathematics.Complex32.Atan(), and BGC.Mathematics.Fourier.BluesteinForward().
Complex32 BGC.Mathematics.Complex32.Conjugate ()
Computes the conjugate of a complex number and returns the result.
static Complex32 BGC.Mathematics.Complex32.Cos (in Complex32 value) inline static
Trigonometric Cosine of a Complex32 number.
Parameters
value The complex value.
Returns
The cosine of a complex number.
Definition at line 209 of file Complex32.cs.
References BGC.Mathematics.GeneralMath.Cosh(), and BGC.Mathematics.GeneralMath.Sinh().
Referenced by BGC.Mathematics.Complex32.Rotation().
         {
             if (value.IsReal())
             {
                 return new Complex32(Mathf.Cos(value.Real), 0f);
             }
             return new Complex32(
                 Mathf.Cos(value.Real) * GeneralMath.Cosh(value.Imaginary),
                 -Mathf.Sin(value.Real) * GeneralMath.Sinh(value.Imaginary));
         }
static Complex32 BGC.Mathematics.Complex32.Cosh (in Complex32 value) inline static
Hyperbolic Cosine of a Complex32 number.
Parameters
value The complex value.
Returns
The hyperbolic cosine of a complex number.
Definition at line 227 of file Complex32.cs.
References BGC.Mathematics.Complex32.CommonLogarithm(), BGC.Mathematics.GeneralMath.Cosh(), BGC.Mathematics.Complex32.Exp(), BGC.Mathematics.Complex32.Exponential(), BGC.Mathematics.Complex32.Logarithm(), BGC.Mathematics.Complex32.NaturalLogarithm(), BGC.Mathematics.Complex32.Power(), BGC.Mathematics.Complex32.Reciprocal(), and BGC.Mathematics.GeneralMath.Sinh().
         {
             if (value.IsReal())
             {
                 return new Complex32(GeneralMath.Cosh(value.Real), 0f);
             }
             // cosh(x + j*y) = cosh(x)*cos(y) + j*sinh(x)*sin(y)
             // if x > huge, cosh(x + j*y) = exp(|x|)/2*cos(y) + j*sign(x)*exp(|x|)/2*sin(y)
             if (Mathf.Abs(value.Real) >= 22f) // Taken from the msun library in FreeBSD
             {
                 float h = Mathf.Exp(Mathf.Abs(value.Real)) * 0.5f;
                 return new Complex32(
                     h * Mathf.Cos(value.Imaginary),
                     Mathf.Sign(value.Real) * h * Mathf.Sin(value.Imaginary));
             }
             return new Complex32(
                 GeneralMath.Cosh(value.Real) * Mathf.Cos(value.Imaginary),
                 GeneralMath.Sinh(value.Real) * Mathf.Sin(value.Imaginary));
         }
static Complex32 BGC.Mathematics.Complex32.Divide (in Complex32 dividend, in Complex32 divisor) static
Divides one complex number by another and returns the result.
bool BGC.Mathematics.Complex32.Equals (in Complex32 value) inline
Returns a value that indicates whether the current instance and a specified complex number have the same value.
Definition at line 477 of file Complex32.cs.
References BGC.Mathematics.GeneralMath.Approximately().
         {
             if (IsNaN() || value.IsNaN())
             {
                 return false;
             }
             if (IsInfinity() && value.IsInfinity())
             {
                 return true;
             }
             return GeneralMath.Approximately(_real, value._real) &&
                 GeneralMath.Approximately(_imag, value._imag);
         }
bool IEquatable<Complex32>. BGC.Mathematics.Complex32.Equals (Complex32 other)
Returns a value that indicates whether the current instance and a specified complex number have the same value.
override bool BGC.Mathematics.Complex32.Equals (object obj)
Returns a value that indicates whether the current instance and a specified object have the same value.
static Complex32 BGC.Mathematics.Complex32.Exp (in Complex32 value) static
Returns e raised to the power specified by a complex number.
Referenced by BGC.Mathematics.Complex32.Cosh(), BGC.Mathematics.Complex32.Exponential(), BGC.Mathematics.Complex32.Sinh(), and BGC.Mathematics.Complex32.Tanh().
Complex32 BGC.Mathematics.Complex32.Exponential () inline
Exponential of this Complex32 (exp(x), E^x).
Returns
The exponential of this complex number.
Definition at line 793 of file Complex32.cs.
References BGC.Mathematics.Complex32._real, and BGC.Mathematics.Complex32.Exp().
Referenced by BGC.Mathematics.Complex32.Cosh().
         {
             float exp = Mathf.Exp(_real);
             if (IsReal())
             {
                 return new Complex32(exp, 0f);
             }
             return new Complex32(exp * Mathf.Cos(_imag), exp * Mathf.Sin(_imag));
         }
static Complex32 BGC.Mathematics.Complex32.FromPolarCoordinates (float magnitude, float phase) static
Creates a complex number from a point's polar coordinates.
static Complex32 BGC.Mathematics.Complex32.FromPolarCoordinates (double magnitude, double phase) static
Creates a complex number from a point's polar coordinates.
override int BGC.Mathematics.Complex32.GetHashCode () inline
Returns the hash code for the current Complex32 object.
Definition at line 506 of file Complex32.cs.
         {
             int hash = 27;
             hash = (13 * hash) + _real.GetHashCode();
             hash = (13 * hash) + _imag.GetHashCode();
             return hash;
         }
static Complex32 BGC.Mathematics.Complex32.InternalDiv (float a, float b, float c, float d, bool swapped) inline static private
Helper method for dividing.
Parameters
a Re first
b Im first
c Re second
d Im second
Definition at line 875 of file Complex32.cs.
         {
             float r = d / c;
             float t = 1 / (c + d * r);
             float e, f;
             if (r != 0f) // one can use r >= float.Epsilon || r <= float.Epsilon instead
             {
                 e = (a + b * r) * t;
                 f = (b - a * r) * t;
             }
             else
             {
                 e = (a + d * (b / c)) * t;
                 f = (b - d * (a / c)) * t;
             }
             if (swapped)
             {
                 f = -f;
             }
             return new Complex32(e, f);
         }
bool BGC.Mathematics.Complex32.IsImaginaryOne ()
Gets a value indicating whether the Complex32 is the imaginary unit.
Returns
true if this instance is ImaginaryOne; otherwise, false.
bool BGC.Mathematics.Complex32.IsInfinity ()
Gets a value indicating whether the provided Complex32 evaluates to an infinite value.
Returns
true if this instance is infinite; otherwise, false.
True if it either evaluates to a complex infinity or to a directed infinity.
bool BGC.Mathematics.Complex32.IsNaN ()
Gets a value indicating whether the provided Complex32evaluates to a value that is not a number.
Returns
true if this instance is NaN; otherwise, false.
bool BGC.Mathematics.Complex32.IsOne ()
Gets a value indicating whether the Complex32 is one.
Returns
true if this instance is one; otherwise, false.
bool BGC.Mathematics.Complex32.IsReal ()
Gets a value indicating whether the provided Complex32 is real.
Returns
true if this instance is a real number; otherwise, false.
bool BGC.Mathematics.Complex32.IsRealNonNegative ()
Gets a value indicating whether the provided Complex32 is real and not negative, that is >= 0.
Returns
true if this instance is real nonnegative number; otherwise, false.
bool BGC.Mathematics.Complex32.IsZero ()
Gets a value indicating whether the Complex32 is zero.
Returns
true if this instance is zero; otherwise, false.
static Complex32 BGC.Mathematics.Complex32.Log (in Complex32 value) static
Returns the natural (base e) logarithm of a specified complex number.
Referenced by BGC.Mathematics.Complex32.CommonLogarithm().
static Complex32 BGC.Mathematics.Complex32.Log (in Complex32 value, float baseValue) static
Returns the logarithm of a specified complex number in a specified base.
static Complex32 BGC.Mathematics.Complex32.Log10 (in Complex32 value) static
Returns the base-10 logarithm of a specified complex number.
Complex32 BGC.Mathematics.Complex32.Logarithm (float baseValue)
Logarithm of this Complex32 with custom base.
Returns
The logarithm of this complex number.
Referenced by BGC.Mathematics.Complex32.Cosh().
static Complex32 BGC.Mathematics.Complex32.Multiply (in Complex32 left, in Complex32 right) static
Returns the product of two complex numbers.
Complex32 BGC.Mathematics.Complex32.NaturalLogarithm () inline
Natural Logarithm of this Complex32 (Base E).
Returns
The natural logarithm of this complex number.
Definition at line 757 of file Complex32.cs.
Referenced by BGC.Mathematics.Complex32.Cosh().
         {
             if (IsRealNonNegative())
             {
                 return new Complex32(Mathf.Log(_real), 0f);
             }
             return new Complex32(0.5f * Mathf.Log(MagnitudeSquared), Phase);
         }
static Complex32 BGC.Mathematics.Complex32.Negate (in Complex32 value) static
Returns the additive inverse of a specified complex number.
static implicit BGC.Mathematics.Complex32.operator Complex32 (byte value) static
Defines an implicit conversion of an unsigned byte to a complex number.
static implicit BGC.Mathematics.Complex32.operator Complex32 (float value) static
Defines an implicit conversion of a single-precision floating-point number to a complex number.
static implicit BGC.Mathematics.Complex32.operator Complex32 (double value) static
Defines an implicit conversion of a double-precision floating-point number to a complex number.
Parameters
value
static implicit BGC.Mathematics.Complex32.operator Complex32 (sbyte value) static
Defines an implicit conversion of a signed byte to a complex number.
static implicit BGC.Mathematics.Complex32.operator Complex32 (ulong value) static
Defines an implicit conversion of a 64-bit unsigned integer to a complex number.
static implicit BGC.Mathematics.Complex32.operator Complex32 (uint value) static
Defines an implicit conversion of a 32-bit unsigned integer to a complex number.
static implicit BGC.Mathematics.Complex32.operator Complex32 (ushort value) static
Defines an implicit conversion of a 16-bit unsigned integer to a complex number.
static implicit BGC.Mathematics.Complex32.operator Complex32 (long value) static
Defines an implicit conversion of a 64-bit signed integer to a complex number.
static implicit BGC.Mathematics.Complex32.operator Complex32 (int value) static
Defines an implicit conversion of a 32-bit signed integer to a complex number.
static implicit BGC.Mathematics.Complex32.operator Complex32 (short value) static
Defines an implicit conversion of a 16-bit signed integer to a complex number.
static BGC.Mathematics.Complex32.operator Complex32 (decimal value) explicit static
Defines an explicit conversion of a System.Decimal value to a complex number.
static bool BGC.Mathematics.Complex32.operator!= (in Complex32 left, in Complex32 right) static
Returns a value that indicates whether two complex numbers are not equal.
static Complex32 BGC.Mathematics.Complex32.operator* (in Complex32 left, in Complex32 right) static
Multiplies two specified complex numbers.
static Complex32 BGC.Mathematics.Complex32.operator+ (in Complex32 left, in Complex32 right) static
Adds two complex numbers.
static Complex32 BGC.Mathematics.Complex32.operator- (in Complex32 value) static
Returns the additive inverse of a specified complex number.
static Complex32 BGC.Mathematics.Complex32.operator- (in Complex32 left, in Complex32 right) static
Subtracts a complex number from another complex number.
static Complex32 BGC.Mathematics.Complex32.operator/ (in Complex32 dividend, in Complex32 divisor) inline static
Divides a specified complex number by another specified complex number.
Definition at line 566 of file Complex32.cs.
References BGC.Mathematics.Complex32.Real.
         {
             if (dividend.IsZero() && divisor.IsZero())
             {
                 return NaN;
             }
             if (divisor.IsZero())
             {
                 return PositiveInfinity;
             }
             float a = dividend.Real;
             float b = dividend.Imaginary;
             float c = divisor.Real;
             float d = divisor.Imaginary;
             if (Mathf.Abs(d) <= Mathf.Abs(c))
             {
                 return InternalDiv(a, b, c, d, false);
             }
             return InternalDiv(b, a, d, c, true);
         }
static bool BGC.Mathematics.Complex32.operator== (in Complex32 left, in Complex32 right) static
Returns a value that indicates whether two complex numbers are equal.
static Complex32 BGC.Mathematics.Complex32.Pow (in Complex32 value, float power) static
Returns a specified complex number raised to a power specified by a float-precision floating-point number.
static Complex32 BGC.Mathematics.Complex32.Pow (in Complex32 value, in Complex32 power) static
Returns a specified complex number raised to a power specified by a complex number.
Complex32 BGC.Mathematics.Complex32.Power (in Complex32 exponent) inline
Raise this Complex32 to the given value.
Parameters
exponent The exponent.
Returns
The complex number raised to the given exponent.
Definition at line 726 of file Complex32.cs.
References BGC.Mathematics.Complex32.Imaginary.
Referenced by BGC.Mathematics.Complex32.Cosh().
         {
             if (IsZero())
             {
                 if (exponent.IsZero())
                 {
                     return One;
                 }
                 if (exponent.Real > 0f)
                 {
                     return Zero;
                 }
                 if (exponent.Real < 0f)
                 {
                     return exponent.Imaginary == 0f
                         ? new Complex32(float.PositiveInfinity, 0f)
                         : new Complex32(float.PositiveInfinity, float.PositiveInfinity);
                 }
                 return NaN;
             }
             return (exponent * NaturalLogarithm()).Exponential();
         }
float BGC.Mathematics.Complex32.RealProduct (in Complex32 other)
Returns the real component of the product of this Complex32 with other.
Returns
The real component of the product.
float BGC.Mathematics.Complex32.RealRotation (float phase)
Retuns the real value of the Complex32 number after rotation by phase radians, or exp(i*phase)
static Complex32 BGC.Mathematics.Complex32.Reciprocal (in Complex32 value) static
Returns the multiplicative inverse of a complex number.
Referenced by BGC.Mathematics.Complex32.Cosh().
Complex32 BGC.Mathematics.Complex32.Reciprocal ()
Returns the multiplicative inverse of a complex number.
Complex32 BGC.Mathematics.Complex32.Rotation (float phase) inline
Retuns the Complex32 number, rotated by phase radians, or exp(i*phase)
Definition at line 459 of file Complex32.cs.
References BGC.Mathematics.Complex32.Cos(), and BGC.Mathematics.Complex32.Sin().
         {
             float cosPhase = Mathf.Cos(phase);
             float sinePhase = Mathf.Sin(phase);
             return new Complex32(
                 _real * cosPhase - _imag * sinePhase,
                 _real * sinePhase + _imag * cosPhase);
         }
static Complex32 BGC.Mathematics.Complex32.Sin (in Complex32 value) inline static
Trigonometric Sine of a Complex32 number.
Parameters
value The complex value.
Returns
The sine of the complex number.
Definition at line 318 of file Complex32.cs.
References BGC.Mathematics.GeneralMath.Cosh(), and BGC.Mathematics.GeneralMath.Sinh().
Referenced by BGC.Mathematics.Complex32.Rotation().
         {
             if (value.IsReal())
             {
                 return new Complex32(Mathf.Sin(value.Real), 0f);
             }
             return new Complex32(
                 Mathf.Sin(value.Real) * GeneralMath.Cosh(value.Imaginary),
                 Mathf.Cos(value.Real) * GeneralMath.Sinh(value.Imaginary));
         }
static Complex32 BGC.Mathematics.Complex32.Sinh (in Complex32 value) inline static
Hyperbolic Sine of a Complex32 number.
Parameters
value The complex value.
Returns
The hyperbolic sine of a complex number.
Definition at line 336 of file Complex32.cs.
References BGC.Mathematics.GeneralMath.Cosh(), BGC.Mathematics.Complex32.Exp(), and BGC.Mathematics.GeneralMath.Sinh().
         {
             if (value.IsReal())
             {
                 return new Complex32(GeneralMath.Sinh(value.Real), 0f);
             }
             // sinh(x + j y) = sinh(x)*cos(y) + j*cosh(x)*sin(y)
             // if x > huge, sinh(x + jy) = sign(x)*exp(|x|)/2*cos(y) + j*exp(|x|)/2*sin(y)
             if (Mathf.Abs(value.Real) >= 22f) // Taken from the msun library in FreeBSD
             {
                 float h = Mathf.Exp(Mathf.Abs(value.Real)) * 0.5f;
                 return new Complex32(
                     Mathf.Sign(value.Real) * h * Mathf.Cos(value.Imaginary),
                     h * Mathf.Sin(value.Imaginary));
             }
             return new Complex32(
                 GeneralMath.Sinh(value.Real) * Mathf.Cos(value.Imaginary),
                 GeneralMath.Cosh(value.Real) * Mathf.Sin(value.Imaginary));
         }
static Complex32 BGC.Mathematics.Complex32.Sqrt (in Complex32 value) static
The Square Root of a complex number
Complex32 BGC.Mathematics.Complex32.Square () inline
The Square (power 2) of this Complex32
Returns
The square of this complex number.
Definition at line 365 of file Complex32.cs.
References BGC.Mathematics.Complex32.SquareRoot().
         {
             if (IsReal())
             {
                 return new Complex32(_real * _real, 0.0f);
             }
             return new Complex32((_real * _real) - (_imag * _imag), 2 * _real * _imag);
         }
Complex32 BGC.Mathematics.Complex32.SquareRoot () inline
The Square Root (power 1/2) of this Complex32
Returns
The square root of this complex number.
Definition at line 829 of file Complex32.cs.
References BGC.Mathematics.Complex32.Abs().
Referenced by BGC.Mathematics.Complex32.Square().
         {
             if (IsRealNonNegative())
             {
                 return new Complex32(Mathf.Sqrt(_real), 0f);
             }
             Complex32 result;
             float absReal = Mathf.Abs(Real);
             float absImag = Mathf.Abs(Imaginary);
             float w;
             if (absReal >= absImag)
             {
                 float ratio = Imaginary / Real;
                 w = Mathf.Sqrt(absReal) * Mathf.Sqrt(0.5f * (1f + Mathf.Sqrt(1f + (ratio * ratio))));
             }
             else
             {
                 float ratio = Real / Imaginary;
                 w = Mathf.Sqrt(absImag) * Mathf.Sqrt(0.5f * (Mathf.Abs(ratio) + Mathf.Sqrt(1f + (ratio * ratio))));
             }
             if (Real >= 0f)
             {
                 result = new Complex32(w, (Imaginary / (2f * w)));
             }
             else if (Imaginary >= 0f)
             {
                 result = new Complex32((absImag / (2f * w)), w);
             }
             else
             {
                 result = new Complex32((absImag / (2f * w)), -w);
             }
             return result;
         }
static Complex32 BGC.Mathematics.Complex32.Subtract (in Complex32 left, Complex32 right) static
The difference between two Complex32 numbers;
Returns
The complex difference.
static Complex32 BGC.Mathematics.Complex32.Tan (in Complex32 value) inline static
Trigonometric Tangent of a Complex32 number.
Parameters
value The complex value.
Returns
The tangent of the complex number.
Definition at line 394 of file Complex32.cs.
Referenced by BGC.Mathematics.Complex32.Tanh().
         {
             if (value.IsReal())
             {
                 return new Complex32(Mathf.Tan(value.Real), 0f);
             }
             // tan(z) = - j*tanh(j*z)
             Complex32 z = Tanh(new Complex32(-value.Imaginary, value.Real));
             return new Complex32(z.Imaginary, -z.Real);
         }
static Complex32 BGC.Mathematics.Complex32.Tanh (in Complex32 value) inline static
Hyperbolic Tangent of a Complex32 number.
Parameters
value The complex value.
Returns
The hyperbolic tangent of a complex number.
Definition at line 413 of file Complex32.cs.
References BGC.Mathematics.GeneralMath.Cosh(), BGC.Mathematics.Complex32.Exp(), BGC.Mathematics.GeneralMath.Sinh(), BGC.Mathematics.Complex32.Tan(), and BGC.Mathematics.GeneralMath.Tanh().
         {
             if (value.IsReal())
             {
                 return new Complex32(GeneralMath.Tanh(value.Real), 0f);
             }
             // tanh(x + j*y) = (cosh(x)*sinh(x)/cos^2(y) + j*tan(y))/(1 + sinh^2(x)/cos^2(y))
             // if |x| > huge, tanh(z) = sign(x) + j*4*cos(y)*sin(y)*exp(-2*|x|)
             // if exp(-|x|) = 0, tanh(z) = sign(x)
             // if tan(y) = +/- oo or 1/cos^2(y) = 1 + tan^2(y) = oo, tanh(z) = cosh(x)/sinh(x)
             //
             // The algorithm is based on Kahan.
             if (Math.Abs(value.Real) >= 22f) // Taken from the msun library in FreeBSD
             {
                 float e = Mathf.Exp(-Mathf.Abs(value.Real));
                 if (e == 0f)
                 {
                     return new Complex32(Mathf.Sign(value.Real), 0f);
                 }
                 else
                 {
                     return new Complex32(
                         Mathf.Sign(value.Real),
                         4f * Mathf.Cos(value.Imaginary) * Mathf.Sin(value.Imaginary) * e * e);
                 }
             }
             float tani = Mathf.Tan(value.Imaginary);
             float beta = 1 + tani * tani; // beta = 1/cos^2(y) = 1 + t^2
             float sinhr = GeneralMath.Sinh(value.Real);
             float coshr = GeneralMath.Cosh(value.Real);
             if (float.IsInfinity(tani))
             {
                 return new Complex32(coshr / sinhr, 0f);
             }
             float denom = 1f + beta * sinhr * sinhr;
             return new Complex32(beta * coshr * sinhr / denom, tani / denom);
         }
string BGC.Mathematics.Complex32.ToString (string format)
Converts the value of the current complex number to its equivalent string representation in Cartesian form by using the specified format for its real and imaginary parts.
string BGC.Mathematics.Complex32.ToString (IFormatProvider provider)
Converts the value of the current complex number to its equivalent string representation in Cartesian form by using the specified culture-specific formatting information.
string BGC.Mathematics.Complex32.ToString (string format, IFormatProvider provider)
Converts the value of the current complex number to its equivalent string representation in Cartesian form by using the specified format and culture-specific format information for its real and imaginary parts.
override string BGC.Mathematics.Complex32.ToString ()
Converts the value of the current complex number to its equivalent string representation in Cartesian form.
Returns
Field Documentation
readonly float BGC.Mathematics.Complex32._imag private
The imaginary component of the complex number.
Definition at line 53 of file Complex32.cs.
readonly float BGC.Mathematics.Complex32._real private
The real component of the complex number.
Definition at line 47 of file Complex32.cs.
Referenced by BGC.Mathematics.Complex32.Exponential().
float BGC.Mathematics.Complex32.Imaginary => _imag
Gets the imaginary component of the current System.Numerics.Complex32 object.
Definition at line 93 of file Complex32.cs.
Referenced by BGC.Mathematics.Complex64.operator/(), and BGC.Mathematics.Complex32.Power().
readonly Complex32 BGC.Mathematics.Complex32.ImaginaryOne = new Complex32(0f, 1f) static
Returns a new Complex32 instance with a real number equal to zero and an imaginary number equal to one.
Definition at line 69 of file Complex32.cs.
float BGC.Mathematics.Complex32.MagnitudeSquared => (_real * _real) + (_imag * _imag)
Gets the squared magnitude (or squared absolute value) of a complex number.
Returns
The squared magnitude of the current instance.
Definition at line 715 of file Complex32.cs.
readonly Complex32 BGC.Mathematics.Complex32.NaN = new Complex32(float.NaN, float.NaN) static
Returns a new Complex32 instance with real and imaginary numbers not a number.
Definition at line 79 of file Complex32.cs.
readonly Complex32 BGC.Mathematics.Complex32.One = new Complex32(1f, 0f) static
Returns a new Complex32 instance with a real number equal to one and an imaginary number equal to zero.
Definition at line 64 of file Complex32.cs.
float BGC.Mathematics.Complex32.Phase => _imag == 0f && _real < 0f ? Mathf.PI : Mathf.Atan2(_imag, _real)
Gets the phase of a complex number in radians.
Definition at line 142 of file Complex32.cs.
readonly Complex32 BGC.Mathematics.Complex32.PositiveInfinity = new Complex32(float.PositiveInfinity, float.PositiveInfinity) static
Returns a new Complex32 instance with real and imaginary numbers positive infinite.
Definition at line 74 of file Complex32.cs.
float BGC.Mathematics.Complex32.Real => _real
Gets the real component of the current System.Numerics.Complex32 object.
Definition at line 98 of file Complex32.cs.
Referenced by BGC.Mathematics.Complex64.operator/(), and BGC.Mathematics.Complex32.operator/().
readonly Complex32 BGC.Mathematics.Complex32.Zero = new Complex32(0f, 0f) static
Returns a new Complex32 instance with a real number equal to zero and an imaginary number equal to zero.
Definition at line 59 of file Complex32.cs.
Property Documentation
float BGC.Mathematics.Complex32.Magnitude get
Gets the magnitude (or absolute value) of a complex number.
Definition at line 104 of file Complex32.cs.
The documentation for this struct was generated from the following file:
Mathematics/Complex32.cs