BGC Tools: BGC.Mathematics.Complex64 Struct Reference
BGC.Mathematics.Complex64 Struct Reference
Represents a complex number with double-precision floating point components
Public Member Functions
Complex64 (double real, double imaginary)
Initializes a new Complex64 structure using the specified real and imaginary values.
Complex64 Square ()
The Square (power 2) of this Complex64
Complex64 Rotation (double phase)
Retuns the Complex64 number, rotated by phase radians, or exp(i*phase)
double RealRotation (double phase)
Retuns the real value of the Complex64 number after rotation by phase radians, or exp(i*phase)
bool Equals (in Complex64 value)
Returns a value that indicates whether the current instance and a specified complex number have the same value.
bool IEquatable< Complex64 >. Equals (Complex64 other)
Returns a value that indicates whether the current instance and a specified complex number have the same value.
override bool Equals (object obj)
Returns a value that indicates whether the current instance and a specified object have the same value.
override int GetHashCode ()
Returns the hash code for the current Complex64 object.
string ToString (string format)
Converts the value of the current complex number to its equivalent string representation in Cartesian form by using the specified format for its real and imaginary parts.
string ToString (IFormatProvider provider)
Converts the value of the current complex number to its equivalent string representation in Cartesian form by using the specified culture-specific formatting information.
string ToString (string format, IFormatProvider provider)
Converts the value of the current complex number to its equivalent string representation in Cartesian form by using the specified format and culture-specific format information for its real and imaginary parts.
override string ToString ()
Converts the value of the current complex number to its equivalent string representation in Cartesian form.
bool IsReal ()
Gets a value indicating whether the provided Complex64 is real.
bool IsRealNonNegative ()
Gets a value indicating whether the provided Complex64 is real and not negative, that is >= 0.
bool IsZero ()
Gets a value indicating whether the Complex64 is zero.
bool IsOne ()
Gets a value indicating whether the Complex64 is one.
bool IsImaginaryOne ()
Gets a value indicating whether the Complex64 is the imaginary unit.
bool IsInfinity ()
Gets a value indicating whether the provided Complex64 evaluates to an infinite value.
bool IsNaN ()
Gets a value indicating whether the provided Complex64evaluates to a value that is not a number.
Complex64 Power (in Complex64 exponent)
Raise this Complex64 to the given value.
Complex64 NaturalLogarithm ()
Natural Logarithm of this Complex64 (Base E).
Complex64 CommonLogarithm ()
Common Logarithm of this Complex64 (Base 10).
Complex64 Logarithm (double baseValue)
Logarithm of this Complex64 with custom base.
Complex64 Exponential ()
Exponential of this Complex64 (exp(x), E^x).
double RealProduct (in Complex64 other)
Returns the real component of the product of this Complex64 with other.
Complex64 Conjugate ()
Computes the conjugate of a complex number and returns the result.
Complex64 Reciprocal ()
Returns the multiplicative inverse of a complex number.
Complex64 SquareRoot ()
The Square Root (power 1/2) of this Complex64
Static Public Member Functions
static double Abs (in Complex64 value)
Gets the absolute value (or magnitude) of a complex number.
static Complex64 Acos (in Complex64 value)
Trigonometric principal Arc Cosine of this Complex64 number.
static Complex64 Add (in Complex64 left, in Complex64 right)
Returns the sum of the two Complex64 inputs
static Complex64 Asin (in Complex64 value)
Trigonometric principal Arc Sine of this Complex64 number.
static Complex64 Atan (in Complex64 value)
Trigonometric principal Arc Tangent of this Complex64 number.
static Complex64 Conjugate (in Complex64 value)
Computes the conjugate of a complex number and returns the result.
static Complex64 Cos (in Complex64 value)
Trigonometric Cosine of a Complex64 number.
static Complex64 Cosh (in Complex64 value)
Hyperbolic Cosine of a Complex64 number.
static Complex64 Divide (in Complex64 dividend, in Complex64 divisor)
Divides one complex number by another and returns the result.
static Complex64 Exp (in Complex64 value)
Returns e raised to the power specified by a complex number.
static Complex64 FromPolarCoordinates (double magnitude, double phase)
Creates a complex number from a point's polar coordinates.
static Complex64 Log (in Complex64 value)
Returns the natural (base e) logarithm of a specified complex number.
static Complex64 Log (in Complex64 value, double baseValue)
Returns the logarithm of a specified complex number in a specified base.
static Complex64 Log10 (in Complex64 value)
Returns the base-10 logarithm of a specified complex number.
static Complex64 Multiply (in Complex64 left, in Complex64 right)
Returns the product of two complex numbers.
static Complex64 Negate (in Complex64 value)
Returns the additive inverse of a specified complex number.
static Complex64 Pow (in Complex64 value, double power)
Returns a specified complex number raised to a power specified by a double-precision doubleing-point number.
static Complex64 Pow (in Complex64 value, in Complex64 power)
Returns a specified complex number raised to a power specified by a complex number.
static Complex64 Reciprocal (in Complex64 value)
Returns the multiplicative inverse of a complex number.
static Complex64 Sin (in Complex64 value)
Trigonometric Sine of a Complex64 number.
static Complex64 Sinh (in Complex64 value)
Hyperbolic Sine of a Complex64 number.
static Complex64 Sqrt (in Complex64 value)
The Square Root of a complex number
static Complex64 Subtract (in Complex64 left, Complex64 right)
The difference between two Complex64 numbers;
static Complex64 Tan (in Complex64 value)
Trigonometric Tangent of a Complex64 number.
static Complex64 Tanh (in Complex64 value)
Hyperbolic Tangent of a Complex64 number.
static Complex64 operator+ (in Complex64 left, in Complex64 right)
Adds two complex numbers.
static Complex64 operator- (in Complex64 value)
Returns the additive inverse of a specified complex number.
static Complex64 operator- (in Complex64 left, in Complex64 right)
Subtracts a complex number from another complex number.
static Complex64 operator* (in Complex64 left, in Complex64 right)
Multiplies two specified complex numbers.
static Complex64 operator/ (in Complex64 dividend, in Complex64 divisor)
Divides a specified complex number by another specified complex number.
static bool operator== (in Complex64 left, in Complex64 right)
Returns a value that indicates whether two complex numbers are equal.
static bool operator!= (in Complex64 left, in Complex64 right)
Returns a value that indicates whether two complex numbers are not equal.
static implicit operator Complex64 (Complex32 value)
Defines an implicit conversion of an unsigned byte to a complex number.
static implicit operator Complex64 (byte value)
Defines an implicit conversion of an unsigned byte to a complex number.
static implicit operator Complex64 (float value)
Defines an implicit conversion of a single-precision floating-point number to a complex number.
static implicit operator Complex64 (double value)
Defines an implicit conversion of a double-precision floating-point number to a complex number.
static implicit operator Complex64 (sbyte value)
Defines an implicit conversion of a signed byte to a complex number.
static implicit operator Complex64 (ulong value)
Defines an implicit conversion of a 64-bit unsigned integer to a complex number.
static implicit operator Complex64 (uint value)
Defines an implicit conversion of a 32-bit unsigned integer to a complex number.
static implicit operator Complex64 (ushort value)
Defines an implicit conversion of a 16-bit unsigned integer to a complex number.
static implicit operator Complex64 (long value)
Defines an implicit conversion of a 64-bit signed integer to a complex number.
static implicit operator Complex64 (int value)
Defines an implicit conversion of a 32-bit signed integer to a complex number.
static implicit operator Complex64 (short value)
Defines an implicit conversion of a 16-bit signed integer to a complex number.
static operator Complex64 (decimal value)
Defines an explicit conversion of a System.Decimal value to a complex number.
Data Fields
double Imaginary => _imag
Gets the imaginary component of the current System.Numerics.Complex64 object.
double Real => _real
Gets the real component of the current System.Numerics.Complex64 object.
double Phase => _imag == 0.0 && _real < 0.0 ? Math.PI : Math.Atan2(_imag, _real)
Gets the phase of a complex number in radians.
double MagnitudeSquared => (_real * _real) + (_imag * _imag)
Gets the squared magnitude (or squared absolute value) of a complex number.
Static Public Attributes
static readonly Complex64 Zero = new Complex64(0.0, 0.0)
Returns a new Complex64 instance with a real number equal to zero and an imaginary number equal to zero.
static readonly Complex64 One = new Complex64(1.0, 0.0)
Returns a new Complex64 instance with a real number equal to one and an imaginary number equal to zero.
static readonly Complex64 ImaginaryOne = new Complex64(0.0, 1.0)
Returns a new Complex64 instance with a real number equal to zero and an imaginary number equal to one.
static readonly Complex64 PositiveInfinity = new Complex64(double.PositiveInfinity, double.PositiveInfinity)
Returns a new Complex64 instance with real and imaginary numbers positive infinite.
static readonly Complex64 NaN = new Complex64(double.NaN, double.NaN)
Returns a new Complex64 instance with real and imaginary numbers not a number.
Properties
double Magnitude [get]
Gets the magnitude (or absolute value) of a complex number.
Static Private Member Functions
static Complex64 InternalDiv (double a, double b, double c, double d, bool swapped)
Helper method for dividing.
Private Attributes
readonly double _real
The real component of the complex number.
readonly double _imag
The imaginary component of the complex number.
Detailed Description
Represents a complex number with double-precision floating point components
Definition at line 39 of file Complex64.cs.
Constructor & Destructor Documentation
BGC.Mathematics.Complex64.Complex64 (double real, double imaginary) inline
Initializes a new Complex64 structure using the specified real and imaginary values.
Definition at line 82 of file Complex64.cs.
         {
             _real = real;
             _imag = imaginary;
         }
Member Function Documentation
static double BGC.Mathematics.Complex64.Abs (in Complex64 value) static
Gets the absolute value (or magnitude) of a complex number.
Referenced by BGC.Mathematics.Complex64.SquareRoot().
static Complex64 BGC.Mathematics.Complex64.Acos (in Complex64 value) inline static
Trigonometric principal Arc Cosine of this Complex64 number.
Parameters
value The complex value.
Returns
The arc cosine of a complex number.
Definition at line 152 of file Complex64.cs.
         {
             if (value.Imaginary < 0.0 || value.Imaginary == 0.0 && value.Real > 0.0)
             {
                 return Math.PI - Acos(-value);
             }
             return -ImaginaryOne * (value + (ImaginaryOne * (1.0 - value.Square()).SquareRoot())).NaturalLogarithm();
         }
static Complex64 BGC.Mathematics.Complex64.Add (in Complex64 left, in Complex64 right) static
Returns the sum of the two Complex64 inputs
static Complex64 BGC.Mathematics.Complex64.Asin (in Complex64 value) inline static
Trigonometric principal Arc Sine of this Complex64 number.
Parameters
value The complex value.
Returns
The arc sine of a complex number.
Definition at line 173 of file Complex64.cs.
         {
             if (value.Imaginary > 0.0 || value.Imaginary == 0.0 && value.Real < 0.0)
             {
                 return -Asin(-value);
             }
             return -ImaginaryOne * ((1.0 - value.Square()).SquareRoot() + (ImaginaryOne * value)).NaturalLogarithm();
         }
static Complex64 BGC.Mathematics.Complex64.Atan (in Complex64 value) inline static
Trigonometric principal Arc Tangent of this Complex64 number.
Parameters
value The complex value.
Returns
The arc tangent of a complex number.
Definition at line 189 of file Complex64.cs.
References BGC.Mathematics.Complex64.Conjugate().
         {
             Complex64 iz = new Complex64(-value.Imaginary, value.Real); // I*this
             return new Complex64(0.0, 0.5) * ((1.0 - iz).NaturalLogarithm() - (1.0 + iz).NaturalLogarithm());
         }
Complex64 BGC.Mathematics.Complex64.CommonLogarithm () inline
Common Logarithm of this Complex64 (Base 10).
Returns
The common logarithm of this complex number.
Definition at line 766 of file Complex64.cs.
References BGC.Mathematics.Complex64.Log().
Referenced by BGC.Mathematics.Complex64.Cosh().
         {
             if (IsRealNonNegative())
             {
                 return new Complex64(Math.Log10(_real), 0.0);
             }
             return new Complex64(0.5 * Math.Log10(MagnitudeSquared), Phase);
         }
static Complex64 BGC.Mathematics.Complex64.Conjugate (in Complex64 value) static
Computes the conjugate of a complex number and returns the result.
Referenced by BGC.Mathematics.Complex64.Atan(), and BGC.Mathematics.Fourier.BluesteinForward().
Complex64 BGC.Mathematics.Complex64.Conjugate ()
Computes the conjugate of a complex number and returns the result.
static Complex64 BGC.Mathematics.Complex64.Cos (in Complex64 value) inline static
Trigonometric Cosine of a Complex64 number.
Parameters
value The complex value.
Returns
The cosine of a complex number.
Definition at line 206 of file Complex64.cs.
References BGC.Mathematics.GeneralMath.Cosh(), and BGC.Mathematics.GeneralMath.Sinh().
Referenced by BGC.Audio.Filters.PhaseVocoder.PhaseVocoder(), and BGC.Mathematics.Complex64.Rotation().
         {
             if (value.IsReal())
             {
                 return new Complex64(Math.Cos(value.Real), 0.0);
             }
             return new Complex64(
                 Math.Cos(value.Real) * GeneralMath.Cosh(value.Imaginary),
                 -Math.Sin(value.Real) * GeneralMath.Sinh(value.Imaginary));
         }
static Complex64 BGC.Mathematics.Complex64.Cosh (in Complex64 value) inline static
Hyperbolic Cosine of a Complex64 number.
Parameters
value The complex value.
Returns
The hyperbolic cosine of a complex number.
Definition at line 224 of file Complex64.cs.
References BGC.Mathematics.Complex64.CommonLogarithm(), BGC.Mathematics.GeneralMath.Cosh(), BGC.Mathematics.Complex64.Exponential(), BGC.Mathematics.Complex64.Logarithm(), BGC.Mathematics.Complex64.NaturalLogarithm(), BGC.Mathematics.Complex64.Power(), BGC.Mathematics.Complex64.Reciprocal(), and BGC.Mathematics.GeneralMath.Sinh().
         {
             if (value.IsReal())
             {
                 return new Complex64(GeneralMath.Cosh(value.Real), 0.0);
             }
             // cosh(x + j*y) = cosh(x)*cos(y) + j*sinh(x)*sin(y)
             // if x > huge, cosh(x + j*y) = exp(|x|)/2*cos(y) + j*sign(x)*exp(|x|)/2*sin(y)
             if (Math.Abs(value.Real) >= 22.0) // Taken from the msun library in FreeBSD
             {
                 double h = Math.Exp(Math.Abs(value.Real)) * 0.5;
                 return new Complex64(
                     h * Math.Cos(value.Imaginary),
                     Math.Sign(value.Real) * h * Math.Sin(value.Imaginary));
             }
             return new Complex64(
                 GeneralMath.Cosh(value.Real) * Math.Cos(value.Imaginary),
                 GeneralMath.Sinh(value.Real) * Math.Sin(value.Imaginary));
         }
static Complex64 BGC.Mathematics.Complex64.Divide (in Complex64 dividend, in Complex64 divisor) static
Divides one complex number by another and returns the result.
bool BGC.Mathematics.Complex64.Equals (in Complex64 value) inline
Returns a value that indicates whether the current instance and a specified complex number have the same value.
Definition at line 467 of file Complex64.cs.
References BGC.Mathematics.GeneralMath.Approximately().
         {
             if (IsNaN() || value.IsNaN())
             {
                 return false;
             }
             if (IsInfinity() && value.IsInfinity())
             {
                 return true;
             }
             return GeneralMath.Approximately(_real, value._real) &&
                 GeneralMath.Approximately(_imag, value._imag);
         }
bool IEquatable<Complex64>. BGC.Mathematics.Complex64.Equals (Complex64 other)
Returns a value that indicates whether the current instance and a specified complex number have the same value.
override bool BGC.Mathematics.Complex64.Equals (object obj)
Returns a value that indicates whether the current instance and a specified object have the same value.
static Complex64 BGC.Mathematics.Complex64.Exp (in Complex64 value) static
Returns e raised to the power specified by a complex number.
Referenced by BGC.Mathematics.Complex64.Exponential().
Complex64 BGC.Mathematics.Complex64.Exponential () inline
Exponential of this Complex64 (exp(x), E^x).
Returns
The exponential of this complex number.
Definition at line 788 of file Complex64.cs.
References BGC.Mathematics.Complex64._real, and BGC.Mathematics.Complex64.Exp().
Referenced by BGC.Mathematics.Complex64.Cosh().
         {
             double exp = Math.Exp(_real);
             if (IsReal())
             {
                 return new Complex64(exp, 0.0);
             }
             return new Complex64(exp * Math.Cos(_imag), exp * Math.Sin(_imag));
         }
static Complex64 BGC.Mathematics.Complex64.FromPolarCoordinates (double magnitude, double phase) static
Creates a complex number from a point's polar coordinates.
Referenced by BGC.Audio.Filters.CarlileShuffler._Initialize(), BGC.Audio.AnalyticStreams.AnalyticFrequencyModulationFilter.AnalyticFrequencyModulationFilter(), BGC.Audio.AnalyticStreams.AnalyticStreamFrequencyShifter.AnalyticStreamFrequencyShifter(), BGC.Audio.AnalyticStreams.AnalyticWave.AnalyticWave(), BGC.Audio.ComplexCarrierTone.ComplexCarrierTone(), BGC.Audio.Synthesis.NoiseAudioClip.CreateSideBands(), BGC.Audio.AnalyticStreams.AnalyticNoiseStream.CreateSideBands(), BGC.Audio.Synthesis.STMAudioClip.CreateSideBands(), BGC.Audio.Synthesis.STMAudioClip.ExpCarrierToneSideBands(), BGC.Audio.Filters.FrequencyModulationFilter.FrequencyModulationFilter(), BGC.Audio.Filters.PhaseVocoder.PhaseVocoder(), BGC.Audio.FrequencyDomain.Populate(), BGC.Audio.AnalyticStreams.AnalyticStreamFrequencyShifter.Read(), BGC.Audio.AnalyticStreams.AnalyticWave.Read(), BGC.Audio.Synthesis.SineWave.Read(), BGC.Audio.Synthesis.SineWave.ReadNextSample(), BGC.Audio.AnalyticStreams.AnalyticStreamFrequencyShifter.Reset(), BGC.Audio.AnalyticStreams.AnalyticWave.Reset(), BGC.Audio.Synthesis.SineWave.Reset(), BGC.Audio.AnalyticStreams.AnalyticStreamFrequencyShifter.Seek(), BGC.Audio.AnalyticStreams.AnalyticWave.Seek(), BGC.Audio.Synthesis.SineWave.Seek(), BGC.Audio.Synthesis.SineWave.SineWave(), and BGC.Tests.SynthesisTests.TryAllpassFilters().
override int BGC.Mathematics.Complex64.GetHashCode () inline
Returns the hash code for the current Complex64 object.
Definition at line 496 of file Complex64.cs.
         {
             int hash = 27;
             hash = (13 * hash) + _real.GetHashCode();
             hash = (13 * hash) + _imag.GetHashCode();
             return hash;
         }
static Complex64 BGC.Mathematics.Complex64.InternalDiv (double a, double b, double c, double d, bool swapped) inline static private
Helper method for dividing.
Parameters
a Re first
b Im first
c Re second
d Im second
Definition at line 870 of file Complex64.cs.
         {
             double r = d / c;
             double t = 1 / (c + d * r);
             double e, f;
             if (r != 0.0) // one can use r >= double.Epsilon || r <= double.Epsilon instead
             {
                 e = (a + b * r) * t;
                 f = (b - a * r) * t;
             }
             else
             {
                 e = (a + d * (b / c)) * t;
                 f = (b - d * (a / c)) * t;
             }
             if (swapped)
             {
                 f = -f;
             }
             return new Complex64(e, f);
         }
bool BGC.Mathematics.Complex64.IsImaginaryOne ()
Gets a value indicating whether the Complex64 is the imaginary unit.
Returns
true if this instance is ImaginaryOne; otherwise, false.
bool BGC.Mathematics.Complex64.IsInfinity ()
Gets a value indicating whether the provided Complex64 evaluates to an infinite value.
Returns
true if this instance is infinite; otherwise, false.
True if it either evaluates to a complex infinity or to a directed infinity.
bool BGC.Mathematics.Complex64.IsNaN ()
Gets a value indicating whether the provided Complex64evaluates to a value that is not a number.
Returns
true if this instance is NaN; otherwise, false.
bool BGC.Mathematics.Complex64.IsOne ()
Gets a value indicating whether the Complex64 is one.
Returns
true if this instance is one; otherwise, false.
bool BGC.Mathematics.Complex64.IsReal ()
Gets a value indicating whether the provided Complex64 is real.
Returns
true if this instance is a real number; otherwise, false.
bool BGC.Mathematics.Complex64.IsRealNonNegative ()
Gets a value indicating whether the provided Complex64 is real and not negative, that is >= 0.
Returns
true if this instance is real nonnegative number; otherwise, false.
bool BGC.Mathematics.Complex64.IsZero ()
Gets a value indicating whether the Complex64 is zero.
Returns
true if this instance is zero; otherwise, false.
static Complex64 BGC.Mathematics.Complex64.Log (in Complex64 value) static
Returns the natural (base e) logarithm of a specified complex number.
Referenced by BGC.Audio.Synthesis.STMAudioClip._Initialize(), and BGC.Mathematics.Complex64.CommonLogarithm().
static Complex64 BGC.Mathematics.Complex64.Log (in Complex64 value, double baseValue) static
Returns the logarithm of a specified complex number in a specified base.
static Complex64 BGC.Mathematics.Complex64.Log10 (in Complex64 value) static
Returns the base-10 logarithm of a specified complex number.
Complex64 BGC.Mathematics.Complex64.Logarithm (double baseValue)
Logarithm of this Complex64 with custom base.
Returns
The logarithm of this complex number.
Referenced by BGC.Mathematics.Complex64.Cosh().
static Complex64 BGC.Mathematics.Complex64.Multiply (in Complex64 left, in Complex64 right) static
Returns the product of two complex numbers.
Complex64 BGC.Mathematics.Complex64.NaturalLogarithm () inline
Natural Logarithm of this Complex64 (Base E).
Returns
The natural logarithm of this complex number.
Definition at line 752 of file Complex64.cs.
Referenced by BGC.Mathematics.Complex64.Cosh().
         {
             if (IsRealNonNegative())
             {
                 return new Complex64(Math.Log(_real), 0.0);
             }
             return new Complex64(0.5 * Math.Log(MagnitudeSquared), Phase);
         }
static Complex64 BGC.Mathematics.Complex64.Negate (in Complex64 value) static
Returns the additive inverse of a specified complex number.
static implicit BGC.Mathematics.Complex64.operator Complex64 (Complex32 value) static
Defines an implicit conversion of an unsigned byte to a complex number.
static implicit BGC.Mathematics.Complex64.operator Complex64 (byte value) static
Defines an implicit conversion of an unsigned byte to a complex number.
static implicit BGC.Mathematics.Complex64.operator Complex64 (float value) static
Defines an implicit conversion of a single-precision floating-point number to a complex number.
static implicit BGC.Mathematics.Complex64.operator Complex64 (double value) static
Defines an implicit conversion of a double-precision floating-point number to a complex number.
Parameters
value
static implicit BGC.Mathematics.Complex64.operator Complex64 (sbyte value) static
Defines an implicit conversion of a signed byte to a complex number.
static implicit BGC.Mathematics.Complex64.operator Complex64 (ulong value) static
Defines an implicit conversion of a 64-bit unsigned integer to a complex number.
static implicit BGC.Mathematics.Complex64.operator Complex64 (uint value) static
Defines an implicit conversion of a 32-bit unsigned integer to a complex number.
static implicit BGC.Mathematics.Complex64.operator Complex64 (ushort value) static
Defines an implicit conversion of a 16-bit unsigned integer to a complex number.
static implicit BGC.Mathematics.Complex64.operator Complex64 (long value) static
Defines an implicit conversion of a 64-bit signed integer to a complex number.
static implicit BGC.Mathematics.Complex64.operator Complex64 (int value) static
Defines an implicit conversion of a 32-bit signed integer to a complex number.
static implicit BGC.Mathematics.Complex64.operator Complex64 (short value) static
Defines an implicit conversion of a 16-bit signed integer to a complex number.
static BGC.Mathematics.Complex64.operator Complex64 (decimal value) explicit static
Defines an explicit conversion of a System.Decimal value to a complex number.
static bool BGC.Mathematics.Complex64.operator!= (in Complex64 left, in Complex64 right) static
Returns a value that indicates whether two complex numbers are not equal.
static Complex64 BGC.Mathematics.Complex64.operator* (in Complex64 left, in Complex64 right) static
Multiplies two specified complex numbers.
static Complex64 BGC.Mathematics.Complex64.operator+ (in Complex64 left, in Complex64 right) static
Adds two complex numbers.
static Complex64 BGC.Mathematics.Complex64.operator- (in Complex64 value) static
Returns the additive inverse of a specified complex number.
static Complex64 BGC.Mathematics.Complex64.operator- (in Complex64 left, in Complex64 right) static
Subtracts a complex number from another complex number.
static Complex64 BGC.Mathematics.Complex64.operator/ (in Complex64 dividend, in Complex64 divisor) inline static
Divides a specified complex number by another specified complex number.
Definition at line 556 of file Complex64.cs.
References BGC.Mathematics.Complex32.Imaginary, BGC.Mathematics.Complex64.Real, and BGC.Mathematics.Complex32.Real.
         {
             if (dividend.IsZero() && divisor.IsZero())
             {
                 return NaN;
             }
             if (divisor.IsZero())
             {
                 return PositiveInfinity;
             }
             double a = dividend.Real;
             double b = dividend.Imaginary;
             double c = divisor.Real;
             double d = divisor.Imaginary;
             if (Math.Abs(d) <= Math.Abs(c))
             {
                 return InternalDiv(a, b, c, d, false);
             }
             return InternalDiv(b, a, d, c, true);
         }
static bool BGC.Mathematics.Complex64.operator== (in Complex64 left, in Complex64 right) static
Returns a value that indicates whether two complex numbers are equal.
static Complex64 BGC.Mathematics.Complex64.Pow (in Complex64 value, double power) static
Returns a specified complex number raised to a power specified by a double-precision doubleing-point number.
static Complex64 BGC.Mathematics.Complex64.Pow (in Complex64 value, in Complex64 power) static
Returns a specified complex number raised to a power specified by a complex number.
Complex64 BGC.Mathematics.Complex64.Power (in Complex64 exponent) inline
Raise this Complex64 to the given value.
Parameters
exponent The exponent.
Returns
The complex number raised to the given exponent.
Definition at line 721 of file Complex64.cs.
References BGC.Mathematics.Complex64.Imaginary.
Referenced by BGC.Mathematics.Complex64.Cosh().
         {
             if (IsZero())
             {
                 if (exponent.IsZero())
                 {
                     return One;
                 }
                 if (exponent.Real > 0.0)
                 {
                     return Zero;
                 }
                 if (exponent.Real < 0.0)
                 {
                     return exponent.Imaginary == 0.0
                         ? new Complex64(double.PositiveInfinity, 0.0)
                         : new Complex64(double.PositiveInfinity, double.PositiveInfinity);
                 }
                 return NaN;
             }
             return (exponent * NaturalLogarithm()).Exponential();
         }
double BGC.Mathematics.Complex64.RealProduct (in Complex64 other)
Returns the real component of the product of this Complex64 with other.
Returns
The real component of the product.
Referenced by BGC.Audio.Filters.FrequencyModulationFilter.Read().
double BGC.Mathematics.Complex64.RealRotation (double phase)
Retuns the real value of the Complex64 number after rotation by phase radians, or exp(i*phase)
static Complex64 BGC.Mathematics.Complex64.Reciprocal (in Complex64 value) static
Returns the multiplicative inverse of a complex number.
Referenced by BGC.Mathematics.Complex64.Cosh().
Complex64 BGC.Mathematics.Complex64.Reciprocal ()
Returns the multiplicative inverse of a complex number.
Complex64 BGC.Mathematics.Complex64.Rotation (double phase) inline
Retuns the Complex64 number, rotated by phase radians, or exp(i*phase)
Definition at line 450 of file Complex64.cs.
References BGC.Mathematics.Complex64.Cos(), and BGC.Mathematics.Complex64.Sin().
         {
             double cosPhase = Math.Cos(phase);
             double sinePhase = Math.Sin(phase);
             return new Complex64(
                 _real * cosPhase - _imag * sinePhase,
                 _real * sinePhase + _imag * cosPhase);
         }
static Complex64 BGC.Mathematics.Complex64.Sin (in Complex64 value) inline static
Trigonometric Sine of a Complex64 number.
Parameters
value The complex value.
Returns
The sine of the complex number.
Definition at line 309 of file Complex64.cs.
References BGC.Mathematics.GeneralMath.Cosh(), and BGC.Mathematics.GeneralMath.Sinh().
Referenced by BGC.Mathematics.Complex64.Rotation().
         {
             if (value.IsReal())
             {
                 return new Complex64(Math.Sin(value.Real), 0.0);
             }
             return new Complex64(
                 Math.Sin(value.Real) * GeneralMath.Cosh(value.Imaginary),
                 Math.Cos(value.Real) * GeneralMath.Sinh(value.Imaginary));
         }
static Complex64 BGC.Mathematics.Complex64.Sinh (in Complex64 value) inline static
Hyperbolic Sine of a Complex64 number.
Parameters
value The complex value.
Returns
The hyperbolic sine of a complex number.
Definition at line 327 of file Complex64.cs.
References BGC.Mathematics.GeneralMath.Cosh(), and BGC.Mathematics.GeneralMath.Sinh().
         {
             if (value.IsReal())
             {
                 return new Complex64(GeneralMath.Sinh(value.Real), 0.0);
             }
             // sinh(x + j y) = sinh(x)*cos(y) + j*cosh(x)*sin(y)
             // if x > huge, sinh(x + jy) = sign(x)*exp(|x|)/2*cos(y) + j*exp(|x|)/2*sin(y)
             if (Math.Abs(value.Real) >= 22.0) // Taken from the msun library in FreeBSD
             {
                 double h = Math.Exp(Math.Abs(value.Real)) * 0.5;
                 return new Complex64(
                     Math.Sign(value.Real) * h * Math.Cos(value.Imaginary),
                     h * Math.Sin(value.Imaginary));
             }
             return new Complex64(
                 GeneralMath.Sinh(value.Real) * Math.Cos(value.Imaginary),
                 GeneralMath.Cosh(value.Real) * Math.Sin(value.Imaginary));
         }
static Complex64 BGC.Mathematics.Complex64.Sqrt (in Complex64 value) static
The Square Root of a complex number
Referenced by BGC.Audio.FrequencyDomain.Populate().
Complex64 BGC.Mathematics.Complex64.Square () inline
The Square (power 2) of this Complex64
Returns
The square of this complex number.
Definition at line 356 of file Complex64.cs.
References BGC.Mathematics.Complex64.SquareRoot().
         {
             if (IsReal())
             {
                 return new Complex64(_real * _real, 0.0);
             }
             return new Complex64((_real * _real) - (_imag * _imag), 2 * _real * _imag);
         }
Complex64 BGC.Mathematics.Complex64.SquareRoot () inline
The Square Root (power 1/2) of this Complex64
Returns
The square root of this complex number.
Definition at line 824 of file Complex64.cs.
References BGC.Mathematics.Complex64.Abs().
Referenced by BGC.Mathematics.Complex64.Square().
         {
             if (IsRealNonNegative())
             {
                 return new Complex64(Math.Sqrt(_real), 0.0);
             }
             Complex64 result;
             double absReal = Math.Abs(Real);
             double absImag = Math.Abs(Imaginary);
             double w;
             if (absReal >= absImag)
             {
                 double ratio = Imaginary / Real;
                 w = Math.Sqrt(absReal) * Math.Sqrt(0.5 * (1.0 + Math.Sqrt(1.0 + (ratio * ratio))));
             }
             else
             {
                 double ratio = Real / Imaginary;
                 w = Math.Sqrt(absImag) * Math.Sqrt(0.5 * (Math.Abs(ratio) + Math.Sqrt(1.0 + (ratio * ratio))));
             }
             if (Real >= 0.0)
             {
                 result = new Complex64(w, (Imaginary / (2.0 * w)));
             }
             else if (Imaginary >= 0.0)
             {
                 result = new Complex64((absImag / (2.0 * w)), w);
             }
             else
             {
                 result = new Complex64((absImag / (2.0 * w)), -w);
             }
             return result;
         }
static Complex64 BGC.Mathematics.Complex64.Subtract (in Complex64 left, Complex64 right) static
The difference between two Complex64 numbers;
Returns
The complex difference.
static Complex64 BGC.Mathematics.Complex64.Tan (in Complex64 value) inline static
Trigonometric Tangent of a Complex64 number.
Parameters
value The complex value.
Returns
The tangent of the complex number.
Definition at line 385 of file Complex64.cs.
References BGC.Mathematics.Complex64.Imaginary, and BGC.Mathematics.Complex64.Real.
Referenced by BGC.Mathematics.Complex64.Tanh().
         {
             if (value.IsReal())
             {
                 return new Complex64(Math.Tan(value.Real), 0.0);
             }
             // tan(z) = - j*tanh(j*z)
             Complex64 z = Tanh(new Complex64(-value.Imaginary, value.Real));
             return new Complex64(z.Imaginary, -z.Real);
         }
static Complex64 BGC.Mathematics.Complex64.Tanh (in Complex64 value) inline static
Hyperbolic Tangent of a Complex64 number.
Parameters
value The complex value.
Returns
The hyperbolic tangent of a complex number.
Definition at line 404 of file Complex64.cs.
References BGC.Mathematics.GeneralMath.Cosh(), BGC.Mathematics.GeneralMath.Sinh(), BGC.Mathematics.Complex64.Tan(), and BGC.Mathematics.GeneralMath.Tanh().
         {
             if (value.IsReal())
             {
                 return new Complex64(GeneralMath.Tanh(value.Real), 0.0);
             }
             // tanh(x + j*y) = (cosh(x)*sinh(x)/cos^2(y) + j*tan(y))/(1 + sinh^2(x)/cos^2(y))
             // if |x| > huge, tanh(z) = sign(x) + j*4*cos(y)*sin(y)*exp(-2*|x|)
             // if exp(-|x|) = 0, tanh(z) = sign(x)
             // if tan(y) = +/- oo or 1/cos^2(y) = 1 + tan^2(y) = oo, tanh(z) = cosh(x)/sinh(x)
             //
             // The algorithm is based on Kahan.
             if (Math.Abs(value.Real) >= 22) // Taken from the msun library in FreeBSD
             {
                 double e = Math.Exp(-Math.Abs(value.Real));
                 if (e == 0.0)
                 {
                     return new Complex64(Math.Sign(value.Real), 0.0);
                 }
                 else
                 {
                     return new Complex64(
                         Math.Sign(value.Real),
                         4.0 * Math.Cos(value.Imaginary) * Math.Sin(value.Imaginary) * e * e);
                 }
             }
             double tani = Math.Tan(value.Imaginary);
             double beta = 1 + tani * tani; // beta = 1/cos^2(y) = 1 + t^2
             double sinhr = GeneralMath.Sinh(value.Real);
             double coshr = GeneralMath.Cosh(value.Real);
             if (double.IsInfinity(tani))
             {
                 return new Complex64(coshr / sinhr, 0.0);
             }
             double denom = 1.0 + beta * sinhr * sinhr;
             return new Complex64(beta * coshr * sinhr / denom, tani / denom);
         }
string BGC.Mathematics.Complex64.ToString (string format)
Converts the value of the current complex number to its equivalent string representation in Cartesian form by using the specified format for its real and imaginary parts.
string BGC.Mathematics.Complex64.ToString (IFormatProvider provider)
Converts the value of the current complex number to its equivalent string representation in Cartesian form by using the specified culture-specific formatting information.
string BGC.Mathematics.Complex64.ToString (string format, IFormatProvider provider)
Converts the value of the current complex number to its equivalent string representation in Cartesian form by using the specified format and culture-specific format information for its real and imaginary parts.
override string BGC.Mathematics.Complex64.ToString ()
Converts the value of the current complex number to its equivalent string representation in Cartesian form.
Returns
Field Documentation
readonly double BGC.Mathematics.Complex64._imag private
The imaginary component of the complex number.
Definition at line 51 of file Complex64.cs.
readonly double BGC.Mathematics.Complex64._real private
The real component of the complex number.
Definition at line 45 of file Complex64.cs.
Referenced by BGC.Mathematics.Complex64.Exponential().
double BGC.Mathematics.Complex64.Imaginary => _imag
Gets the imaginary component of the current System.Numerics.Complex64 object.
Definition at line 91 of file Complex64.cs.
Referenced by BGC.Mathematics.Complex64.Power(), and BGC.Mathematics.Complex64.Tan().
readonly Complex64 BGC.Mathematics.Complex64.ImaginaryOne = new Complex64(0.0, 1.0) static
Returns a new Complex64 instance with a real number equal to zero and an imaginary number equal to one.
Definition at line 67 of file Complex64.cs.
double BGC.Mathematics.Complex64.MagnitudeSquared => (_real * _real) + (_imag * _imag)
Gets the squared magnitude (or squared absolute value) of a complex number.
Returns
The squared magnitude of the current instance.
Definition at line 710 of file Complex64.cs.
readonly Complex64 BGC.Mathematics.Complex64.NaN = new Complex64(double.NaN, double.NaN) static
Returns a new Complex64 instance with real and imaginary numbers not a number.
Definition at line 77 of file Complex64.cs.
readonly Complex64 BGC.Mathematics.Complex64.One = new Complex64(1.0, 0.0) static
Returns a new Complex64 instance with a real number equal to one and an imaginary number equal to zero.
Definition at line 62 of file Complex64.cs.
double BGC.Mathematics.Complex64.Phase => _imag == 0.0 && _real < 0.0 ? Math.PI : Math.Atan2(_imag, _real)
Gets the phase of a complex number in radians.
Definition at line 139 of file Complex64.cs.
readonly Complex64 BGC.Mathematics.Complex64.PositiveInfinity = new Complex64(double.PositiveInfinity, double.PositiveInfinity) static
Returns a new Complex64 instance with real and imaginary numbers positive infinite.
Definition at line 72 of file Complex64.cs.
double BGC.Mathematics.Complex64.Real => _real
Gets the real component of the current System.Numerics.Complex64 object.
Definition at line 96 of file Complex64.cs.
Referenced by BGC.Audio.Synthesis.NoiseAudioClip._Initialize(), BGC.Audio.AnalyticStreams.AnalyticStreamExtensions.CalculateRMS(), BGC.Audio.AnalyticStreams.AnalyticNoiseStream.Initialize(), BGC.Mathematics.Complex64.operator/(), BGC.Audio.Filters.AllPassFilter.ProcessSample(), and BGC.Mathematics.Complex64.Tan().
readonly Complex64 BGC.Mathematics.Complex64.Zero = new Complex64(0.0, 0.0) static
Returns a new Complex64 instance with a real number equal to zero and an imaginary number equal to zero.
Definition at line 57 of file Complex64.cs.
Property Documentation
double BGC.Mathematics.Complex64.Magnitude get
Gets the magnitude (or absolute value) of a complex number.
Definition at line 102 of file Complex64.cs.
The documentation for this struct was generated from the following file:
Mathematics/Complex64.cs